// Step-specific "what to type" content for the core ISO 9001 steps of E2E-01 (context,
// policy, objectives, process architecture). Each entry returns the form values a trained
// IMS manager would record, so the seeded runs and the user guides show useful outputs
// instead of generic text. Placeholders: {org} {product} {line} {city} {customer} {supplier}
// {d0} {d1} {d2} (profile defects) and {std}. All organizations and people are fictional.
import { addDays } from './rng.js';

const L = (en, fr, ar) => ({ en, fr, ar });
export function fv(t, v) {
  if (!t || typeof t !== 'object') return t;
  const out = {};
  for (const l of ['en', 'fr', 'ar']) out[l] = (t[l] ?? t.en).replace(/\{(\w+)\}/g, (m, k) => { const x = v[k]; if (x === undefined || x === null) return m; return typeof x === 'object' ? (x[l] ?? x.en) : String(x); });
  return out;
}
const row = (item, category, detail, priority, source) => ({ item, category, detail, priority, source });
const crit = (criterion, weight, score, justification) => ({ criterion, weight, score, justification });

// Categories
const C = {
  eco: L('Economic', 'Économique', 'اقتصادي'), mkt: L('Market and customers', 'Marché et clients', 'السوق والعملاء'), reg: L('Legal and regulatory', 'Légal et réglementaire', 'قانوني وتنظيمي'),
  tech: L('Technological', 'Technologique', 'تقني'), sup: L('Supply', 'Approvisionnement', 'التوريد'), env: L('Environmental', 'Environnemental', 'بيئي'), soc: L('Social', 'Social', 'اجتماعي'),
  proc: L('Process', 'Processus', 'العملية'), com: L('Commercial', 'Commercial', 'تجاري'), res: L('Resources', 'Ressources', 'الموارد'), comp: L('Competence', 'Compétences', 'الكفاءات'), info: L('Information', 'Information', 'المعلومات'),
  ext: L('External party', 'Partie externe', 'طرف خارجي'), int: L('Internal party', 'Partie interne', 'طرف داخلي'),
  iface: L('Interface', 'Interface', 'واجهة'), scope: L('Scope statement', 'Énoncé du périmètre', 'بيان النطاق'), site: L('Site', 'Site', 'الموقع'), excl: L('Non-applicable requirement', 'Exigence non applicable', 'متطلب غير منطبق'), out: L('Outsourced process', 'Processus externalisé', 'عملية مسندة لجهة خارجية'),
  std: L('Standard', 'Norme', 'المعيار'), commit: L('Commitment', 'Engagement', 'الالتزام'), dir: L('Strategic direction', 'Orientation stratégique', 'التوجه الاستراتيجي'),
  mgmt: L('Management process', 'Processus de management', 'عملية إدارية'), core: L('Core process', 'Processus de réalisation', 'عملية أساسية'), supp: L('Support process', 'Processus support', 'عملية داعمة'),
};


// Interested parties of MP-001.4 (same labels, so needs map to them) and their needs (MP-001.5).
const PARTY = {
  cust: (c) => fv(L('Customers ({customer})', 'Clients ({customer})', 'العملاء ({customer})'), c.v), staff: () => L('Employees and their representatives', 'Salariés et leurs représentants', 'الموظفون وممثلوهم'),
  owner: () => L('Owner and shareholders', 'Dirigeant et actionnaires', 'المالك والمساهمون'), sup: (c) => fv(L('Suppliers of {supplier}', 'Fournisseurs de {supplier}', 'موردو {supplier}'), c.v),
  cb: () => L('Certification body', 'Organisme de certification', 'جهة الاعتماد'), auth: () => L('Authorities (labour inspection, municipality)', 'Autorités (inspection du travail, commune)', 'السلطات (مفتشية الشغل، البلدية)'),
};
const TYPE = {
  contract: L('Contractual requirement', 'Exigence contractuelle', 'متطلب تعاقدي'), legal: L('Legal or regulatory requirement', 'Exigence légale ou réglementaire', 'متطلب قانوني أو تنظيمي'),
  expect: L('Customer expectation', 'Attente client', 'توقع العميل'), internal: L('Internal expectation', 'Attente interne', 'توقع داخلي'), vol: L('Voluntary commitment', 'Engagement volontaire', 'التزام طوعي'),
};
const need = (c, text, parties, type, obligation, response, priority, origin, source) => ({ need: text, parties: parties.map(k => ({ id: null, name: PARTY[k](c) })), type, obligation, response, priority, origin, source });
export function needsRows(c) {
  return [
    need(c, L('Service delivered on the agreed date, right first time', 'Prestation réalisée à la date convenue, bien du premier coup', 'تقديم الخدمة في الموعد المتفق عليه وبشكل صحيح من المرة الأولى'), ['cust'], TYPE.contract, 'Yes', L('Planning and job order control (service delivery process); KPI on-time service', 'Planification et maîtrise des ordres de travail (processus de réalisation) ; KPI ponctualité', 'التخطيط وضبط أوامر العمل (عملية تقديم الخدمة)؛ مؤشر الالتزام بالموعد'), 'High', 'Manual', L('Framework contracts; satisfaction survey 2025', 'Contrats-cadres ; enquête de satisfaction 2025', 'العقود الإطارية؛ استبيان الرضا 2025')),
    need(c, L('Correct quotes and clear invoices', 'Devis justes et factures claires', 'عروض أسعار صحيحة وفواتير واضحة'), ['cust', 'owner'], TYPE.expect, 'No', L('Quote review before sending; invoice checked against the signed job sheet', 'Revue du devis avant envoi ; facture contrôlée avec la fiche signée', 'مراجعة العرض قبل إرساله؛ ومطابقة الفاتورة مع بطاقة العمل الموقعة'), 'High', 'Manual', L('Quotation register: 9 corrections in Q3 2025', 'Registre des devis : 9 corrections au T3 2025', 'سجل العروض: 9 تصحيحات في الربع الثالث 2025')),
    need(c, L('ISO 9001 certification within 12 months', 'Certification ISO 9001 sous 12 mois', 'الحصول على شهادة ISO 9001 خلال 12 شهرًا'), ['cust', 'owner', 'cb'], TYPE.vol, 'Yes', L('QMS project AT-UNI-QMS; certification audit planned', 'Projet SMQ ; audit de certification planifié', 'مشروع نظام إدارة الجودة؛ تدقيق الاعتماد مخطط'), 'High', 'Library', L('Tender files 2025; business plan 2025–2027', 'Appels d\'offres 2025 ; plan d\'affaires 2025–2027', 'ملفات المناقصات 2025؛ خطة الأعمال 2025–2027')),
    need(c, L('Safe work, training and clear work instructions', 'Travail en sécurité, formation et instructions claires', 'عمل آمن وتدريب وتعليمات عمل واضحة'), ['staff'], TYPE.legal, 'Yes', L('Training plan (MP-013) and work instructions (MP-006)', 'Plan de formation (MP-013) et instructions de travail (MP-006)', 'خطة التدريب (MP-013) وتعليمات العمل (MP-006)'), 'High', 'Library', L('Labour code; staff meeting minutes, October 2025', 'Code du travail ; réunion du personnel, octobre 2025', 'مدونة الشغل؛ محضر اجتماع الموظفين، أكتوبر 2025')),
    need(c, L('Workload planned during peaks', 'Charge de travail planifiée pendant les pics', 'تخطيط عبء العمل في أوقات الذروة'), ['staff', 'owner'], TYPE.internal, 'No', L('Capacity planning reviewed weekly; seasonal staff', 'Planification de capacité revue chaque semaine ; saisonniers', 'مراجعة تخطيط القدرة أسبوعيًا؛ عمالة موسمية'), 'Medium', 'AI', L('Planning board and overtime records', 'Planning et relevés d\'heures supplémentaires', 'لوحة التخطيط وسجلات الساعات الإضافية')),
    need(c, L('Forecast of needs and payment on time', 'Prévision des besoins et paiement à l\'échéance', 'توقع الاحتياجات والسداد في الموعد'), ['sup'], TYPE.contract, 'No', L('Quarterly forecast shared; payment terms 60 days', 'Prévision trimestrielle partagée ; paiement à 60 jours', 'مشاركة التوقعات الفصلية؛ السداد خلال 60 يومًا'), 'Medium', 'Manual', L('Supplier meetings, 2025', 'Réunions fournisseurs, 2025', 'اجتماعات الموردين، 2025')),
    need(c, L('Access to records and people during audits', 'Accès aux enregistrements et aux personnes pendant les audits', 'إتاحة الوصول إلى السجلات والأشخاص أثناء التدقيق'), ['cb'], TYPE.contract, 'Yes', L('Records control (MP-030); audit coordination (MP-017)', 'Maîtrise des enregistrements (MP-030) ; coordination d\'audit (MP-017)', 'ضبط السجلات (MP-030)؛ تنسيق التدقيق (MP-017)'), 'Medium', 'Library', L('Certification contract', 'Contrat de certification', 'عقد الاعتماد')),
    need(c, L('Compliance with labour law, business licence and waste rules', 'Respect du droit du travail, de l\'autorisation d\'exercer et des règles sur les déchets', 'الامتثال لقانون الشغل ورخصة المزاولة وقواعد النفايات'), ['auth', 'staff'], TYPE.legal, 'Yes', L('Legal register and compliance evaluation (MP-028)', 'Registre réglementaire et évaluation de conformité (MP-028)', 'السجل القانوني وتقييم الامتثال (MP-028)'), 'Medium', 'AI', L('Legal register', 'Registre réglementaire', 'السجل القانوني')),
  ];
}

export const STEP_CONTENT = {
  // ------------------------------------------------------------ MP-001 Context analysis
  'MP-001.1': (c) => ({
    frequency: 'Annual', nextDate: addDays(c.due, 365), chair: 'ims_manager', scope: c.obsAll,
    notes: fv(L('Inputs to the next diagnosis: last management review outputs, customer complaints of the year, regulatory watch bulletins, supplier evaluation results and the strategic plan. An extraordinary review is triggered by a new site, a new service line or a major regulatory change.', 'Éléments d\'entrée du prochain diagnostic : conclusions de la dernière revue de direction, réclamations clients de l\'année, bulletins de veille réglementaire, résultats d\'évaluation des fournisseurs et plan stratégique. Une revue extraordinaire est déclenchée par un nouveau site, une nouvelle activité ou un changement réglementaire majeur.', 'مدخلات التشخيص القادم: مخرجات آخر مراجعة للإدارة، وشكاوى العملاء خلال السنة، ونشرات الرصد التنظيمي، ونتائج تقييم الموردين، والخطة الاستراتيجية. وتُطلق مراجعة استثنائية عند إضافة موقع أو خط خدمة جديد أو تغيير تنظيمي كبير.'), c.v),
  }),
  'MP-001.2': (c) => ({ items: [
    row(fv(L('Price competition from informal {product} providers', 'Concurrence par les prix des prestataires informels de {product}', 'منافسة سعرية من مقدمي {product} غير الرسميين'), c.v), C.eco, fv(L('Pressure on quote margins; risk of losing price-sensitive {customer}.', 'Pression sur les marges des devis ; risque de perdre des {customer} sensibles au prix.', 'ضغط على هوامش عروض الأسعار وخطر فقدان {customer} الحساسين للسعر.'), c.v), 'High', L('Sales team market study, Q3 2025', 'Étude de marché de l\'équipe commerciale, T3 2025', 'دراسة السوق لفريق المبيعات، الربع الثالث 2025')),
    row(fv(L('Customers require ISO 9001 certification in tenders', 'Les clients exigent la certification ISO 9001 dans les appels d\'offres', 'اشتراط العملاء شهادة ISO 9001 في المناقصات'), c.v), C.mkt, fv(L('Certification is needed to keep and win contracts with {customer}.', 'La certification est nécessaire pour conserver et gagner des contrats avec les {customer}.', 'الاعتماد ضروري للحفاظ على العقود مع {customer} والفوز بعقود جديدة.'), c.v), 'High', L('Tender files received in 2025 (4 of 11 require ISO 9001)', 'Dossiers d\'appels d\'offres reçus en 2025 (4 sur 11 exigent ISO 9001)', 'ملفات المناقصات المستلمة في 2025 (4 من 11 تشترط ISO 9001)')),
    row(L('ISO 9001 amendment on climate change (Amd 1:2024)', 'Amendement ISO 9001 sur le changement climatique (Amd 1:2024)', 'تعديل ISO 9001 بشأن تغير المناخ (Amd 1:2024)'), C.reg, L('Context analysis must state whether climate change is a relevant issue.', 'L\'analyse du contexte doit indiquer si le changement climatique est un enjeu pertinent.', 'يجب أن يبين تحليل السياق ما إذا كان تغير المناخ قضية ذات صلة.'), 'Medium', L('ISO 9001:2015/Amd 1:2024; regulatory watch bulletin', 'ISO 9001:2015/Amd 1:2024 ; bulletin de veille réglementaire', 'ISO 9001:2015/Amd 1:2024؛ نشرة الرصد التنظيمي')),
    row(fv(L('Availability and price of {supplier}', 'Disponibilité et prix des {supplier}', 'توفر {supplier} وأسعارها'), c.v), C.sup, L('Delays when parts are missing; lead times doubled for imported references.', 'Retards quand les pièces manquent ; délais doublés pour les références importées.', 'تأخيرات عند نقص القطع وتضاعف آجال التوريد للمراجع المستوردة.'), 'Medium', L('Supplier evaluation file and purchase orders 2025', 'Dossier d\'évaluation fournisseurs et commandes 2025', 'ملف تقييم الموردين وأوامر الشراء 2025')),
    row(L('Customers send requests through portals and messaging', 'Les clients envoient leurs demandes via portails et messageries', 'يرسل العملاء طلباتهم عبر البوابات وتطبيقات المراسلة'), C.tech, L('Requests can be lost if they are not logged in one place.', 'Des demandes peuvent être perdues si elles ne sont pas enregistrées en un seul endroit.', 'قد تضيع الطلبات إذا لم تُسجَّل في مكان واحد.'), 'Medium', L('Customer request log, sample of 60 requests', 'Journal des demandes clients, échantillon de 60 demandes', 'سجل طلبات العملاء، عينة من 60 طلبًا')),
  ] }),
  'MP-001.3': (c) => ({ items: [
    row(fv(L('{d0}', '{d0}', '{d0}'), c.v), C.proc, L('No proof of service accepted; invoices disputed and paid late.', 'Pas de preuve d\'acceptation de la prestation ; factures contestées et payées en retard.', 'غياب دليل قبول الخدمة؛ فواتير متنازع عليها ومدفوعة متأخرة.'), 'High', L('Review of records Jan–Oct 2025: 14% not compliant', 'Revue des enregistrements janv.–oct. 2025 : 14 % non conformes', 'مراجعة السجلات يناير–أكتوبر 2025: 14% غير مطابقة')),
    row(fv(L('{d1}', '{d1}', '{d1}'), c.v), C.com, L('Rework of quotes and margin loss; two customer complaints.', 'Reprise de devis et perte de marge ; deux réclamations clients.', 'إعادة إعداد العروض وخسارة في الهامش؛ شكويان من العملاء.'), 'High', L('Quotation register: 9 corrections in Q3 2025', 'Registre des devis : 9 corrections au T3 2025', 'سجل عروض الأسعار: 9 تصحيحات في الربع الثالث 2025')),
    row(fv(L('Workload peaks on {line}', 'Pics de charge sur {line}', 'ذروات عبء العمل في {line}'), c.v), C.res, fv(L('{d2} during summer peaks; overtime above 12%.', '{d2} pendant les pics d\'été ; heures supplémentaires au-delà de 12 %.', '{d2} خلال ذروات الصيف؛ ساعات إضافية تتجاوز 12%.'), c.v), 'Medium', L('Planning board and overtime records', 'Planning et relevés d\'heures supplémentaires', 'لوحة التخطيط وسجلات الساعات الإضافية')),
    row(L('Know-how held by two senior staff', 'Savoir-faire détenu par deux salariés seniors', 'خبرة يمتلكها موظفان قديمان فقط'), C.comp, L('Dependency on two people; no written work instructions.', 'Dépendance à deux personnes ; pas d\'instructions de travail écrites.', 'اعتماد على شخصين وعدم وجود تعليمات عمل مكتوبة.'), 'Medium', L('Competence matrix 2025', 'Matrice des compétences 2025', 'مصفوفة الكفاءات 2025')),
  ] }),
  'MP-001.4': (c) => ({ items: [
    { ...row(fv(L('Customers ({customer})', 'Clients ({customer})', 'العملاء ({customer})'), c.v), C.ext, L('On-time service, correct quotes, signed proof of service, clear invoices.', 'Prestation dans les délais, devis justes, preuve de service signée, factures claires.', 'خدمة في الموعد وعروض أسعار صحيحة ودليل خدمة موقع وفواتير واضحة.'), 'High', L('Customer satisfaction survey 2025 (n = 48)', 'Enquête de satisfaction 2025 (n = 48)', 'استبيان رضا العملاء 2025 (العدد 48)')), influence: '5', interest: '5' },
    { ...row(L('Employees and their representatives', 'Salariés et leurs représentants', 'الموظفون وممثلوهم'), C.int, L('Safe work, training, clear instructions, workload planning.', 'Travail en sécurité, formation, instructions claires, planification de la charge.', 'عمل آمن وتدريب وتعليمات واضحة وتخطيط عبء العمل.'), 'High', L('Staff meeting minutes, October 2025', 'Compte rendu de réunion du personnel, octobre 2025', 'محضر اجتماع الموظفين، أكتوبر 2025')), influence: '4', interest: '4' },
    { ...row(L('Owner and shareholders', 'Dirigeant et actionnaires', 'المالك والمساهمون'), C.int, L('Profitable growth, certification obtained within 12 months.', 'Croissance rentable, certification obtenue sous 12 mois.', 'نمو مربح والحصول على الاعتماد خلال 12 شهرًا.'), 'High', L('Business plan 2025–2027', 'Plan d\'affaires 2025–2027', 'خطة الأعمال 2025–2027')), influence: '5', interest: '5' },
    { ...row(fv(L('Suppliers of {supplier}', 'Fournisseurs de {supplier}', 'موردو {supplier}'), c.v), C.ext, L('Forecast of needs, clear specifications, payment on time.', 'Prévision des besoins, spécifications claires, paiement à l\'échéance.', 'توقع الاحتياجات ومواصفات واضحة وسداد في الموعد.'), 'Medium', L('Supplier meetings, 2025', 'Réunions fournisseurs, 2025', 'اجتماعات الموردين، 2025')), influence: '3', interest: '3' },
    { ...row(L('Certification body', 'Organisme de certification', 'جهة الاعتماد'), C.ext, L('Conforming management system, access to records and people.', 'Système de management conforme, accès aux enregistrements et aux personnes.', 'نظام إدارة مطابق وإتاحة الوصول إلى السجلات والأشخاص.'), 'Medium', L('Certification contract', 'Contrat de certification', 'عقد الاعتماد')), influence: '4', interest: '3' },
    { ...row(L('Authorities (labour inspection, municipality)', 'Autorités (inspection du travail, commune)', 'السلطات (مفتشية الشغل، البلدية)'), C.ext, L('Compliance with labour law, business licence and waste rules.', 'Respect du droit du travail, de l\'autorisation d\'exercer et des règles sur les déchets.', 'الامتثال لقانون الشغل ورخصة المزاولة وقواعد النفايات.'), 'Medium', L('Legal register', 'Registre réglementaire', 'السجل القانوني')), influence: '5', interest: '2' },
  ] }),
  'MP-001.5': (c) => ({
    needs: needsRows(c),
    matrix: [
      crit(L('Customer requirements identified and written down', 'Exigences clients identifiées et formalisées', 'تحديد متطلبات العملاء وتوثيقها'), 30, 4, L('Requirements of the 12 main customers are in the requirements matrix; 2 framework contracts still to review.', 'Les exigences des 12 principaux clients figurent dans la matrice ; 2 contrats-cadres restent à revoir.', 'متطلبات أكبر 12 عميلًا مدرجة في المصفوفة؛ وبقي عقدان إطاريان للمراجعة.')),
      crit(L('Legal and regulatory requirements identified', 'Exigences légales et réglementaires identifiées', 'تحديد المتطلبات القانونية والتنظيمية'), 20, 3, L('Labour and licence requirements listed; vehicle and waste rules to confirm with the legal register (MP-028).', 'Exigences du travail et d\'autorisation listées ; règles véhicules et déchets à confirmer avec le registre réglementaire (MP-028).', 'تم إدراج متطلبات الشغل والترخيص؛ وقواعد المركبات والنفايات تحتاج إلى تأكيد مع السجل القانوني (MP-028).')),
      crit(L('Requirements adopted as compliance obligations', 'Exigences retenues comme obligations de conformité', 'اعتماد المتطلبات كالتزامات امتثال'), 20, 3, L('Adopted for customers and authorities; supplier expectations kept as information.', 'Retenues pour les clients et les autorités ; attentes des fournisseurs gardées pour information.', 'معتمدة للعملاء والسلطات؛ وتوقعات الموردين للاطلاع فقط.')),
      crit(L('Needs monitored (survey, meetings, complaints)', 'Besoins surveillés (enquête, réunions, réclamations)', 'مراقبة الاحتياجات (استبيان، اجتماعات، شكاوى)'), 15, 4, L('Annual survey and monthly complaint review in place.', 'Enquête annuelle et revue mensuelle des réclamations en place.', 'استبيان سنوي ومراجعة شهرية للشكاوى قائمان.')),
      crit(L('Requirements reflected in processes and objectives', 'Exigences reprises dans les processus et objectifs', 'انعكاس المتطلبات في العمليات والأهداف'), 15, 3, L('On-time service and quote accuracy objectives defined; proof of service to add to the delivery process.', 'Objectifs de ponctualité et de justesse des devis définis ; preuve de service à ajouter au processus de réalisation.', 'تم تحديد أهداف الالتزام بالموعد ودقة العروض؛ ويجب إضافة دليل الخدمة إلى عملية التنفيذ.')),
    ],
    rationale: L('Needs and expectations of the six relevant interested parties are known (weighted score 3.5 = "Defined"). Two actions: confirm vehicle and waste requirements in the legal register; add the signed job sheet as a release criterion.', 'Les besoins et attentes des six parties intéressées pertinentes sont connus (note pondérée 3,5 = « Défini »). Deux actions : confirmer les exigences véhicules et déchets dans le registre réglementaire ; ajouter la fiche signée comme critère de libération.', 'احتياجات الأطراف المعنية الست ذات الصلة معروفة (الدرجة المرجحة 3.5 = "محدد"). إجراءان: تأكيد متطلبات المركبات والنفايات في السجل القانوني، وإضافة بطاقة العمل الموقعة كمعيار للإفراج.'),
  }),
  'MP-001.6': (c) => ({
    criteria: [
      { criterion: L('Issues reviewed with top management', 'Enjeux revus avec la direction', 'مراجعة القضايا مع الإدارة العليا'), met: 'Yes', evidence: fv(L('Meeting of {date}', 'Réunion du {date}', 'اجتماع {date}'), { date: addDays(c.due, -2) }) },
      { criterion: L('Interested parties and requirements validated', 'Parties intéressées et exigences validées', 'المصادقة على الأطراف المعنية ومتطلباتها'), met: 'Yes', evidence: L('Interested parties register v1.0', 'Registre des parties intéressées v1.0', 'سجل الأطراف المعنية الإصدار 1.0') },
      { criterion: L('Requirements cascaded to process owners', 'Exigences déclinées aux pilotes de processus', 'تفريع المتطلبات إلى مالكي العمليات'), met: 'Partly', evidence: L('Sent to operations and sales; purchasing on the next meeting', 'Envoyées aux opérations et au commercial ; achats à la prochaine réunion', 'أُرسلت للعمليات والمبيعات؛ والمشتريات في الاجتماع القادم') },
    ],
    decision: 'Go', approver: 'top_management',
    comment: L('Go: context and requirements approved. Condition: purchasing receives the requirements matrix before the next steering meeting.', 'Go : contexte et exigences approuvés. Condition : les achats reçoivent la matrice des exigences avant le prochain comité de pilotage.', 'المضي: تمت الموافقة على السياق والمتطلبات. الشرط: تسلُّم المشتريات مصفوفة المتطلبات قبل اجتماع التوجيه القادم.'),
  }),
  'MP-001.7': (c) => ({ items: [
    { from: L('Sales and quotation', 'Commercial et devis', 'المبيعات والعروض'), to: L('Service delivery', 'Réalisation de la prestation', 'تقديم الخدمة'), category: L('Output → input', 'Sortie → entrée', 'مخرج ← مدخل'), detail: L('Validated quote and job order with customer requirements.', 'Devis validé et ordre de travail avec les exigences du client.', 'عرض سعر معتمد وأمر عمل بمتطلبات العميل.'), priority: 'High', source: L('Job order form', 'Formulaire d\'ordre de travail', 'نموذج أمر العمل') },
    { from: L('Service delivery', 'Réalisation de la prestation', 'تقديم الخدمة'), to: L('Invoicing', 'Facturation', 'الفوترة'), category: L('Shared record or tool', 'Enregistrement ou outil partagé', 'سجل أو أداة مشتركة'), detail: fv(L('Signed proof of service; the missing signature causes "{d0}".', 'Preuve de service signée ; l\'absence de signature cause « {d0} ».', 'دليل خدمة موقع؛ وغياب التوقيع يسبب "{d0}".'), c.v), priority: 'High', source: L('Job sheet', 'Fiche d\'intervention', 'بطاقة العمل') },
    { from: 'MP-024', to: L('Service delivery', 'Réalisation de la prestation', 'تقديم الخدمة'), category: L('Resources provided', 'Ressources fournies', 'موارد مقدمة'), detail: fv(L('Availability of {supplier} on the planned date.', 'Disponibilité des {supplier} à la date prévue.', 'توفر {supplier} في الموعد المخطط.'), c.v), priority: 'Medium', source: L('Purchase orders and stock list', 'Commandes et état du stock', 'أوامر الشراء وقائمة المخزون') },
    { from: 'MP-013', to: L('All processes', 'Tous les processus', 'جميع العمليات'), category: L('Support service', 'Service support', 'خدمة داعمة'), detail: L('Competent and authorized staff; training plan.', 'Personnel compétent et habilité ; plan de formation.', 'موظفون أكفاء ومؤهلون؛ خطة التدريب.'), priority: 'Medium', source: L('Competence matrix', 'Matrice des compétences', 'مصفوفة الكفاءات') },
    { from: 'MP-034', to: L('All processes', 'Tous les processus', 'جميع العمليات'), category: L('Control and feedback', 'Pilotage et retour', 'الضبط والتغذية الراجعة'), detail: L('Policy, objectives, resources and review decisions.', 'Politique, objectifs, ressources et décisions de revue.', 'السياسة والأهداف والموارد وقرارات المراجعة.'), priority: 'Medium', source: L('Management review minutes', 'Compte rendu de revue de direction', 'محضر مراجعة الإدارة') },
  ] }),
  'MP-001.8': (c) => ({ items: [
    row(fv(L('Design and delivery of {product} for {customer} in the {city} region', 'Conception et réalisation de {product} pour les {customer} de la région de {city}', 'تصميم {product} وتقديمها لـ {customer} في منطقة {city}'), c.v), C.scope, L('Covers sales and quotation, planning, delivery, invoicing and after-sales.', 'Couvre commercial et devis, planification, réalisation, facturation et après-vente.', 'يشمل المبيعات والعروض والتخطيط والتنفيذ والفوترة وخدمة ما بعد البيع.'), 'High', L('Strategic plan and service catalogue', 'Plan stratégique et catalogue de services', 'الخطة الاستراتيجية ودليل الخدمات')),
    row(fv(L('Head office and workshop, {city}', 'Siège et atelier, {city}', 'المقر الرئيسي والورشة، {city}'), c.v), C.site, L('Single site; interventions at customer premises are included.', 'Site unique ; les interventions chez les clients sont incluses.', 'موقع واحد؛ والتدخلات في مقار العملاء مشمولة.'), 'High', L('Business licence', 'Autorisation d\'exercer', 'رخصة المزاولة')),
    row(L('ISO 9001 §8.3 Design and development', 'ISO 9001 §8.3 Conception et développement', 'ISO 9001 §8.3 التصميم والتطوير'), C.excl, L('Not applicable: services follow customer or manufacturer specifications; no design responsibility.', 'Non applicable : les prestations suivent les spécifications du client ou du fabricant ; aucune responsabilité de conception.', 'غير منطبق: تتبع الخدمات مواصفات العميل أو الصانع دون مسؤولية تصميم.'), 'Medium', L('Contracts review', 'Revue des contrats', 'مراجعة العقود')),
    row(L('Vehicle maintenance', 'Entretien des véhicules', 'صيانة المركبات'), C.out, L('Outsourced to an approved garage; controlled through the supplier evaluation.', 'Externalisé à un garage agréé ; maîtrisé par l\'évaluation fournisseurs.', 'مسندة إلى مرآب معتمد وتُضبط عبر تقييم الموردين.'), 'Low', L('Service contract', 'Contrat de service', 'عقد الخدمة')),
  ] }),
  'MP-001.10': (c) => ({
    frequency: 'Annual', date: c.due, nextDate: addDays(c.due, 365), chair: 'ims_manager', participants: ['top_management', 'quality_manager', 'operations_manager', 'risk_manager'],
    inputs: [
      { input: L('External and internal issues', 'Enjeux externes et internes', 'القضايا الخارجية والداخلية'), finding: L('New competitor offer at lower price; issues list still valid.', 'Nouvelle offre concurrente moins chère ; liste des enjeux toujours valable.', 'عرض منافس جديد بسعر أقل؛ قائمة القضايا لا تزال صالحة.') },
      { input: L('Interested parties register', 'Registre des parties intéressées', 'سجل الأطراف المعنية'), finding: L('Add the new logistics partner.', 'Ajouter le nouveau partenaire logistique.', 'إضافة الشريك اللوجستي الجديد.') },
      { input: L('Customer satisfaction and complaints', 'Satisfaction et réclamations clients', 'رضا العملاء وشكاواهم'), finding: L('Satisfaction 82% (target 85%); complaints on quotes down by 40%.', 'Satisfaction 82 % (cible 85 %) ; réclamations sur devis en baisse de 40 %.', 'الرضا 82% (المستهدف 85%)؛ وانخفاض شكاوى العروض بنسبة 40%.') },
    ],
    decisions: [
      { decision: L('Add supplier price risk to the risk register', 'Ajouter le risque prix fournisseurs au registre des risques', 'إضافة مخاطر أسعار الموردين إلى سجل المخاطر'), owner: c.user('risk_manager'), due: addDays(c.due, 30) },
      { decision: L('Update the scope statement for the new maintenance contracts', 'Mettre à jour l\'énoncé du périmètre pour les nouveaux contrats de maintenance', 'تحديث بيان النطاق لعقود الصيانة الجديدة'), owner: c.user('ims_manager'), due: addDays(c.due, 45) },
    ],
  }),
  // ------------------------------------------------------------ MP-002 Quality policy
  'MP-002.10': (c) => ({
    standards: c.standards, scopeType: c.qhse ? 'Integrated' : 'Single-standard', coverage: c.obsAll,
    rationale: fv(c.qhse ? L('Integrated policy for {std}: customers ask for ISO 9001, and the owner wants to prevent road and workshop accidents and control waste.', 'Politique intégrée pour {std} : les clients demandent ISO 9001 et le dirigeant veut prévenir les accidents de la route et d\'atelier et maîtriser les déchets.', 'سياسة متكاملة لـ {std}: يطلب العملاء ISO 9001 ويريد المالك منع حوادث الطريق والورشة وضبط النفايات.') : L('ISO 9001 only: certification is a customer requirement; environment and safety are managed through legal compliance for now.', 'ISO 9001 seule : la certification est une exigence client ; environnement et sécurité sont gérés par la conformité légale pour l\'instant.', 'ISO 9001 فقط: الاعتماد متطلب للعملاء؛ وتُدار البيئة والسلامة عبر الامتثال القانوني حاليًا.'), c.v),
  }),
  'MP-002.1': (c) => ({
    frequency: 'Annual', nextDate: addDays(c.due, 365), chair: 'top_management', scope: c.obsAll,
    notes: L('Reviewed at each management review, and earlier after a change of strategy, a merger, a new site or a major customer requirement.', 'Revue à chaque revue de direction, et plus tôt en cas de changement de stratégie, de fusion, de nouveau site ou d\'exigence client majeure.', 'تُراجع في كل مراجعة للإدارة، وقبل ذلك عند تغيير الاستراتيجية أو الاندماج أو فتح موقع جديد أو ظهور متطلب رئيسي للعملاء.'),
  }),
  'MP-002.3': (c) => ({ items: [
    row(L('Meet customer requirements on time, first time', 'Satisfaire les exigences clients à temps, du premier coup', 'تلبية متطلبات العملاء في الموعد ومن المرة الأولى'), C.commit, L('Priority of the Managing Director: on-time service and correct quotes.', 'Priorité du directeur général : ponctualité et devis justes.', 'أولوية المدير العام: الالتزام بالمواعيد ودقة العروض.'), 'High', fv(L('Interview with the Managing Director, {date}', 'Entretien avec le directeur général, {date}', 'مقابلة مع المدير العام، {date}'), { date: addDays(c.due, -3) })),
    row(L('Comply with legal and contractual requirements', 'Respecter les exigences légales et contractuelles', 'الامتثال للمتطلبات القانونية والتعاقدية'), C.commit, L('Includes customer contracts and labour law.', 'Inclut les contrats clients et le droit du travail.', 'يشمل عقود العملاء وقانون الشغل.'), 'High', L('Interview with the Managing Director', 'Entretien avec le directeur général', 'مقابلة مع المدير العام')),
    row(L('Develop staff competence', 'Développer les compétences du personnel', 'تطوير كفاءات العاملين'), C.commit, L('Two senior technicians coach the new hires.', 'Deux techniciens seniors accompagnent les nouveaux.', 'يؤطر فنيان قديمان الموظفين الجدد.'), 'Medium', L('HR interview', 'Entretien RH', 'مقابلة الموارد البشرية')),
    row(fv(L('Become the reference {product} provider in the {city} region by 2027', 'Devenir le prestataire de référence en {product} dans la région de {city} d\'ici 2027', 'أن نصبح المزود المرجعي لـ {product} في منطقة {city} بحلول 2027'), c.v), C.dir, L('Strategic direction for the objectives.', 'Orientation stratégique pour les objectifs.', 'التوجه الاستراتيجي للأهداف.'), 'High', L('Strategic plan 2025–2027', 'Plan stratégique 2025–2027', 'الخطة الاستراتيجية 2025–2027')),
  ] }),
  'MP-002.11': (c) => ({
    context: fv(L('Standards: {std}. Scope: {product} for {customer} in {city}. Commitments from the management consultation: on-time and right-first-time service, legal compliance, staff competence, continual improvement. Strategic direction: reference provider in the region by 2027.', 'Normes : {std}. Périmètre : {product} pour les {customer} à {city}. Engagements issus de la consultation de la direction : service ponctuel et juste du premier coup, conformité légale, compétence du personnel, amélioration continue. Orientation : prestataire de référence de la région d\'ici 2027.', 'المعايير: {std}. النطاق: {product} لـ {customer} في {city}. الالتزامات الناتجة عن استشارة الإدارة: خدمة في الموعد وصحيحة من المرة الأولى، والامتثال القانوني، وكفاءة العاملين، والتحسين المستمر. التوجه: المزود المرجعي في المنطقة بحلول 2027.'), c.v),
    outcome: 'Edited',
    final: fv(c.qhse ? L('{org} provides {product} to {customer} in the {city} region. We commit to: satisfy our customers and the applicable legal requirements; provide safe and healthy working conditions and prevent injury and ill health; protect the environment and prevent pollution; consult and involve our workers; set measurable objectives every year and continually improve our integrated management system ({std}).', '{org} fournit des {product} aux {customer} de la région de {city}. Nous nous engageons à : satisfaire nos clients et les exigences légales applicables ; assurer des conditions de travail sûres et saines et prévenir les traumatismes et pathologies ; protéger l\'environnement et prévenir la pollution ; consulter et faire participer nos travailleurs ; fixer chaque année des objectifs mesurables et améliorer en continu notre système de management intégré ({std}).', 'تقدم {org} {product} إلى {customer} في منطقة {city}. ونلتزم بما يلي: إرضاء عملائنا والوفاء بالمتطلبات القانونية المنطبقة؛ وتوفير ظروف عمل آمنة وصحية ومنع الإصابات والأمراض المهنية؛ وحماية البيئة ومنع التلوث؛ واستشارة عمالنا وإشراكهم؛ ووضع أهداف قابلة للقياس كل عام والتحسين المستمر لنظام إدارتنا المتكامل ({std}).') : L('{org} provides {product} to {customer} in the {city} region. We commit to: deliver on time and right first time; satisfy our customers and the applicable legal and contractual requirements; develop the competence of our staff; set measurable quality objectives every year and continually improve our quality management system ({std}).', '{org} fournit des {product} aux {customer} de la région de {city}. Nous nous engageons à : intervenir à temps et bien du premier coup ; satisfaire nos clients et les exigences légales et contractuelles applicables ; développer les compétences de notre personnel ; fixer chaque année des objectifs qualité mesurables et améliorer en continu notre système de management de la qualité ({std}).', 'تقدم {org} {product} إلى {customer} في منطقة {city}. ونلتزم بما يلي: التنفيذ في الموعد وبشكل صحيح من المرة الأولى؛ وإرضاء عملائنا والوفاء بالمتطلبات القانونية والتعاقدية المنطبقة؛ وتطوير كفاءات موظفينا؛ ووضع أهداف جودة قابلة للقياس كل عام والتحسين المستمر لنظام إدارة الجودة ({std}).'), c.v),
  }),
  'MP-002.2': (c) => ({ template: c.qhse ? 'TPL-POL-IMS' : 'TPL-POL-Q', docRef: `${c.orgCode}-${c.ms}-POL`, version: '0.2',
    summary: L('Commitments adapted: "right first time" wording, signed proof of service, reference to the 2027 strategic direction.', 'Engagements adaptés : formulation « bien du premier coup », preuve de service signée, référence à l\'orientation stratégique 2027.', 'تكييف الالتزامات: صياغة "صحيح من المرة الأولى" ودليل الخدمة الموقع والإشارة إلى توجه 2027.') }),
  'MP-002.4': (c) => ({ items: [
    row(L('§5.2.1 a) Appropriate to purpose and context', '§5.2.1 a) Adaptée à la finalité et au contexte', '§5.2.1 أ) ملائمة للغاية والسياق'), C.commit, fv(L('First sentence describes {product}, {customer} and the region.', 'La première phrase décrit les {product}, les {customer} et la région.', 'تصف الجملة الأولى {product} و{customer} والمنطقة.'), c.v), 'High', L('Policy draft v0.2, paragraph 1', 'Projet de politique v0.2, paragraphe 1', 'مسودة السياسة 0.2، الفقرة 1')),
    row(L('§5.2.1 b) Framework for quality objectives', '§5.2.1 b) Cadre pour les objectifs qualité', '§5.2.1 ب) إطار لأهداف الجودة'), C.commit, L('"Set measurable quality objectives every year".', '« Fixer chaque année des objectifs qualité mesurables ».', '"وضع أهداف جودة قابلة للقياس كل عام".'), 'High', L('Policy draft v0.2, commitment 4', 'Projet de politique v0.2, engagement 4', 'مسودة السياسة 0.2، الالتزام 4')),
    row(L('§5.2.1 c) Commitment to satisfy applicable requirements', '§5.2.1 c) Engagement à satisfaire les exigences applicables', '§5.2.1 ج) الالتزام بتلبية المتطلبات المنطبقة'), C.commit, L('Customer, legal and contractual requirements named.', 'Exigences clients, légales et contractuelles citées.', 'ذكر متطلبات العملاء والمتطلبات القانونية والتعاقدية.'), 'High', L('Policy draft v0.2, commitment 2', 'Projet de politique v0.2, engagement 2', 'مسودة السياسة 0.2، الالتزام 2')),
    row(L('§5.2.1 d) Commitment to continual improvement', '§5.2.1 d) Engagement d\'amélioration continue', '§5.2.1 د) الالتزام بالتحسين المستمر'), C.commit, L('"Continually improve our quality management system".', '« Améliorer en continu notre système de management de la qualité ».', '"التحسين المستمر لنظام إدارة الجودة".'), 'High', L('Policy draft v0.2, commitment 4', 'Projet de politique v0.2, engagement 4', 'مسودة السياسة 0.2، الالتزام 4')),
  ] }),
  'MP-002.5': (c) => ({ evidence: L('Policy cross-checked with the strategic plan 2025–2027 and the requirements matrix: two wording changes (customer proof of service, 2027 direction). No conflict with customer contracts.', 'Politique comparée au plan stratégique 2025–2027 et à la matrice des exigences : deux changements de formulation (preuve de service, orientation 2027). Aucun conflit avec les contrats clients.', 'تمت مقارنة السياسة بالخطة الاستراتيجية 2025–2027 ومصفوفة المتطلبات: تعديلان في الصياغة (دليل الخدمة، توجه 2027). لا تعارض مع عقود العملاء.'), completion: 100 }),
  'MP-002.12': (c) => ({
    matrix: [
      crit(L('§5.2.1 a) Appropriate to the purpose and context', '§5.2.1 a) Adaptée à la finalité et au contexte', '§5.2.1 أ) ملاءمة الغاية والسياق'), 20, 5, L('Services, customers and region described.', 'Services, clients et région décrits.', 'الخدمات والعملاء والمنطقة موصوفة.')),
      crit(L('§5.2.1 b) Framework for setting objectives', '§5.2.1 b) Cadre pour fixer les objectifs', '§5.2.1 ب) إطار لوضع الأهداف'), 20, 4, L('Measurable objectives required every year; link to KPIs to show in MP-003.', 'Objectifs mesurables exigés chaque année ; lien avec les KPI à montrer en MP-003.', 'اشتراط أهداف قابلة للقياس سنويًا؛ والربط بالمؤشرات يظهر في MP-003.')),
      crit(L('§5.2.1 c) Commitment to satisfy applicable requirements', '§5.2.1 c) Engagement à satisfaire les exigences applicables', '§5.2.1 ج) الالتزام بتلبية المتطلبات'), 20, 5, L('Explicit.', 'Explicite.', 'صريح.')),
      crit(L('§5.2.1 d) Commitment to continual improvement', '§5.2.1 d) Engagement d\'amélioration continue', '§5.2.1 د) الالتزام بالتحسين المستمر'), 20, 5, L('Explicit.', 'Explicite.', 'صريح.')),
      crit(L('§5.2.2 Available, communicated, understood', '§5.2.2 Disponible, communiquée, comprise', '§5.2.2 متاحة ومبلّغة ومفهومة'), 20, 3, L('Communication plan ready (step 11); understanding to check in the next internal audit.', 'Plan de communication prêt (étape 11) ; compréhension à vérifier au prochain audit interne.', 'خطة التواصل جاهزة (الخطوة 11)؛ والفهم يُتحقق منه في التدقيق الداخلي القادم.')),
    ],
    rationale: L('Draft meets ISO 9001 §5.2.1 (weighted score 4.4). §5.2.2 will be met once the communication step is done. Ready for top management approval.', 'Le projet satisfait ISO 9001 §5.2.1 (note pondérée 4,4). §5.2.2 sera satisfait une fois l\'étape de communication réalisée. Prêt pour l\'approbation de la direction.', 'المسودة تستوفي ISO 9001 §5.2.1 (الدرجة المرجحة 4.4). ويُستوفى §5.2.2 بعد إتمام خطوة التواصل. جاهزة لموافقة الإدارة العليا.'),
  }),
  'MP-002.6': (c) => ({
    criteria: [
      { criterion: L('Compliance check against ISO 9001 §5.2 done', 'Vérification de conformité ISO 9001 §5.2 faite', 'تم التحقق من المطابقة مع ISO 9001 §5.2'), met: 'Yes', evidence: L('Decision matrix, step 8 (score 4.4)', 'Matrice de décision, étape 8 (note 4,4)', 'مصفوفة القرار، الخطوة 8 (الدرجة 4.4)') },
      { criterion: L('Consistent with strategic direction', 'Cohérente avec l\'orientation stratégique', 'متسقة مع التوجه الاستراتيجي'), met: 'Yes', evidence: L('Strategic plan 2025–2027', 'Plan stratégique 2025–2027', 'الخطة الاستراتيجية 2025–2027') },
    ],
    decision: 'Go', approver: 'top_management', comment: L('Approved and signed by the Managing Director. Publish version 1.0.', 'Approuvée et signée par le directeur général. Publier la version 1.0.', 'تمت الموافقة والتوقيع من المدير العام. يُنشر الإصدار 1.0.'),
  }),
  'MP-002.13': (c) => ({ result: fv(L('Quality policy v1.0 published; DOCX and PDF generated; notice-board version printed.', 'Politique qualité v1.0 publiée ; DOCX et PDF générés ; version d\'affichage imprimée.', 'نُشرت سياسة الجودة الإصدار 1.0؛ وتم توليد ملفي DOCX وPDF؛ وطُبعت نسخة للوحة الإعلانات.'), c.v) }),
  'MP-002.7': (c) => ({ messages: [
    { audience: [c.obsName('Operations')], channel: 'Meeting', date: addDays(c.due, -1), message: L('Toolbox talk: what the policy means for each job (right first time, signed job sheet).', 'Causerie : ce que la politique signifie pour chaque métier (bien du premier coup, fiche signée).', 'حديث قصير: ماذا تعني السياسة لكل وظيفة (صحيح من المرة الأولى، بطاقة عمل موقعة).'), by: 'ims_manager' },
    { audience: [{ id: null, name: L('All employees', 'Tout le personnel', 'جميع الموظفين') }], channel: 'Notice board', date: c.due, message: L('Signed policy posted in the workshop and the office.', 'Politique signée affichée à l\'atelier et au bureau.', 'تعليق السياسة الموقعة في الورشة والمكتب.'), by: 'document_controller' },
    { audience: [{ id: null, name: L('Customers and interested parties', 'Clients et parties intéressées', 'العملاء والأطراف المعنية') }], channel: 'Portal', date: addDays(c.due, 2), message: L('Policy published on the website.', 'Politique publiée sur le site web.', 'نشر السياسة على الموقع الإلكتروني.'), by: 'ims_manager' },
  ] }),
  'MP-002.8': (c) => ({
    frequency: 'Annual', date: c.due, nextDate: addDays(c.due, 365), chair: 'top_management', participants: ['ims_manager', 'quality_manager', 'operations_manager'],
    inputs: [
      { input: L('Changes in context and strategy', 'Changements du contexte et de la stratégie', 'تغيرات السياق والاستراتيجية'), finding: L('New maintenance contract segment.', 'Nouveau segment de contrats de maintenance.', 'شريحة جديدة من عقود الصيانة.') },
      { input: L('Achievement of quality objectives', 'Atteinte des objectifs qualité', 'تحقيق أهداف الجودة'), finding: L('3 of 4 objectives on track.', '3 objectifs sur 4 dans les temps.', '3 من 4 أهداف في المسار.') },
      { input: L('Audit results and staff feedback', 'Résultats d\'audit et retours du personnel', 'نتائج التدقيق وملاحظات الموظفين'), finding: L('Policy known by 90% of interviewed staff.', 'Politique connue par 90 % du personnel interrogé.', 'السياسة معروفة لـ 90% من الموظفين الذين تمت مقابلتهم.') },
    ],
    decisions: [{ decision: L('Add a confidentiality commitment for customer data', 'Ajouter un engagement de confidentialité des données clients', 'إضافة التزام بسرية بيانات العملاء'), owner: c.user('ims_manager'), due: addDays(c.due, 20) }],
  }),
  'MP-002.9': (c) => ({ change: L('Added a commitment on confidentiality of customer data (new maintenance contracts). Version 1.1 issued.', 'Ajout d\'un engagement de confidentialité des données clients (nouveaux contrats de maintenance). Version 1.1 émise.', 'إضافة التزام بسرية بيانات العملاء (عقود الصيانة الجديدة). صدر الإصدار 1.1.'), reason: L('Decision D-1 of the policy review', 'Décision D-1 de la revue de politique', 'القرار D-1 لمراجعة السياسة') }),
  // ------------------------------------------------------------ MP-003 Objectives
  'MP-003.1': (c) => ({ objectives: c.objectives.slice(0, 2) }),
  'MP-003.2': (c) => ({ objectives: c.objectives }),
  'MP-003.10': (c) => ({ objectives: c.objectives.slice(2) }),
  'MP-003.3': (c) => ({ evidence: L('Each objective linked to a policy commitment and to one KPI of the dashboard; no objective without an owner.', 'Chaque objectif est relié à un engagement de la politique et à un KPI du tableau de bord ; aucun objectif sans responsable.', 'كل هدف مرتبط بالتزام في السياسة وبمؤشر في لوحة المتابعة؛ ولا هدف دون مسؤول.'), completion: 100 }),
  'MP-003.4': (c) => ({ activities: c.objectives.map((o, i) => ({ activity: fv(L('Build the action plan for: {x}', 'Construire le plan d\'actions pour : {x}', 'إعداد خطة العمل لـ: {x}'), { x: o.objective }), owner: o.owner, start: c.due, due: addDays(c.due, 21 + i * 7), deliverable: L('Action plan approved', 'Plan d\'actions approuvé', 'خطة عمل معتمدة') })) }),
  'MP-003.7': (c) => ({ evidence: L('Objectives board displayed in the workshop and the office; monthly results updated by the Performance Manager.', 'Tableau des objectifs affiché à l\'atelier et au bureau ; résultats mensuels mis à jour par le responsable performance.', 'لوحة الأهداف معروضة في الورشة والمكتب؛ ويحدّث مدير الأداء النتائج شهريًا.'), completion: 100 }),
  // ------------------------------------------------------------ MP-004 Process architecture
  'MP-004.1': (c) => ({ items: [
    row(fv(L('All activities of {org} in the {city} region', 'Toutes les activités de {org} dans la région de {city}', 'جميع أنشطة {org} في منطقة {city}'), c.v), C.scope, L('Same boundary as the management system scope (MP-001 step 8).', 'Même limite que le périmètre du système (MP-001 étape 8).', 'نفس حدود نطاق نظام الإدارة (MP-001 الخطوة 8).'), 'High', L('Scope statement v1.0', 'Énoncé du périmètre v1.0', 'بيان النطاق الإصدار 1.0')),
    row(L('Three levels: macro process > task > step', 'Trois niveaux : macro-processus > tâche > étape', 'ثلاثة مستويات: عملية كلية > مهمة > خطوة'), L('Modeling rule', 'Règle de modélisation', 'قاعدة النمذجة'), L('Steps are the lowest level and carry the forms and records.', 'Les étapes sont le plus bas niveau et portent les formulaires et enregistrements.', 'الخطوات هي أدنى مستوى وتحمل النماذج والسجلات.'), 'Medium', L('Process level definitions', 'Définitions des niveaux de processus', 'تعريفات مستويات العمليات')),
  ] }),
  'MP-004.2': (c) => ({ items: [
    row(L('Strategy and management review', 'Stratégie et revue de direction', 'الاستراتيجية ومراجعة الإدارة'), C.mgmt, L('Owner: Managing Director', 'Pilote : directeur général', 'المالك: المدير العام'), 'High', L('Organization chart', 'Organigramme', 'الهيكل التنظيمي')),
    row(L('Sales and quotation', 'Commercial et devis', 'المبيعات والعروض'), C.core, L('Owner: Operations Manager', 'Pilote : responsable des opérations', 'المالك: مدير العمليات'), 'High', L('Organization chart', 'Organigramme', 'الهيكل التنظيمي')),
    row(fv(L('Delivery of {product}', 'Réalisation des {product}', 'تقديم {product}'), c.v), C.core, L('Owner: Operations Manager', 'Pilote : responsable des opérations', 'المالك: مدير العمليات'), 'High', L('Job orders', 'Ordres de travail', 'أوامر العمل')),
    row(L('Purchasing and suppliers', 'Achats et fournisseurs', 'المشتريات والموردون'), C.supp, L('Owner: Quality Manager', 'Pilote : responsable qualité', 'المالك: مدير الجودة'), 'Medium', L('Purchase procedure', 'Procédure achats', 'إجراء المشتريات')),
    row(L('People and competence', 'Personnes et compétences', 'الأشخاص والكفاءات'), C.supp, L('Owner: HR Manager', 'Pilote : responsable RH', 'المالك: مدير الموارد البشرية'), 'Medium', L('Competence matrix', 'Matrice des compétences', 'مصفوفة الكفاءات')),
    row(L('Measurement, audit and improvement', 'Mesure, audit et amélioration', 'القياس والتدقيق والتحسين'), C.mgmt, L('Owner: Quality Manager', 'Pilote : responsable qualité', 'المالك: مدير الجودة'), 'Medium', L('Audit programme', 'Programme d\'audit', 'برنامج التدقيق')),
  ] }),
  'MP-004.3': (c) => ({ items: [
    row(fv(L('Delivery of {product}: request → planning → intervention → signed job sheet → invoice', 'Réalisation des {product} : demande → planification → intervention → fiche signée → facture', 'تقديم {product}: الطلب ← التخطيط ← التدخل ← بطاقة عمل موقعة ← الفاتورة'), c.v), L('BPMN diagram', 'Diagramme BPMN', 'مخطط BPMN'), L('Two lanes (Operations, Customer); gateway "job sheet signed?" before invoicing.', 'Deux couloirs (Opérations, Client) ; passerelle « fiche signée ? » avant facturation.', 'مساران (العمليات، العميل)؛ وبوابة "هل البطاقة موقعة؟" قبل الفوترة.'), 'High', L('Process workshop with the technicians', 'Atelier processus avec les techniciens', 'ورشة العمليات مع الفنيين')),
    row(L('Sales and quotation: request → site visit → quote → second check → customer approval', 'Commercial et devis : demande → visite → devis → double contrôle → accord client', 'المبيعات والعروض: الطلب ← الزيارة ← العرض ← المراجعة الثانية ← موافقة العميل'), L('BPMN diagram', 'Diagramme BPMN', 'مخطط BPMN'), L('Second check added to prevent quote errors.', 'Double contrôle ajouté pour éviter les erreurs de devis.', 'أضيفت مراجعة ثانية لمنع أخطاء العروض.'), 'High', L('Quotation register', 'Registre des devis', 'سجل العروض')),
    row(L('Purchasing: need → order → reception check → stock', 'Achats : besoin → commande → contrôle réception → stock', 'المشتريات: الحاجة ← الطلب ← فحص الاستلام ← المخزون'), L('BPMN diagram', 'Diagramme BPMN', 'مخطط BPMN'), L('Reception check against the order.', 'Contrôle réception par rapport à la commande.', 'فحص الاستلام مقارنة بالطلب.'), 'Medium', L('Purchase orders', 'Commandes', 'أوامر الشراء')),
  ] }),
  'MP-004.5': (c) => ({
    criteria: [
      { criterion: L('Every process has an owner', 'Chaque processus a un pilote', 'لكل عملية مالك'), met: 'Yes', evidence: L('RACSI matrix', 'Matrice RACSI', 'مصفوفة RACSI') },
      { criterion: L('Inputs, outputs and interactions shown', 'Entrées, sorties et interactions indiquées', 'إظهار المدخلات والمخرجات والتفاعلات'), met: 'Yes', evidence: L('Process map v0.9', 'Cartographie v0.9', 'خريطة العمليات 0.9') },
      { criterion: L('Owners agree with their process description', 'Les pilotes valident la description de leur processus', 'موافقة المالكين على وصف عملياتهم'), met: 'Yes', evidence: L('Validation meeting minutes', 'Compte rendu de validation', 'محضر اجتماع المصادقة') },
    ],
    decision: 'Go', approver: 'process_excellence_manager', comment: L('Process map validated; publish version 1.0.', 'Cartographie validée ; publier la version 1.0.', 'تمت المصادقة على خريطة العمليات؛ يُنشر الإصدار 1.0.'),
  }),
  'MP-004.6': (c) => ({
    matrix: [
      crit(L('§4.4.1 a–b) Inputs, outputs, sequence and interaction determined', '§4.4.1 a–b) Entrées, sorties, séquence et interactions déterminées', '§4.4.1 أ–ب) تحديد المدخلات والمخرجات والتسلسل والتفاعل'), 25, 4, L('All core processes modeled in BPMN.', 'Tous les processus de réalisation modélisés en BPMN.', 'نمذجة جميع العمليات الأساسية بـ BPMN.')),
      crit(L('§4.4.1 c) Criteria, methods and KPIs', '§4.4.1 c) Critères, méthodes et KPI', '§4.4.1 ج) المعايير والطرق والمؤشرات'), 25, 3, L('KPIs defined for core processes; support processes to complete.', 'KPI définis pour la réalisation ; processus support à compléter.', 'المؤشرات محددة للعمليات الأساسية؛ والداعمة تحتاج استكمالًا.')),
      crit(L('§4.4.1 d–e) Resources, responsibilities and authorities', '§4.4.1 d–e) Ressources, responsabilités et autorités', '§4.4.1 د–هـ) الموارد والمسؤوليات والصلاحيات'), 25, 4, L('RACSI for every macro process.', 'RACSI pour chaque macro-processus.', 'مصفوفة RACSI لكل عملية كلية.')),
      crit(L('§4.4.1 f) Risks and opportunities addressed', '§4.4.1 f) Risques et opportunités traités', '§4.4.1 و) معالجة المخاطر والفرص'), 25, 3, L('Linked to the risk register; 2 processes without risk review.', 'Lien avec le registre des risques ; 2 processus sans revue des risques.', 'مرتبطة بسجل المخاطر؛ وعمليتان دون مراجعة للمخاطر.')),
    ],
    rationale: L('Process approach in place (weighted score 3.5). Complete KPIs and risk review for purchasing and HR before the mock audit.', 'Approche processus en place (note pondérée 3,5). Compléter KPI et revue des risques pour achats et RH avant l\'audit à blanc.', 'نهج العمليات قائم (الدرجة المرجحة 3.5). يُستكمل تحديد المؤشرات ومراجعة المخاطر للمشتريات والموارد البشرية قبل التدقيق التجريبي.'),
  }),
};

// SMART objectives of a run (MP-003), consistent with the objectives register.
export function smartObjectives(c) {
  const k = (code) => c.kpiByCode[code];
  const mk = (objective, code, baseline, relevance, ownerRole, months, resources) => ({
    objective, kpi: k(code)?.id || null, baseline, target: k(code)?.targetText || '', relevance, owner: c.user(ownerRole), deadline: addDays(c.start, 30 * months), resources,
  });
  const list = [
    mk(fv(L('Raise customer satisfaction on {product}', 'Augmenter la satisfaction client sur les {product}', 'رفع رضا العملاء عن {product}'), c.v), 'Q-KPI-01', '78%', L('Satisfy customer requirements', 'Satisfaire les exigences clients', 'تلبية متطلبات العملاء'), 'quality_manager', 12, L('Quarterly survey; complaint review meeting', 'Enquête trimestrielle ; réunion de revue des réclamations', 'استبيان ربع سنوي؛ اجتماع مراجعة الشكاوى')),
    mk(fv(L('Deliver {product} on time', 'Réaliser les {product} dans les délais', 'تقديم {product} في الموعد'), c.v), 'Q-KPI-02', '86%', L('On time, right first time', 'À temps, du premier coup', 'في الموعد ومن المرة الأولى'), 'operations_manager', 9, L('Planning board; one extra technician in summer', 'Planning ; un technicien de plus l\'été', 'لوحة التخطيط؛ فني إضافي في الصيف')),
    mk(L('Reduce the cost of poor quality', 'Réduire le coût de la non-qualité', 'خفض تكلفة ضعف الجودة'), 'Q-KPI-04', '4.1%', L('Continual improvement', 'Amélioration continue', 'التحسين المستمر'), 'quality_manager', 12, L('Rework tracking in the NC register', 'Suivi des reprises dans le registre NC', 'تتبع إعادة العمل في سجل عدم المطابقة')),
    mk(L('Close corrective actions on time', 'Clôturer les actions correctives à temps', 'إغلاق الإجراءات التصحيحية في موعدها'), 'Q-KPI-05', '70%', L('Continual improvement', 'Amélioration continue', 'التحسين المستمر'), 'ims_manager', 6, L('Weekly action review', 'Revue hebdomadaire des actions', 'مراجعة أسبوعية للإجراءات')),
  ];
  return list.filter(o => o.kpi);
}
