// Platform libraries: SME tracks, complexity criteria, Gate Library, Checklist
// Library and Project Template Catalog (SRS 4.29, 4.30, 4.23, 4.33, 4.35).
const S = (en, fr, ar) => ({ en, fr, ar });

export const SME_TRACKS = [
  { code: 'TRK-LIGHT', name: S('Light track', 'Parcours léger', 'المسار الخفيف'), description: S('Micro and small companies: essential processes, 2 gates, 8 weeks.', 'Micro et petites entreprises : processus essentiels, 2 jalons, 8 semaines.', 'المؤسسات الصغيرة جدًا والصغيرة: العمليات الأساسية، بوابتان، 8 أسابيع.'), mp: 3, e2e: 2, gates: 2, items: 6, weeks: 8, min: 0, max: 35 },
  { code: 'TRK-STANDARD', name: S('Standard track', 'Parcours standard', 'المسار القياسي'), description: S('Small and medium companies seeking first certification: 4 gates, 16 weeks.', 'PME visant une première certification : 4 jalons, 16 semaines.', 'المؤسسات الصغيرة والمتوسطة الساعية لأول اعتماد: 4 بوابات، 16 أسبوعًا.'), mp: 4, e2e: 4, gates: 4, items: 8, weeks: 16, min: 35, max: 65 },
  { code: 'TRK-ADVANCED', name: S('Advanced track', 'Parcours avancé', 'المسار المتقدم'), description: S('Medium companies with multi-standard or regulated scope: 6 gates, 26 weeks.', 'Moyennes entreprises multi-normes ou réglementées : 6 jalons, 26 semaines.', 'المؤسسات المتوسطة متعددة المعايير أو الخاضعة للتنظيم: 6 بوابات، 26 أسبوعًا.'), mp: 5, e2e: 6, gates: 6, items: 10, weeks: 26, min: 65, max: 100 },
];

const LV = (a, b, c, d, e) => [a, b, c, d, e];
export const COMPLEXITY_CRITERIA = [
  { code: 'CX-01', name: S('Strategic impact', 'Impact stratégique', 'الأثر الاستراتيجي'), weight: 20, levels: LV(S('Local improvement', 'Amélioration locale', 'تحسين محلي'), S('Department', 'Service', 'قسم'), S('Business unit', 'Unité', 'وحدة أعمال'), S('Whole company', 'Toute l\'entreprise', 'المؤسسة بأكملها'), S('Group-wide', 'Tout le groupe', 'المجموعة بأكملها')) },
  { code: 'CX-02', name: S('Technical novelty', 'Nouveauté technique', 'الحداثة التقنية'), weight: 10, levels: LV(S('Known practice', 'Pratique connue', 'ممارسة معروفة'), S('Minor change', 'Changement mineur', 'تغيير طفيف'), S('New method', 'Nouvelle méthode', 'طريقة جديدة'), S('New technology', 'Nouvelle technologie', 'تقنية جديدة'), S('First of a kind', 'Inédit', 'غير مسبوق')) },
  { code: 'CX-03', name: S('Regulatory burden', 'Charge réglementaire', 'العبء التنظيمي'), weight: 20, levels: LV(S('None', 'Aucune', 'لا يوجد'), S('Voluntary standard', 'Norme volontaire', 'معيار طوعي'), S('Customer-mandated', 'Exigée par le client', 'مفروض من العميل'), S('Regulated sector', 'Secteur réglementé', 'قطاع خاضع للتنظيم'), S('Licence-critical', 'Critique pour la licence', 'حرج للترخيص')) },
  { code: 'CX-04', name: S('Investment size', 'Montant d\'investissement', 'حجم الاستثمار'), weight: 15, levels: LV(S('< 10k', '< 10 k', '< 10 آلاف'), S('10–50k', '10–50 k', '10–50 ألفًا'), S('50–250k', '50–250 k', '50–250 ألفًا'), S('250k–1M', '250 k–1 M', '250 ألفًا–مليون'), S('> 1M', '> 1 M', '> مليون')) },
  { code: 'CX-05', name: S('Cross-functional scope', 'Périmètre transverse', 'النطاق متعدد الوظائف'), weight: 15, levels: LV(S('1 function', '1 fonction', 'وظيفة واحدة'), S('2 functions', '2 fonctions', 'وظيفتان'), S('3–4 functions', '3–4 fonctions', '3–4 وظائف'), S('5–8 functions', '5–8 fonctions', '5–8 وظائف'), S('All functions and sites', 'Toutes fonctions et sites', 'جميع الوظائف والمواقع')) },
  { code: 'CX-06', name: S('Market uncertainty', 'Incertitude du marché', 'عدم اليقين في السوق'), weight: 10, levels: LV(S('Stable', 'Stable', 'مستقر'), S('Low', 'Faible', 'منخفض'), S('Moderate', 'Modérée', 'متوسط'), S('High', 'Élevée', 'مرتفع'), S('Very high', 'Très élevée', 'مرتفع جدًا')) },
  { code: 'CX-07', name: S('Time-to-market pressure', 'Pression sur les délais', 'ضغط الوقت'), weight: 10, levels: LV(S('None', 'Aucune', 'لا يوجد'), S('Low', 'Faible', 'منخفض'), S('Moderate', 'Modérée', 'متوسط'), S('High', 'Élevée', 'مرتفع'), S('Critical deadline', 'Échéance critique', 'موعد حرج')) },
];
// Vertical-specific drivers (FR-DA-SCO-03)
export const VERTICAL_DRIVERS = {
  AUT: { name: S('Functional safety (ASIL) exposure', 'Exposition à la sécurité fonctionnelle (ASIL)', 'التعرض للسلامة الوظيفية (ASIL)'), weight: 10 },
  AER: { name: S('Export control (ITAR/EAR)', 'Contrôle des exportations (ITAR/EAR)', 'ضبط الصادرات (ITAR/EAR)'), weight: 10 },
  HLS: { name: S('Patient risk class', 'Classe de risque patient', 'فئة المخاطر على المريض'), weight: 10 },
  PHM: { name: S('GMP criticality', 'Criticité BPF', 'حرجية ممارسات التصنيع الجيدة'), weight: 10 },
  FNB: { name: S('Food safety hazard level', 'Niveau de danger sécurité des aliments', 'مستوى خطر سلامة الأغذية'), weight: 10 },
  PCH: { name: S('Process safety (PSM) exposure', 'Exposition sécurité des procédés (PSM)', 'التعرض لسلامة العمليات (PSM)'), weight: 10 },
  AEC: { name: S('Structural and site safety exposure', 'Exposition structurelle et sécurité chantier', 'التعرض الإنشائي وسلامة الموقع'), weight: 10 },
};

// One gate per E2E phase of the lifecycle (Gate Library).
export const GATES = [
  ['E2E-01', S('G1 — Strategy baseline approved', 'J1 — Référence stratégique approuvée', 'ب1 — اعتماد خط الأساس الاستراتيجي'), S('Context, policy, objectives and risk register approved by top management.', 'Contexte, politique, objectifs et registre des risques approuvés par la direction.', 'اعتماد السياق والسياسة والأهداف وسجل المخاطر من الإدارة العليا.')],
  ['E2E-02', S('G2 — People and communication ready', 'J2 — Personnes et communication prêtes', 'ب2 — جاهزية الأفراد والتواصل'), S('Competence matrix, communication plan and qualified auditors in place.', 'Matrice des compétences, plan de communication et auditeurs qualifiés en place.', 'مصفوفة الكفاءات وخطة التواصل والمدققون المؤهلون قائمون.')],
  ['E2E-03', S('G3 — Risk controls effective', 'J3 — Maîtrise des risques efficace', 'ب3 — فعالية ضوابط المخاطر'), S('Key controls tested; continuity plan tested; safety cases approved where applicable.', 'Contrôles clés testés ; PCA testé ; dossiers de sécurité approuvés le cas échéant.', 'اختبار الضوابط الرئيسية وخطة الاستمرارية؛ واعتماد ملفات السلامة عند الاقتضاء.')],
  ['E2E-04', S('G4 — Ready for certification', 'J4 — Prêt pour la certification', 'ب4 — الجاهزية للاعتماد'), S('Mock audit closed; no open major finding; certification body scheduled.', 'Audit à blanc clôturé ; aucun écart majeur ouvert ; organisme de certification planifié.', 'إغلاق التدقيق التجريبي؛ لا ملاحظة رئيسية مفتوحة؛ جدولة جهة الاعتماد.')],
  ['E2E-05', S('G5 — Documented information controlled', 'J5 — Informations documentées maîtrisées', 'ب5 — ضبط المعلومات الموثقة'), S('Documents approved and distributed; records retention defined; equipment calibrated.', 'Documents approuvés et diffusés ; conservation définie ; équipements étalonnés.', 'اعتماد الوثائق وتوزيعها؛ تحديد مدد الاحتفاظ؛ معايرة المعدات.')],
  ['E2E-06', S('G6 — Infrastructure secured', 'J6 — Infrastructure sécurisée', 'ب6 — تأمين البنية التحتية'), S('Access rights recertified; data protection register complete; assets under maintenance plan.', 'Droits d\'accès recertifiés ; registre de protection des données complet ; actifs sous plan de maintenance.', 'إعادة اعتماد صلاحيات الوصول؛ اكتمال سجل حماية البيانات؛ الأصول ضمن خطة الصيانة.')],
  ['E2E-07', S('G7 — Data and formulas governed', 'J7 — Données et formules gouvernées', 'ب7 — حوكمة البيانات والصيغ'), S('Master data owners named; KPI formulas validated before activation.', 'Propriétaires des données désignés ; formules des KPI validées avant activation.', 'تسمية مالكي البيانات الرئيسية؛ التحقق من صيغ المؤشرات قبل التفعيل.')],
  ['E2E-08', S('G8 — Operations under control', 'J8 — Opérations maîtrisées', 'ب8 — العمليات تحت السيطرة'), S('Control plans active; approved supplier list current; traceability tested.', 'Plans de surveillance actifs ; liste des fournisseurs homologués à jour ; traçabilité testée.', 'خطط الضبط فعالة؛ قائمة الموردين المعتمدين محدثة؛ اختبار التتبع.')],
  ['E2E-09', S('G9 — Problem solving effective', 'J9 — Résolution de problèmes efficace', 'ب9 — فعالية حل المشكلات'), S('Critical NCs contained within 24 h; corrective actions verified by an independent evaluator.', 'NC critiques contenues sous 24 h ; actions correctives vérifiées par un évaluateur indépendant.', 'احتواء حالات عدم المطابقة الحرجة خلال 24 ساعة؛ تحقق مقيّم مستقل من الإجراءات التصحيحية.')],
  ['E2E-10', S('G10 — Performance reviewed', 'J10 — Performance revue', 'ب10 — مراجعة الأداء'), S('KPIs measured for three periods; management review held; internal audit programme on track.', 'KPI mesurés sur trois périodes ; revue de direction tenue ; programme d\'audit interne à jour.', 'قياس المؤشرات لثلاث فترات؛ عقد مراجعة الإدارة؛ برنامج التدقيق الداخلي في مساره.')],
  ['E2E-11', S('G11 — Assurance in place', 'J11 — Assurance en place', 'ب11 — الضمان قائم'), S('Predictive alerts reviewed by humans; ESG and carbon data verified.', 'Alertes prédictives revues par des humains ; données ESG et carbone vérifiées.', 'مراجعة التنبيهات التنبؤية بشريًا؛ التحقق من بيانات الاستدامة والكربون.')],
  ['E2E-12', S('G12 — Improvement cycle closed', 'J12 — Cycle d\'amélioration bouclé', 'ب12 — إغلاق دورة التحسين'), S('Improvement pipeline prioritized by ROI; lessons learned capitalized in the knowledge base.', 'Pipeline d\'amélioration priorisé par ROI ; enseignements capitalisés dans la base de connaissances.', 'ترتيب مسار التحسين حسب العائد؛ الاستفادة من الدروس في قاعدة المعرفة.')],
];

const CI = (en, fr, ar, mandatory = true, evidence = true) => ({ text: S(en, fr, ar), mandatory, evidence });
export const CHECKLISTS = {
  'E2E-01': [CI('Context analysis report approved', 'Rapport d\'analyse du contexte approuvé', 'اعتماد تقرير تحليل السياق'), CI('Management system policy signed', 'Politique du système de management signée', 'توقيع سياسة نظام الإدارة'), CI('SMART objectives cascaded to functions', 'Objectifs SMART déclinés aux fonctions', 'تفريع الأهداف الذكية إلى الوظائف'), CI('Risk and opportunity register reviewed', 'Registre des risques et opportunités revu', 'مراجعة سجل المخاطر والفرص'), CI('Process map published', 'Cartographie des processus publiée', 'نشر خريطة العمليات', false)],
  'E2E-02': [CI('Competence matrix complete', 'Matrice des compétences complète', 'اكتمال مصفوفة الكفاءات'), CI('Communication plan approved', 'Plan de communication approuvé', 'اعتماد خطة التواصل'), CI('Internal auditors qualified (ISO 19011)', 'Auditeurs internes qualifiés (ISO 19011)', 'تأهيل المدققين الداخليين (ISO 19011)')],
  'E2E-03': [CI('Key controls tested', 'Contrôles clés testés', 'اختبار الضوابط الرئيسية'), CI('Business continuity plan tested', 'PCA testé', 'اختبار خطة استمرارية الأعمال'), CI('Third-party risk scores assigned', 'Scores de risque tiers attribués', 'إسناد درجات مخاطر الأطراف الثالثة', false)],
  'E2E-04': [CI('Mock audit report issued', 'Rapport d\'audit à blanc émis', 'إصدار تقرير التدقيق التجريبي'), CI('All major findings closed', 'Tous les écarts majeurs clôturés', 'إغلاق جميع الملاحظات الرئيسية'), CI('Certification body contract signed', 'Contrat avec l\'organisme de certification signé', 'توقيع عقد جهة الاعتماد')],
  'E2E-05': [CI('Master document list current', 'Liste maîtresse des documents à jour', 'القائمة الرئيسية للوثائق محدثة'), CI('Retention schedule approved', 'Calendrier de conservation approuvé', 'اعتماد جدول الاحتفاظ'), CI('Calibration status 100%', 'Statut d\'étalonnage à 100 %', 'حالة المعايرة 100%')],
  'E2E-06': [CI('Access rights recertified', 'Droits d\'accès recertifiés', 'إعادة اعتماد صلاحيات الوصول'), CI('Processing register complete', 'Registre des traitements complet', 'اكتمال سجل المعالجة'), CI('Asset register reconciled', 'Registre des actifs rapproché', 'مطابقة سجل الأصول', false)],
  'E2E-07': [CI('Data owners designated', 'Propriétaires des données désignés', 'تعيين مالكي البيانات'), CI('KPI formulas validated', 'Formules des KPI validées', 'التحقق من صيغ المؤشرات')],
  'E2E-08': [CI('Control plans released', 'Plans de surveillance diffusés', 'إصدار خطط الضبط'), CI('Approved supplier list current', 'Liste des fournisseurs homologués à jour', 'قائمة الموردين المعتمدين محدثة'), CI('Traceability test passed', 'Test de traçabilité réussi', 'اجتياز اختبار التتبع')],
  'E2E-09': [CI('Containment within 24 h for critical NCs', 'Confinement sous 24 h des NC critiques', 'الاحتواء خلال 24 ساعة لحالات عدم المطابقة الحرجة'), CI('Root cause validated for major NCs', 'Cause racine validée pour les NC majeures', 'المصادقة على السبب الجذري لحالات عدم المطابقة الرئيسية'), CI('Effectiveness verified by independent evaluator', 'Efficacité vérifiée par un évaluateur indépendant', 'تحقق مقيّم مستقل من الفعالية')],
  'E2E-10': [CI('KPI dashboard live', 'Tableau de bord des KPI opérationnel', 'تشغيل لوحة المؤشرات'), CI('Management review minutes signed', 'Compte rendu de revue de direction signé', 'توقيع محضر مراجعة الإدارة'), CI('Internal audit programme ≥ 90% complete', 'Programme d\'audit interne ≥ 90 % réalisé', 'إنجاز برنامج التدقيق الداخلي بنسبة ≥ 90%')],
  'E2E-11': [CI('Predictive alerts reviewed by a human', 'Alertes prédictives revues par un humain', 'مراجعة التنبيهات التنبؤية بشريًا'), CI('Regulatory watch log current', 'Journal de veille réglementaire à jour', 'سجل الرصد التنظيمي محدث', false)],
  'E2E-12': [CI('Improvement ideas prioritized by ROI', 'Idées d\'amélioration priorisées par ROI', 'ترتيب أفكار التحسين حسب العائد'), CI('Lessons learned indexed in knowledge base', 'Enseignements indexés dans la base de connaissances', 'فهرسة الدروس المستفادة في قاعدة المعرفة')],
};

// Vertical checklists (not related to a gate; attachable to any phase).
export const VERTICAL_CHECKLISTS = {
  AUT: [CI('PPAP level 3 submission complete', 'Soumission PPAP niveau 3 complète', 'اكتمال تقديم PPAP المستوى 3'), CI('Layered process audit schedule active', 'Calendrier d\'audits LPA actif', 'جدول تدقيقات LPA فعال')],
  AEC: [CI('EN 1090 factory production control certificate valid', 'Certificat CPU EN 1090 valide', 'شهادة ضبط الإنتاج وفق EN 1090 سارية'), CI('BIM execution plan (ISO 19650) approved', 'Plan d\'exécution BIM (ISO 19650) approuvé', 'اعتماد خطة تنفيذ BIM (ISO 19650)'), CI('Site safety induction for subcontractors', 'Accueil sécurité chantier des sous-traitants', 'تعريف المقاولين من الباطن بسلامة الموقع')],
  FNB: [CI('HACCP plan verified', 'Plan HACCP vérifié', 'التحقق من خطة HACCP'), CI('Allergen matrix current', 'Matrice des allergènes à jour', 'مصفوفة مسببات الحساسية محدثة')],
  HLS: [CI('Design history file complete', 'Dossier de conception complet', 'اكتمال ملف تاريخ التصميم'), CI('ISO 14971 risk file current', 'Dossier de risques ISO 14971 à jour', 'ملف المخاطر وفق ISO 14971 محدث')],
  PHM: [CI('Data integrity (ALCOA+) review done', 'Revue d\'intégrité des données (ALCOA+) faite', 'إجراء مراجعة سلامة البيانات (ALCOA+)'), CI('Cleanroom classification current', 'Classification des salles propres à jour', 'تصنيف الغرف النظيفة محدث')],
  PCH: [CI('PHA revalidation within 5 years', 'Revalidation PHA sous 5 ans', 'إعادة المصادقة على تحليل المخاطر خلال 5 سنوات'), CI('PSSR closed before startup', 'PSSR clôturée avant démarrage', 'إغلاق مراجعة ما قبل التشغيل قبل البدء')],
  SME: [CI('Owner dashboard configured', 'Tableau de bord du dirigeant configuré', 'تهيئة لوحة معلومات المالك'), CI('Top 10 risks reviewed quarterly', 'Top 10 des risques revu chaque trimestre', 'مراجعة أبرز 10 مخاطر ربع سنويًا')],
};

export const TEMPLATE_DEFS = [
  { code: 'TPL-UNI-FULL-QMS', scope: 'universal', mode: 'FULL', ms: 'QMS', name: S('Universal QMS — full lifecycle (ISO 9001)', 'SMQ universel — cycle de vie complet (ISO 9001)', 'نظام إدارة الجودة العام — دورة الحياة الكاملة (ISO 9001)') },
  { code: 'TPL-UNI-FULL-QHSE', scope: 'universal', mode: 'FULL', ms: 'QHSE', name: S('Universal QHSE — full lifecycle (ISO 9001, 14001, 45001)', 'QHSE universel — cycle de vie complet (ISO 9001, 14001, 45001)', 'الجودة والصحة والسلامة والبيئة العام — دورة الحياة الكاملة (ISO 9001، 14001، 45001)') },
  { code: 'TPL-UNI-SME-QMS', scope: 'universal', mode: 'SME', ms: 'QMS', name: S('SME QMS — quick start', 'SMQ PME — démarrage rapide', 'نظام إدارة الجودة للمؤسسات الصغيرة — بدء سريع') },
  { code: 'TPL-UNI-SME-QHSE', scope: 'universal', mode: 'SME', ms: 'QHSE', name: S('SME QHSE — quick start', 'QHSE PME — démarrage rapide', 'الجودة والصحة والسلامة والبيئة للمؤسسات الصغيرة — بدء سريع') },
];
