// src/lib/constants.js

export const ADMIN_EMAIL = import.meta.env.VITE_ADMIN_EMAIL || 'admin@example.com'

export const SECTORS = ['Manufacturing','Logistics','Retail','Finance','Pharma','Service','Healthcare','Energy','Technology','Government']
export const PROCESS_TYPES = ['Operational - Fulfilment','Operational - Assurance','Operational Management','Strategic Management']
export const PARENT_CYCLES = ['Plan','Source','Make','Deliver','Return','Enable']
export const START_EVENT_TYPES = ['Message','Timer','UserTask','Error']
export const END_EVENT_TYPES = ['EndEvent','Message']
export const FREQUENCIES = ['Real-time','Hourly','Daily','Weekly','Monthly','Yearly','On demand','On event']
export const CRITICALITIES = ['Critical','High','Medium','Low']
export const ROI_METHODS = ['Cost reduction','Revenue uplift','Inventory reduction','Cost savings','Quality improvement','Compliance','Customer retention','Efficiency','Working capital','Resilience','Profitability','Cash flow']
export const VOI_METHODS = ['Service level improvement','Alignment','Responsiveness','Customer experience','Trust','Accuracy','Visibility','Agility','Risk reduction','Brand reputation','Employee satisfaction']
export const REUSABLE_OPTIONS = ['Yes','No']

export const DEFAULT_EDITABLE = {
  // Identity (editable)
  Process_Type: '',
  Parent_Cycle: '',
  // BPMN
  Start_Event_Type: '',
  End_Event_Type: '',
  // Operational
  Frequency: '',
  Process_Criticality: '',
  Audit_Criticality: '',
  SLA: '',
  // BPMN Readiness
  Process_Clarity: 0,
  Exception_Logic: 0,
  Data_Rule_Availability: 0,
  Automation_Suitability: 0,
  Compliance_HITL_Readiness: 0,
  // Human
  Human_judgment: 0,
  Human_ethics: 0,
  Human_accountability: 0,
  Human_regulatory_signoff: 0,
  // Workflow
  Workflow_approval_chain: 0,
  Workflow_SLA: 0,
  Workflow_exception_paths: 0,
  Workflow_handoff_complexity: 0,
  Workflow_audit_checkpoint: 0,
  // RPA
  RPA_rule_based: 0,
  RPA_structured_data: 0,
  RPA_zero_judgment: 0,
  RPA_stable: 0,
  // AI
  AI_judgment: 0,
  AI_unstructured: 0,
  AI_variability: 0,
  AI_training: 0,
  AI_risk_inverse: 0,
  // Financial
  Benefit_Annualized_USD: 0,
  Cost_OneTime_USD: 0,
  Automation_Cost_Estimate_USD: 0,
  Strategic_Alignment_Score: 0,
  VOI_risk_reduction_score: 0,
  VOI_agility_score: 0,
  VOI_brand_reputation_score: 0,
  VOI_employee_satisfaction_score: 0,
  ROI_Method: '',
  VOI_Method: '',
  // Scope
  inScope: false,
  Justification: '',
  // References
  Reusable: '',
  Standard_Mapping: '',
  Automation_KPI_IDs: '',
  Workflow_Template: '',
}

// 49 MASTER processes — read-only fields
export const MASTER_PROCESSES = [
  // ── PLAN ──
  {
    macroId: 'Plan_01', macroName: 'Demand sensing & forecast', capabilityCluster: 'Demand Planning',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Plan_Lane', owningModule: 'mySCM_Plan',
    sourceModule: 'CRM, POS, ERP', consumingModules: 'S&OP, Inventory',
    triggerEvent: 'Time trigger (Weekly)', inputs: 'POS data, Sales history, Market signals',
    outputs: 'Demand forecast', inputsProviders: 'Sales, Market data feeds', beneficiaries: 'Supply planning, Finance',
    r: 'DemandPlanner', a: 'DemandLead', c: 'SalesOps', s: 'IT', i: 'Finance',
    macroGoals: 'Generate accurate demand forecast to drive supply decisions',
  },
  {
    macroId: 'Plan_02', macroName: 'S&OP consensus planning', capabilityCluster: 'S&OP',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Plan_Lane', owningModule: 'mySCM_Plan',
    sourceModule: 'Demand, Supply, Finance', consumingModules: 'Master plan, Budget',
    triggerEvent: 'Time trigger (Monthly)', inputs: 'Demand plan, Supply capacity, Financial targets',
    outputs: 'Agreed S&OP plan', inputsProviders: 'Demand planner, Supply planner, Finance', beneficiaries: 'Executive, Operations',
    r: 'SOP_Manager', a: 'COO', c: 'Finance, Sales', s: 'IT', i: 'Board',
    macroGoals: 'Align demand and supply plans with financial targets',
  },
  {
    macroId: 'Plan_03', macroName: 'Master production scheduling', capabilityCluster: 'Production Planning',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Plan_Lane', owningModule: 'mySCM_Plan',
    sourceModule: 'S&OP, Capacity', consumingModules: 'Manufacturing, Procurement',
    triggerEvent: 'Time trigger (Weekly)', inputs: 'S&OP plan, Capacity data, Open orders',
    outputs: 'Master production schedule', inputsProviders: 'S&OP, Operations', beneficiaries: 'Manufacturing, Procurement',
    r: 'MPS_Planner', a: 'PlannngLead', c: 'Manufacturing', s: 'IT', i: 'Procurement',
    macroGoals: 'Create feasible production schedule aligned with demand and capacity',
  },
  {
    macroId: 'Plan_04', macroName: 'Inventory policy management', capabilityCluster: 'Inventory Optimisation',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Plan_Lane', owningModule: 'mySCM_Plan',
    sourceModule: 'ERP, WMS', consumingModules: 'Replenishment, S&OP',
    triggerEvent: 'Time trigger (Monthly)', inputs: 'Lead times, Service targets, Demand variability',
    outputs: 'Safety stock levels, Reorder points', inputsProviders: 'Analytics, Supply chain', beneficiaries: 'Warehouse, Finance',
    r: 'InvOptimiser', a: 'InvLead', c: 'Finance, Logistics', s: 'IT', i: 'Sales',
    macroGoals: 'Set optimal inventory targets to balance service and working capital',
  },
  {
    macroId: 'Plan_05', macroName: 'Supply network design', capabilityCluster: 'Network Design',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Plan_Lane', owningModule: 'mySCM_Plan',
    sourceModule: 'Finance, Operations', consumingModules: 'Logistics, Sourcing',
    triggerEvent: 'On event (Strategic review)', inputs: 'Cost data, Service requirements, Market data',
    outputs: 'Network design recommendations', inputsProviders: 'Strategy, Finance', beneficiaries: 'Operations, Executive',
    r: 'NetworkDesigner', a: 'SupplyChainDir', c: 'Finance, Ops', s: 'Consultants', i: 'Board',
    macroGoals: 'Design optimal supply network configuration to minimise cost and risk',
  },
  // ── SOURCE ──
  {
    macroId: 'Source_01', macroName: 'Supplier identification & RFQ', capabilityCluster: 'Sourcing',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Source_Lane', owningModule: 'mySCM_Source',
    sourceModule: 'ERP, Spend analytics', consumingModules: 'Procurement, Contracts',
    triggerEvent: 'Event: New sourcing need identified', inputs: 'Category requirements, Spend data, Market intel',
    outputs: 'Qualified supplier list, RFQ', inputsProviders: 'Category manager, Finance', beneficiaries: 'Procurement, Operations',
    r: 'CategoryMgr', a: 'ProcLead', c: 'Legal, Finance', s: 'IT', i: 'Operations',
    macroGoals: 'Identify and qualify suitable suppliers for category requirements',
  },
  {
    macroId: 'Source_02', macroName: 'Supplier evaluation & selection', capabilityCluster: 'Sourcing',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Source_Lane', owningModule: 'mySCM_Source',
    sourceModule: 'SRM, Procurement', consumingModules: 'Contracts, ERP',
    triggerEvent: 'Event: RFQ responses received', inputs: 'Bid responses, Supplier scorecards',
    outputs: 'Selected supplier, Award recommendation', inputsProviders: 'Suppliers, Category team', beneficiaries: 'Procurement, Finance',
    r: 'CategoryMgr', a: 'CPO', c: 'Legal, Operations', s: 'Finance', i: 'Stakeholders',
    macroGoals: 'Evaluate and select best-value supplier using structured scorecard',
  },
  {
    macroId: 'Source_03', macroName: 'Contract negotiation & award', capabilityCluster: 'Contract Management',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Source_Lane', owningModule: 'mySCM_Source',
    sourceModule: 'CLM, Legal', consumingModules: 'ERP, SRM',
    triggerEvent: 'Event: Supplier selected', inputs: 'Commercial terms, Legal requirements, Award decision',
    outputs: 'Signed contract', inputsProviders: 'Legal, Category', beneficiaries: 'Operations, Finance',
    r: 'CategoryMgr', a: 'CPO', c: 'Legal', s: 'Finance', i: 'Operations',
    macroGoals: 'Negotiate and execute supplier contract meeting commercial and legal requirements',
  },
  {
    macroId: 'Source_04', macroName: 'Purchase order creation', capabilityCluster: 'Procurement Execution',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Source_Lane', owningModule: 'mySCM_Source',
    sourceModule: 'ERP, MRP', consumingModules: 'Supplier, Warehouse',
    triggerEvent: 'Event: MRP requirement generated', inputs: 'MRP demand, Contract terms, Supplier data',
    outputs: 'Purchase order', inputsProviders: 'MRP, Planner', beneficiaries: 'Warehouse, Finance',
    r: 'Buyer', a: 'ProcLead', c: 'Finance', s: 'IT', i: 'Warehouse',
    macroGoals: 'Create and transmit purchase order to supplier for required materials',
  },
  {
    macroId: 'Source_05', macroName: 'Supplier performance monitoring', capabilityCluster: 'Supplier Management',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Source_Lane', owningModule: 'mySCM_Source',
    sourceModule: 'SRM, ERP, Quality', consumingModules: 'Sourcing, Risk',
    triggerEvent: 'Time trigger (Monthly)', inputs: 'Delivery data, Quality results, Invoice data',
    outputs: 'Supplier scorecard, Performance report', inputsProviders: 'Warehouse, Quality, Finance', beneficiaries: 'Procurement, Operations',
    r: 'SRM_Manager', a: 'ProcLead', c: 'Quality, Operations', s: 'IT', i: 'Finance',
    macroGoals: 'Monitor and improve supplier performance against agreed KPIs',
  },
  {
    macroId: 'Source_06', macroName: 'Goods receipt & inspection', capabilityCluster: 'Inbound Logistics',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Source_Lane', owningModule: 'mySCM_Source',
    sourceModule: 'WMS, ERP', consumingModules: 'Inventory, Finance',
    triggerEvent: 'Event: Delivery arrives', inputs: 'ASN, Purchase order, Physical delivery',
    outputs: 'GRN, Stock update, Quality result', inputsProviders: 'Supplier, Transport', beneficiaries: 'Warehouse, Finance, Operations',
    r: 'WarehouseClerk', a: 'WarehouseMgr', c: 'Quality, Procurement', s: 'IT', i: 'Finance',
    macroGoals: 'Receive, inspect and record incoming goods against purchase orders',
  },
  {
    macroId: 'Source_07', macroName: 'Invoice processing & payment', capabilityCluster: 'Accounts Payable',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Source_Lane', owningModule: 'mySCM_Source',
    sourceModule: 'ERP, Finance', consumingModules: 'Accounting, Bank',
    triggerEvent: 'Event: Invoice received', inputs: 'Supplier invoice, GRN, PO',
    outputs: 'Approved payment, Journal entry', inputsProviders: 'Supplier, Warehouse', beneficiaries: 'Finance, Supplier',
    r: 'APClerk', a: 'FinanceMgr', c: 'Procurement', s: 'IT', i: 'Supplier',
    macroGoals: 'Process supplier invoices through 3-way match and authorise payment',
  },
  // ── MAKE ──
  {
    macroId: 'Make_01', macroName: 'Work order creation & release', capabilityCluster: 'Production Control',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Make_Lane', owningModule: 'mySCM_Make',
    sourceModule: 'MPS, ERP', consumingModules: 'Shop floor, WMS',
    triggerEvent: 'Event: MPS triggered work order', inputs: 'MPS, BOM, Routing',
    outputs: 'Work order', inputsProviders: 'Planning, Engineering', beneficiaries: 'Manufacturing, Warehouse',
    r: 'ProductionPlanner', a: 'ProdLead', c: 'Engineering', s: 'IT', i: 'Quality',
    macroGoals: 'Create and release work orders to production floor for scheduled output',
  },
  {
    macroId: 'Make_02', macroName: 'Material staging & kitting', capabilityCluster: 'Production Logistics',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Make_Lane', owningModule: 'mySCM_Make',
    sourceModule: 'WMS, Work order', consumingModules: 'Shop floor',
    triggerEvent: 'Event: Work order released', inputs: 'Work order, BOM, Warehouse stock',
    outputs: 'Kitted materials at line', inputsProviders: 'Warehouse, Planning', beneficiaries: 'Production',
    r: 'WarehouseClerk', a: 'ProdLead', c: 'Planning', s: 'IT', i: 'Quality',
    macroGoals: 'Stage and kit all materials required for production work order',
  },
  {
    macroId: 'Make_03', macroName: 'Production execution & reporting', capabilityCluster: 'Manufacturing Execution',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Make_Lane', owningModule: 'mySCM_Make',
    sourceModule: 'MES, ERP', consumingModules: 'Quality, Inventory',
    triggerEvent: 'Event: Production starts', inputs: 'Work order, Materials, Machine capacity',
    outputs: 'Finished goods, Production report', inputsProviders: 'Operators, MES', beneficiaries: 'Warehouse, Finance',
    r: 'Operator', a: 'ProdSupervisor', c: 'Quality, Engineering', s: 'Maintenance', i: 'Finance',
    macroGoals: 'Execute production operations and record output against work order',
  },
  {
    macroId: 'Make_04', macroName: 'Quality inspection & disposition', capabilityCluster: 'Quality Management',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Make_Lane', owningModule: 'mySCM_Make',
    sourceModule: 'QMS, MES', consumingModules: 'Inventory, ERP',
    triggerEvent: 'Event: Production batch complete', inputs: 'Batch output, Quality plan, Inspection criteria',
    outputs: 'Inspection result, Disposition (pass/fail/rework)', inputsProviders: 'Quality, Production', beneficiaries: 'Warehouse, Regulatory',
    r: 'QualityInspector', a: 'QualityMgr', c: 'Regulatory, Engineering', s: 'Production', i: 'Finance',
    macroGoals: 'Inspect finished production and determine quality disposition',
  },
  {
    macroId: 'Make_05', macroName: 'Capacity planning & optimisation', capabilityCluster: 'Capacity Management',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Make_Lane', owningModule: 'mySCM_Make',
    sourceModule: 'ERP, MPS', consumingModules: 'S&OP, Production',
    triggerEvent: 'Time trigger (Weekly)', inputs: 'Production schedule, Machine availability, Labour',
    outputs: 'Capacity plan, Overload alerts', inputsProviders: 'Planning, Operations', beneficiaries: 'Production, S&OP',
    r: 'CapacityPlanner', a: 'ProdLead', c: 'HR, Maintenance', s: 'IT', i: 'Finance',
    macroGoals: 'Balance production demand against available capacity and identify constraints',
  },
  {
    macroId: 'Make_06', macroName: 'Yield & waste management', capabilityCluster: 'Production Efficiency',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Make_Lane', owningModule: 'mySCM_Make',
    sourceModule: 'MES, Quality', consumingModules: 'Finance, Sustainability',
    triggerEvent: 'Time trigger (Daily)', inputs: 'Production data, Scrap data, Material consumption',
    outputs: 'Yield report, Waste analysis', inputsProviders: 'MES, Quality', beneficiaries: 'Finance, Operations',
    r: 'ProcessEngineer', a: 'ProdLead', c: 'Finance, Quality', s: 'IT', i: 'Sustainability',
    macroGoals: 'Monitor and reduce production yield losses and material waste',
  },
  // ── DELIVER ──
  {
    macroId: 'Deliver_01', macroName: 'Customer order capture', capabilityCluster: 'Order Management',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Order_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'CRM, Web', consumingModules: 'ATP, Sales',
    triggerEvent: 'Event: Customer submits order', inputs: 'Order data, Payment',
    outputs: 'Customer order', inputsProviders: 'Customer, Web store', beneficiaries: 'Order processor',
    r: 'CustOrder', a: 'CustOrderLead', c: 'CustOrderQuality', s: 'CustOrderSupport', i: 'CustOrderInfo',
    macroGoals: 'Receive and capture customer order into order management system',
  },
  {
    macroId: 'Deliver_02', macroName: 'ATP check', capabilityCluster: 'ATP',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Order_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'Inventory, Order', consumingModules: 'Sales',
    triggerEvent: 'Event: Order entry', inputs: 'Product, Quantity, Location',
    outputs: 'ATP quantity', inputsProviders: 'ATP engine', beneficiaries: 'Order processor',
    r: 'ATP', a: 'ATPLead', c: 'ATPQuality', s: 'ATPSupport', i: 'ATPInfo',
    macroGoals: 'Check available inventory for incoming order',
  },
  {
    macroId: 'Deliver_03', macroName: 'CTP check', capabilityCluster: 'CTP',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Order_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'MRP, MPS, Order', consumingModules: 'Sales',
    triggerEvent: 'Event: Order requires CTP', inputs: 'Product, Quantity, Date',
    outputs: 'CTP date', inputsProviders: 'CTP engine', beneficiaries: 'Order processor',
    r: 'CTP', a: 'CTPLead', c: 'CTPQuality', s: 'CTPSupport', i: 'CTPInfo',
    macroGoals: 'Check material and production capacity for order fulfilment date',
  },
  {
    macroId: 'Deliver_04', macroName: 'Delivery date commitment', capabilityCluster: 'Order Confirmation',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Order_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'ATP/CTP result', consumingModules: 'Customer',
    triggerEvent: 'Event: Promise calculated', inputs: 'Confirmed date, Shipping method',
    outputs: 'Commitment to customer', inputsProviders: 'Order system', beneficiaries: 'Customer',
    r: 'DelivCommit', a: 'DelivCommitLead', c: 'DelivCommitQuality', s: 'DelivCommitSupport', i: 'DelivCommitInfo',
    macroGoals: 'Communicate confirmed delivery date commitment to customer',
  },
  {
    macroId: 'Deliver_05', macroName: 'Order orchestration plan', capabilityCluster: 'Order Orchestration',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Order_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'Order, Inventory, Supply', consumingModules: 'Warehouse, Transport',
    triggerEvent: 'Event: Order received', inputs: 'Product, Quantity, Location',
    outputs: 'Fulfilment steps (pick, pack, ship)', inputsProviders: 'Orchestration engine', beneficiaries: 'Warehouse, Transport',
    r: 'OrderOrchPlan', a: 'OrderOrchPlanLead', c: 'OrderOrchPlanQuality', s: 'OrderOrchPlanSupport', i: 'OrderOrchPlanInfo',
    macroGoals: 'Create fulfilment plan for confirmed customer order',
  },
  {
    macroId: 'Deliver_06', macroName: 'Luminate dynamic fulfillment decision', capabilityCluster: 'AI Fulfillment',
    bpmnPool: 'SCM_Pool', bpmnLane: 'AI_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'WMS, Inventory, Transport', consumingModules: 'Order orchestration',
    triggerEvent: 'Event: Order received', inputs: 'Stock levels, Cost, Lead time, Emissions',
    outputs: 'Fulfilment decision', inputsProviders: 'Inventory, Transport, Orders', beneficiaries: 'Order manager',
    r: 'DynFulfill', a: 'DynFulfillLead', c: 'DynFulfillQuality', s: 'DynFulfillSupport', i: 'DynFulfillInfo',
    macroGoals: 'Use AI to decide best fulfilment node considering cost, lead time and emissions',
  },
  {
    macroId: 'Deliver_07', macroName: 'Warehouse pick & pack', capabilityCluster: 'Warehouse Operations',
    bpmnPool: 'SCM_Pool', bpmnLane: 'WH_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'WMS, Order', consumingModules: 'Shipping',
    triggerEvent: 'Event: Pick instruction released', inputs: 'Pick list, Location data, Packing spec',
    outputs: 'Packed shipment', inputsProviders: 'WMS, Order system', beneficiaries: 'Shipping, Customer',
    r: 'WarehousePicker', a: 'WHManager', c: 'Quality', s: 'IT', i: 'Transport',
    macroGoals: 'Pick and pack customer order items ready for shipment',
  },
  {
    macroId: 'Deliver_08', macroName: 'Transport planning & booking', capabilityCluster: 'Transport Management',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Transport_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'TMS, WMS', consumingModules: 'Carrier, Shipping',
    triggerEvent: 'Event: Shipment ready', inputs: 'Shipment details, Rate cards, Carrier availability',
    outputs: 'Booked transport, PRO number', inputsProviders: 'WMS, Rate engine', beneficiaries: 'Shipping, Customer',
    r: 'TransportPlanner', a: 'LogisticsMgr', c: 'Finance', s: 'IT', i: 'Warehouse',
    macroGoals: 'Plan and book optimal transport for outbound shipment',
  },
  {
    macroId: 'Deliver_09', macroName: 'Shipment execution & tracking', capabilityCluster: 'Outbound Logistics',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Transport_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'TMS, Carrier APIs', consumingModules: 'Customer, ERP',
    triggerEvent: 'Event: Shipment dispatched', inputs: 'Booking confirmation, Carrier data',
    outputs: 'Tracking updates, POD', inputsProviders: 'Carrier, TMS', beneficiaries: 'Customer, Operations',
    r: 'LogisticsCoord', a: 'LogisticsMgr', c: 'Customer Service', s: 'IT', i: 'Finance',
    macroGoals: 'Execute shipment and provide real-time tracking to customer',
  },
  {
    macroId: 'Deliver_10', macroName: 'Customs & trade compliance', capabilityCluster: 'Trade Compliance',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Compliance_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'ERP, Customs systems', consumingModules: 'Shipping, Finance',
    triggerEvent: 'Event: Cross-border shipment', inputs: 'HS codes, Export licence, Trade agreements',
    outputs: 'Customs declaration, Cleared shipment', inputsProviders: 'Customs broker, Legal', beneficiaries: 'Logistics, Finance',
    r: 'TradeCompliance', a: 'TradeLead', c: 'Legal, Finance', s: 'Customs broker', i: 'Logistics',
    macroGoals: 'Ensure all cross-border shipments comply with trade and customs regulations',
  },
  {
    macroId: 'Deliver_11', macroName: 'Customer invoicing', capabilityCluster: 'Order to Cash',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Finance_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'ERP, Order', consumingModules: 'Accounts Receivable, Customer',
    triggerEvent: 'Event: Delivery confirmed', inputs: 'Delivery confirmation, Order, Contract terms',
    outputs: 'Customer invoice', inputsProviders: 'Logistics, Order system', beneficiaries: 'Finance, Customer',
    r: 'ARClerk', a: 'FinanceMgr', c: 'Sales', s: 'IT', i: 'Customer',
    macroGoals: 'Generate and send accurate customer invoice following delivery',
  },
  {
    macroId: 'Deliver_12', macroName: 'Cash collection & AR management', capabilityCluster: 'Order to Cash',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Finance_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'ERP, Bank', consumingModules: 'Accounting, Treasury',
    triggerEvent: 'Time trigger (Daily)', inputs: 'Customer payments, Ageing report',
    outputs: 'Cash allocation, Chasing actions', inputsProviders: 'Bank, Customer', beneficiaries: 'Finance, Treasury',
    r: 'CollectionsClerk', a: 'ARMgr', c: 'Sales, Legal', s: 'IT', i: 'Executive',
    macroGoals: 'Collect customer payments and manage accounts receivable balance',
  },
  // ── RETURN ──
  {
    macroId: 'Return_01', macroName: 'Customer return authorisation', capabilityCluster: 'Reverse Logistics',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Return_Lane', owningModule: 'mySCM_Return',
    sourceModule: 'CRM, ERP', consumingModules: 'Warehouse, Finance',
    triggerEvent: 'Event: Return request received', inputs: 'Return request, Order reference, Reason code',
    outputs: 'RMA number, Return instruction', inputsProviders: 'Customer, CRM', beneficiaries: 'Customer, Warehouse',
    r: 'CustomerService', a: 'CSMgr', c: 'Finance, Quality', s: 'IT', i: 'Logistics',
    macroGoals: 'Authorise and process customer return requests with RMA',
  },
  {
    macroId: 'Return_02', macroName: 'Returned goods receipt & inspection', capabilityCluster: 'Reverse Logistics',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Return_Lane', owningModule: 'mySCM_Return',
    sourceModule: 'WMS, RMA', consumingModules: 'Quality, Finance',
    triggerEvent: 'Event: Return shipment received', inputs: 'RMA, Physical return, Condition assessment',
    outputs: 'Return inspection result, Disposition', inputsProviders: 'Customer, Logistics', beneficiaries: 'Finance, Quality',
    r: 'WarehouseClerk', a: 'WHManager', c: 'Quality, Finance', s: 'IT', i: 'Customer Service',
    macroGoals: 'Receive and inspect returned goods and determine disposition action',
  },
  {
    macroId: 'Return_03', macroName: 'Credit note & refund processing', capabilityCluster: 'Returns Finance',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Return_Lane', owningModule: 'mySCM_Return',
    sourceModule: 'ERP, Finance', consumingModules: 'Accounting, Customer',
    triggerEvent: 'Event: Return disposition approved', inputs: 'Inspection result, Original invoice, Policy',
    outputs: 'Credit note, Refund', inputsProviders: 'Warehouse, Policy', beneficiaries: 'Customer, Finance',
    r: 'ARClerk', a: 'FinanceMgr', c: 'Legal, Customer Service', s: 'IT', i: 'Customer',
    macroGoals: 'Issue credit note or refund to customer following approved return',
  },
  {
    macroId: 'Return_04', macroName: 'Product refurbishment & resale', capabilityCluster: 'Value Recovery',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Return_Lane', owningModule: 'mySCM_Return',
    sourceModule: 'WMS, Quality', consumingModules: 'Inventory, Sales',
    triggerEvent: 'Event: Returned item approved for refurb', inputs: 'Returned product, Refurb specification',
    outputs: 'Refurbished product, Updated stock', inputsProviders: 'Quality, Production', beneficiaries: 'Sales, Finance',
    r: 'RefurbTech', a: 'WHManager', c: 'Quality, Sales', s: 'Engineering', i: 'Finance',
    macroGoals: 'Refurbish returned products and return them to saleable inventory',
  },
  {
    macroId: 'Return_05', macroName: 'Supplier return & debit management', capabilityCluster: 'Vendor Returns',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Return_Lane', owningModule: 'mySCM_Return',
    sourceModule: 'ERP, Quality', consumingModules: 'Procurement, Finance',
    triggerEvent: 'Event: Defective goods identified', inputs: 'Quality rejection, PO reference, Defect report',
    outputs: 'Supplier debit note, Return shipment', inputsProviders: 'Quality, Warehouse', beneficiaries: 'Finance, Procurement',
    r: 'Buyer', a: 'ProcLead', c: 'Legal, Quality', s: 'IT', i: 'Supplier',
    macroGoals: 'Manage return of defective goods to supplier and recover value via debit',
  },
  // ── ENABLE ──
  {
    macroId: 'Enable_01', macroName: 'Master data management', capabilityCluster: 'Data Governance',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Enable_Lane', owningModule: 'mySCM_Enable',
    sourceModule: 'MDM, ERP', consumingModules: 'All modules',
    triggerEvent: 'Event: Data change request', inputs: 'Change request, Validation rules, Approval',
    outputs: 'Approved master data', inputsProviders: 'Business users, IT', beneficiaries: 'All SCM modules',
    r: 'MDM_Steward', a: 'DataGovernanceLead', c: 'IT, Business', s: 'IT', i: 'All users',
    macroGoals: 'Govern and maintain accurate master data across all SCM systems',
  },
  {
    macroId: 'Enable_02', macroName: 'Risk identification & assessment', capabilityCluster: 'Supply Chain Risk',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Enable_Lane', owningModule: 'mySCM_Enable',
    sourceModule: 'Risk tools, External data', consumingModules: 'S&OP, Sourcing',
    triggerEvent: 'Time trigger (Monthly)', inputs: 'Risk signals, Supplier data, Market events',
    outputs: 'Risk register, Mitigation plan', inputsProviders: 'Risk team, External feeds', beneficiaries: 'Operations, Executive',
    r: 'RiskAnalyst', a: 'RiskLead', c: 'Operations, Legal', s: 'IT', i: 'Board',
    macroGoals: 'Identify and assess supply chain risks to enable proactive mitigation',
  },
  {
    macroId: 'Enable_03', macroName: 'Supply chain analytics & reporting', capabilityCluster: 'Analytics',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Enable_Lane', owningModule: 'mySCM_Enable',
    sourceModule: 'BI, ERP, WMS', consumingModules: 'S&OP, Executive',
    triggerEvent: 'Time trigger (Daily/Weekly)', inputs: 'Transactional data, KPIs, Benchmarks',
    outputs: 'Dashboards, Reports, Alerts', inputsProviders: 'All SCM systems', beneficiaries: 'Management, Operations',
    r: 'DataAnalyst', a: 'AnalyticsLead', c: 'Business', s: 'IT', i: 'All stakeholders',
    macroGoals: 'Provide actionable supply chain insights through analytics and reporting',
  },
  {
    macroId: 'Enable_04', macroName: 'Process compliance & audit', capabilityCluster: 'Compliance',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Enable_Lane', owningModule: 'mySCM_Enable',
    sourceModule: 'GRC, ERP', consumingModules: 'Legal, Finance',
    triggerEvent: 'Time trigger (Quarterly)', inputs: 'Process logs, Controls framework, Audit plan',
    outputs: 'Audit report, Findings, Actions', inputsProviders: 'Internal audit, Compliance', beneficiaries: 'Board, Legal, Regulatory',
    r: 'ComplianceOfficer', a: 'ComplianceLead', c: 'Legal, Operations', s: 'IT', i: 'Board',
    macroGoals: 'Ensure supply chain processes comply with regulatory and internal standards',
  },
  {
    macroId: 'Enable_05', macroName: 'Technology & system management', capabilityCluster: 'IT Enablement',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Enable_Lane', owningModule: 'mySCM_Enable',
    sourceModule: 'IT, DevOps', consumingModules: 'All SCM modules',
    triggerEvent: 'On event (Change request / incident)', inputs: 'Change request, Incident ticket, System data',
    outputs: 'Deployed change, Resolved incident', inputsProviders: 'IT, Business', beneficiaries: 'All SCM users',
    r: 'ITEngineer', a: 'ITLead', c: 'Business, Security', s: 'Vendors', i: 'All users',
    macroGoals: 'Manage SCM technology landscape including changes, incidents and upgrades',
  },
  {
    macroId: 'Enable_06', macroName: 'Workforce & training management', capabilityCluster: 'People Enablement',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Enable_Lane', owningModule: 'mySCM_Enable',
    sourceModule: 'HR, LMS', consumingModules: 'Operations, Compliance',
    triggerEvent: 'Time trigger (Quarterly)', inputs: 'Competency framework, Training needs analysis',
    outputs: 'Training plan, Completion records', inputsProviders: 'HR, Line managers', beneficiaries: 'All SCM staff',
    r: 'HRBusiness_Partner', a: 'HRLead', c: 'Operations, Compliance', s: 'LMS', i: 'All staff',
    macroGoals: 'Develop and maintain SCM workforce capability through structured training',
  },
  {
    macroId: 'Enable_07', macroName: 'Sustainability & ESG reporting', capabilityCluster: 'Sustainability',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Enable_Lane', owningModule: 'mySCM_Enable',
    sourceModule: 'ESG platform, ERP, Logistics', consumingModules: 'Executive, Regulatory',
    triggerEvent: 'Time trigger (Quarterly)', inputs: 'Carbon data, Waste data, Supplier ESG scores',
    outputs: 'ESG report, Improvement plan', inputsProviders: 'Operations, Logistics, Suppliers', beneficiaries: 'Executive, Investors, Regulatory',
    r: 'ESG_Manager', a: 'SustainabilityLead', c: 'Legal, Finance', s: 'IT', i: 'Board',
    macroGoals: 'Measure and report supply chain sustainability performance against ESG targets',
  },
  {
    macroId: 'Enable_08', macroName: 'Continuous improvement management', capabilityCluster: 'CI & Lean',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Enable_Lane', owningModule: 'mySCM_Enable',
    sourceModule: 'CI tools, Analytics', consumingModules: 'All SCM modules',
    triggerEvent: 'On event (Improvement idea raised)', inputs: 'Process data, Pain points, Benchmarks',
    outputs: 'Improvement actions, Benefits tracking', inputsProviders: 'Operations, Analytics', beneficiaries: 'All operations',
    r: 'CI_Lead', a: 'OperationsDir', c: 'Finance, IT', s: 'Change management', i: 'All staff',
    macroGoals: 'Drive ongoing operational improvement through lean and CI methodology',
  },
  // ── Additional Plan ──
  {
    macroId: 'Plan_06', macroName: 'Replenishment planning', capabilityCluster: 'Inventory Replenishment',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Plan_Lane', owningModule: 'mySCM_Plan',
    sourceModule: 'ERP, WMS, Demand', consumingModules: 'Procurement, Warehouse',
    triggerEvent: 'Time trigger (Daily)', inputs: 'Stock levels, Reorder points, Demand forecast',
    outputs: 'Replenishment orders, Transfer orders', inputsProviders: 'Inventory, Demand', beneficiaries: 'Warehouse, Operations',
    r: 'ReplenishmentPlanner', a: 'PlannngLead', c: 'Procurement, Warehouse', s: 'IT', i: 'Finance',
    macroGoals: 'Generate replenishment orders to maintain optimal stock levels',
  },
  {
    macroId: 'Plan_07', macroName: 'Distribution requirements planning', capabilityCluster: 'Distribution Planning',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Plan_Lane', owningModule: 'mySCM_Plan',
    sourceModule: 'ERP, Demand, Inventory', consumingModules: 'Logistics, Warehouse',
    triggerEvent: 'Time trigger (Weekly)', inputs: 'DC stock, Demand plan, Lead times',
    outputs: 'DRP plan, Transfer orders', inputsProviders: 'Planning, Warehouse', beneficiaries: 'Logistics, Operations',
    r: 'DRPPlanner', a: 'LogisticsLead', c: 'Warehouse, Procurement', s: 'IT', i: 'Finance',
    macroGoals: 'Plan distribution replenishment across the network to meet customer demand',
  },
  // ── Additional Source ──
  {
    macroId: 'Source_08', macroName: 'Spend analytics & category management', capabilityCluster: 'Strategic Sourcing',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Source_Lane', owningModule: 'mySCM_Source',
    sourceModule: 'ERP, Spend analytics', consumingModules: 'Sourcing, Finance',
    triggerEvent: 'Time trigger (Monthly)', inputs: 'Purchase data, Supplier data, Market prices',
    outputs: 'Spend cube, Category strategy', inputsProviders: 'Finance, Procurement', beneficiaries: 'CPO, Finance',
    r: 'SpendAnalyst', a: 'CPO', c: 'Finance, Operations', s: 'IT', i: 'Executive',
    macroGoals: 'Analyse spend data and develop category strategies to optimise procurement',
  },
  // ── Additional Make ──
  {
    macroId: 'Make_07', macroName: 'Maintenance & asset management', capabilityCluster: 'Asset Management',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Make_Lane', owningModule: 'mySCM_Make',
    sourceModule: 'CMMS, ERP', consumingModules: 'Production, Finance',
    triggerEvent: 'On event (Failure / schedule trigger)', inputs: 'Asset data, Maintenance schedule, Work orders',
    outputs: 'Maintenance records, Asset health', inputsProviders: 'Engineering, Operators', beneficiaries: 'Production, Finance',
    r: 'MaintenanceTech', a: 'MaintenanceMgr', c: 'Engineering, Finance', s: 'OEM vendors', i: 'Production',
    macroGoals: 'Manage planned and reactive maintenance to maximise asset availability',
  },
  // ── Additional Deliver ──
  {
    macroId: 'Deliver_13', macroName: 'Last-mile delivery management', capabilityCluster: 'Last Mile',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Transport_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'TMS, Carrier APIs', consumingModules: 'Customer, CRM',
    triggerEvent: 'Event: Shipment at hub', inputs: 'Delivery instructions, Route plan, Customer contact',
    outputs: 'Delivery confirmation, Signature', inputsProviders: 'Carrier, TMS', beneficiaries: 'Customer',
    r: 'DeliveryDriver', a: 'LogisticsMgr', c: 'Customer Service', s: 'IT', i: 'Customer',
    macroGoals: 'Manage final delivery to customer location with proof of delivery',
  },
  {
    macroId: 'Deliver_14', macroName: 'Cold chain & temperature monitoring', capabilityCluster: 'Cold Chain',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Transport_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'IoT sensors, TMS', consumingModules: 'Quality, Compliance',
    triggerEvent: 'Real-time IoT event', inputs: 'Temperature readings, Transit data, Threshold rules',
    outputs: 'Temperature log, Excursion alert', inputsProviders: 'IoT devices, Carrier', beneficiaries: 'Quality, Regulatory',
    r: 'ColdChainSpecialist', a: 'QualityMgr', c: 'Regulatory, Logistics', s: 'IoT platform', i: 'Customer',
    macroGoals: 'Monitor and maintain cold chain integrity throughout the delivery journey',
  },
  {
    macroId: 'Deliver_15', macroName: 'Order exception & dispute management', capabilityCluster: 'Order Management',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Order_Lane', owningModule: 'mySCM_Deliver',
    sourceModule: 'ERP, CRM', consumingModules: 'Finance, Operations',
    triggerEvent: 'Event: Customer dispute raised', inputs: 'Dispute reason, Order data, Delivery proof',
    outputs: 'Resolution action, Customer communication', inputsProviders: 'Customer, CRM', beneficiaries: 'Customer, Finance',
    r: 'DisputeHandler', a: 'CSMgr', c: 'Finance, Logistics', s: 'Legal', i: 'Customer',
    macroGoals: 'Resolve order exceptions and customer disputes to protect satisfaction and revenue',
  },
  // ── Additional Return ──
  {
    macroId: 'Return_06', macroName: 'Waste & disposal management', capabilityCluster: 'Circular Economy',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Return_Lane', owningModule: 'mySCM_Return',
    sourceModule: 'WMS, Sustainability', consumingModules: 'Finance, Regulatory',
    triggerEvent: 'Time trigger (Monthly)', inputs: 'Waste data, Disposal contracts, Regulatory requirements',
    outputs: 'Waste disposal record, Compliance report', inputsProviders: 'Warehouse, Suppliers', beneficiaries: 'Regulatory, Finance',
    r: 'WasteCoord', a: 'SustainabilityLead', c: 'Legal, Finance', s: 'Disposal vendors', i: 'Board',
    macroGoals: 'Manage responsible disposal of waste and end-of-life products',
  },
  // ── Additional Enable ──
  {
    macroId: 'Enable_09', macroName: 'Business continuity planning', capabilityCluster: 'Resilience',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Enable_Lane', owningModule: 'mySCM_Enable',
    sourceModule: 'Risk, Operations', consumingModules: 'Executive, All modules',
    triggerEvent: 'On event (Disruption / review cycle)', inputs: 'Risk register, Critical process list, Recovery strategies',
    outputs: 'BCP document, Recovery playbooks', inputsProviders: 'Risk team, Operations', beneficiaries: 'Executive, Operations',
    r: 'BCPManager', a: 'COO', c: 'IT, Legal, Operations', s: 'Insurance', i: 'Board',
    macroGoals: 'Develop and test business continuity plans for critical supply chain disruptions',
  },
  {
    macroId: 'Enable_10', macroName: 'Supply chain finance & working capital', capabilityCluster: 'Supply Chain Finance',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Enable_Lane', owningModule: 'mySCM_Enable',
    sourceModule: 'ERP, Finance, Banks', consumingModules: 'Treasury, Procurement',
    triggerEvent: 'Time trigger (Monthly)', inputs: 'Cash position, AP/AR data, Supply chain finance terms',
    outputs: 'Working capital optimisation plan, Dynamic discounting actions', inputsProviders: 'Finance, Procurement', beneficiaries: 'Treasury, Suppliers',
    r: 'TreasuryAnalyst', a: 'CFO', c: 'Procurement, Legal', s: 'Banks', i: 'Executive',
    macroGoals: 'Optimise supply chain working capital through finance instruments and payment terms',
  },
  {
    macroId: 'Enable_11', macroName: 'Demand-driven supply chain transformation', capabilityCluster: 'Transformation',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Enable_Lane', owningModule: 'mySCM_Enable',
    sourceModule: 'Strategy, PMO', consumingModules: 'All SCM modules',
    triggerEvent: 'On event (Strategic initiative launch)', inputs: 'Transformation roadmap, Business case, Change plan',
    outputs: 'Programme deliverables, Change adoption metrics', inputsProviders: 'PMO, Strategy', beneficiaries: 'Executive, Operations',
    r: 'TransformationLead', a: 'COO', c: 'All functions, IT', s: 'Consultants', i: 'Board',
    macroGoals: 'Lead supply chain transformation programme to achieve strategic objectives',
  },
  {
    macroId: 'Enable_12', macroName: 'Regulatory & trade policy management', capabilityCluster: 'Trade & Regulatory',
    bpmnPool: 'SCM_Pool', bpmnLane: 'Enable_Lane', owningModule: 'mySCM_Enable',
    sourceModule: 'Legal, External regulatory feeds', consumingModules: 'Compliance, Logistics',
    triggerEvent: 'On event (Regulatory change)', inputs: 'Regulatory updates, Trade policy changes, Licence requirements',
    outputs: 'Compliance assessment, Updated SOPs', inputsProviders: 'Legal, Customs, Government', beneficiaries: 'Operations, Finance',
    r: 'RegulatorySpecialist', a: 'ComplianceLead', c: 'Legal, Logistics', s: 'External counsel', i: 'Executive',
    macroGoals: 'Monitor and ensure compliance with evolving trade and regulatory requirements',
  },
]
