// Object of each macro process: the thing its steps act on. Used to make step and
// task names explicit ("Fix review periodicity" -> "Fix quality policy review periodicity").
// [English noun phrase, French direct object with article, Arabic construct form]
export const MP_OBJECTS = {
  'MP-001': ['organizational context', "le contexte de l'organisme", 'سياق المؤسسة'],
  'MP-002': ['quality policy', 'la politique qualité', 'سياسة الجودة'],
  'MP-003': ['quality objectives', 'les objectifs qualité', 'أهداف الجودة'],
  'MP-004': ['process architecture', "l'architecture des processus", 'بنية العمليات'],
  'MP-005': ['SIPOC and value stream', 'le SIPOC et la chaîne de valeur', 'مخطط SIPOC وسلسلة القيمة'],
  'MP-006': ['procedures and work instructions', 'les procédures et instructions de travail', 'إجراءات وتعليمات العمل'],
  'MP-007': ['process control plan', 'le plan de surveillance des processus', 'خطة ضبط العمليات'],
  'MP-008': ['business rules', 'les règles métier', 'قواعد العمل'],
  'MP-009': ['process KPIs', 'les KPI des processus', 'مؤشرات أداء العمليات'],
  'MP-010': ['alert and escalation thresholds', "les seuils d'alerte et d'escalade", 'عتبات التنبيه والتصعيد'],
  'MP-011': ['process dashboard', 'le tableau de bord des processus', 'لوحة متابعة العمليات'],
  'MP-012': ['operational risks and opportunities', 'les risques et opportunités opérationnels', 'مخاطر وفرص التشغيل'],
  'MP-013': ['training', 'la formation', 'التدريب'],
  'MP-014': ['management system communication plan', 'le plan de communication du système de management', 'خطة تواصل نظام الإدارة'],
  'MP-015': ['management system deployment', 'le déploiement du système de management', 'نشر نظام الإدارة'],
  'MP-016': ['mock audit and gap diagnosis', "l'audit à blanc et le diagnostic des écarts", 'تدقيق تجريبي وتشخيص الفجوات'],
  'MP-017': ['certification audit', "l'audit de certification", 'تدقيق الاعتماد'],
  'MP-018': ['quality problem', 'le problème qualité', 'مشكلة الجودة'],
  'MP-019': ['immediate actions', 'les actions immédiates', 'إجراءات فورية'],
  'MP-020': ['root cause analysis', "l'analyse des causes racines", 'تحليل السبب الجذري'],
  'MP-021': ['corrective actions', 'les actions correctives', 'إجراءات تصحيحية'],
  'MP-022': ['nonconformity closure', 'la clôture des non-conformités', 'إغلاق عدم المطابقة'],
  'MP-023': ['improvement pipeline', "le pipeline d'amélioration", 'مسار التحسين'],
  'MP-024': ['supplier quality performance', 'la performance qualité des fournisseurs', 'أداء جودة الموردين'],
  'MP-025': ['measuring equipment', 'les équipements de mesure', 'معدات القياس'],
  'MP-026': ['internal auditor qualification', 'la qualification des auditeurs internes', 'تأهيل المدققين الداخليين'],
  'MP-027': ['harmonized requirements', 'les exigences harmonisées', 'متطلبات موحدة'],
  'MP-028': ['compliance obligations', 'les obligations de conformité', 'التزامات الامتثال'],
  'MP-029': ['controlled documents', 'les documents maîtrisés', 'وثائق خاضعة للضبط'],
  'MP-030': ['records and evidence', 'les enregistrements et preuves', 'سجلات وأدلة'],
  'MP-031': ['performance indicators', 'les indicateurs de performance', 'مؤشرات الأداء'],
  'MP-032': ['management system performance', 'la performance du système de management', 'أداء نظام الإدارة'],
  'MP-033': ['operational process performance', 'la performance des processus opérationnels', 'أداء العمليات التشغيلية'],
  'MP-034': ['governance reviews', 'les revues de gouvernance', 'مراجعات الحوكمة'],
  'MP-035': ['customer satisfaction survey', 'le baromètre de satisfaction client', 'استبيان رضا العملاء'],
  'MP-036': ['policies and procedures', 'les politiques et procédures', 'سياسات وإجراءات'],
  'MP-037': ['enterprise risk register', 'le registre des risques', 'سجل المخاطر المؤسسية'],
  'MP-038': ['risk treatment plan', 'le plan de traitement des risques', 'خطة معالجة المخاطر'],
  'MP-039': ['internal audit programme', "le programme d'audit interne", 'برنامج التدقيق الداخلي'],
  'MP-040': ['GRC dashboard', 'le tableau de bord GRC', 'لوحة الحوكمة والمخاطر والامتثال'],
  'MP-041': ['AI management system', "le système de management de l'IA", 'نظام إدارة الذكاء الاصطناعي'],
  'MP-042': ['IT controls', 'les contrôles informatiques', 'ضوابط تقنية المعلومات'],
  'MP-043': ['personal data processing', 'les traitements de données personnelles', 'معالجة البيانات الشخصية'],
  'MP-044': ['master data', 'les données de référence', 'البيانات المرجعية'],
  'MP-045': ['access rights', "les droits d'accès", 'صلاحيات الوصول'],
  'MP-046': ['application repository', 'le référentiel des applications', 'مستودع التطبيقات'],
  'MP-047': ['technology architecture', "l'architecture technologique", 'البنية التقنية'],
  'MP-048': ['tenant security', 'la sécurité du locataire', 'أمن المستأجر'],
  'MP-049': ['internal controls', 'les contrôles internes', 'الضوابط الداخلية'],
  'MP-050': ['third-party risks', 'les risques tiers', 'مخاطر الأطراف الثالثة'],
  'MP-051': ['whistleblowing case', "le signalement d'alerte", 'بلاغ المخالفات'],
  'MP-052': ['business continuity plan', "le plan de continuité d'activité", 'خطة استمرارية الأعمال'],
  'MP-053': ['optimization project', "le projet d'optimisation", 'مشروع التحسين'],
  'MP-054': ['macro process portfolio', 'le portefeuille de macro-processus', 'محفظة العمليات الكلية'],
  'MP-055': ['enterprise simulation', "la simulation d'entreprise", 'محاكاة المؤسسة'],
  'MP-056': ['automation score', "le score d'automatisation", 'درجة الأتمتة'],
  'MP-057': ['formula repository', 'le référentiel de formules', 'مستودع الصيغ'],
  'MP-058': ['formula execution', "l'exécution des formules", 'تنفيذ الصيغ'],
  'MP-059': ['configuration parameters', 'les paramètres de configuration', 'معاملات التهيئة'],
  'MP-060': ['ROI case', 'le dossier de ROI', 'حالة العائد على الاستثمار'],
  'MP-061': ['VOI case', 'le dossier de VOI', 'حالة القيمة المضافة'],
  'MP-062': ['predictive risk model', 'le modèle prédictif des risques', 'نموذج التنبؤ بالمخاطر'],
  'MP-063': ['regulatory watch', 'la veille réglementaire', 'الرصد التنظيمي'],
  'MP-064': ['multi-standard mapping', 'la correspondance multi-normes', 'مطابقة المعايير المتعددة'],
  'MP-065': ['generated documents', 'les documents générés', 'الوثائق المولَّدة'],
  'MP-066': ['process digital twin', 'le jumeau numérique des processus', 'التوأم الرقمي للعمليات'],
  'MP-067': ['ESG performance', 'la performance ESG', 'أداء الاستدامة'],
  'MP-068': ['carbon footprint', "l'empreinte carbone", 'البصمة الكربونية'],
  'MP-069': ['supply chain traceability', "la traçabilité de la chaîne d'approvisionnement", 'تتبع سلسلة التوريد'],
  'MP-070': ['supplier ecosystem', "l'écosystème fournisseurs", 'منظومة الموردين'],
  'MP-071': ['customer experience', "l'expérience client", 'تجربة العملاء'],
  'MP-072': ['voice of the customer', 'la voix du client', 'صوت العميل'],
  'MP-073': ['innovation pipeline', "le pipeline d'innovation", 'مسار الابتكار'],
  'MP-074': ['knowledge graph', 'le graphe de connaissances', 'رسم المعرفة'],
  'MP-075': ['process mining', 'le process mining', 'تنقيب العمليات'],
  'MP-076': ['root cause intelligence', "l'intelligence des causes racines", 'ذكاء الأسباب الجذرية'],
  'MP-077': ['cross-site benchmark', 'le benchmark inter-sites', 'مقارنة المواقع'],
  'MP-078': ['compliance prediction', 'la prédiction de conformité', 'التنبؤ بالامتثال'],
  'MP-079': ['blockchain audit trail', "la piste d'audit blockchain", 'سجل التدقيق بسلسلة الكتل'],
  'MP-080': ['regulatory change impact', "l'impact des changements réglementaires", 'أثر التغييرات التنظيمية'],
  'MP-081': ['CAPA recommendations', 'les recommandations de CAPA', 'توصيات الإجراءات التصحيحية والوقائية'],
  'MP-082': ['NCP knowledge base', 'la base de connaissances NCP', 'قاعدة معرفة المشكلات'],
  'MP-083': ['AI problem-solving agents', 'les agents IA de résolution', 'وكلاء الذكاء الاصطناعي لحل المشكلات'],
  'MP-084': ['alert engine', "le moteur d'alertes", 'محرك التنبيهات'],
  'MP-085': ['composable modules', 'les modules composables', 'الوحدات القابلة للتركيب'],
  'MP-086': ['tenant isolation', "l'isolation des locataires", 'عزل المستأجرين'],
  'MP-087': ['lessons learned (REX)', 'le retour d\'expérience (REX)', 'الدروس المستفادة'],
  'MP-088': ['AI explanations', "les explications de l'IA", 'تفسيرات الذكاء الاصطناعي'],
  'MP-089': ['co-authored documents', 'les documents co-rédigés', 'الوثائق المشتركة التحرير'],
  'MP-090': ['field operations', 'les opérations terrain', 'العمليات الميدانية'],
  'MP-091': ['voice reports', 'les signalements vocaux', 'البلاغات الصوتية'],
  'MP-092': ['IoT sensor data', 'les données des capteurs IoT', 'بيانات مستشعرات إنترنت الأشياء'],
  'MP-093': ['AR-guided inspections', 'les inspections guidées en RA', 'عمليات التفتيش بالواقع المعزز'],
  'MP-094': ['e-signature workflow', 'le circuit de signature électronique', 'مسار التوقيع الإلكتروني'],
  'MP-095': ['compliance pack', 'le pack de conformité', 'حزمة الامتثال'],
  'MP-096': ['certification portfolio', 'le portefeuille de certifications', 'محفظة الشهادات'],
  'MP-097': ['remote audit', "l'audit à distance", 'التدقيق عن بعد'],
  'MP-098': ['continuous controls monitoring', 'la surveillance continue des contrôles', 'المراقبة المستمرة للضوابط'],
  'MP-099': ['task mining', 'le task mining', 'تنقيب المهام'],
  'MP-100': ['low-code workflows', 'les workflows low-code', 'مسارات العمل منخفضة البرمجة'],
  'MP-101': ['marketplace items', 'les éléments de la place de marché', 'عناصر السوق'],
  'MP-102': ['supplier portal', 'le portail fournisseurs', 'بوابة الموردين'],
  'MP-103': ['customer complaints', 'les réclamations clients', 'شكاوى العملاء'],
  'MP-104': ['microlearning content', 'les contenus de microlearning', 'محتوى التعلم المصغر'],
  'MP-105': ['compliance calendar', 'le calendrier de conformité', 'تقويم الامتثال'],
  'MP-106': ['scope 3 emissions', 'les émissions de scope 3', 'انبعاثات النطاق 3'],
  'MP-107': ['product traceability and recall', 'la traçabilité et le rappel des produits', 'تتبع المنتجات واسترجاعها'],
  'MP-108': ['crisis communication', 'la communication de crise', 'تواصل الأزمات'],
  'MP-109': ['functional safety lifecycle', 'le cycle de vie de la sécurité fonctionnelle', 'دورة حياة السلامة الوظيفية'],
  'MP-110': ['safety integrity level', "le niveau d'intégrité de sécurité", 'مستوى سلامة التكامل'],
  'MP-111': ['automotive safety integrity level', "le niveau d'intégrité de sécurité automobile", 'مستوى سلامة التكامل للسيارات'],
  'MP-112': ['automotive threat analysis', "l'analyse des menaces automobiles", 'تحليل تهديدات السيارات'],
  'MP-113': ['process hazard analysis', "l'analyse des risques des procédés", 'تحليل مخاطر العمليات'],
  'MP-114': ['mechanical integrity', "l'intégrité mécanique", 'السلامة الميكانيكية'],
  'MP-115': ['pre-startup safety review', 'la revue de sécurité avant démarrage', 'مراجعة السلامة قبل التشغيل'],
  'MP-116': ['occupational exposure', "l'exposition professionnelle", 'التعرض المهني'],
  'MP-117': ['medical surveillance', 'la surveillance médicale', 'المراقبة الطبية'],
  'MP-118': ['pressure equipment', 'les équipements sous pression', 'معدات الضغط'],
  'MP-119': ['asset maintenance', 'la maintenance des actifs', 'صيانة الأصول'],
  'MP-120': ['maritime safety', 'la sécurité maritime', 'السلامة البحرية'],
  'MP-121': ['marine pollution prevention', 'la prévention de la pollution marine', 'منع التلوث البحري'],
  'MP-122': ['cleanroom', 'la salle propre', 'الغرفة النظيفة'],
  'MP-123': ['welding quality', 'la qualité du soudage', 'جودة اللحام'],
  'MP-124': ['chemical substances', 'les substances chimiques', 'المواد الكيميائية'],
  'MP-125': ['safety data sheets', 'les fiches de données de sécurité', 'صحائف بيانات السلامة'],
  'MP-126': ['extended producer responsibility', 'la responsabilité élargie du producteur', 'مسؤولية المنتج الممتدة'],
  'MP-127': ['human rights due diligence', 'le devoir de vigilance droits humains', 'العناية الواجبة لحقوق الإنسان'],
  'MP-128': ['conflict minerals report', 'le rapport sur les minerais de conflit', 'تقرير معادن النزاع'],
  'MP-129': ['modern slavery statement', "la déclaration sur l'esclavage moderne", 'بيان العبودية الحديثة'],
  'MP-130': ['anti-bribery programme', 'le programme anticorruption', 'برنامج مكافحة الرشوة'],
  'MP-131': ['road safety', 'la sécurité routière', 'السلامة المرورية'],
  'MP-132': ['water efficiency', "l'efficacité hydrique", 'كفاءة استخدام المياه'],
  'MP-133': ['facilities', 'les installations', 'المرافق'],
  'MP-134': ['IT services', 'les services informatiques', 'خدمات تقنية المعلومات'],
  'MP-135': ['cloud security', 'la sécurité du cloud', 'أمن السحابة'],
  'MP-136': ['laboratory tests and calibrations', 'les essais et étalonnages du laboratoire', 'اختبارات المختبر ومعايراته'],
  'MP-137': ['medical laboratory examinations', 'les examens de biologie médicale', 'فحوص المختبر الطبي'],
  'MP-138': ['business relationships', "les relations d'affaires", 'علاقات الأعمال'],
  'MP-139': ['eco-design', "l'écoconception", 'التصميم البيئي'],
  'MP-140': ['life cycle assessment', "l'analyse du cycle de vie", 'تقييم دورة الحياة'],
  'MP-141': ['water footprint', "l'empreinte eau", 'البصمة المائية'],
  'MP-142': ['environmental communication', 'la communication environnementale', 'التواصل البيئي'],
  'MP-143': ['SME onboarding', "l'onboarding de la PME", 'تهيئة المنشأة الصغيرة'],
  'MP-144': ['SME process model', 'le modèle de processus de la PME', 'نموذج عمليات المنشأة الصغيرة'],
  'MP-145': ['SME document templates', 'les modèles de documents PME', 'نماذج وثائق المنشأة الصغيرة'],
  'MP-146': ['fractional expert support', "l'appui d'expert à temps partagé", 'دعم الخبير بدوام جزئي'],
  'MP-147': ['SME peer benchmark', 'le benchmark PME entre pairs', 'مقارنة المنشآت الصغيرة'],
  'MP-148': ['SME user roles', 'les rôles des utilisateurs PME', 'أدوار مستخدمي المنشأة الصغيرة'],
  'MP-149': ['SME risk register', 'le registre des risques PME', 'سجل مخاطر المنشأة الصغيرة'],
  'MP-150': ['SME KPI dashboard', 'le tableau de bord KPI PME', 'لوحة مؤشرات المنشأة الصغيرة'],
  'MP-151': ['SME audit preparation', "la préparation d'audit PME", 'التحضير لتدقيق المنشأة الصغيرة'],
  'MP-152': ['SME training plan', 'le plan de formation PME', 'خطة تدريب المنشأة الصغيرة'],
  'MP-153': ['SME compliance budget', 'le budget de conformité PME', 'ميزانية امتثال المنشأة الصغيرة'],
  'MP-154': ['SME growth readiness', 'la préparation à la croissance PME', 'جاهزية نمو المنشأة الصغيرة'],
  'MP-155': ['informal processes', 'les processus informels', 'العمليات غير الرسمية'],
  'MP-156': ['owner dashboard', 'le tableau de bord du dirigeant', 'لوحة المالك'],
  'MP-157': ['regulatory alerts', 'les alertes réglementaires', 'التنبيهات التنظيمية'],
  'MP-158': ['SME nonconformities', 'les non-conformités PME', 'حالات عدم المطابقة في المنشأة الصغيرة'],
  'MP-159': ['low-cost improvements', 'les améliorations à faible coût', 'تحسينات منخفضة التكلفة'],
  'MP-160': ['multi-standard certification', 'la certification multi-normes', 'الاعتماد متعدد المعايير'],
  'MP-161': ['SME community', 'la communauté PME', 'مجتمع المنشآت الصغيرة'],
  'MP-162': ['SME exit and transition', 'la cession et la transition PME', 'تخارج المنشأة الصغيرة وانتقالها'],
};

// ISO 9001 / 14001 / 45001 clauses a macro process mainly answers (for step guidance and templates).
export const MP_CLAUSES = {
  'MP-001': 'ISO 9001 §4.1, §4.2, §4.3', 'MP-002': 'ISO 9001 §5.1, §5.2', 'MP-003': 'ISO 9001 §6.2', 'MP-004': 'ISO 9001 §4.4',
  'MP-005': 'ISO 9001 §4.4, §8.1', 'MP-006': 'ISO 9001 §7.5, §8.1', 'MP-007': 'ISO 9001 §8.5.1, §9.1.1', 'MP-008': 'ISO 9001 §8.1',
  'MP-009': 'ISO 9001 §9.1.1', 'MP-010': 'ISO 9001 §9.1.1', 'MP-011': 'ISO 9001 §9.1.3', 'MP-012': 'ISO 9001 §6.1',
  'MP-013': 'ISO 9001 §7.2, §7.3', 'MP-014': 'ISO 9001 §7.4', 'MP-015': 'ISO 9001 §8.1', 'MP-016': 'ISO 9001 §9.2',
  'MP-017': 'ISO/IEC 17021-1 (certification audit)', 'MP-018': 'ISO 9001 §10.2.1', 'MP-019': 'ISO 9001 §8.7, §10.2.1 a)', 'MP-020': 'ISO 9001 §10.2.1 b)',
  'MP-021': 'ISO 9001 §10.2.1 c)–d)', 'MP-022': 'ISO 9001 §10.2.2', 'MP-023': 'ISO 9001 §10.1, §10.3', 'MP-024': 'ISO 9001 §8.4',
  'MP-025': 'ISO 9001 §7.1.5', 'MP-026': 'ISO 9001 §7.2, ISO 19011 §7', 'MP-027': 'ISO Harmonized Structure (Annex SL)', 'MP-028': 'ISO 9001 §4.2, ISO 14001 §6.1.3, ISO 45001 §6.1.3',
  'MP-029': 'ISO 9001 §7.5.2, §7.5.3', 'MP-030': 'ISO 9001 §7.5.3', 'MP-031': 'ISO 9001 §9.1.3', 'MP-032': 'ISO 9001 §9.1',
  'MP-033': 'ISO 9001 §9.1.3', 'MP-034': 'ISO 9001 §9.3', 'MP-035': 'ISO 9001 §9.1.2', 'MP-036': 'ISO 9001 §5.2, §7.5',
  'MP-037': 'ISO 9001 §6.1, ISO 31000', 'MP-038': 'ISO 9001 §6.1.2', 'MP-039': 'ISO 9001 §9.2', 'MP-040': 'ISO 9001 §9.1.3',
  'MP-052': 'ISO 22301', 'MP-103': 'ISO 9001 §9.1.2, ISO 10002', 'MP-105': 'ISO 9001 §4.2, §6.1', 'MP-143': 'ISO 9001 §4, §5',
  'MP-144': 'ISO 9001 §4.4', 'MP-145': 'ISO 9001 §7.5', 'MP-146': 'ISO 9001 §7.1.6', 'MP-149': 'ISO 9001 §6.1',
  'MP-150': 'ISO 9001 §9.1', 'MP-151': 'ISO 9001 §9.2', 'MP-152': 'ISO 9001 §7.2', 'MP-158': 'ISO 9001 §10.2',
  'MP-160': 'ISO 9001, ISO 14001, ISO 45001', 'MP-162': 'ISO 9001 §6.3',
};

// Steps whose source name does not start with a verb, rewritten verb-first.
export const NAME_OVERRIDES = {
  'Document and communicate': ['Document and communicate the context analysis', "Documenter et communiquer l'analyse du contexte", 'توثيق تحليل السياق والتواصل بشأنه'],
  'Document': ['Document the process control plan', 'Documenter le plan de surveillance', 'توثيق خطة ضبط العمليات'],
  'Inventory': ['Inventory measuring equipment', 'Inventorier les équipements de mesure', 'جرد معدات القياس'],
  'Label': ['Label calibration status on equipment', "Étiqueter l'état d'étalonnage des équipements", 'وسم حالة معايرة المعدات'],
  'Refresher training': ['Deliver auditor refresher training', 'Dispenser la formation de recyclage des auditeurs', 'تقديم التدريب التنشيطي للمدققين'],
  'Peer review': ['Peer-review draft documents', 'Relire les projets de documents par les pairs', 'مراجعة مسودات الوثائق من قبل الأقران'],
  'Mini-reviews': ['Hold monthly process mini-reviews', 'Tenir les mini-revues mensuelles des processus', 'عقد مراجعات شهرية مصغرة للعمليات'],
  'Full reviews': ['Hold full management reviews', 'Tenir les revues de direction complètes', 'عقد مراجعات الإدارة الشاملة'],
  'ExCo': ['Present results to the Executive Committee', 'Présenter les résultats au comité exécutif', 'عرض النتائج على اللجنة التنفيذية'],
  'Commercial committees': ['Hold commercial committee reviews', 'Tenir les revues des comités commerciaux', 'عقد مراجعات اللجان التجارية'],
  'Closing meeting': ['Hold the audit closing meeting', "Tenir la réunion de clôture d'audit", 'عقد الاجتماع الختامي للتدقيق'],
  'Due diligence': ['Perform third-party due diligence', 'Réaliser la due diligence des tiers', 'إجراء العناية الواجبة للأطراف الثالثة'],
  'Alert': ['Alert owners of regulatory changes', 'Alerter les responsables des changements réglementaires', 'تنبيه المسؤولين إلى التغييرات التنظيمية'],
  'Power AI': ['Feed AI assistants with the knowledge graph', 'Alimenter les assistants IA avec le graphe de connaissances', 'تغذية المساعدات الذكية برسم المعرفة'],
  'RBAC-aware retrieval': ['Retrieve knowledge within access rights', "Rechercher la connaissance dans la limite des droits d'accès", 'استرجاع المعرفة ضمن صلاحيات الوصول'],
  'Multi-language': ['Translate knowledge articles (EN/FR/AR)', 'Traduire les articles de connaissance (EN/FR/AR)', 'ترجمة مقالات المعرفة (EN/FR/AR)'],
  'Log with confidence': ['Log agent answers with confidence score', "Journaliser les réponses de l'agent avec l'indice de confiance", 'تسجيل إجابات الوكيل مع درجة الثقة'],
  'Alert A (high-priority)': ['Send alert A for high-priority problems', 'Envoyer l\'alerte A pour les problèmes prioritaires', 'إرسال التنبيه A للمشكلات عالية الأولوية'],
  'Alert B (overdue)': ['Send alert B for overdue actions', "Envoyer l'alerte B pour les actions en retard", 'إرسال التنبيه B للإجراءات المتأخرة'],
  'Alert C (pending eval)': ['Send alert C for pending evaluations', "Envoyer l'alerte C pour les évaluations en attente", 'إرسال التنبيه C للتقييمات المعلقة'],
  'Alert D (RCA delay)': ['Send alert D for delayed root cause analyses', "Envoyer l'alerte D pour les ACR en retard", 'إرسال التنبيه D لتأخر تحليل السبب الجذري'],
  'Alert E (capitalization)': ['Send alert E for lessons to capitalize', "Envoyer l'alerte E pour les enseignements à capitaliser", 'إرسال التنبيه E للدروس الواجب الاستفادة منها'],
  'Alert F (KPI breach)': ['Send alert F for KPI breaches', "Envoyer l'alerte F pour les dépassements de KPI", 'إرسال التنبيه F لتجاوز مؤشرات الأداء'],
  'Alerts G–I (J-1/J-2 reminders)': ['Send reminders G–I one and two days before due dates', "Envoyer les rappels G–I à J-1 et J-2 de l'échéance", 'إرسال التذكيرات G–I قبل الموعد بيوم ويومين'],
  'Alert J (inactive)': ['Send alert J for inactive records', "Envoyer l'alerte J pour les enregistrements inactifs", 'إرسال التنبيه J للسجلات غير النشطة'],
  'Log': ['Log alert dispatches and acknowledgements', 'Journaliser les envois et accusés de réception des alertes', 'تسجيل إرسال التنبيهات والإقرار بها'],
  'Versioning': ['Version module configurations', 'Versionner les configurations des modules', 'إدارة إصدارات تهيئة الوحدات'],
  'Document lessons (AI-assisted)': ['Document lessons learned with AI assistance', "Documenter les enseignements avec l'aide de l'IA", 'توثيق الدروس المستفادة بمساعدة الذكاء الاصطناعي'],
  'Inline comments': ['Add inline comments to shared documents', 'Ajouter des commentaires en ligne aux documents partagés', 'إضافة تعليقات مضمنة على الوثائق المشتركة'],
  'Threaded discussions': ['Discuss changes in threaded conversations', 'Discuter des modifications en fils de discussion', 'مناقشة التعديلات في نقاشات متسلسلة'],
  'Field-optimized checklists': ['Complete field-optimized checklists', 'Renseigner les listes de contrôle terrain', 'تعبئة قوائم التحقق الميدانية'],
  'Barcode/QR scanning': ['Scan asset barcodes and QR codes', 'Scanner les codes-barres et QR des équipements', 'مسح الباركود ورموز QR للأصول'],
  'Auto-sync': ['Synchronize offline captures automatically', 'Synchroniser automatiquement les saisies hors ligne', 'مزامنة الإدخالات دون اتصال تلقائيًا'],
  'Offline access to procedures': ['Access procedures offline', 'Consulter les procédures hors ligne', 'الاطلاع على الإجراءات دون اتصال'],
  'Speech-to-text (EN/FR/AR)': ['Transcribe voice reports to text (EN/FR/AR)', 'Transcrire les signalements vocaux en texte (EN/FR/AR)', 'تحويل البلاغات الصوتية إلى نص (EN/FR/AR)'],
  'Threshold/anomaly detection': ['Detect sensor threshold breaches and anomalies', 'Détecter les dépassements de seuils et anomalies des capteurs', 'اكتشاف تجاوز العتبات والانحرافات في المستشعرات'],
  'Predictive quality models': ['Run predictive quality models on sensor data', 'Exécuter les modèles prédictifs de qualité sur les données capteurs', 'تشغيل نماذج الجودة التنبؤية على بيانات المستشعرات'],
  'Remote expert': ['Connect a remote expert to the inspection', "Connecter un expert à distance à l'inspection", 'ربط خبير عن بعد بعملية التفتيش'],
  'Auto-log findings': ['Log inspection findings automatically', "Journaliser automatiquement les constats d'inspection", 'تسجيل ملاحظات التفتيش تلقائيًا'],
  'AR training mode': ['Train inspectors in augmented-reality mode', 'Former les inspecteurs en mode réalité augmentée', 'تدريب المفتشين بوضع الواقع المعزز'],
  'Bulk signatures': ['Sign documents in bulk', 'Signer les documents en masse', 'توقيع الوثائق بشكل مجمع'],
  'Multi-party': ['Route documents for multi-party signature', 'Acheminer les documents pour signature multipartite', 'توجيه الوثائق للتوقيع متعدد الأطراف'],
  'Pre-load standards': ['Pre-load sector standards into the pack', 'Précharger les normes sectorielles dans le pack', 'تحميل معايير القطاع مسبقًا في الحزمة'],
  'Video interviews': ['Conduct audit interviews by video', "Mener les entretiens d'audit par vidéo", 'إجراء مقابلات التدقيق عبر الفيديو'],
  'Governance/versioning': ['Govern and version low-code workflows', 'Gouverner et versionner les workflows low-code', 'حوكمة مسارات العمل منخفضة البرمجة وإدارة إصداراتها'],
  'Ratings/reviews': ['Rate and review marketplace items', 'Noter et commenter les éléments de la place de marché', 'تقييم عناصر السوق ومراجعتها'],
  'Revenue sharing': ['Calculate marketplace revenue sharing', 'Calculer le partage des revenus de la place de marché', 'احتساب تقاسم إيرادات السوق'],
  'Performance dashboards': ['Publish supplier performance dashboards', 'Publier les tableaux de bord de performance fournisseurs', 'نشر لوحات أداء الموردين'],
  'CAPA collaboration': ['Collaborate with suppliers on CAPA', 'Collaborer avec les fournisseurs sur les CAPA', 'التعاون مع الموردين في الإجراءات التصحيحية والوقائية'],
  'Auto-classify/route': ['Classify and route complaints automatically', 'Classer et router automatiquement les réclamations', 'تصنيف الشكاوى وتوجيهها تلقائيًا'],
  'Post-crisis analysis': ['Analyze the crisis response after closure', 'Analyser la réponse à la crise après clôture', 'تحليل الاستجابة للأزمة بعد انتهائها'],
  'Thickness measurements': ['Measure wall thickness', "Mesurer l'épaisseur des parois", 'قياس سماكة الجدران'],
  'Visual inspections': ['Perform visual inspections', 'Réaliser les inspections visuelles', 'إجراء عمليات الفحص البصري'],
  'NDT': ['Perform non-destructive testing', 'Réaliser les contrôles non destructifs', 'إجراء الاختبارات غير الإتلافية'],
  'Fitness-for-service': ['Assess fitness for service', "Évaluer l'aptitude au service", 'تقييم الصلاحية للخدمة'],
  'Remaining life': ['Estimate remaining life of equipment', 'Estimer la durée de vie résiduelle des équipements', 'تقدير العمر المتبقي للمعدات'],
  'Personal sampling': ['Take personal exposure samples', "Réaliser les prélèvements individuels d'exposition", 'أخذ عينات التعرض الشخصية'],
  'Area sampling': ['Take workplace area samples', "Réaliser les prélèvements d'ambiance", 'أخذ عينات بيئة العمل'],
  'Pre-employment exams': ['Schedule pre-employment medical exams', "Planifier les visites médicales d'embauche", 'جدولة الفحوص الطبية قبل التوظيف'],
  'Periodic exams': ['Schedule periodic medical exams', 'Planifier les visites médicales périodiques', 'جدولة الفحوص الطبية الدورية'],
  'Exit exams': ['Schedule exit medical exams', 'Planifier les visites médicales de fin de contrat', 'جدولة الفحوص الطبية عند انتهاء الخدمة'],
  'External inspections': ['Perform external inspections of pressure equipment', 'Réaliser les inspections externes des équipements sous pression', 'إجراء التفتيش الخارجي لمعدات الضغط'],
  'Internal inspections': ['Perform internal inspections of pressure equipment', 'Réaliser les inspections internes des équipements sous pression', 'إجراء التفتيش الداخلي لمعدات الضغط'],
  'Hydrostatic testing': ['Perform hydrostatic tests', 'Réaliser les épreuves hydrostatiques', 'إجراء الاختبارات الهيدروستاتيكية'],
  'Criticality analysis': ['Analyze asset criticality', 'Analyser la criticité des actifs', 'تحليل الأهمية الحرجة للأصول'],
  'Predictive maintenance': ['Plan predictive maintenance', 'Planifier la maintenance prédictive', 'تخطيط الصيانة التنبؤية'],
  'Vessel inspections': ['Inspect vessels', 'Inspecter les navires', 'تفتيش السفن'],
  'Crew certifications': ['Verify crew certifications', "Vérifier les brevets de l'équipage", 'التحقق من شهادات الطاقم'],
  'Drills/training': ['Run safety drills and training', 'Organiser les exercices et formations de sécurité', 'تنفيذ تمارين السلامة والتدريب'],
  'Safety equipment': ['Inspect safety equipment', 'Inspecter les équipements de sécurité', 'فحص معدات السلامة'],
  'Internal audits': ['Conduct internal safety audits', 'Réaliser les audits internes de sécurité', 'إجراء تدقيقات السلامة الداخلية'],
  'Emergency response': ['Respond to maritime emergencies', 'Intervenir sur les urgences maritimes', 'الاستجابة للطوارئ البحرية'],
  'Oil discharge': ['Record oil discharges', "Enregistrer les rejets d'hydrocarbures", 'تسجيل تصريفات الزيوت'],
  'Waste disposal': ['Record waste disposal', "Enregistrer l'élimination des déchets", 'تسجيل التخلص من النفايات'],
  'Emissions': ['Measure air emissions', 'Mesurer les émissions atmosphériques', 'قياس الانبعاثات الهوائية'],
  'Environmental inspections': ['Perform environmental inspections', 'Réaliser les inspections environnementales', 'إجراء عمليات التفتيش البيئي'],
  'Particle monitoring': ['Monitor airborne particles', 'Surveiller les particules en suspension', 'مراقبة الجسيمات العالقة'],
  'Microbial monitoring': ['Monitor microbial contamination', 'Surveiller la contamination microbiologique', 'مراقبة التلوث الميكروبي'],
  'Pressure differentials': ['Monitor pressure differentials', 'Surveiller les différentiels de pression', 'مراقبة فروق الضغط'],
  'Temp/humidity': ['Monitor temperature and humidity', "Surveiller la température et l'humidité", 'مراقبة الحرارة والرطوبة'],
  'Corrective actions': ['Launch cleanroom corrective actions', 'Lancer les actions correctives de la salle propre', 'إطلاق الإجراءات التصحيحية للغرفة النظيفة'],
  'Visual inspection': ['Inspect welds visually', 'Contrôler visuellement les soudures', 'فحص اللحامات بصريًا'],
  'Inventory analysis': ['Analyze the life cycle inventory', "Analyser l'inventaire du cycle de vie", 'تحليل جرد دورة الحياة'],
  'Impact assessment': ['Assess life cycle impacts', 'Évaluer les impacts du cycle de vie', 'تقييم آثار دورة الحياة'],
  'Water inventory': ['Inventory water uses', "Inventorier les usages de l'eau", 'جرد استخدامات المياه'],
  'Mock audit': ['Conduct a mock audit', 'Réaliser un audit à blanc', 'إجراء تدقيق تجريبي'],
  'Immediate action': ['Take immediate action on the nonconformity', 'Prendre une action immédiate sur la non-conformité', 'اتخاذ إجراء فوري بشأن عدم المطابقة'],
  'Simple RCA': ['Perform a simple root cause analysis', 'Réaliser une analyse simple des causes racines', 'إجراء تحليل مبسط للسبب الجذري'],
  'Corrective action': ['Define the corrective action', "Définir l'action corrective", 'تحديد الإجراء التصحيحي'],
  'Change control': ['Control changes to configuration parameters', 'Maîtriser les changements des paramètres de configuration', 'ضبط التغييرات على معاملات التهيئة'],
  'MP-162|Archive records': ['Archive SME exit and transition records', 'Archiver les enregistrements de cession et de transition', 'أرشفة سجلات التخارج والانتقال'],
  'MP-154|Train new': ['Train new employees on the management system', 'Former les nouveaux salariés au système de management', 'تدريب الموظفين الجدد على نظام الإدارة'],
  'Mock audits': ['Conduct mock audits for each standard', 'Réaliser des audits à blanc pour chaque norme', 'إجراء تدقيقات تجريبية لكل معيار'],
  // Explicit rewrites for the SME QMS scenario (MB feedback, User Guide 2)
  'MP-001|Review periodically': ['Review organizational context periodically', "Revoir périodiquement le contexte de l'organisme", 'مراجعة سياق المؤسسة دوريًا'],
  'MP-001|Validate and cascade': ['Validate and cascade stakeholder requirements', 'Valider et décliner les exigences des parties intéressées', 'المصادقة على متطلبات الأطراف المعنية وتفريعها'],
  'MP-001|Identify interactions': ['Identify interactions between processes', 'Identifier les interactions entre processus', 'تحديد التفاعلات بين العمليات'],
  'MP-001|Define/review scope': ['Define or review the management system scope', 'Définir ou revoir le périmètre du système de management', 'تحديد نطاق نظام الإدارة أو مراجعته'],
  'MP-001|Determine needs/expectations': ['Determine needs and expectations of interested parties', 'Déterminer les besoins et attentes des parties intéressées', 'تحديد احتياجات الأطراف المعنية وتوقعاتها'],
  'MP-002|Select policy standards and scope type': ['Select the standards and scope type of the quality policy', 'Sélectionner les normes et le type de périmètre de la politique qualité', 'اختيار معايير سياسة الجودة ونوع نطاقها'],
  'MP-002|Draft policy': ['Write quality policy commitments', "Rédiger les engagements de la politique qualité", 'صياغة التزامات سياسة الجودة'],
  'MP-002|Draft policy from template': ['Generate the quality policy draft from the template', 'Générer le projet de politique qualité à partir du modèle', 'توليد مسودة سياسة الجودة من النموذج'],
  'MP-002|Consult top mgmt': ['Consult top management on the quality policy', 'Consulter la direction sur la politique qualité', 'استشارة الإدارة العليا بشأن سياسة الجودة'],
  'MP-002|Integrate commitments': ['Integrate mandatory commitments into the quality policy', 'Intégrer les engagements obligatoires dans la politique qualité', 'دمج الالتزامات الإلزامية في سياسة الجودة'],
  'MP-002|Align with requirements': ['Align the quality policy with ISO requirements and strategy', 'Aligner la politique qualité sur les exigences ISO et la stratégie', 'مواءمة سياسة الجودة مع متطلبات ISO والاستراتيجية'],
  'MP-002|Obtain approval': ['Obtain top management approval of the quality policy', 'Obtenir l\'approbation de la politique qualité par la direction', 'الحصول على موافقة الإدارة العليا على سياسة الجودة'],
  'MP-002|Communicate': ['Communicate the quality policy', 'Communiquer la politique qualité', 'التواصل بشأن سياسة الجودة'],
  'MP-002|Plan review': ['Plan the quality policy review', 'Planifier la revue de la politique qualité', 'تخطيط مراجعة سياسة الجودة'],
  'MP-002|Update': ['Update the quality policy document', 'Mettre à jour le document de politique qualité', 'تحديث وثيقة سياسة الجودة'],
  'MP-002|Review and approve policy version': ['Review and approve the quality policy version', 'Revoir et approuver la version de la politique qualité', 'مراجعة إصدار سياسة الجودة واعتماده'],
  'MP-002|Publish policy and generate downloadable files': ['Publish the quality policy and generate its files', 'Publier la politique qualité et générer ses fichiers', 'نشر سياسة الجودة وتوليد ملفاتها'],
  'MP-003|Cascade': ['Cascade the quality policy into quality objectives', 'Décliner la politique qualité en objectifs qualité', 'تفريع سياسة الجودة إلى أهداف جودة'],
  'MP-003|Define SMART': ['Define SMART quality objectives', 'Définir des objectifs qualité SMART', 'تحديد أهداف جودة ذكية (SMART)'],
  'MP-003|Align': ['Align quality objectives with the quality policy', 'Aligner les objectifs qualité sur la politique qualité', 'مواءمة أهداف الجودة مع سياسة الجودة'],
  'MP-003|Designate responsible': ['Designate an owner for each quality objective', 'Désigner un responsable pour chaque objectif qualité', 'تعيين مسؤول لكل هدف من أهداف الجودة'],
  'MP-003|Deploy': ['Deploy quality objectives in the objectives register', 'Déployer les objectifs qualité dans le registre des objectifs', 'نشر أهداف الجودة في سجل الأهداف'],
  'MP-003|Monitor': ['Monitor progress of quality objectives', "Suivre l'avancement des objectifs qualité", 'متابعة تقدم أهداف الجودة'],
  'MP-003|Ensure visibility': ['Display quality objectives at workstations', 'Afficher les objectifs qualité aux postes de travail', 'عرض أهداف الجودة في مواقع العمل'],
  'MP-003|Adjust': ['Adjust quality objectives and targets', 'Ajuster les objectifs et cibles qualité', 'تعديل أهداف الجودة ومستهدفاتها'],
  'MP-003|Celebrate': ['Recognize teams that reach quality objectives', 'Reconnaître les équipes qui atteignent les objectifs qualité', 'تكريم الفرق التي تحقق أهداف الجودة'],
  'MP-003|Translate policy': ['Translate quality policy commitments into objective statements', 'Traduire les engagements de la politique en énoncés d\'objectifs', 'ترجمة التزامات السياسة إلى صيغ أهداف'],
  'MP-004|Define scope': ['Define the process architecture scope', "Définir le périmètre de l'architecture des processus", 'تحديد نطاق بنية العمليات'],
  'MP-004|Identify core/support': ['Identify core, support and management processes', 'Identifier les processus de réalisation, de support et de management', 'تحديد العمليات الأساسية والداعمة والإدارية'],
  'MP-004|Map in BPMN': ['Map each process in BPMN', 'Modéliser chaque processus en BPMN', 'نمذجة كل عملية بتدوين BPMN'],
  'MP-004|Assign RACI': ['Assign RACSI roles to each process', 'Attribuer les rôles RACSI à chaque processus', 'إسناد أدوار RACSI لكل عملية'],
  'MP-004|Validate': ['Validate the process map with process owners', 'Valider la cartographie avec les pilotes de processus', 'المصادقة على خريطة العمليات مع مالكيها'],
  'MP-004|Verify alignment': ['Verify process map alignment with ISO 9001 §4.4', 'Vérifier l\'alignement de la cartographie avec ISO 9001 §4.4', 'التحقق من توافق خريطة العمليات مع ISO 9001 §4.4'],
  'MP-004|Publish': ['Publish the process map', 'Publier la cartographie des processus', 'نشر خريطة العمليات'],
  'MP-004|Review': ['Review the process map', 'Revoir la cartographie des processus', 'مراجعة خريطة العمليات'],
  'MP-004|Flag lowest-level elements as tasks': ['Flag lowest-level process elements as executable tasks', 'Marquer les éléments de plus bas niveau comme tâches exécutables', 'وسم عناصر المستوى الأدنى كمهام قابلة للتنفيذ'],
};

// Step order fixes. MP-002: standards are selected once, before any policy drafting; the
// template draft (AI) comes before the manual adaptation, so the two drafting steps no longer
// look like duplicates. [stepId, task, optional form kind]
export const MP_REORDER = {
  'MP-002': [
    ['MP-002.10', 'T1', 'standards'], ['MP-002.1', 'T1'], ['MP-002.3', 'T1'],
    ['MP-002.11', 'T2'], ['MP-002.2', 'T2'], ['MP-002.4', 'T2', 'list'], ['MP-002.5', 'T2'],
    ['MP-002.12', 'T3', 'assess'], ['MP-002.6', 'T3'], ['MP-002.13', 'T3'], ['MP-002.7', 'T3'], ['MP-002.8', 'T3', 'review'], ['MP-002.9', 'T3'],
  ],
};
// Renames that come with the reorder.
Object.assign(NAME_OVERRIDES, {
  'MP-002|Draft policy': ['Adapt the quality policy commitments to the organization', "Adapter les engagements de la politique qualité à l'organisme", 'تكييف التزامات سياسة الجودة مع المؤسسة'],
  'MP-002|Review and approve policy version': ['Check the quality policy draft against ISO 9001 §5.2', 'Vérifier le projet de politique qualité au regard d\'ISO 9001 §5.2', 'فحص مسودة سياسة الجودة وفق ISO 9001 §5.2'],
});
