// Facts verified against journi's SRS / Master User Guide and this project's
// own archetype-guide series. Every module number, phase name, alert ID,
// and milestone below is drawn from real source, not invented.

const TYPES = [
  {
    id: 'ERP', name: 'ERP Implementation', icon: 'server', color: '2E5F8A',
    oneLiner: 'A full system cutover across every site at once — the only archetype where all four frameworks matter equally, all the time.',
    businessDriver: 'Replacing fragmented, manual, or legacy tooling with one integrated system of record across every site and function.',
    population: 'The broadest population of any archetype — every user of the system being replaced, across every site.',
    templateId: 'TPL-ERP-8', phaseCount: 8,
    phases: ['Discovery', 'Design', 'Build', 'Test', 'Train', 'Deploy', 'Hypercare', 'Sustain'],
    weighting: 'ADKAR + Lewin dominate equally. A system cutover needs organizational readiness (Lewin\'s Change → Refreeze) and individual capability (ADKAR\'s Knowledge/Ability) at the same time — neither alone is sufficient, and this is the only archetype where that is true throughout, not just at one phase.',
    modules: [
      ['M17 (WBS & Gantt)', 'The 8-phase TPL-ERP-8 template, the longest and most detailed schedule of any archetype.'],
      ['M5 (ADKAR Engine)', 'Scored per site/cohort — the direct input to catching site-level divergence (Exception E6).'],
      ['M9 (Training)', 'The Train phase\'s entire content — job aids, sandbox environments, per-site delivery waves.'],
      ['M12 (Sustainment)', 'The Hypercare-to-Sustain handoff — the checkpoint that actually justifies closing Lewin at Refreeze.'],
    ],
    scenario: {
      name: 'Bouregreg ERP Adoption Program', population: '3,400 staff, all sites (Casablanca, Kenitra, Settat)', weeks: 'W1–64',
      milestones: [
        ['W1', 'Discovery opens; Lewin opens at Unfreeze.'],
        ['W28', 'Test phase; Casablanca finance cohort fires ALT-001 (Divergence Pattern Detected).'],
        ['W36–39', 'Train phase; site-level Composite Readiness Index disaggregation (Exception E6).'],
        ['W48', 'Deploy — go-live across all three sites.'],
        ['W60+', 'Hypercare exits clean; Sustain phase confirms adoption holds.'],
      ],
      proof: 'A real Divergence Pattern catch before go-live, a real cross-site CRI disaggregation, and a Refreeze closed only once Sustain\'s own evidence supports it.',
    },
    alerts: { fires: ['ALT-001 (Divergence Pattern Detected)', 'ALT-009 (Phase Gate No-Go/Conditional, if any gate closes non-Go)'], note: 'The throughline case — the one most likely to exercise a Knowledge/Ability-vs-Bridges divergence, given its scale and duration.' },
    team: [
      ['CFO, Bouregreg Group', 'ES', 'Sponsor'],
      ['Driss El Amrani', 'CM', 'Change Manager — owns day-to-day program execution'],
      ['Ghita Bennis', 'PM', 'Practitioner / Contributor — PM-track coordination'],
      ['Houda Zerouali', 'FPO', 'People Manager'],
      ['Reda Loukili', 'EU', 'Employee'],
    ],
  },
  {
    id: 'BPR', name: 'Business Process Redesign', icon: 'route', color: RED_COLOR(),
    oneLiner: 'Redesigning a process independent of any system change — where staff who privately own today\'s workarounds resist a redesign that makes those workarounds obsolete.',
    businessDriver: 'A process that works, technically, but costs the organization real time or money by design — not a tooling problem.',
    population: 'A single function or process family, typically 100-200 staff — narrower than ERP, but often the most emotionally invested population in the library.',
    templateId: 'TPL-BPR-7', phaseCount: 7,
    phases: ['Intake & Diagnosis', 'Clean-Slate Design', 'Build', 'Pilot', 'Rollout', 'Stabilization', 'Sustainment'],
    weighting: 'Kübler-Ross dominates. Staff who built and privately own today\'s manual workarounds resist a redesign that makes those workarounds obsolete — the Resistance/Anger stage, and the Resistance Log it feeds, is this archetype\'s central risk, more than any specific skill gap.',
    modules: [
      ['M10 (Resistance Log)', 'The archetype\'s most-watched module — 3+ open entries fires ALT-004.'],
      ['M4 (Stakeholder Mapping)', 'Identifies exactly whose workaround is being redesigned away, by name.'],
      ['M17 (WBS & Gantt)', 'The TPL-BPR-7 template — Clean-Slate Design is this archetype\'s defining phase.'],
      ['M21 (Field Notes)', 'Captures the specific, named fear behind a resistance entry, not just its existence.'],
    ],
    scenario: {
      name: 'Order-to-Cash Process Redesign', population: '140 staff, Casablanca finance', weeks: '50 weeks (guide numbering)',
      milestones: [
        ['Wk 1', 'Intake & Diagnosis opens, run alongside the ERP program\'s own Discovery.'],
        ['Wk 10', 'Clean-Slate Design signed off.'],
        ['Wk 20–24', 'Pilot on a single process step; third resistance entry lands, firing ALT-004.'],
        ['Wk 34', 'Organization-wide rollout.'],
        ['Wk 50', 'Sustainment handoff.'],
      ],
      proof: 'A real ALT-004 firing, resolved through a co-designed accuracy safeguard the resisting staff themselves helped define — not overridden from above.',
    },
    alerts: { fires: ['ALT-004 (Resistance Escalation Threshold Breached)'], note: 'Built deliberately to cross the resistance-escalation threshold — the defining alert of this archetype.' },
    team: [
      ['Karim Zniber', 'ES', 'Sponsor — VP Finance'],
      ['Imane Berrada', 'CM', 'Change Manager'],
      ['Othmane Rifai', 'PM', 'Program Manager'],
      ['Salwa Tazi', 'FPO', 'Functional Process Owner'],
      ['Karim Alami', 'ITL', 'IT/Technical Lead'],
      ['Amina Sebti', 'SUP', 'Supervisor'],
    ],
  },
  {
    id: 'Automation', name: 'Business Process Automation', icon: 'robot', color: TEAL_COLOR(),
    oneLiner: 'A narrow, well-scoped RPA project with no judgment calls — journi\'s deliberate low-resistance, fast-moving contrast case.',
    businessDriver: 'A repetitive task with no judgment calls involved — a strong automation candidate by nature, not a cultural or process problem.',
    population: 'The narrowest population of any archetype — a single team, often under 20 staff, already bought into the change.',
    templateId: 'TPL-BPA-7', phaseCount: 7,
    phases: ['Automation-Opportunity Assessment', 'Architecture Design', 'Build', 'UAT & Shadow-Mode', 'Production Go-Live', 'Exception Tuning', 'CoE Handover'],
    weighting: 'All four frameworks read favorably from the start, by design. This is journi\'s deliberate contrast case: a narrow scope, an already-bought-in team, and a visibly active Sponsor mean no framework carries unusual risk — the point being that not every program needs a recovery playbook.',
    modules: [
      ['M17 (WBS & Gantt)', 'The shortest phase template in the library — closed in as few as 18-19 weeks.'],
      ['M5 (ADKAR Engine)', 'A light-touch score, since the team starts already bought in.'],
      ['M7 (Sponsor & Coalition)', 'A visibly active Sponsor from day one — the opposite pattern of the Cultural case.'],
      ['M21 (Field Notes)', 'Routine logging — this archetype\'s data is notable for how little it needs to escalate.'],
    ],
    scenario: {
      name: 'Kenitra Invoice-Matching Automation', population: '18 staff, Kenitra accounts payable', weeks: '19 weeks (guide numbering)',
      milestones: [
        ['Wk 1', 'Opportunity assessment; already-bought-in team confirmed.'],
        ['Wk 5', 'Architecture design.'],
        ['Wk 10', 'Build complete.'],
        ['Wk 13–14', 'UAT and shadow-mode — the bot runs alongside the manual process for two weeks.'],
        ['Wk 16', 'Production go-live.'],
        ['Wk 19', 'CoE handover — closed without any of journi\'s 9 live alerts firing.'],
      ],
      proof: 'A clean-close record stated plainly, without a manufactured crisis — the deliberate contrast to every other case in the library.',
    },
    alerts: { fires: [], note: 'None. Closed by design without any of journi\'s 9 live alerts firing — the clean-close contrast case that proves not every program needs a recovery playbook.' },
    team: [
      ['Hakim Berrada', 'ES', 'Sponsor'],
      ['Salma Ouazzani', 'CM', 'Change Manager'],
      ['Amine Sqalli', 'PM', 'Program Manager'],
      ['Yassine Kabbaj', 'ITL', 'IT/Technical Lead'],
      ['Nawal Fassi', 'FPO, SUP', 'Functional Process Owner and Supervisor, combined'],
    ],
  },
  {
    id: 'QMS', name: 'Integrated Management System', icon: 'certificate', color: ORANGE_COLOR(),
    oneLiner: 'Pursuing ISO 9001/14001 certification on one management system rather than two — sponsored alone, without a guiding coalition.',
    businessDriver: 'A customer contract now requires certified quality management; a parallel certification is bundled in for efficiency.',
    population: 'A plant\'s operations and quality function together — often 300-500 staff, spanning shop floor and back office.',
    templateId: 'TPL-IMS-7', phaseCount: 7,
    phases: ['Intake & Diagnosis', 'Design', 'Implementation', 'Mock-up Audit', 'Certifying Audit', 'Surveillance Prep', 'Ongoing Surveillance'],
    weighting: 'Lewin never fully closes. Ongoing Surveillance is the longest single-phase tail in the library by design — certification surveillance never formally ends, so Refreeze is the one Lewin stage this archetype treats as a standing state, not a destination.',
    modules: [
      ['M7 (Sponsor & Coalition)', 'The archetype\'s central risk — fewer than 2 coalition members fires ALT-010.'],
      ['M17 (WBS & Gantt)', 'The TPL-IMS-7 template — Mock-up and Certifying Audit are external-facing gates.'],
      ['M12 (Sustainment)', 'Ongoing Surveillance checkpoints, run indefinitely past program close.'],
      ['M19 (Charter Registry)', 'Formal charters carry unusual weight given the external audit stakes.'],
    ],
    scenario: {
      name: 'ISO 9001/14001 Integrated Management System', population: '410 staff, Settat plant operations + quality', weeks: '60 weeks (guide numbering)',
      milestones: [
        ['Wk 1', 'Intake & diagnosis, started alongside the ERP program\'s own kickoff.'],
        ['Wk 12', 'Design.'],
        ['Wk 26', 'Implementation; the Quality Manager\'s coalition gap is logged and ALT-010 fires.'],
        ['Wk 38', 'Mock-up audit.'],
        ['Wk 46', 'Certifying audit — passes clean.'],
        ['Wk 50+', 'Surveillance prep, then ongoing surveillance — never formally closes.'],
      ],
      proof: 'A real ALT-010 firing, resolved by recruiting a Procurement Director and HR Business Partner as genuine coalition members — not just a wider distribution list.',
    },
    alerts: { fires: ['ALT-010 (Guiding Coalition Gap)'], note: 'Built specifically because a Quality Manager sponsoring alone, without a broader coalition, is a realistic single-sponsor failure mode.' },
    team: [
      ['Nadia Fassi', 'ES', 'Sponsor — Quality Manager'],
      ['Rania Bensouda', 'CM', 'Change Manager'],
      ['Samir Chraibi', 'PM', 'Program Manager'],
      ['Mehdi Ouahbi', 'FPO', 'Functional Process Owner'],
      ['Yasmine Kadiri', 'ITL', 'IT/Technical Lead'],
      ['Aziz Berrada', 'SUP', 'Supervisor'],
    ],
  },
  {
    id: 'Cultural', name: 'Cultural / Values Transformation', icon: 'people-group', color: PURPLE_COLOR(),
    oneLiner: 'Aligning two distinct ways of working under one set of values after an acquisition — not a system or process change at all.',
    businessDriver: 'A stated acquisition synergy that depends on two separate workforces actually operating as one company within a fixed horizon.',
    population: 'An acquired team plus their new counterparts — identity-level change reaching everyone touched by the integration, not a functional subset.',
    templateId: 'TPL-CULT-7', phaseCount: 7,
    phases: ['Diagnosis', 'Target Values Design', 'Leadership Modeling & Reinforcement Build', 'Pilot Cohort', 'Organization-Wide Rollout', 'Reinforcement Through Skepticism', 'Institutionalization'],
    weighting: 'Bridges and Kübler-Ross dominate. Identity and emotional integration matter more than any specific skill here — a newly appointed Sponsor with zero logged actions damages exactly these two frameworks fastest, which is why this archetype is built to fire ALT-003 early.',
    modules: [
      ['M6 (Emotional & Transition Layer)', 'The heaviest use of Bridges and Kübler-Ross of any archetype — two starting cultures tracked side by side.'],
      ['M7 (Sponsor & Coalition)', 'A newly appointed Sponsor starts with zero logged actions — the direct ALT-003 trigger.'],
      ['M5 (ADKAR Engine)', 'Desire is the block most exposed here — a named, specific fear (job security) stalls it.'],
      ['M8 (Communications)', 'Joint briefings for paired cohorts, not separate messaging for each legacy culture.'],
    ],
    scenario: {
      name: 'One Bouregreg: Post-Acquisition Culture Integration', population: '260 staff (acquired Tangier team) + Bouregreg counterparts', weeks: '18-month horizon, W27 onward',
      milestones: [
        ['Wk 1 (org W27)', 'Diagnosis opens, six months into the ERP program.'],
        ['Wk 4 (org W30)', 'Target-values design; ALT-003 fires before the Sponsor\'s first logged action.'],
        ['Wk 12 (org W38)', 'Leadership modeling and reinforcement build begins.'],
        ['Wk 20 (org W46)', 'Pilot cohort — one Tangier team paired with one legacy Bouregreg team.'],
        ['Wk 32 (org W58)', 'Organization-wide rollout; reinforcement continues well past the ERP program\'s own close.'],
      ],
      proof: 'A real Sponsor Coverage Gap that fires and is corrected, a real Desire stall traced to a named fear, and a Refreeze signed only once the evidence — not the acquisition\'s press-release timeline — supports it.',
    },
    alerts: { fires: ['ALT-003 (Sponsor Coverage Gap)'], note: 'Built deliberately around a newly appointed Sponsor\'s slow start — the archetype most exposed to sponsorship visibility risk.' },
    team: [
      ['Karim Fassi', 'ES', 'Sponsor — newly appointed integration Sponsor'],
      ['Nadia Chraibi', 'CM', 'Change Manager'],
      ['Youssef Idrissi', 'PM', 'Integration Program Manager'],
      ['Amal Ziani', 'FPO', 'HR Business Partner for the integration'],
      ['Hicham Bennani', 'ITL', 'Systems/tooling lead'],
      ['Fatima-Zahra Idrissi', 'SUP', 'Tangier Distribution Center site lead'],
      ['Rachid Amrani', 'SUP', 'Casablanca supply chain/logistics lead'],
    ],
  },
  {
    id: 'Operating Model', name: 'Operating Model Redesign', icon: 'sitemap', color: BLUE_COLOR(),
    oneLiner: 'Realigning reporting lines from site-based to function-based — where the real risk is reversion under pressure, not initial adoption.',
    businessDriver: 'A prior program (often ERP) exposes how much duplicated decision-making the old structure causes.',
    population: 'People-manager-level staff across every site — narrower in headcount than ERP, but concentrated at the decision-making layer.',
    templateId: 'TPL-OM-7', phaseCount: 7,
    phases: ['Current Operating Model Assessment', 'TOM Design', 'Detailed Org Design', 'Pilot Transition', 'Full Transition', 'Governance Adoption Tracking', 'Standing Rhythm Handover'],
    weighting: 'ADKAR Reinforcement dominates. Function Heads can pass every earlier checkpoint and still revert to old decision-making under real operational pressure — this archetype is built specifically to show that failure mode, not initial adoption, is the real test.',
    modules: [
      ['M12 (Sustainment)', 'The 30-day post-transition checkpoint — where a High regression risk fires ALT-002.'],
      ['M5 (ADKAR Engine)', 'Reinforcement tracked separately from Ability, since this archetype is where the two diverge.'],
      ['M17 (WBS & Gantt)', 'The TPL-OM-7 template — Pilot Transition de-risks Full Transition, one site at a time.'],
      ['M6 (Emotional & Transition Layer)', 'A premature "New Beginning" reading is exactly what a regression later contradicts.'],
    ],
    scenario: {
      name: 'Regional Operating Model Redesign', population: '95 staff, people managers across 3 sites', weeks: '34 weeks (guide numbering)',
      milestones: [
        ['Wk 1', 'Current operating model assessment opens, once the ERP Build phase exposes duplication.'],
        ['Wk 8', 'Target operating model design.'],
        ['Wk 14', 'Detailed org design.'],
        ['Wk 18', 'Pilot transition — Casablanca Finance first.'],
        ['Wk 22 / 26', 'Full transition; the 30-day checkpoint lands High regression risk, firing ALT-002/ALT-015.'],
        ['Wk 34', 'Governance adoption tracking and standing rhythm handover, resolved only once a clean checkpoint follows.'],
      ],
      proof: 'A real regression caught by a genuine 30-day checkpoint — not glossed over — and a training-completion record (100% by Week 25) that proves Reinforcement, not Knowledge, was the actual gap.',
    },
    alerts: { fires: ['ALT-002 (Regression Risk Score Critical)', 'ALT-015 (Sustainment Sign-Off Blocked)'], note: 'Built to run past its first sustainment checkpoint with High regression risk — the clearest real-data proof in the library that training completion alone does not guarantee reinforcement.' },
    team: [
      ['Yassine Berrada', 'ES', 'Sponsor — COO'],
      ['Salma Idrissi', 'CM', 'Change Manager'],
      ['Rachid Alaoui', 'PM', 'Program Manager'],
      ['Amina Sqalli', 'FPO', 'Finance Function Head'],
      ['Nabil Ouazzani', 'ITL', 'IT/Technical Lead'],
      ['Loubna Tazi', 'SUP', 'Casablanca pilot site'],
    ],
  },
  {
    id: 'Compliance', name: 'Compliance-Driven Change', icon: 'gavel', color: INK_COLOR(),
    oneLiner: 'Bringing data handling into compliance with a fixed external deadline — the case where a Phase Gate closing as anything but Go has zero schedule slack to absorb it.',
    businessDriver: 'A scheduled regulatory audit with a fixed external deadline, not a discretionary program timeline.',
    population: 'Any function touching the regulated data — often 300+ staff spanning HR, Sales, and Customer Service.',
    templateId: 'TPL-COMP-7', phaseCount: 7,
    phases: ['Regulatory Requirement & Gap Analysis', 'Control Design', 'Control Implementation', 'Internal Audit / Independent Testing', 'Controls Go Live', 'First Monitoring Cycle', 'Ongoing Compliance Handover'],
    weighting: 'Awareness and Ability dominate; Desire matters least of any archetype. Staff do not need to want to comply — they need to know the rule and be able to follow it correctly. The Phase Gate itself is the framework that matters most, since the real risk here is schedule risk, not adoption risk.',
    modules: [
      ['M17 (WBS & Gantt)', 'The TPL-COMP-7 template — every phase gate dated against a fixed external deadline.'],
      ['M5 (ADKAR Engine)', 'Awareness and Ability scored against specific, checkable rules — not general sentiment.'],
      ['M19 (Charter Registry)', 'Formal charters matter more here given the external regulator relationship.'],
      ['M9 (Training)', 'Checkable-behavior training — data handling, retention, access requests — not persuasion.'],
    ],
    scenario: {
      name: 'Loi 09-08 Data Protection Compliance Program', population: '310 staff, HR, Sales, Customer Service', weeks: '64 weeks (guide numbering)',
      milestones: [
        ['Wk 1', 'Regulatory requirement and gap analysis, run from the tenant\'s own start given the fixed deadline.'],
        ['Wk 14', 'Control design.'],
        ['Wk 28', 'Control implementation.'],
        ['Wk 40', 'Internal audit / independent testing.'],
        ['Wk 48', 'Controls go live, timed deliberately ahead of the ERP program\'s own Deploy week.'],
        ['Wk 52', 'First monitoring cycle confirms controls hold under real operating conditions.'],
      ],
      proof: 'Seven consecutive clean Phase Gate decisions — ALT-009 matters here precisely because it never fires, given zero schedule slack for anything less than Go.',
    },
    alerts: { fires: [], note: 'None fire in this program\'s real record — every Phase Gate closes Go, on schedule, which is the entire point: ALT-009 (Phase Gate No-Go/Conditional) matters most here precisely because it does not fire.' },
    team: [
      ['Karim Idrissi', 'ES', 'Sponsor — General Counsel/Chief Compliance Officer'],
      ['Sanaa Bouzoubaa', 'CM', 'Change Manager'],
      ['Hamza Alaoui', 'PM', 'Compliance Program Lead'],
      ['Nadia Squalli', 'FPO', 'HR Data Privacy Lead'],
      ['Reda Fassi', 'ITL', 'Data systems and access-control lead'],
      ['Amine Tazi', 'SUP', 'Sales Operations Manager'],
    ],
  },
  {
    id: 'Training & Skills', name: 'Training & Skills Development', icon: 'graduation-cap', color: TEAL_MID_COLOR(),
    oneLiner: 'A standalone digital-skills program with no go-live of its own — the only archetype where training is the entire content of every phase, not a supporting track.',
    businessDriver: 'A skills gap identified independently of any other program, run to prepare a workforce for years of technology change generally.',
    population: 'Plant-floor staff without prior systems training — often 600+ staff across multiple sites, the largest population of any non-ERP archetype.',
    templateId: 'TPL-TSD-7', phaseCount: 7,
    phases: ['Skills Gap Diagnosis', 'Curriculum Design', 'Training Delivery', 'Competency Verification', 'Practical Application', 'On-the-Job Coaching', 'Skills Sustainment'],
    weighting: 'All five ADKAR blocks dominate equally, in sequence. Reinforcement is engineered by two dedicated phases (Practical Application, On-the-Job Coaching) — the only archetype in the series to build reinforcement deliberately rather than leave it to chance.',
    modules: [
      ['M9 (Training)', 'The heaviest use of any archetype — the entire program\'s content runs through this module.'],
      ['M16 (AI Use Case Library)', 'AI-assisted curriculum drafting — the archetype that most exercises this module.'],
      ['M5 (ADKAR Engine)', 'All five blocks tracked in sequence, from Awareness through Reinforcement.'],
      ['M12 (Sustainment)', 'Two consecutive clean checkpoints, spaced apart, before the program closes Refreeze.'],
    ],
    scenario: {
      name: 'Plant Digital Skills Upskilling Program', population: '620 staff, plant floor, Kenitra and Settat', weeks: '43 weeks (guide numbering)',
      milestones: [
        ['Wk 1', 'Skills gap diagnosis opens.'],
        ['Wk 15', 'Curriculum finalized, AI-assisted via M16.'],
        ['Wk 23', 'Pilot cohort validated.'],
        ['Wk 29', 'Full deployment complete across both plants.'],
        ['Wk 31', 'Competency verification confirms 100% certification.'],
        ['Wk 43', 'Two consecutive sustainment checks confirm the skill holds without coaching; program closes.'],
      ],
      proof: 'A skill genuinely verified through hands-on testing (not attendance), and reinforcement engineered on purpose through two dedicated phases — not left to chance.',
    },
    alerts: { fires: [], note: 'None — none of journi\'s 9 live alerts are built around a standalone skills program with no go-live and no resistance log of its own.' },
    team: [
      ['Fouad Belghazi', 'ES', 'Sponsor — VP Manufacturing Operations'],
      ['Houda Amrani', 'CM', 'Change Manager'],
      ['Tarik Benjelloun', 'PM', 'Skills Program Lead'],
      ['Leila Ouahbi', 'FPO', 'Learning & Development Lead'],
      ['Younes Berrada', 'ITL', 'Learning-systems and AI-drafting-tool lead'],
      ['Karima Semlali', 'SUP', 'Kenitra Plant Floor Supervisor'],
      ['Mustapha Idrissi', 'SUP', 'Settat Plant Floor Supervisor'],
    ],
  },
];

// small helpers so the color literals above stay readable without importing deck.js here
function RED_COLOR() { return 'B4463B'; }
function TEAL_COLOR() { return '1F6459'; }
function ORANGE_COLOR() { return 'C2661C'; }
function PURPLE_COLOR() { return '6B4C8A'; }
function BLUE_COLOR() { return '2E5F8A'; }
function INK_COLOR() { return '16221F'; }
function TEAL_MID_COLOR() { return '2C7A6B'; }

module.exports = { TYPES };
