// Demo organizations for the seven industries. All names, people and figures are fictional.
// Each project follows a lifecycle plan (see PLANS in seed.js); plans are listed in the same order for
// every industry so that project codes (e.g. PUB-011) are predictable for the user guide.
export const PLAN_ORDER = [
  'full-retired', 'full-retired', 'full-retiring', 'full-relaunched-03', 'full-relaunched-05', 'full-relaunched-04',
  'full-relaunch-active', 'full-relaunch-active', 'full-eol-active', 'full-eol-recycle', 'full-aftersales', 'full-performance',
  'light-launched', 'light-design', 'light-gate-pending', 'fast-launched', 'fast-dev', 'fast-parked', 'full-killed', 'full-hold', 'full-new',
];

export const INDUSTRIES = [
  {
    key: 'PUB', industry: 'Public Sector', name: 'Metro City Digital Services Agency', domain: 'metrocity.example', country: 'Morocco',
    subscription: 'PACK-11', seats: 60, addons: ['ADD-SEC-02', 'ADD-PRO-01', 'ADD-AI-04', 'ADD-SUP-01'], compliance: ['GDPR', 'ISO27001'],
    integrations: [['INT-CRM-03', 'Citizen service desk (ServiceNow)'], ['INT-DAT-01', 'Open data BI (Power BI)'], ['INT-COL-01', 'Staff notifications (Teams)']],
    segments: ['residents aged 25-60', 'small businesses', 'architects and contractors'], regions: ['Central district', 'North district', 'Coastal district'],
    regulation: 'national data protection law, public procurement code and web accessibility guidelines (WCAG 2.1 AA)',
    risks: ['low digital literacy among older residents', 'integration delays with the national identity platform', 'budget freeze in the next fiscal year'],
    partners: ['the national digital identity agency', 'a local telecom operator'], channels: ['city web portal', 'service kiosks in civic centres'],
    kpiWord: 'online completion rate', unit: 'service requests',
    projects: [
      ['Digital Building Permit Portal', 'Online submission, review and tracking of building permits for residents and architects.', 'Service'],
      ['Smart Parking Permit Service', 'Residents apply for and renew street parking permits online with licence-plate recognition.', 'Service'],
      ['Citizen ID Renewal Kiosks', 'Self-service kiosks in civic centres that capture photos and fingerprints for ID renewal.', 'Product-Service'],
      ['Open Data Transport Dashboard', 'Public dashboard publishing bus punctuality and traffic data as open data.', 'Service'],
      ['Waste Collection Scheduling App', 'Mobile app that tells households their collection days and takes bulky-waste bookings.', 'Service'],
      ['E-Procurement Supplier Portal', 'Portal for suppliers to register, bid on tenders and track purchase orders.', 'Service'],
      ['Tele-Consultation for Social Services', 'Video appointments between social workers and families who cannot travel.', 'Service'],
      ['Public Wi-Fi in Civic Centres', 'Free managed Wi-Fi with a citizen login in 24 civic centres.', 'Product-Service'],
      ['Digital Birth Certificate Service', 'Online request and electronic delivery of certified birth certificates.', 'Service'],
      ['Property Tax Online Payment', 'Online statement, instalment plans and card payment for property tax.', 'Service'],
      ['Street Lighting Fault Reporting', 'Residents report broken street lights with a photo and location; crews get work orders.', 'Service'],
      ['School Enrolment Online Platform', 'Families apply for school places online and receive allocation decisions.', 'Service'],
      ['Library E-Lending Service', 'E-book and audiobook lending through the municipal library card.', 'Service'],
      ['Business Licence Renewal Wizard', 'Guided online renewal of trade licences with document checks.', 'Service'],
      ['Senior Citizen Transport Card', 'Discounted smart transport card for residents over 65 with online top-up.', 'Product-Service'],
      ['City Hall Appointment Booking', 'Online booking of counter appointments at City Hall.', 'Service'],
      ['Water Outage SMS Alerts', 'Opt-in SMS alerts for planned and unplanned water outages by street.', 'Service'],
      ['Tax Questions Chatbot', 'Chatbot answering frequent questions about local taxes.', 'Service'],
      ['Drone Survey of Public Roads', 'Drone imaging to detect potholes and road-marking wear.', 'Product-Service'],
      ['Integrated Emergency Call Dispatch', 'Single dispatch platform for fire, ambulance and municipal police calls.', 'Product-Service'],
      ['Participatory Budget Voting Platform', 'Residents propose and vote on neighbourhood projects funded by the city.', 'Service'],
    ],
  },
  {
    key: 'MFG', industry: 'Manufacturing', name: 'Cedarline Precast Systems', domain: 'cedarline.example', country: 'United Arab Emirates',
    subscription: 'BND-03', seats: 40, addons: ['ADD-SEC-02', 'ADD-INT-02', 'ADD-AI-02'], compliance: ['ISO9001'],
    integrations: [['INT-ERP-01', 'BOM sync with ERP (SAP S/4HANA)'], ['INT-MES-01', 'Work instructions to MES (Opcenter)'], ['INT-SRM-03', 'Supply chain risk feed (Resilinc)']],
    segments: ['residential developers', 'infrastructure contractors', 'modular builders'], regions: ['Gulf region', 'East Africa', 'South Asia'],
    regulation: 'structural design codes, CE / conformity marking for construction products and fire-resistance classification',
    risks: ['cement price volatility', 'curing defects in hot weather', 'transport damage of large elements'],
    partners: ['a structural engineering consultancy', 'a crane and logistics provider'], channels: ['direct sales to contractors', 'distributor network'],
    kpiWord: 'first-pass yield', unit: 'precast elements',
    projects: [
      ['Precast Hollow-Core Floor Slab Line', 'New extrusion line for 200-400 mm hollow-core slabs for residential towers.', 'Product'],
      ['Insulated Sandwich Wall Panel', 'Load-bearing sandwich panel with 100 mm insulation core for fast envelope closure.', 'Product'],
      ['Modular Bathroom Pod', 'Factory-finished bathroom pods delivered ready to connect on site.', 'Product'],
      ['Low-Carbon Cement Blend CX-40', 'Cement blend with 40% supplementary materials to cut embodied carbon.', 'Product'],
      ['Precast Stair and Landing Unit', 'One-piece stair flights with integrated landings and anti-slip nosing.', 'Product'],
      ['Prestressed Bridge Beam Series', 'Standard prestressed beams for 20-35 m highway overpasses.', 'Product'],
      ['GFRC Facade Panel', 'Thin glass-fibre reinforced concrete facade panels in custom textures.', 'Product'],
      ['Reinforced Retaining Wall Block', 'Interlocking retaining wall blocks with steel reinforcement for 6 m walls.', 'Product'],
      ['Modular Classroom Unit', 'Relocatable precast classroom modules with installation service.', 'Product-Service'],
      ['Recycled Aggregate Paving Stone', 'Paving stones with 30% recycled aggregate from demolition waste.', 'Product'],
      ['Precast Utility Vault', 'Underground vaults for electrical and telecom networks.', 'Product'],
      ['Acoustic Noise Barrier Panel', 'Absorptive noise barrier panels for highways and rail lines.', 'Product'],
      ['Lightweight Partition Block', 'Aerated lightweight blocks for internal partitions.', 'Product'],
      ['3D-Printed Column Formwork', 'Reusable 3D-printed formwork for architectural columns.', 'Product'],
      ['Hempcrete Insulation Board', 'Bio-based insulation board for wall retrofits.', 'Product'],
      ['Paving Colour Pigment Update', 'Switch to a UV-stable pigment for the existing paving range.', 'Product'],
      ['Lifting Anchor Redesign', 'Redesigned cast-in lifting anchor for wall panels.', 'Product'],
      ['Decorative Kerb Stone Range', 'Decorative kerb stones for landscaping projects.', 'Product'],
      ['Self-Healing Concrete Pilot', 'Bacteria-based self-healing concrete for water tanks.', 'Product'],
      ['Embedded Sensor Smart Slab', 'Floor slabs with embedded strain and temperature sensors.', 'Product-Service'],
      ['Carbon-Cured Masonry Unit', 'Masonry units cured with captured CO2.', 'Product'],
    ],
  },
  {
    key: 'HLT', industry: 'Healthcare', name: 'Meridale Health Network', domain: 'meridale.example', country: 'France',
    subscription: 'BND-06', seats: 40, addons: ['ADD-SEC-01', 'ADD-SEC-03', 'ADD-IND-04', 'ADD-AI-02'], compliance: ['GDPR', 'HIPAA', 'ISO9001'],
    integrations: [['INT-QMS-02', 'CAPA and NCR sync (MasterControl)'], ['INT-QMS-04', 'Regulatory submissions (Veeva Vault)'], ['INT-ALM-01', 'Software requirements traceability (Polarion)']],
    segments: ['chronic patients at home', 'hospital wards', 'general practitioners'], regions: ['Ile-de-France', 'Occitanie', 'Grand Est'],
    regulation: 'EU Medical Device Regulation 2017/745, GDPR health-data rules and hospital accreditation requirements',
    risks: ['clinical evidence gaps for the notified body', 'patient data privacy breach', 'nurse adoption and training time'],
    partners: ['a university hospital clinical research unit', 'a home-care nursing provider'], channels: ['hospital procurement', 'referral by general practitioners'],
    kpiWord: 'patient adherence', unit: 'patients',
    projects: [
      ['Remote Patient Monitoring Kit', 'Connected blood-pressure, weight and SpO2 kit with nurse follow-up for heart failure patients.', 'Product-Service'],
      ['Tele-Radiology Reading Service', 'Night and weekend remote reading of CT and MRI scans for partner hospitals.', 'Service'],
      ['Smart Infusion Pump Connectivity', 'Connects infusion pumps to the drug library and electronic patient record.', 'Product'],
      ['Home Dialysis Support Programme', 'Training, equipment and remote supervision for home haemodialysis.', 'Product-Service'],
      ['Digital Pathology Scanner Service', 'Whole-slide scanning and remote review of pathology slides.', 'Product-Service'],
      ['Post-Surgery Rehabilitation App', 'Guided exercises and pain tracking after knee and hip surgery.', 'Service'],
      ['Maternal Health Tele-Follow-up', 'Remote follow-up of high-risk pregnancies with midwife video calls.', 'Service'],
      ['Hospital Bed Management System', 'Real-time bed status and discharge planning across wards.', 'Product-Service'],
      ['Diabetic Foot Screening Device', 'Thermal imaging device to detect diabetic foot ulcer risk.', 'Product'],
      ['Chronic Care Nurse Hotline', '24/7 nurse hotline for patients with chronic conditions.', 'Service'],
      ['Sterilization Tracking Service', 'Barcode tracking of surgical instrument sets through sterilization.', 'Product-Service'],
      ['Paediatric Asthma Inhaler Tracker', 'Sensor clip that records inhaler use for children with asthma.', 'Product'],
      ['Patient Portal Lab Results', 'Patients see validated lab results in the patient portal.', 'Service'],
      ['Pharmacy Stock Forecasting', 'Forecasts drug consumption to reduce stock-outs in hospital pharmacies.', 'Service'],
      ['Wearable ECG Patch', 'Seven-day wearable ECG patch with cloud analysis.', 'Product'],
      ['Appointment Reminder SMS', 'SMS reminders 48 hours before outpatient appointments.', 'Service'],
      ['Discharge Summary Template Update', 'Revised discharge summary template for general practitioners.', 'Service'],
      ['Hospital Parking App', 'App to find and pay for visitor parking.', 'Service'],
      ['AI Sepsis Early Warning', 'Algorithm predicting sepsis risk from vital signs.', 'Product'],
      ['Robotic Pharmacy Dispensing', 'Robot dispensing unit doses for inpatient wards.', 'Product'],
      ['Home Chemotherapy Service', 'Oral and subcutaneous chemotherapy at home with nurse visits.', 'Service'],
    ],
  },
  {
    key: 'DAI', industry: 'Agro-Business - Dairy Products', name: 'Valdora Dairy Cooperative', domain: 'valdora.example', country: 'Morocco',
    subscription: 'BND-07', seats: 30, addons: ['ADD-SEC-02', 'ADD-AI-03', 'ADD-CAP-02'], compliance: ['ISO9001'],
    integrations: [['INT-SRM-02', 'Packaging material compliance (Assent)'], ['INT-IOT-01', 'Cold-room sensors (Azure IoT)'], ['INT-DAT-03', 'Sales data lake (Databricks)']],
    segments: ['health-conscious adults', 'families with children', 'food-service buyers'], regions: ['Casablanca-Settat', 'Rabat-Sale', 'Souss-Massa'],
    regulation: 'food safety law, HACCP plan requirements, nutrition and allergen labelling rules',
    risks: ['raw milk supply shortfall in summer', 'shelf-life failure in hot distribution', 'packaging supplier delays'],
    partners: ['member farms of the cooperative', 'a national supermarket chain'], channels: ['modern retail', 'traditional grocery shops'],
    kpiWord: 'shelf-life compliance', unit: 'litres',
    projects: [
      ['Lactose-Free Greek Yogurt', 'Strained yogurt made lactose-free with lactase enzyme, 10% protein.', 'Product'],
      ['Probiotic Drinking Yogurt', 'Drinking yogurt with two clinically studied probiotic strains.', 'Product'],
      ['Aged Goat Cheese Range', 'Three aged goat cheeses sourced from member farms in the Atlas region.', 'Product'],
      ['Plant-Protein Blended Milk', 'Milk blended with pea protein for lower fat and higher protein.', 'Product'],
      ['High-Protein Skyr Cup', 'Skyr-style cup with 15 g protein per serving.', 'Product'],
      ['Organic Butter with Sea Salt', 'Organic butter churned from certified organic cream.', 'Product'],
      ['Ready-to-Drink Coffee Milk', 'Chilled coffee milk in 250 ml bottles for convenience stores.', 'Product'],
      ["Kids' Fruit Yogurt Pouch", 'Squeezable fruit yogurt pouch with reduced sugar for children.', 'Product'],
      ['Whey Protein Isolate Powder', 'Whey protein isolate from cheese-making by-product.', 'Product'],
      ['UHT Milk in Recyclable Carton', 'UHT milk in a fully recyclable carton with a plant-based cap.', 'Product'],
      ['Farm-to-Door Milk Subscription', 'Weekly delivery of fresh milk and yogurt to households.', 'Product-Service'],
      ['Camel Milk Line', 'Pasteurised camel milk and camel milk yogurt.', 'Product'],
      ['Reduced-Sugar Flavoured Milk', 'Flavoured milk with 30% less sugar.', 'Product'],
      ['Kefir Grain Starter Kit', 'Home kefir starter kit with instructions.', 'Product'],
      ['Mozzarella for Food Service', 'Low-moisture mozzarella blocks for pizza restaurants.', 'Product'],
      ['New Laban Label Design', 'Updated label design for the existing laban range.', 'Product'],
      ['1 L Bottle Cap Change', 'Switch to a tethered cap on the 1 L milk bottle.', 'Product'],
      ['Seasonal Date-Flavoured Yogurt', 'Limited edition date-flavoured yogurt for Ramadan.', 'Product'],
      ['Lab-Grown Dairy Protein', 'Precision-fermentation dairy protein pilot.', 'Product'],
      ['Automated Cheese Ripening Room', 'Automated turning and climate control for cheese ripening.', 'Product-Service'],
      ['A2 Milk Range', 'Milk from cows producing only A2 beta-casein.', 'Product'],
    ],
  },
  {
    key: 'TRN', industry: 'Transportation', name: 'Orvane Transit Group', domain: 'orvane.example', country: 'Canada',
    subscription: 'BND-04', seats: 30, addons: ['ADD-SEC-02', 'ADD-PRO-01'], compliance: ['ISO27001'],
    integrations: [['INT-CRM-03', 'Customer service tickets (Salesforce Service Cloud)'], ['INT-IOT-02', 'Vehicle predictive maintenance (ThingWorx)'], ['INT-CAD-04', '3D visualization of vehicle parts']],
    segments: ['daily commuters', 'students', 'business travellers'], regions: ['Metro North', 'Metro South', 'Airport corridor'],
    regulation: 'motor vehicle safety standards, accessibility regulations for transport and payment card security (PCI DSS)',
    risks: ['vehicle delivery delays from the manufacturer', 'union negotiation on new shift patterns', 'fare system cyber attack'],
    partners: ['the regional transit authority', 'a vehicle leasing company'], channels: ['mobile app', 'station ticket machines'],
    kpiWord: 'on-time performance', unit: 'passenger trips',
    projects: [
      ['Electric City Bus Fleet Service', '60 battery-electric buses with depot charging and maintenance contract.', 'Product-Service'],
      ['Contactless Fare Payment System', 'Open-loop contactless card and phone payment on buses and trams.', 'Product-Service'],
      ['Real-Time Passenger Information', 'Stop displays and app feeds with live arrival predictions.', 'Service'],
      ['Predictive Maintenance for Rail Switches', 'Sensors and analytics that predict rail switch failures.', 'Product-Service'],
      ['Bus Rapid Transit Corridor Service', 'Dedicated-lane BRT line with level boarding and signal priority.', 'Service'],
      ['Fleet Telematics Platform', 'Vehicle location, fuel and driving-behaviour data for 900 vehicles.', 'Product-Service'],
      ['Airport Shuttle Service', 'Express shuttle between the airport and the central station every 15 minutes.', 'Service'],
      ['On-Demand Minibus Service', 'App-booked shared minibuses for low-density suburbs.', 'Service'],
      ['Tram Depot Charging Upgrade', 'Upgraded traction power and charging at the main tram depot.', 'Product'],
      ['Freight Rail Tracking Service', 'Wagon tracking and ETA service for freight customers.', 'Service'],
      ['Driver Fatigue Detection System', 'In-cab camera system detecting driver drowsiness.', 'Product'],
      ['Park-and-Ride Smart Access', 'Licence-plate access and payment at park-and-ride lots.', 'Product-Service'],
      ['Mobile Ticketing App v2', 'Second version of the ticketing app with trip planning.', 'Service'],
      ['Bike-Share Integration', 'Bike-share accounts linked to the transit card.', 'Service'],
      ['Accessible Boarding Ramp Retrofit', 'Automatic boarding ramps retrofitted on 120 buses.', 'Product'],
      ['Timetable Print Refresh', 'New printed timetable layout at stops.', 'Service'],
      ['Seat Upholstery Change', 'Anti-vandal seat fabric for the bus fleet.', 'Product'],
      ['Loyalty Points Pilot', 'Loyalty points for frequent riders.', 'Service'],
      ['Autonomous Shuttle Pilot', 'Driverless shuttle on a closed business-park route.', 'Product-Service'],
      ['Hydrogen Bus Trial', 'Trial of five fuel-cell buses.', 'Product'],
      ['Night Bus Network Redesign', 'New night bus network covering hospital and industrial shifts.', 'Service'],
    ],
  },
  {
    key: 'ENR', industry: 'Oil, Gas & Energy', name: 'Kestrel Energy & Utilities', domain: 'kestrel.example', country: 'Oman',
    subscription: 'BND-05', seats: 30, addons: ['ADD-SEC-02', 'ADD-AI-04', 'ADD-PRO-04'], compliance: ['ISO27001', 'ISO9001'],
    integrations: [['INT-ERP-03', 'Cost roll-up with ERP (SAP CO-PA)'], ['INT-COL-02', 'Project milestones (MS Project)'], ['INT-CRM-02', 'Configure-price-quote (Tacton)']],
    segments: ['upstream operators', 'industrial customers', 'residential energy customers'], regions: ['Northern oilfields', 'Coastal industrial zone', 'Capital region'],
    regulation: 'process safety management rules, grid connection codes and environmental permit conditions',
    risks: ['hazardous-area certification delays', 'grid connection approval', 'oil price swings affecting investment'],
    partners: ['an EPC contractor', 'the national grid operator'], channels: ['key account managers', 'utility customer portal'],
    kpiWord: 'availability', unit: 'MWh',
    projects: [
      ['Pipeline Leak Detection Sensor', 'Acoustic fibre sensing that locates pipeline leaks within 10 m.', 'Product-Service'],
      ['Solar Microgrid for Remote Sites', 'Containerised solar and battery microgrid for remote oilfield camps.', 'Product-Service'],
      ['Smart Meter Rollout Service', 'Installation and data service for 250,000 residential smart meters.', 'Product-Service'],
      ['Gas Turbine Predictive Maintenance', 'Vibration and thermal analytics to plan turbine overhauls.', 'Service'],
      ['Offshore Corrosion Monitoring', 'Wireless corrosion probes on offshore platform risers.', 'Product-Service'],
      ['EV Fast-Charging Network', '150 kW fast chargers at 40 service stations.', 'Product-Service'],
      ['Battery Storage for Solar Farms', '50 MWh battery storage to shift solar output to evening peak.', 'Product'],
      ['LPG Home Delivery Service', 'App-ordered LPG cylinder delivery with safety checks.', 'Service'],
      ['Drone Blade Inspection Service', 'Drone inspection of wind turbine blades with defect classification.', 'Service'],
      ['Flare Gas Recovery Unit', 'Compressor package recovering refinery flare gas as fuel.', 'Product'],
      ['Energy Efficiency Audit Service', 'Energy audits and savings plans for industrial customers.', 'Service'],
      ['Green Hydrogen Electrolyser Pilot', '5 MW electrolyser producing hydrogen from solar power.', 'Product'],
      ['Customer Energy Usage App', 'App showing daily consumption and bill forecasts.', 'Service'],
      ['Substation Remote Monitoring', 'Remote monitoring of 60 secondary substations.', 'Product-Service'],
      ['Agricultural Biogas Plant', 'Biogas from date-palm and livestock waste.', 'Product'],
      ['Tariff Leaflet Update', 'Updated tariff leaflet for residential customers.', 'Service'],
      ['Meter Seal Redesign', 'Tamper-evident meter seal redesign.', 'Product'],
      ['Fuel Card Rewards Programme', 'Rewards on the business fuel card.', 'Service'],
      ['Carbon Capture Retrofit', 'Post-combustion carbon capture on a gas power unit.', 'Product'],
      ['Geothermal Heating Network', 'District heating from a shallow geothermal field.', 'Product-Service'],
      ['Floating Solar on Reservoirs', 'Floating solar arrays on water reservoirs.', 'Product'],
    ],
  },
  {
    key: 'RED', industry: 'Real Estate Development', name: 'Ridgeway Real Estate Development', domain: 'ridgeway.example', country: 'Saudi Arabia',
    subscription: 'BND-05', seats: 40, addons: ['ADD-SEC-02', 'ADD-AI-02'], compliance: ['ISO9001', 'ISO27001'],
    integrations: [['INT-ERP-01', 'Sales and cost sync with ERP (Oracle)'], ['INT-COL-01', 'Sales team notifications (Teams)'], ['INT-DAT-01', 'Portfolio BI (Power BI)']],
    segments: ['first-time home buyers', 'investors in off-plan units', 'corporate tenants'], regions: ['Riyadh region', 'Eastern Province', 'Red Sea coast'],
    regulation: 'off-plan sales regulation with escrow accounts, the national building code, municipal zoning approvals and green building rating',
    risks: ['slow off-plan sales in a rising interest-rate market', 'late permits from the municipality', 'contractor delays on handover dates'],
    partners: ['a design-and-build contractor', 'a mortgage bank'], channels: ['sales centres', 'broker network', 'online reservation'],
    kpiWord: 'off-plan pre-sales rate', unit: 'residential units',
    projects: [
      ['Smart Home Apartment Line', 'Apartments delivered with pre-installed smart lighting, climate and access control managed from one app.', 'Product'],
      ['Off-Plan Sales Digital Platform', 'Online reservation, contract signature and escrow instalment tracking for off-plan buyers.', 'Service'],
      ['Build-to-Rent Community Model', 'Rental community designed, built and operated by the developer with a resident services package.', 'Product-Service'],
      ['Net-Zero Villa Prototype', 'Villa type with solar roof, high-performance envelope and smart metering that reaches net-zero energy.', 'Product'],
      ['Virtual Property Tour and Configurator', 'Buyers tour units in 3D and choose finishes online; choices flow to the contractor as change orders.', 'Service'],
      ['Modular Townhouse Range', 'Townhouses assembled from factory-built modules to cut construction time by 40%.', 'Product'],
      ['Community Facility Management Service', 'Service-charge funded maintenance, security and landscaping for handed-over communities.', 'Service'],
      ['Co-Living Residence Concept', 'Furnished private rooms with shared kitchens and workspaces for young professionals.', 'Product-Service'],
      ['Green Building Certification Programme', 'Design and construction process that earns a green building rating for every new tower.', 'Service'],
      ['Escrow Payment Tracking Portal', 'Portal where buyers and the regulator follow escrow balances against construction milestones.', 'Service'],
      ['Resident Mobile App and Concierge', 'Resident app for maintenance requests, visitor access, amenity booking and concierge services.', 'Service'],
      ['Mixed-Use Retail Podium Format', 'Standard retail podium with food court and clinics under residential towers.', 'Product'],
      ['Senior Living Apartment Concept', 'Accessible apartments with on-site care services and emergency call systems.', 'Product-Service'],
      ['Handover Snagging App', 'Buyers and inspectors record defects at handover with photos; the contractor receives work orders.', 'Service'],
      ['Solar Rooftop Offer for Buyers', 'Optional rooftop solar package financed with the mortgage.', 'Product-Service'],
      ['Parking Guidance System Upgrade', 'Replacement of the parking bay sensors in existing community car parks.', 'Product'],
      ['Sales Brochure and Kit Refresh', 'New brochure, floor-plan booklet and sales kit for the current launch.', 'Product'],
      ['Show Apartment Fit-Out Update', 'Updated furniture and finishes in the show apartment of the sales centre.', 'Product'],
      ['Floating Waterfront Villas Pilot', 'Pilot of floating villas moored in a marina on the Red Sea coast.', 'Product'],
      ['Digital Twin for Asset Management', 'Building digital twin used by the facility team for maintenance planning and energy use.', 'Service'],
      ['Fractional Ownership Investment Scheme', 'Investors buy shares of rental units through a regulated fund with quarterly distributions.', 'Service'],
    ],
  },
];

// Groups: organizations of a group can benchmark against each other; the others operate independently.
export const GROUPS = [
  { key: 'ATLAS', name: 'Atlas Infrastructure Holding', description: 'Real estate development, precast manufacturing and transport operations under one holding.', members: ['MFG', 'RED', 'TRN'] },
  { key: 'CRESCENT', name: 'Crescent Agro-Energy Group', description: 'Dairy cooperative and energy utility owned by the same regional investment group.', members: ['DAI', 'ENR'] },
];

// Project team (OBS) per track: node name -> [person alias or 'owner', role id, role played in the project].
export const PROJECT_TEAMS = {
  Full: [
    ['Steering committee', [['exec', 'R01', 'Executive sponsor'], ['board1', 'R02', 'Gate board member'], ['board2', 'R02', 'Gate board member']]],
    ['Project management', [['owner', 'R03', 'Project manager'], ['portfolio', 'R04', 'Portfolio manager'], ['process', 'R17', 'Track administrator'], ['data', 'R16', 'Data & AI specialist']]],
    ['Engineering & delivery', [['engineering', 'R05', 'Engineering lead'], ['operations', 'R06', 'Operations engineer'], ['procurement', 'R11', 'Procurement lead'], ['sustainability', 'R15', 'Sustainability officer']]],
    ['Quality & compliance', [['quality', 'R07', 'Quality manager'], ['compliance', 'R08', 'Compliance officer'], ['legal', 'R09', 'Legal & IP counsel']]],
    ['Commercial & finance', [['marketing', 'R12', 'Marketing lead'], ['finance', 'R10', 'Finance controller']]],
    ['Service & support', [['service', 'R13', 'Service manager'], ['training', 'R19', 'Training manager'], ['technician', 'R14', 'Field service technician']]],
  ],
  Light: [
    ['Steering committee', [['exec', 'R01', 'Executive sponsor'], ['board1', 'R02', 'Gate board member']]],
    ['Project management', [['owner', 'R03', 'Project manager'], ['portfolio', 'R04', 'Portfolio manager']]],
    ['Delivery team', [['engineering', 'R05', 'Engineering lead'], ['operations', 'R06', 'Operations engineer'], ['quality', 'R07', 'Quality manager']]],
    ['Commercial & finance', [['marketing', 'R12', 'Marketing lead'], ['finance', 'R10', 'Finance controller']]],
  ],
  Fast: [
    ['Project management', [['owner', 'R03', 'Project manager'], ['portfolio', 'R04', 'Portfolio manager']]],
    ['Delivery team', [['engineering', 'R05', 'Engineering lead'], ['quality', 'R07', 'Quality manager']]],
  ],
};

// One organization-authored (custom) AI use case per sector, next to the seeded catalog.
export const CUSTOM_AI = {
  PUB: ['Citizen feedback theme clustering', 'MP-03.2', 'Assistive', 'Low', 'Service designer confirms each theme before it enters the requirements list.'],
  MFG: ['Curing defect root-cause hints', 'MP-08.1', 'Assistive', 'Medium', 'Quality manager validates the proposed causes before a CAPA is opened.'],
  HLT: ['Regulatory change impact summary', 'MP-30.1', 'Augmented', 'High', 'Regulatory affairs officer reviews every impact statement before it is filed.'],
  DAI: ['Shelf-life claim wording check', 'MP-39.1', 'Assistive', 'Medium', 'Food safety lead approves the final label wording.'],
  TRN: ['Passenger complaint triage', 'MP-03.1', 'Assistive', 'Low', 'Customer service lead confirms the category of each complaint.'],
  ENR: ['Permit condition extraction', 'MP-30.1', 'Augmented', 'High', 'HSE manager checks every extracted condition against the permit text.'],
  RED: ['Buyer request classification', 'MP-03.1', 'Assistive', 'Low', 'Sales manager confirms the classification before a change order is raised.'],
};

// People (role alias -> title, roles) and names come from the shared organization setup.
export { PEOPLE, personName } from '../lib/orgSetup.js';
