// Each template drives one AI Use Case (metadata) plus its version-1 content
// (the labeled sections: inputs, prompt, expected output, constraints/guardrails).

export const AI_USE_CASE_TEMPLATES = {
  public_infrastructure: [
    {
      title: 'Predictive maintenance for structural sensors', business_function: 'operations', ai_technique: 'predictive_analytics', maturity_stage: 3, status: 'pilot',
      expected_impact: 'Reduce unplanned bridge/road asset downtime by anticipating sensor-detected structural anomalies.',
      inputs: 'Time-series strain/vibration/tilt sensor readings per asset; maintenance history; weather/load conditions.',
      prompt: 'Given the last 90 days of sensor readings for {asset_id}, flag any trend consistent with early-stage structural fatigue and estimate days-to-threshold.',
      expected_output: 'A ranked list of assets with an anomaly score, the deviating sensor(s), and a recommended inspection window.',
      constraints_guardrails: 'Never auto-close an inspection recommendation; a certified structural engineer must review and sign off before any maintenance action is scheduled.',
      model_technique_notes: 'Baseline: seasonal-decomposition + change-point detection on sensor time series; escalate to a gradient-boosted anomaly model once 12 months of labeled incidents are available.',
    },
    {
      title: 'Computer vision for site safety compliance (PPE detection)', business_function: 'operations', ai_technique: 'computer_vision', maturity_stage: 2, status: 'pilot',
      expected_impact: 'Automatically flag missing PPE (harnesses, helmets) from site CCTV feeds to reduce HSE incidents.',
      inputs: 'Live/recorded CCTV frames from active work zones; zone-to-required-PPE mapping.',
      prompt: 'Detect all persons in frame, classify visible PPE (helmet, harness, hi-vis vest) against the zone requirement, and output any non-compliant detections with a timestamp and camera ID.',
      expected_output: 'A list of non-compliance events (camera, timestamp, missing PPE type, confidence) routed to the HSE dashboard/Alert Engine.',
      constraints_guardrails: 'No facial recognition or worker identification; detections are anonymized to PPE-compliance status only, per privacy policy.',
      model_technique_notes: 'Off-the-shelf object detector (e.g. YOLO-class) fine-tuned on site-specific PPE classes; runs at the edge to avoid streaming raw video off-site.',
    },
    {
      title: 'RAG-based standards and permits assistant', business_function: 'quality', ai_technique: 'rag', maturity_stage: 4, status: 'production',
      expected_impact: 'Give engineers instant, cited answers from thousands of pages of codes, permits and past NCP resolutions.',
      inputs: 'Standards Knowledge Base documents, permit records, and the Capitalization Library of closed NCP sheets for this tenant.',
      prompt: 'Answer the engineer\'s question using only the retrieved passages; always cite the source document/section and, where relevant, the past NCP sheet number.',
      expected_output: 'A grounded answer with inline citations and a "sources" list; if no passage supports an answer, respond that no source was found rather than guessing.',
      constraints_guardrails: 'RBAC-aware retrieval — never surfaces another tenant\'s data; answers are advisory only and do not substitute for a compliance sign-off.',
      model_technique_notes: 'TF-IDF/cosine retrieval over tenant-scoped Standards + Capitalization Library indices (see server/src/services/rag.js); swappable for a vector-DB + embedding model in production.',
    },
    {
      title: 'Traffic management plan anomaly detection', business_function: 'operations', ai_technique: 'anomaly_detection', maturity_stage: 1, status: 'idea',
      expected_impact: 'Detect when on-site signage photos do not match the currently approved traffic management plan.',
      inputs: 'Daily site-supervisor signage photos; the current approved Traffic Management Plan (layout + revision number).',
      prompt: 'Compare the submitted signage photo set against the approved plan\'s expected sign layout for this section and list any mismatches or missing signs.',
      expected_output: 'A mismatch report (missing sign, wrong sign, wrong location) with confidence, or a pass confirmation.',
      constraints_guardrails: 'A mismatch never auto-triggers road closure changes; it only raises an alert for human verification within 4 hours.',
      model_technique_notes: 'Planned: vision-based sign detection/classification compared against a structured plan layout; not yet implemented (status: idea).',
    },
  ],
  manufacturing: [
    {
      title: 'Vision-based casting porosity inspection', business_function: 'quality', ai_technique: 'computer_vision', maturity_stage: 4, status: 'production',
      expected_impact: 'Automate X-ray defect detection to catch porosity issues earlier than manual sampling.',
      inputs: 'X-ray images per casting unit; ISO 5817 acceptance criteria by level; batch/lot metadata.',
      prompt: 'Classify each X-ray image region for porosity defects and score severity against the configured ISO 5817 acceptance level for this part number.',
      expected_output: 'Per-unit pass/fail with defect heatmap and severity score; batch-level defect rate summary for QA sign-off.',
      constraints_guardrails: 'Borderline scores (within 5% of the acceptance threshold) are always routed to a human inspector — never auto-passed.',
      model_technique_notes: 'CNN-based defect segmentation, retrained quarterly on newly confirmed defect/non-defect labels from closed NCP sheets.',
    },
    {
      title: 'Predictive maintenance for CNC tool wear', business_function: 'maintenance', ai_technique: 'predictive_analytics', maturity_stage: 3, status: 'pilot',
      expected_impact: 'Predict tool wear drift to trigger recalibration before dimensional non-conformities occur.',
      inputs: 'Spindle load, vibration, and cycle-count telemetry per tool; tool material/supplier metadata; last calibration date.',
      prompt: 'Given the current telemetry trend for {tool_id}, estimate remaining useful life and flag if projected wear will breach the dimensional tolerance before the next scheduled calibration.',
      expected_output: 'A remaining-useful-life estimate (cycles/days) and a recalibrate-now / recalibrate-by-date recommendation.',
      constraints_guardrails: 'Recommendation only — the maintenance supervisor confirms and schedules the actual recalibration; no automatic machine stoppage.',
      model_technique_notes: 'Regression on wear-compensation drift curves, re-fit whenever a tool insert supplier change is logged (see NC-2026 shaft tolerance case).',
    },
    {
      title: 'NCP root-cause recommendation assistant', business_function: 'quality', ai_technique: 'rag', maturity_stage: 4, status: 'production',
      expected_impact: 'Surface similar historical non-conformities and proven corrective actions during root cause analysis.',
      inputs: 'The active NCP sheet\'s title/description; the tenant\'s closed-sheet Capitalization Library (root causes, corrective actions, REX).',
      prompt: 'Retrieve the most semantically similar closed NCP sheets for this problem description and summarize their root causes and effective corrective actions.',
      expected_output: 'A ranked list of similar sheets with root cause excerpts and corrective actions, each with a similarity score.',
      constraints_guardrails: 'Always attributes suggestions to their source sheet number; the NCP team must still validate applicability before adopting a suggested action.',
      model_technique_notes: 'Same RAG engine as the Root Cause Mining / Action Recommendation agents (server/src/services/aiAgents.js), TF-IDF over the Capitalization Library.',
    },
    {
      title: 'Supply chain anomaly detection for calibration compliance', business_function: 'supply_chain', ai_technique: 'anomaly_detection', maturity_stage: 2, status: 'pilot',
      expected_impact: 'Flag tooling and instruments approaching calibration expiry before they cause non-conformities.',
      inputs: 'Tooling/instrument register with calibration due-dates; usage logs; historical NCP sheets caused by expired calibration.',
      prompt: 'List all tools/instruments whose calibration will expire within 14 days, ranked by how frequently that tool type has been linked to a past non-conformity.',
      expected_output: 'A prioritized expiry watch-list with days-remaining and a link to any related historical NCP sheets.',
      constraints_guardrails: 'Read-only advisory list; does not remove tools from service automatically.',
      model_technique_notes: 'Simple rule-based ranking today (days-to-expiry × historical incident weight); candidate for a learned risk-scoring model once more incident data accumulates.',
    },
  ],
  agro_business: [
    {
      title: 'Cold-chain temperature anomaly detection', business_function: 'supply_chain', ai_technique: 'anomaly_detection', maturity_stage: 3, status: 'pilot',
      expected_impact: 'Real-time alerts on temperature excursions during transport to prevent spoilage and food-safety incidents.',
      inputs: 'Reefer trailer temperature/humidity logger stream; trip route and product cold-chain requirement (e.g. 4°C max).',
      prompt: 'Monitor the live temperature stream for {trip_id} and flag any reading (or missing-data gap) that breaches the product\'s cold-chain requirement.',
      expected_output: 'A real-time excursion alert (start time, duration, peak deviation) pushed to the Alert Engine; end-of-trip compliance summary.',
      constraints_guardrails: 'A logger data gap is treated as a potential excursion (fail-safe), never silently ignored.',
      model_technique_notes: 'Threshold + gap-detection rule engine on the telemetry stream; no ML model required at this maturity stage.',
    },
    {
      title: 'Pesticide application & MRL compliance optimizer', business_function: 'operations', ai_technique: 'optimization', maturity_stage: 2, status: 'idea',
      expected_impact: 'Recommend safe application windows respecting pre-harvest intervals to avoid MRL breaches.',
      inputs: 'Planned harvest date; candidate pesticide product and its regulatory pre-harvest interval; field/crop calendar.',
      prompt: 'Given the target harvest date and the pre-harvest interval for the requested product, compute the latest safe application date and flag any request that violates it.',
      expected_output: 'A recommended application date range, or a hard rejection with the regulatory reason if no safe window remains before harvest.',
      constraints_guardrails: 'Any override of a rejected application date requires QA sign-off and is logged to the audit trail.',
      model_technique_notes: 'Deterministic constraint calculation from the regulatory pre-harvest-interval table; not a learned model.',
    },
    {
      title: 'Yield & spoilage prediction from IoT silo sensors', business_function: 'operations', ai_technique: 'predictive_analytics', maturity_stage: 3, status: 'pilot',
      expected_impact: 'Predict spoilage risk from humidity/temperature trends to trigger proactive aeration.',
      inputs: 'Per-silo humidity/temperature sensor time series; grain type and moisture-at-intake; historical spoilage incidents.',
      prompt: 'Given the last 14 days of sensor readings for {silo_id}, estimate spoilage risk over the next 72 hours and recommend an aeration action if risk exceeds threshold.',
      expected_output: 'A spoilage risk score (0-100) per silo and a recommended action (none / aerate / inspect).',
      constraints_guardrails: 'Silos without full sensor coverage are flagged as "unmonitored" rather than assigned a false low-risk score.',
      model_technique_notes: 'Trend + threshold model today; roadmap to a learned time-series model once the IoT rollout covers all silos (see Silo 3 coverage-gap NCP case).',
    },
    {
      title: 'Food-safety knowledge base assistant (HACCP/RAG)', business_function: 'quality', ai_technique: 'rag', maturity_stage: 4, status: 'production',
      expected_impact: 'Instant, source-cited HACCP and allergen-control guidance for QA staff during changeovers.',
      inputs: 'HACCP plan documents, allergen-control SOPs, and the tenant\'s Standards Knowledge Base and Capitalization Library.',
      prompt: 'Answer the QA question using only retrieved HACCP/standards passages and similar past NCP sheets; cite every source used.',
      expected_output: 'A grounded, cited answer; explicitly states "no source found" rather than fabricating guidance when retrieval is empty.',
      constraints_guardrails: 'Advisory only — does not replace a validated changeover sign-off or allergen swab test result.',
      model_technique_notes: 'Tenant-scoped TF-IDF retrieval (server/src/services/rag.js) over Standards + Capitalization Library; RBAC-filtered at query time.',
    },
  ],
  real_estate: [
    {
      title: 'Snag-list defect classification from inspection photos', business_function: 'quality', ai_technique: 'computer_vision', maturity_stage: 2, status: 'pilot',
      expected_impact: 'Auto-classify and prioritize handover snag-list defects from mobile inspection photos.',
      inputs: 'Mobile inspection photos tagged by unit/room; defect taxonomy (finishing, MEP, structural, cosmetic).',
      prompt: 'Classify the defect shown in the photo against the taxonomy and assign a severity (cosmetic / functional / safety) for triage.',
      expected_output: 'A defect record (category, severity, suggested trade) attached to the unit\'s snag list.',
      constraints_guardrails: 'Safety-severity classifications are always reviewed by the site QA lead before a unit is cleared for handover.',
      model_technique_notes: 'Image classification fine-tuned on a labeled defect-photo set collected from prior handover inspections.',
    },
    {
      title: 'Schedule-risk prediction for long-lead procurement', business_function: 'operations', ai_technique: 'predictive_analytics', maturity_stage: 2, status: 'idea',
      expected_impact: 'Flag long-lead items (elevators, façade) at risk of delay whenever the master schedule shifts.',
      inputs: 'Master project schedule (current + revision history); long-lead item order dates and supplier lead times.',
      prompt: 'Whenever the master schedule is revised, recompute whether each open long-lead order still fits before its required-on-site date and flag any that no longer do.',
      expected_output: 'A list of at-risk long-lead items with the shortfall in days and the schedule revision that caused it.',
      constraints_guardrails: 'Flags for review only; does not auto-expedite or re-order with suppliers.',
      model_technique_notes: 'Deterministic date-math against the schedule revision log today; not yet a learned model (status: idea).',
    },
    {
      title: 'As-built vs. sales-material consistency checker', business_function: 'quality', ai_technique: 'anomaly_detection', maturity_stage: 1, status: 'idea',
      expected_impact: 'Detect discrepancies between published sales materials and the latest as-built drawings.',
      inputs: 'Published sales brochure unit area/spec tables; latest approved as-built drawing set (with revision date).',
      prompt: 'Compare each published unit\'s stated area/spec against the latest as-built figure and flag any discrepancy beyond the configured tolerance.',
      expected_output: 'A discrepancy report (unit, published value, as-built value, delta) for marketing/design sign-off before any customer notification.',
      constraints_guardrails: 'Never sends customer-facing corrections automatically; routes to Marketing + Design for a joint sign-off first.',
      model_technique_notes: 'Planned structured-data comparison (brochure table vs. drawing metadata); not yet implemented.',
    },
    {
      title: 'Compliance & fire-code RAG assistant', business_function: 'quality', ai_technique: 'rag', maturity_stage: 4, status: 'production',
      expected_impact: 'Give compliance officers instant answers on fire codes and building regulations with citations.',
      inputs: 'Fire code/building regulation documents in the Standards Knowledge Base; past NCP sheets tagged compliance/fire-safety.',
      prompt: 'Answer the compliance question using only retrieved code passages and similar past NCP sheets; always cite the code section and, where relevant, the past sheet number.',
      expected_output: 'A grounded, cited answer, or an explicit "no source found" rather than an unsupported guess.',
      constraints_guardrails: 'Advisory only — final fire-code compliance sign-off remains with the licensed compliance officer.',
      model_technique_notes: 'Tenant-scoped TF-IDF retrieval over Standards + Capitalization Library (server/src/services/rag.js).',
    },
  ],
};
