// Generic AI Use Case catalog: the governed inventory of every AI capability
// in NCP Solver, one entry per capability, seeded identically for every
// Organization regardless of sector. Every entry sits in one of two tiers -
// Assistive (observes/suggests; a human performs the task and decision) or
// Augmented (drafts a substantial part of the task; a human must review,
// edit, and approve before it is finalized) - deliberately excluding
// Autonomous AI, which is out of scope for this release.
//
// The first 7 (module_key fiche_s1..fiche_s7) document the AI Agents wired
// into the S1-S7 process (server/src/services/aiAgents.js) and are the only
// ones with an optional real-LLM-augmented path (see aiGeneration.js) behind
// the browser-local Real LLM Provider Connection - every one of them also
// falls back to its deterministic generator automatically if no connection is
// configured or the call fails. The remaining 7 document AI capabilities
// elsewhere in the platform; module_key ties each entry to the module whose
// screens it appears on and to the activation check performed there.

export const AI_USE_CASE_TEMPLATES = [
  {
    title: 'NCP Classification & Similar-Case Assistant', module_key: 'fiche_s1', tier: 'assistive',
    business_function: 'quality', ai_technique: 'nlp', maturity_stage: 5, status: 'production',
    description: 'At S1 — Detection & Alert, suggests an initial criticality, priority, and a shortlist of similar past NCP Sheets the moment a new problem is registered, so triage starts from context instead of a blank slate.',
    trigger_desc: 'A new NCP Sheet is registered (S1 — Detection & Alert).',
    output_desc: 'A suggested criticality/priority pair and a ranked shortlist of similar past Sheets with a confidence score.',
    human_checkpoint: 'The Reporter or CI Pilot confirms or overrides the suggested criticality/priority before the Sheet is saved; nothing is set automatically.',
    expected_impact: 'Faster, more consistent initial triage and fewer missed "this happened before" signals right from the point of detection.',
    inputs: 'The new Sheet\'s title and description; the tenant\'s own closed-Sheet history.',
    prompt: 'Given this Sheet\'s title and description, suggest a criticality and priority, and surface the most similar past Sheets in this organization with a confidence score.',
    expected_output: 'A suggested criticality/priority pair plus a ranked shortlist of similar past Sheets; never applied automatically — the Reporter or CI Pilot accepts, adjusts, or ignores it.',
    constraints_guardrails: 'Never auto-sets criticality/priority on the Sheet; scoped strictly to the requesting organization\'s own data; every invocation is logged to the AI Agent Log with a confidence score.',
    model_technique_notes: 'Rule-based severity heuristics plus TF-IDF similarity search over the tenant\'s closed-Sheet corpus (runClassificationAgent); optionally augmented with a real LLM narrative, grounded in the organization\'s own Standards, if a Real LLM Provider Connection is configured — always falls back to the deterministic result on any failure.',
  },
  {
    title: '5W2H Problem-Structuring Assistant', module_key: 'fiche_s2', tier: 'augmented',
    business_function: 'quality', ai_technique: 'nlp', maturity_stage: 5, status: 'production',
    description: 'At S2 — Problem Understanding, drafts a starting-point 5W2H (What/Where/When/Who/Why/How/How-Much) breakdown from a Sheet\'s title and description, so the team edits a scaffold instead of writing one from scratch.',
    trigger_desc: 'User opens the S2 — Problem Understanding tab on a Sheet with no 5W2H record yet.',
    output_desc: 'A draft 5W2H record; any dimension it cannot confidently infer is left blank rather than guessed.',
    human_checkpoint: 'The NCP Team Member reviews and edits every field, then explicitly saves — the draft is never persisted until a human submits it.',
    expected_impact: 'Faster, more complete problem framing before any corrective work begins, especially valuable when a case is filed under time pressure.',
    inputs: 'The Sheet\'s title, description, and detection context.',
    prompt: 'Draft a candidate 5W2H breakdown from this Sheet\'s title and description, flagging any dimension it cannot confidently infer.',
    expected_output: 'A draft 5W2H record the NCP Team Member reviews and edits before saving; unresolved dimensions are left blank rather than guessed.',
    constraints_guardrails: 'Draft only — never saved until a human reviews and submits it; no dimension is fabricated when the source text doesn\'t support it.',
    model_technique_notes: 'Rule-based template extraction from the Sheet\'s free text (runProblemStructuringAgent); optional real-LLM narrative augmentation, same fallback contract as the S1 agent.',
  },
  {
    title: 'Immediate Containment Action Advisor', module_key: 'fiche_s3', tier: 'assistive',
    business_function: 'operations', ai_technique: 'rag', maturity_stage: 5, status: 'production',
    description: 'At S3 — Immediate/Containment Actions, retrieves containment actions that worked on similar past problems in this organization, so the team isn\'t starting its short-term response from zero.',
    trigger_desc: 'User requests suggestions while defining an Immediate Action (S3).',
    output_desc: 'A ranked list of containment actions recorded effective on similar past Sheets, with source Sheet numbers.',
    human_checkpoint: 'The Action Owner (AR) adapts the suggestion to the real situation and executes it; the Evaluator (AE) still confirms whether it was effective.',
    expected_impact: 'Faster, more effective containment, reducing exposure time between detection and a validated fix.',
    inputs: 'The current Sheet\'s description and the tenant\'s closed-Sheet Capitalization Library.',
    prompt: 'Given this Sheet\'s description, retrieve the most similar closed Sheets and summarize the immediate/containment actions that were recorded as effective.',
    expected_output: 'A ranked list of suggested containment actions with their source Sheet number, for the Action Owner (AR) to adapt to the current situation.',
    constraints_guardrails: 'Every suggestion is attributed to its source Sheet; the Action Owner (AR) must still define and execute the actual action — nothing is auto-applied.',
    model_technique_notes: 'TF-IDF/cosine retrieval (RagIndex) over the tenant\'s own closed-Sheet corpus (runContainmentAdvisor); tenant-isolated, optional real-LLM augmentation with the same fallback contract.',
  },
  {
    title: 'Root Cause Mining Assistant', module_key: 'fiche_s4', tier: 'assistive',
    business_function: 'quality', ai_technique: 'rag', maturity_stage: 5, status: 'production',
    description: 'At S4 — Root Cause Analysis, mines the organization\'s own history of closed Sheets for candidate root causes and 6M categories similar to the current problem.',
    trigger_desc: 'User requests suggestions while recording a Root Cause (S4).',
    output_desc: 'A ranked list of candidate root causes and 6M categories drawn from similar closed Sheets.',
    human_checkpoint: 'The NCP Team validates the true root cause via 5-Why or Ishikawa before recording it — a suggestion is never recorded as-is.',
    expected_impact: 'Deeper, faster root cause analysis grounded in what has actually caused similar problems before, rather than starting the investigation cold.',
    inputs: 'The current Sheet\'s description and root causes recorded on similar closed Sheets.',
    prompt: 'Given this Sheet\'s description, retrieve similar closed Sheets and summarize their recorded root causes and 6M categories as candidates for this investigation.',
    expected_output: 'A ranked list of candidate root causes with 6M category and source Sheet number, for the NCP Team to validate or discard.',
    constraints_guardrails: 'Candidates only — the team must still validate the true root cause via 5-Why or Ishikawa; nothing is written to the Sheet automatically.',
    model_technique_notes: 'Same RagIndex TF-IDF engine as the Capitalization Library search (runRootCauseMining), tenant-scoped, optional real-LLM augmentation with the same fallback contract.',
  },
  {
    title: 'Corrective Action Recommendation Engine', module_key: 'fiche_s5', tier: 'assistive',
    business_function: 'quality', ai_technique: 'rag', maturity_stage: 5, status: 'production',
    description: 'At S5 — Corrective Action Plan, recommends proven corrective actions for a given root cause, drawn from this organization\'s own Capitalization Library of resolved problems.',
    trigger_desc: 'User requests suggestions while defining a Corrective Action (S5).',
    output_desc: 'A ranked list of corrective actions recorded effective for a similar root cause, with source Sheet numbers.',
    human_checkpoint: 'The CI Pilot and Action Owner (AR) define the actual corrective action plan; a suggestion is a starting point, never a decision.',
    expected_impact: 'Higher first-time effectiveness rate on corrective actions by starting from what has already been proven to work.',
    inputs: 'The validated root cause(s) for this Sheet and the tenant\'s closed-Sheet Capitalization Library.',
    prompt: 'Given this root cause, retrieve closed Sheets with a similar root cause and summarize the corrective actions that were recorded as effective.',
    expected_output: 'A ranked list of candidate corrective actions with source Sheet number and, where available, their recorded effectiveness.',
    constraints_guardrails: 'Recommendation only; the Action Owner (AR) and CI Pilot decide the actual corrective action plan for this Sheet.',
    model_technique_notes: 'TF-IDF retrieval over the Capitalization Library (runActionRecommendation); optional real-LLM augmentation with the same fallback contract.',
  },
  {
    title: 'Corrective Action Effectiveness Evaluation Assistant', module_key: 'fiche_s6', tier: 'assistive',
    business_function: 'quality', ai_technique: 'predictive_analytics', maturity_stage: 5, status: 'production',
    description: 'At S6 — Execution & Evaluation, surfaces the specific root cause an Evaluator needs to re-verify for each pending corrective action, plus this organization\'s historical corrective-action effectiveness rate, as context for the effectiveness verdict.',
    trigger_desc: 'User opens the S6 — Execution & Evaluation tab with a pending effectiveness verdict.',
    output_desc: 'The specific root cause to re-verify per action, plus the organization\'s historical corrective-action effectiveness rate.',
    human_checkpoint: 'The Evaluator (AE), who must differ from the Action Owner (AR), always makes and records the actual effectiveness verdict.',
    expected_impact: 'More consistent, evidence-informed effectiveness verdicts, judged against a visible organizational baseline rather than gut feel.',
    inputs: 'The Sheet\'s root causes and corrective actions, and the organization\'s historical corrective-action evaluation outcomes.',
    prompt: 'For each pending corrective action on this Sheet, state the specific root cause to re-verify and this organization\'s historical corrective-action effectiveness rate.',
    expected_output: 'Per-action evaluation context (root cause to re-check, historical effectiveness %) shown to the Evaluator (AE) before they record Effective / Not Effective.',
    constraints_guardrails: 'Context only — the Evaluator (AE), who must differ from the Action Owner (AR), always makes and records the actual verdict.',
    model_technique_notes: 'Aggregates the tenant\'s own historical action-evaluation outcomes (runEvaluationAssistant); optional real-LLM augmentation with the same fallback contract.',
  },
  {
    title: 'REX (Lessons-Learned) Drafting Assistant', module_key: 'fiche_s7', tier: 'augmented',
    business_function: 'quality', ai_technique: 'nlp', maturity_stage: 5, status: 'production',
    description: 'At S7 — Capitalization, drafts the REX narrative — lessons learned and standardization/generalization recommendations — from the Sheet\'s full S1-S6 content, for the team to review and finalize.',
    trigger_desc: 'All corrective actions on a Sheet are marked Effective and S7 — Capitalization is opened.',
    output_desc: 'A draft REX: Lessons Learned narrative, root cause summary, solution summary, and a standardization/generalization recommendation.',
    human_checkpoint: 'The CI Pilot or Quality Manager reviews, edits, and finalizes the REX; a human always approves it before the Sheet can close.',
    expected_impact: 'Faster, more consistent capitalization, so fewer resolved problems go un-documented for lack of time to write up the REX.',
    inputs: 'The Sheet\'s full S1-S6 content: problem understanding, root causes, immediate and corrective actions, and their evaluation outcomes.',
    prompt: 'Draft a Lessons Learned narrative and a standardization/generalization recommendation from this Sheet\'s full S1-S6 content.',
    expected_output: 'A draft REX (Lessons Learned, Root Cause Summary, Solution Summary, Standardization/Generalization recommendation) for the CI Pilot or Quality Manager to review, edit, and finalize before closing the Sheet.',
    constraints_guardrails: 'Draft only — a human always reviews and finalizes the REX before the Sheet can close; nothing is published to the Capitalization Library un-reviewed.',
    model_technique_notes: 'Rule-based template synthesis from the Sheet\'s structured S1-S6 fields (runRexGenerationAgent); optional real-LLM augmentation with the same fallback contract.',
  },
  {
    title: 'Data Query Assistant', module_key: 'assistant_data', tier: 'assistive',
    business_function: 'operations', ai_technique: 'nlp', maturity_stage: 5, status: 'production',
    description: 'Answers plain-language questions about the organization\'s own data, strictly limited to what the asking user\'s role can see, from the AI Assistant\'s "Query My Data" mode.',
    trigger_desc: 'User asks a question in the AI Assistant\'s Query My Data mode.',
    output_desc: 'A direct answer computed live from the organization\'s own data, or a transparent named-permission refusal.',
    human_checkpoint: 'The user reads the answer and independently verifies it before relying on it for a decision — the answer is a computed fact, not a recommendation to act on unreviewed.',
    expected_impact: 'Faster self-service access to organizational data without waiting on a report or a colleague, with RBAC enforced identically to every other screen.',
    inputs: 'The question, matched to one of a fixed set of data-query intents, each tied to the RBAC permission required to answer it.',
    prompt: 'Match the question to a known data-query intent and, only if the requesting role holds the required permission, compute and return the answer from the organization\'s own data.',
    expected_output: 'A short, direct textual answer, or a refusal naming the missing permission.',
    constraints_guardrails: 'The permission check happens after intent-matching but strictly before running any query; a denied request never partially leaks data.',
    model_technique_notes: 'Deterministic keyword-scored intent matching over parameterized queries (runDataQueryAgent); no real-LLM path — a live model would risk asserting numbers not actually present in the data, which this use case must never do.',
  },
  {
    title: 'Application Help Assistant', module_key: 'assistant_app', tier: 'assistive',
    business_function: 'operations', ai_technique: 'rag', maturity_stage: 5, status: 'production',
    description: 'Answers "Can it...?" / "How do I...?" questions about NCP Solver itself, from the AI Assistant\'s "Ask About the Application" mode, grounded in a built-in FAQ knowledge base.',
    trigger_desc: 'User asks a question in the AI Assistant\'s Ask About the Application mode.',
    output_desc: 'The best-matching answer(s) from the built-in application FAQ knowledge base, ranked by relevance.',
    human_checkpoint: 'The user reads the returned answer(s) and judges whether it addressed their question; if not, they rephrase or check Help directly.',
    expected_impact: 'Faster answers to "how do I..." questions without leaving the screen the user is already on.',
    inputs: 'The question, matched against a curated FAQ corpus covering every module.',
    prompt: 'Rank the FAQ corpus by relevance to the question and return the top matches with their similarity score.',
    expected_output: 'One or more question/answer pairs with a similarity score; an honest "no match found" when nothing scores above threshold.',
    constraints_guardrails: 'Answers only from the curated FAQ corpus — never invents application behavior that isn\'t documented there.',
    model_technique_notes: 'Same TF-IDF RagIndex engine as the Capitalization Library search (runAppFeatureQueryAgent); no real-LLM path, by the same reasoning as the Data Query Assistant.',
  },
  {
    title: 'BPMN Diagram Documentation Assistant', module_key: 'bpmn', tier: 'assistive',
    business_function: 'operations', ai_technique: 'nlp', maturity_stage: 2, status: 'idea',
    description: 'Would generate a plain-language, step-by-step walkthrough of an open BPMN diagram\'s flow, gateways, and loops, for training and onboarding material.',
    trigger_desc: 'User requests a walkthrough of an open BPMN diagram.',
    output_desc: 'A plain-language, step-by-step narrative of the diagram\'s flow, gateways, and loops.',
    human_checkpoint: 'The diagram owner reviews the narrative for accuracy before including it in training or onboarding material.',
    expected_impact: 'Faster onboarding material for a process diagram without a manual write-up.',
    inputs: 'The BPMN 2.0 XML of the open diagram.',
    prompt: 'Describe this BPMN diagram\'s flow in plain language, calling out every gateway condition and loop explicitly.',
    expected_output: 'A short narrative paragraph a new team member could read instead of parsing the diagram cold.',
    constraints_guardrails: 'Describes only what is structurally present in the diagram XML; never infers a business rule the diagram itself doesn\'t encode.',
    model_technique_notes: 'Not yet implemented (status: idea) — would parse the BPMN XML\'s task/gateway/flow structure directly; a natural candidate for real-LLM narration once prioritized.',
  },
  {
    title: 'Risk Narrative & Mitigation Drafting Assistant', module_key: 'riskOpportunity', tier: 'augmented',
    business_function: 'quality', ai_technique: 'rag', maturity_stage: 2, status: 'idea',
    description: 'Would draft a description, likely causes, and a candidate mitigation/action plan for a new or updated Risk/Opportunity item, grounded in similar past risks and root causes from closed NCP Sheets.',
    trigger_desc: 'User starts a new Risk/Opportunity record, or requests a refresh on an existing one.',
    output_desc: 'A draft description, likely causes, and a candidate mitigation/action plan.',
    human_checkpoint: 'The risk owner reviews, edits, and approves the draft before the record is saved as active.',
    expected_impact: 'Faster, more complete risk register entries grounded in the organization\'s own incident history rather than a blank form.',
    inputs: 'The risk category/title and the tenant\'s closed-Sheet Capitalization Library.',
    prompt: 'Draft a risk description, likely causes, and a mitigation plan for this risk category, citing similar past Sheets where relevant.',
    expected_output: 'A draft description/causes/mitigation-plan triple, each claim traceable to a source Sheet where one was used.',
    constraints_guardrails: 'Draft only; the risk owner must review and approve before the record is saved as active — never auto-published.',
    model_technique_notes: 'Not yet implemented (status: idea) — would reuse the same RagIndex over the Capitalization Library as the S3-S5 agents.',
  },
  {
    title: 'Control Test Summary Assistant', module_key: 'control', tier: 'assistive',
    business_function: 'quality', ai_technique: 'predictive_analytics', maturity_stage: 1, status: 'idea',
    description: 'Would summarize a Control\'s test history and effectiveness trend in one plain-language paragraph whenever a periodic test is recorded or comes due.',
    trigger_desc: 'A Control\'s periodic test is recorded or comes due.',
    output_desc: 'A one-paragraph plain-language summary of the control\'s test history and effectiveness trend.',
    human_checkpoint: 'The control owner confirms the summary is accurate before it is attached to the control record.',
    expected_impact: 'Faster COSO compliance reporting without manually re-reading every past test result.',
    inputs: 'The control\'s test history (dates, results, effectiveness ratings).',
    prompt: 'Summarize this control\'s test history and effectiveness trend in one paragraph, citing only dates and ratings present in the record.',
    expected_output: 'A short trend summary attachable to the control record.',
    constraints_guardrails: 'States only dates/ratings present in the control\'s own test history; never estimates a rating that wasn\'t recorded.',
    model_technique_notes: 'Not yet implemented (status: idea) — deterministic trend description over the control\'s own test_history rows.',
  },
  {
    title: 'Business Rule Drafting Assistant', module_key: 'businessRule', tier: 'augmented',
    business_function: 'quality', ai_technique: 'rag', maturity_stage: 1, status: 'idea',
    description: 'Would draft a Condition (IF) / Action (THEN) statement pair and a suggested severity for a new Business Rule, grounded in a recurring pattern noticed across closed Sheets.',
    trigger_desc: 'User starts drafting a new Business Rule.',
    output_desc: 'A draft Condition (IF) / Action (THEN) pair and a suggested severity.',
    human_checkpoint: 'The CI Pilot or Quality Manager reviews and edits the rule before activating it.',
    expected_impact: 'Faster rule authoring directly from an observed recurring pattern, rather than writing the IF/THEN logic from scratch.',
    inputs: 'The recurring pattern description and the tenant\'s closed-Sheet Capitalization Library.',
    prompt: 'Given this recurring pattern, draft a Condition (IF) / Action (THEN) rule and a suggested severity, citing the Sheets that show the pattern.',
    expected_output: 'A draft IF/THEN pair with severity and supporting Sheet citations.',
    constraints_guardrails: 'Draft only; a human always reviews and activates — a rule is never auto-enabled.',
    model_technique_notes: 'Not yet implemented (status: idea) — would reuse the same RagIndex over the Capitalization Library as the S3-S5 agents.',
  },
  {
    title: 'RACSI Assignment Recommendation Assistant', module_key: 'racsi', tier: 'assistive',
    business_function: 'operations', ai_technique: 'predictive_analytics', maturity_stage: 1, status: 'idea',
    description: 'Would suggest an Accountable role/person and typical Responsible/Consulted/Support/Informed assignees for a new RACSI Activity, based on similar activities elsewhere in the OBS.',
    trigger_desc: 'A new RACSI Activity is created with no assignments yet.',
    output_desc: 'Suggested Accountable / Responsible / Consulted / Support / Informed assignees, based on similar activities.',
    human_checkpoint: 'The user creating the activity confirms or changes every suggested assignment before saving — nothing is auto-assigned.',
    expected_impact: 'Faster, more consistent RACSI coverage across similar activities in different OBS units.',
    inputs: 'The activity\'s reference type and the OBS structure\'s existing RACSI assignments for similar activities.',
    prompt: 'Given this activity\'s type, suggest an Accountable and typical other assignees based on how similar activities elsewhere are staffed.',
    expected_output: 'A suggested assignment set the user accepts, edits, or discards per role.',
    constraints_guardrails: 'Suggestion only; the one-Accountable-per-activity rule is still enforced server-side regardless of what is suggested.',
    model_technique_notes: 'Not yet implemented (status: idea) — would pattern-match against existing racsi_assignments for structurally similar activities.',
  },
];
