// Simulated non-compliance / problem scenarios per sector, used to seed
// realistic demo data. Each entry drives one NCP Fiche end-to-end (S1-S7).

import { SHOWCASE_SECTOR_TEMPLATES, SHOWCASE_SECTOR_LABELS } from './sectorShowcaseTemplates.js';

export const SECTOR_TEMPLATES = {
  public_infrastructure: [
    {
      title: 'Rebar diameter non-conforming on Bridge Pylon P4',
      description: 'Site inspection found 16mm rebar installed on Pylon P4 reinforcement cage where the approved structural drawing specifies 20mm rebar, a deviation from the design load requirements.',
      department: 'Structural Engineering', criticality: 'high', priority: 1, frequency: 'first_time',
      standard: 'AASHTO LRFD Bridge Design Specifications',
      rootCause: 'An outdated rebar specification sheet was used by the procurement team; the drawing revision control register was not enforced on-site, so superseded documents remained in circulation.',
      causeCategory: 'method',
      immediateAction: 'Halt further concrete pour on Pylon P4; cordon off the work zone and issue a stop-work notice to the rebar subcontractor.',
      correctiveAction: 'Remove and replace the non-conforming rebar cage with 20mm rebar per the approved drawing; implement a QR-coded drawing register so only the latest revision is accessible on-site.',
      lessons: 'Any drawing distributed to a subcontractor must be pulled live from the master document register, never stored as a local copy, to prevent superseded revisions from being used.',
    },
    {
      title: 'Concrete compressive strength below spec on Section 12 pour',
      description: '28-day cylinder test results for Section 12 deck pour returned 28.4 MPa against a 32 MPa design requirement.',
      department: 'Quality Control', criticality: 'high', priority: 1, frequency: 'first_time',
      standard: 'ACI 318 Building Code Requirements for Structural Concrete',
      rootCause: 'Curing temperature was not monitored during an unseasonal cold spell; no automated curing-temperature alert existed for critical pours.',
      causeCategory: 'measurement',
      immediateAction: 'Quarantine Section 12 pour; commission a structural engineer core-sample assessment before any load is applied.',
      correctiveAction: 'Install automated curing-temperature sensors with SMS alerting on all critical structural pours; revise the cold-weather concreting procedure.',
      lessons: 'Curing conditions are as critical as mix design; temperature monitoring must be automated rather than relying on manual site log entries.',
    },
    {
      title: 'Missing fall-protection harnesses on elevated deck works',
      description: 'Safety audit observed two workers on the Section 9 elevated deck (12m) without fall-arrest harnesses connected to the anchor line.',
      department: 'HSE', criticality: 'high', priority: 1, frequency: 'recurring',
      standard: 'ISO 45001 Occupational Health & Safety',
      rootCause: 'PPE inventory replenishment was triggered only by employee request rather than a scheduled stock check, leading to intermittent harness shortages.',
      causeCategory: 'method',
      immediateAction: 'Stop elevated works immediately; issue harnesses from the site safety office and re-brief the crew on mandatory fall protection.',
      correctiveAction: 'Implement a weekly PPE stock-check checklist owned by the HSE supervisor with a minimum-stock trigger for harness reordering.',
      lessons: 'Safety-critical PPE availability cannot depend on reactive requests; proactive stock management prevents exposure gaps.',
    },
    {
      title: 'Traffic diversion signage inconsistent with approved traffic management plan',
      description: 'Approved Traffic Management Plan v4 was not reflected on-site; two diversion signs still showed the v3 lane configuration, creating a safety hazard for motorists.',
      department: 'Traffic Management', criticality: 'medium', priority: 2, frequency: 'first_time',
      standard: 'MUTCD Manual on Uniform Traffic Control Devices',
      rootCause: 'The site supervisor used an outdated signage plan version stored on a local device instead of the master document management system.',
      causeCategory: 'method',
      immediateAction: 'Replace outdated signage with the current v4 configuration within 4 hours; notify local traffic authority.',
      correctiveAction: 'Mandate that all traffic control layout changes are downloaded fresh from the document management system each shift, with a signed acknowledgment log.',
      lessons: 'Field teams need a single authoritative source for time-critical documents like traffic plans; local copies create drift risk.',
    },
    {
      title: 'Storm-water drainage pipe installed with incorrect gradient on Section 7',
      description: 'Post-installation survey found the 300mm storm-water pipe on Section 7 laid at a 0.3% gradient instead of the specified 0.6% minimum, risking standing water.',
      department: 'Site Execution', criticality: 'medium', priority: 2, frequency: 'first_time',
      rootCause: 'The laser level equipment used for grade-setting had not been recalibrated per its maintenance schedule, producing a systematic elevation error.',
      causeCategory: 'machine',
      immediateAction: 'Suspend further pipe-laying on Section 7 pending equipment recalibration and a re-survey of completed sections.',
      correctiveAction: 'Re-lay the affected pipe section to the correct gradient; add laser-level calibration checks to the weekly equipment maintenance schedule.',
      lessons: 'Survey equipment calibration status should be verified before each critical grading task, not only on a fixed calendar interval.',
    },
    {
      title: 'Public utility relocation delayed beyond contractual milestone',
      description: 'Relocation of an existing gas utility line under Section 5 has slipped 18 days past the milestone date, blocking downstream excavation works.',
      department: 'Project Management', criticality: 'low', priority: 3, frequency: 'recurring',
      rootCause: 'Utility company coordination meetings were tracked informally by email rather than in the master project schedule, so slippage was not visible until it caused a downstream block.',
      causeCategory: 'method',
      immediateAction: 'Escalate directly to the utility company project liaison and re-sequence downstream works around the delay where possible.',
      correctiveAction: 'Add all third-party utility milestones to the master project schedule with automated slippage alerts to the project manager.',
      lessons: 'External-party dependencies must be tracked with the same rigor as internal tasks to avoid downstream schedule surprises.',
    },
    {
      title: 'Retaining wall weep-holes blocked on Section 3 embankment',
      description: 'Post-rain inspection of the Section 3 retaining wall found 60% of drainage weep-holes blocked by fines migration, risking hydrostatic pressure buildup behind the wall.',
      department: 'Site Execution', criticality: 'medium', priority: 2, frequency: 'first_time',
      rootCause: 'The specified geotextile filter fabric behind the weep-holes was omitted during backfilling, allowing fine soil particles to migrate and clog the drainage outlets.',
      causeCategory: 'method',
      immediateAction: 'Manually clear the blocked weep-holes and install temporary surface drainage to relieve pressure.',
      correctiveAction: 'Excavate and retrofit the missing geotextile filter fabric behind affected sections; add a mandatory backfill-layer photo checklist before wall sections are closed out.',
      lessons: 'Hidden work like drainage filter fabric needs a photographic sign-off gate before it is covered, since it cannot be verified after backfilling.',
    },
    {
      title: 'Asphalt compaction density below spec on access road Km 2-3',
      description: 'Nuclear density gauge testing on the Km 2-3 access road asphalt layer returned 91% of maximum theoretical density against a 95% specification.',
      department: 'Quality Control', criticality: 'medium', priority: 2, frequency: 'recurring',
      standard: 'AASHTO LRFD Bridge Design Specifications',
      rootCause: 'Paving continued during a period of falling ambient temperature below the mix’s minimum compaction-window threshold, without a documented temperature cutoff rule for the paving crew.',
      causeCategory: 'method',
      immediateAction: 'Halt paving for the day; mark the affected stretch for core sampling and potential milling and repaving.',
      correctiveAction: 'Establish and enforce a minimum ambient/mix-temperature cutoff for paving operations, with a thermometer check logged at the start of each paving run.',
      lessons: 'Weather-sensitive process windows need a hard, documented cutoff rule the crew must check, not a judgment call under schedule pressure.',
    },
    {
      title: 'Crane lift plan not updated after ground condition change',
      description: 'A mobile crane completed a 40-tonne lift near the Section 6 excavation using a lift plan that had not been revised after the excavation depth increased by 1.5m the previous week.',
      department: 'HSE', criticality: 'high', priority: 1, frequency: 'first_time',
      standard: 'ISO 45001 Occupational Health & Safety',
      rootCause: 'There was no trigger linking excavation-scope changes to a mandatory review of nearby crane lift plans; the two work packages were coordinated by different teams.',
      causeCategory: 'method',
      immediateAction: 'Suspend all crane operations near Section 6 pending an updated ground-bearing assessment and revised lift plan.',
      correctiveAction: 'Add a cross-discipline coordination check requiring lift-plan review whenever ground conditions change within a defined radius of a planned lift.',
      lessons: 'Interdependent work packages (excavation and crane lifts) need an explicit coordination trigger, not reliance on informal awareness between teams.',
    },
  ],

  manufacturing: [
    {
      title: 'Cylinder head porosity exceeding ISO 5817 level B on casting batch 4471',
      description: 'X-ray inspection of casting batch 4471 revealed porosity defects exceeding the ISO 5817 level B acceptance criteria on 6% of parts.',
      department: 'Production', criticality: 'high', priority: 1, frequency: 'recurring',
      standard: 'ISO 5817:2023 Welding - Fusion-welded joints',
      rootCause: 'Mould preheat temperature drifted outside the tolerance band during a furnace controller fault; no automated temperature interlock existed to halt pouring outside spec.',
      causeCategory: 'machine',
      immediateAction: 'Quarantine batch 4471; 100% X-ray inspection of the batch before any release to assembly.',
      correctiveAction: 'Install an automated temperature interlock on the furnace that blocks the pour cycle when preheat is out of tolerance; recalibrate the furnace controller.',
      lessons: 'Process parameters directly tied to structural integrity (like preheat temperature) need hard interlocks, not just operator monitoring.',
    },
    {
      title: 'Torque values out of spec on chassis assembly line 2',
      description: 'In-process audit found 4 of 20 sampled chassis bolts torqued below the 85 Nm ± 5 Nm specification on assembly line 2.',
      department: 'Quality', criticality: 'medium', priority: 2, frequency: 'first_time',
      rootCause: "The line's torque wrench calibration certificate had expired 3 weeks prior; calibration due-dates were tracked on a spreadsheet, not the CMMS, so the expiry was missed.",
      causeCategory: 'measurement',
      immediateAction: 'Remove the uncalibrated torque wrench from service; re-torque all chassis assembled since the last valid calibration date.',
      correctiveAction: 'Migrate all torque tool calibration tracking into the CMMS with automated 2-week-ahead expiry alerts to the tooling supervisor.',
      lessons: 'Calibration tracking must live in a system with automated alerting, not a manually maintained spreadsheet, for safety-critical tooling.',
    },
    {
      title: 'Packaging labels missing lot traceability code',
      description: '350 units of SKU 88213 were packaged with labels missing the lot traceability barcode field, blocking recall traceability if ever required.',
      department: 'Packaging', criticality: 'medium', priority: 2, frequency: 'first_time',
      rootCause: 'A label template update for a new SKU accidentally removed the traceability barcode field; the change was not caught because the change-control review checklist did not explicitly verify barcode presence.',
      causeCategory: 'method',
      immediateAction: 'Quarantine the 350 affected units; hand-apply traceability labels before release.',
      correctiveAction: 'Add a mandatory barcode-presence check to the label change-control checklist, with a second-person verification sign-off before any label template goes live.',
      lessons: 'Any change to a controlled document (like a label template) needs an explicit checklist item for every regulatory/traceability field, not a general review.',
    },
    {
      title: 'Surface finish defect (orange peel) on painted body panels',
      description: 'Paint shop quality check identified an "orange peel" surface texture defect on 12 body panels over 3 shifts, requiring rework.',
      department: 'Paint Shop', criticality: 'low', priority: 3, frequency: 'recurring',
      rootCause: "The spray booth's humidity control unit was malfunctioning intermittently; the preventive maintenance interval was set too long for this unit's actual failure profile.",
      causeCategory: 'machine',
      immediateAction: 'Rework the 12 affected panels; switch to the backup spray booth pending repair.',
      correctiveAction: 'Repair the humidity control unit and shorten its preventive maintenance interval based on its observed failure pattern; add a humidity-log spot-check to shift start-up.',
      lessons: 'Preventive maintenance intervals should be tuned to each asset\'s actual failure history rather than a generic fleet-wide schedule.',
    },
    {
      title: 'Dimensional non-conformity on precision-machined shaft (+0.05mm over tolerance)',
      description: 'CMM inspection found shaft diameter on batch S-2290 measuring 0.05mm above the upper tolerance limit on 8% of parts.',
      department: 'CNC Machining', criticality: 'high', priority: 2, frequency: 'first_time',
      rootCause: 'Cutting tool wear compensation values were not updated after a supplier change in tool insert material, which wears at a different rate than the previous supplier\'s inserts.',
      causeCategory: 'material',
      immediateAction: 'Segregate the affected batch for 100% dimensional inspection; revert to the previous tool insert supplier for the current run.',
      correctiveAction: 'Establish a new wear-compensation curve for the new insert material and validate it via a first-article inspection before releasing future batches.',
      lessons: 'A supplier change on any consumable that affects a controlled dimension requires re-validation of the associated process parameters, not just an equivalence assumption.',
    },
    {
      title: 'Near-miss: forklift operating without daily pre-use inspection checklist',
      description: 'A forklift was found operating in the warehouse without evidence of the mandatory daily pre-use inspection checklist being completed, and was later found to have a hydraulic leak.',
      department: 'Warehouse', criticality: 'high', priority: 1, frequency: 'recurring',
      standard: 'ISO 45001 Occupational Health & Safety',
      rootCause: 'The pre-use inspection checklist was paper-based and frequently skipped during shift changeovers when time pressure was highest.',
      causeCategory: 'method',
      immediateAction: 'Remove the forklift from service for hydraulic repair; conduct a fleet-wide spot check of pre-use checklist compliance.',
      correctiveAction: 'Digitize the pre-use inspection checklist with a mandatory sign-off on a tablet before the forklift ignition can be enabled.',
      lessons: 'Safety checklists that can be silently skipped under time pressure should be enforced by a hard system control, not a paper process.',
    },
    {
      title: 'Wrong revision of work instruction posted at CNC Station 7',
      description: 'Station 7 operators were found following work instruction WI-204 Rev.C, superseded by Rev.D two weeks earlier which changed a critical feed-rate parameter.',
      department: 'CNC Machining', criticality: 'medium', priority: 2, frequency: 'first_time',
      rootCause: 'Printed work instructions posted at stations are updated manually by shift leads; the Rev.D rollout was not tracked to confirm every station’s posted copy had been swapped.',
      causeCategory: 'method',
      immediateAction: 'Replace the posted instruction with Rev.D immediately; inspect parts produced since the revision date against Rev.D parameters.',
      correctiveAction: 'Replace printed work instructions at high-change stations with a tablet display pulling live from the document system, removing the manual swap step.',
      lessons: 'Manually posted controlled documents at the point of use are a recurring drift risk; electronic, live-linked display removes the human handoff step.',
    },
    {
      title: 'Supplier certificate of analysis missing for raw material batch RM-5521',
      description: 'Raw material batch RM-5521 was released to production before its supplier certificate of analysis (CoA) had been received and reviewed by incoming quality.',
      department: 'Quality', criticality: 'medium', priority: 2, frequency: 'first_time',
      rootCause: 'The warehouse receiving process allowed a batch to be moved to available inventory once the physical goods arrived, independent of whether the CoA had been logged as received.',
      causeCategory: 'method',
      immediateAction: 'Quarantine any remaining stock from batch RM-5521 and hold any in-process product made from it pending CoA review.',
      correctiveAction: 'Change the warehouse system so a batch cannot be moved out of quarantine status until the CoA is logged as received and reviewed.',
      lessons: 'A physical receiving event and a documentation receiving event must be linked in the system, or one will eventually be allowed to bypass the other.',
    },
    {
      title: 'Ergonomic strain injury reported at manual carton-lifting station',
      description: 'A packaging operator reported lower-back strain after repetitive manual lifting of 18kg cartons at the end-of-line palletizing station, which has no mechanical lift assist.',
      department: 'Packaging', criticality: 'medium', priority: 2, frequency: 'recurring',
      standard: 'ISO 45001 Occupational Health & Safety',
      rootCause: 'The station’s ergonomic risk assessment predates a packaging format change that increased average carton weight from 12kg to 18kg, and was never re-triggered.',
      causeCategory: 'method',
      immediateAction: 'Temporarily rotate operators through the station at shorter intervals and provide back-support belts pending a permanent fix.',
      correctiveAction: 'Install a mechanical lift-assist device at the station; require an ergonomic risk re-assessment whenever a packaging format change alters manual handling weights.',
      lessons: 'A change that alters physical handling parameters (like carton weight) should automatically re-trigger the associated ergonomic risk assessment.',
    },
  ],

  agro_business: [
    {
      title: 'Pesticide residue above MRL threshold on citrus batch B-2291',
      description: 'Laboratory testing of citrus batch B-2291 detected chlorpyrifos residue at 0.09 mg/kg, above the Codex Alimentarius MRL of 0.05 mg/kg.',
      department: 'Quality Assurance', criticality: 'high', priority: 1, frequency: 'first_time',
      standard: 'Codex Alimentarius Maximum Residue Limits',
      rootCause: 'The pre-harvest interval for the applied pesticide was miscalculated after a last-minute application schedule change requested by the field team.',
      causeCategory: 'method',
      immediateAction: 'Quarantine batch B-2291; halt shipment and notify the export compliance officer.',
      correctiveAction: 'Implement a mandatory pre-harvest-interval calculator check, requiring QA sign-off before any pesticide application schedule change is approved.',
      lessons: 'Any last-minute change to a spray schedule must trigger a fresh pre-harvest-interval recalculation, not be approved on field-team judgment alone.',
    },
    {
      title: 'Cold chain temperature excursion during transport of dairy batch',
      description: 'Temperature logger data for dairy batch D-1187 showed a 6-hour excursion above 8°C during transport, exceeding the 4°C cold chain requirement.',
      department: 'Logistics', criticality: 'high', priority: 1, frequency: 'first_time',
      rootCause: "The refrigerated trailer's temperature data-logger battery had failed silently; battery-check was not part of the driver's pre-trip checklist.",
      causeCategory: 'machine',
      immediateAction: 'Reject and destroy the affected batch per food safety policy; inspect and replace all trailer logger batteries fleet-wide.',
      correctiveAction: 'Add a data-logger battery and function test to the mandatory pre-trip checklist, with driver sign-off before departure.',
      lessons: 'Cold-chain monitoring equipment is itself a critical control point and needs its own preventive-maintenance check, not just the refrigeration unit.',
    },
    {
      title: 'Allergen cross-contamination risk on shared production line',
      description: 'A changeover from a peanut-containing product to an allergen-free product on Line 3 was completed without a validated allergen swab test, creating undisclosed cross-contamination risk.',
      department: 'Food Safety', criticality: 'high', priority: 1, frequency: 'recurring',
      standard: 'HACCP - Hazard Analysis Critical Control Points',
      rootCause: 'The line changeover cleaning procedure did not include a validated allergen swab test step; visual inspection alone was relied upon.',
      causeCategory: 'method',
      immediateAction: 'Hold the affected production run; perform retroactive allergen swab testing before release decision.',
      correctiveAction: 'Add a mandatory ATP/allergen swab test with documented pass criteria to the changeover procedure before any allergen-free run can start.',
      lessons: 'Visual cleanliness is not evidence of allergen absence; changeover validation for allergens requires a quantitative test, not visual inspection.',
    },
    {
      title: 'Irrigation water microbiological test exceeded threshold',
      description: 'Quarterly irrigation water testing on Field 12 returned E. coli counts of 180 CFU/100mL, above the 126 CFU/100mL GAP threshold.',
      department: 'Agronomy', criticality: 'medium', priority: 2, frequency: 'first_time',
      rootCause: 'Well water testing frequency had been reduced from monthly to quarterly during a budget review, without a documented risk reassessment to justify the reduced frequency.',
      causeCategory: 'measurement',
      immediateAction: 'Suspend irrigation from the affected well; switch to the backup water source pending retesting and remediation.',
      correctiveAction: 'Restore monthly testing frequency for wells feeding ready-to-eat crops; require a documented risk assessment for any future testing-frequency change.',
      lessons: 'Cost-reduction decisions on food-safety monitoring frequency must go through a formal risk assessment, not a budget-driven default.',
    },
    {
      title: 'Incorrect net weight on packaged grain bags (underfilled by 3%)',
      description: 'Random weight check of 25kg grain bags found an average underfill of 3% (24.25kg actual), a consumer-protection non-conformity.',
      department: 'Packaging', criticality: 'medium', priority: 2, frequency: 'recurring',
      rootCause: 'The filling scale had drifted out of calibration between the scheduled quarterly checks; no in-process weight-check sampling existed to catch drift earlier.',
      causeCategory: 'measurement',
      immediateAction: 'Stop the filling line; recalibrate the scale and re-check all bags filled since the last valid calibration.',
      correctiveAction: 'Introduce hourly in-process weight-check sampling with a control chart, in addition to the quarterly full calibration.',
      lessons: 'Quarterly calibration alone cannot catch gradual drift; in-process sampling between calibrations closes that detection gap.',
    },
    {
      title: 'Storage silo humidity causing early grain spoilage',
      description: 'Grain sampled from Silo 3 showed early mold development, traced to elevated internal humidity not detected by the site\'s monitoring program.',
      department: 'Warehouse', criticality: 'low', priority: 3, frequency: 'first_time',
      rootCause: 'Humidity sensors had been installed on Silos 1, 2, and 4 during the IoT monitoring rollout, but Silo 3 was inadvertently omitted from the project scope.',
      causeCategory: 'machine',
      immediateAction: 'Manually aerate Silo 3 and inspect/segregate spoiled grain; deploy a temporary humidity logger.',
      correctiveAction: 'Extend the IoT humidity monitoring rollout to Silo 3 and audit the full facility asset list against the monitoring scope to close any other gaps.',
      lessons: 'Facility-wide monitoring rollouts need an asset-list reconciliation step to guarantee no unit is silently excluded from scope.',
    },
    {
      title: 'Organic certification label applied to non-certified produce batch',
      description: 'A batch of tomatoes from a transitional (not-yet-certified) plot was packed with organic certification labels intended only for fully certified fields.',
      department: 'Packaging', criticality: 'high', priority: 1, frequency: 'first_time',
      rootCause: 'The plot-to-label mapping used by the packing line was not updated after a field re-classification; packers relied on the previous season\'s plot list.',
      causeCategory: 'method',
      immediateAction: 'Halt shipment of the affected batch and relabel with correct (non-organic) labeling; notify the certification body per protocol.',
      correctiveAction: 'Link the packing line\'s label-selection system directly to the current certified-plot register so mislabeling cannot occur from an outdated list.',
      lessons: 'Certification-dependent labeling must be driven by a live, single source of truth for plot status, not a manually maintained seasonal list.',
    },
    {
      title: 'Pest infestation detected in grain storage Warehouse 2',
      description: 'Routine inspection found live weevil infestation in 3 grain storage bins in Warehouse 2, exceeding the zero-tolerance action threshold.',
      department: 'Warehouse', criticality: 'high', priority: 1, frequency: 'recurring',
      standard: 'HACCP - Hazard Analysis Critical Control Points',
      rootCause: 'The pest control contractor\'s treatment frequency had not been adjusted after the facility began storing a grain variety more susceptible to weevil infestation.',
      causeCategory: 'method',
      immediateAction: 'Isolate and fumigate the affected bins; hold all grain from those bins pending re-inspection.',
      correctiveAction: 'Increase pest control treatment frequency for bins storing the susceptible grain variety and add a variety-specific risk factor to the pest management plan.',
      lessons: 'A change in stored material type can change the risk profile a pest control program was designed around, requiring the program to be re-tuned, not left on a generic schedule.',
    },
    {
      title: 'Irrigation water extraction exceeding permitted volume for Q2',
      description: 'Water usage records show Q2 extraction from the licensed well exceeded the regulatory permit volume by 8%.',
      department: 'Agronomy', criticality: 'medium', priority: 2, frequency: 'first_time',
      rootCause: 'Field-level irrigation scheduling did not account for an unusually dry Q2, and there was no running total of extraction tracked against the permit limit during the quarter.',
      causeCategory: 'method',
      immediateAction: 'Reduce irrigation volumes for the remainder of the reporting period and notify the water authority of the exceedance per regulatory requirement.',
      correctiveAction: 'Implement a running extraction dashboard tracked weekly against the permit limit, with an alert threshold at 80% of the quarterly allowance.',
      lessons: 'Regulatory usage limits need active, running tracking against actual consumption, not a retrospective quarterly reconciliation.',
    },
  ],

  real_estate: [
    {
      title: 'Waterproofing membrane installed incorrectly on rooftop terrace, Building C',
      description: 'Post-installation inspection of Building C rooftop terrace found the waterproofing membrane overlaps installed in the wrong direction relative to water flow, risking leaks.',
      department: 'Site Supervision', criticality: 'high', priority: 1, frequency: 'first_time',
      rootCause: 'The subcontractor crew was not re-briefed on updated manufacturer installation guidelines after a mid-project product substitution to a different membrane brand.',
      causeCategory: 'method',
      immediateAction: 'Cover the affected area with temporary protection; halt further membrane installation until re-training is complete.',
      correctiveAction: 'Remove and correctly re-install the affected membrane sections; require documented toolbox-talk sign-off whenever a specified material is substituted.',
      lessons: 'Any material substitution mid-project must trigger a mandatory re-briefing of the installation crew on the new product\'s specific requirements.',
    },
    {
      title: 'Fire-rated door specification mismatch on residential Tower B',
      description: '14 fire-rated doors installed on Tower B floors 8-10 were found to carry a 30-minute fire rating where the approved fire strategy requires 60 minutes.',
      department: 'Compliance', criticality: 'high', priority: 1, frequency: 'first_time',
      standard: 'NFPA 80 Standard for Fire Doors and Other Opening Protectives',
      rootCause: "Procurement ordered doors from the previous project's approved-supplier list without re-verifying the fire-rating requirement specific to this project's fire strategy.",
      causeCategory: 'method',
      immediateAction: 'Restrict access to the affected floors; expedite replacement door order with correct 60-minute rating.',
      correctiveAction: 'Replace all 14 non-conforming doors; add a project-specific fire-strategy cross-check step to the procurement approval workflow for any fire-rated component.',
      lessons: 'Approved-supplier lists from prior projects cannot be reused for critical safety specifications without re-verifying against the current project\'s specific requirements.',
    },
    {
      title: 'Customer handover snag list exceeds acceptable defect threshold (Tower A units)',
      description: 'Pre-handover inspection of Tower A units found an average of 22 snags per unit, exceeding the 10-snag acceptable threshold, delaying handover.',
      department: 'Quality Control', criticality: 'medium', priority: 2, frequency: 'recurring',
      rootCause: 'The pre-handover inspection checklist did not include a dedicated finishing-trades sign-off stage before the unit was scheduled for final QC inspection.',
      causeCategory: 'method',
      immediateAction: 'Delay handover dates for the affected units; deploy an additional finishing crew to clear the snag list.',
      correctiveAction: 'Insert a mandatory finishing-trades self-inspection and sign-off stage before a unit becomes eligible for final QC inspection.',
      lessons: 'Quality gates work best when each trade signs off its own work before the next inspection stage, catching defects earlier and cheaper to fix.',
    },
    {
      title: 'Elevator installation delayed beyond planned milestone, Tower D',
      description: 'Elevator installation on Tower D is 6 weeks behind the planned milestone, now on the project\'s critical path.',
      department: 'Project Management', criticality: 'medium', priority: 2, frequency: 'first_time',
      rootCause: 'The long-lead elevator equipment order was placed using the original project schedule, which was never revised after an earlier 4-week structural delay.',
      causeCategory: 'method',
      immediateAction: 'Engage the elevator supplier for an expedited delivery option and re-sequence trailing finishing works where feasible.',
      correctiveAction: 'Establish a rule that all long-lead equipment orders are re-verified against the current schedule at each monthly project review, not only at initial order placement.',
      lessons: 'Long-lead procurement decisions must be revisited whenever the master schedule shifts, not treated as a one-time order-and-forget action.',
    },
    {
      title: 'Soil compaction test results below specification on Plot 14 foundation',
      description: 'Nuclear density gauge testing on Plot 14 foundation returned 88% relative compaction against a 95% specification requirement.',
      department: 'Geotechnical', criticality: 'high', priority: 1, frequency: 'first_time',
      rootCause: "Compaction testing frequency followed a generic industry standard rather than the project's specific geotechnical report, which called for tighter test spacing in this soil type.",
      causeCategory: 'method',
      immediateAction: 'Halt foundation works on Plot 14; commission additional geotechnical testing across the full footprint.',
      correctiveAction: 'Re-compact the affected areas to specification; update the site quality plan to follow the project-specific geotechnical report\'s testing frequency, not a generic default.',
      lessons: 'Generic industry testing standards are a floor, not a substitute for the project-specific geotechnical report\'s requirements.',
    },
    {
      title: 'Sales brochure area figures inconsistent with as-built drawings',
      description: 'Unit area figures published in the sales brochure for Tower E differ from the latest as-built drawings by up to 4 square meters on 6 unit types.',
      department: 'Marketing', criticality: 'low', priority: 3, frequency: 'first_time',
      rootCause: 'Marketing materials were finalized before the final design-change round was communicated by the design department, using an earlier drawing set.',
      causeCategory: 'method',
      immediateAction: 'Pull the affected brochure version from circulation; issue a corrected version and proactively notify buyers of the affected units.',
      correctiveAction: 'Require design department sign-off on final as-built area figures as a mandatory gate before any sales material can be published.',
      lessons: 'Any customer-facing material derived from design data needs a formal sign-off gate tied to the final design revision, not an earlier snapshot.',
    },
    {
      title: 'Balcony guardrail height below building code minimum, Tower F',
      description: 'Site measurement of balcony guardrails on Tower F floors 3-5 found a height of 96cm against the 107cm local building code minimum.',
      department: 'Compliance', criticality: 'high', priority: 1, frequency: 'first_time',
      standard: 'NFPA 80 Standard for Fire Doors and Other Opening Protectives',
      rootCause: 'The guardrail fabrication shop drawings referenced an older code edition; the design department\'s code-edition register had not been updated when the local authority revised the requirement.',
      causeCategory: 'method',
      immediateAction: 'Restrict balcony access on the affected floors; order corrected guardrail sections.',
      correctiveAction: 'Replace all non-conforming guardrails; add a code-edition verification step to shop drawing approval, cross-checked against the current local authority register.',
      lessons: 'Shop drawings must be checked against the currently-in-force code edition at approval time, not the edition current when the project design started.',
    },
    {
      title: 'Parking garage ventilation system failed commissioning test, Tower B',
      description: 'CO-level commissioning test of the Tower B basement parking ventilation system found air changes per hour 30% below the design requirement in Zone 2.',
      department: 'Site Supervision', criticality: 'medium', priority: 2, frequency: 'first_time',
      rootCause: 'A duct damper in Zone 2 was left in its factory-shipped closed position after installation, with no commissioning checklist item to verify damper positions before testing.',
      causeCategory: 'method',
      immediateAction: 'Correct the damper position and re-run the commissioning test for Zone 2 before occupancy sign-off.',
      correctiveAction: 'Add an explicit damper-position verification step to the mechanical commissioning checklist for every zone before airflow testing begins.',
      lessons: 'Commissioning checklists must explicitly verify component state (like damper position), not assume default/as-installed positions are correct.',
    },
    {
      title: 'Unauthorized design change implemented without approval, Tower G lobby',
      description: 'The lobby ceiling height on Tower G was altered on-site by the finishing subcontractor without a documented design change approval, affecting fire-sprinkler clearances.',
      department: 'Project Management', criticality: 'high', priority: 1, frequency: 'first_time',
      rootCause: 'The subcontractor received a verbal instruction from a site coordinator without following the mandatory written change-request process, and no one cross-checked fire-system clearance impact.',
      causeCategory: 'method',
      immediateAction: 'Halt further lobby finishing work; commission a fire-engineer clearance review of the altered ceiling height.',
      correctiveAction: 'Reinforce that only written, approved change requests may be actioned on-site, with disciplinary escalation for verbal-instruction deviations; add a fire-system clearance check to the change-approval workflow.',
      lessons: 'Verbal instructions bypassing the change-control process are a recurring root cause for safety-system impacts; the control has to be enforced, not just documented.',
    },
  ],
  // 7 additional "showcase" sectors (25+ sheets each), see sectorShowcaseTemplates.js.
  ...SHOWCASE_SECTOR_TEMPLATES,
};

// Sample Projects per sector, seeded under Hierarchy so the Project level of
// Group -> Organization -> Project is populated (previously the table existed
// but no Organization had any Project rows).
export const PROJECT_TEMPLATES = {
  public_infrastructure: [
    { name: 'Northern Ring Road Bridge Expansion', description: 'Design-build of 4 new bridge structures extending the Northern Ring Road, including approach embankments and drainage works.', status: 'active', startOffsetDays: -420, endOffsetDays: 180 },
    { name: 'Coastal Highway Resurfacing Program', description: 'Multi-phase resurfacing and drainage upgrade of 60km of the Coastal Highway.', status: 'active', startOffsetDays: -200, endOffsetDays: 90 },
    { name: 'Riverside Flood Defense Wall', description: 'Completed flood defense wall and pumping station protecting the riverside district.', status: 'closed', startOffsetDays: -900, endOffsetDays: -60 },
  ],
  manufacturing: [
    { name: 'Line 2 Automation Upgrade', description: 'Retrofit of assembly Line 2 with automated torque control and vision-inspection stations.', status: 'active', startOffsetDays: -150, endOffsetDays: 120 },
    { name: 'Paint Shop Capacity Expansion', description: 'New spray booth and curing oven installation to add a third paint shift.', status: 'active', startOffsetDays: -60, endOffsetDays: 200 },
    { name: 'Foundry Furnace Replacement Q1', description: 'Completed replacement of Furnace 3 with an automated temperature-interlocked unit.', status: 'closed', startOffsetDays: -500, endOffsetDays: -120 },
  ],
  agro_business: [
    { name: 'Cold Chain Fleet Modernization', description: 'Replacement of the refrigerated transport fleet with IoT-monitored trailers across all distribution routes.', status: 'active', startOffsetDays: -180, endOffsetDays: 150 },
    { name: 'Warehouse 2 IoT Monitoring Rollout', description: 'Extension of humidity/temperature IoT sensors to all remaining storage silos and warehouses.', status: 'active', startOffsetDays: -90, endOffsetDays: 60 },
    { name: 'Organic Certification Transition Program', description: 'Completed multi-plot transition to organic certification, including plot register digitization.', status: 'closed', startOffsetDays: -700, endOffsetDays: -30 },
  ],
  real_estate: [
    { name: 'Tower F Residential Development', description: 'Construction of Tower F, a 22-storey residential tower including basement parking and rooftop amenities.', status: 'active', startOffsetDays: -300, endOffsetDays: 240 },
    { name: 'Meridian Business District Phase 2', description: 'Mixed-use commercial and office development, second phase of the Meridian Business District master plan.', status: 'on_hold', startOffsetDays: -120, endOffsetDays: 365 },
    { name: 'Tower A Handover Completion', description: 'Completed handover of all Tower A residential units to buyers.', status: 'closed', startOffsetDays: -600, endOffsetDays: -45 },
  ],
};

export const SECTOR_LABELS = {
  public_infrastructure: { en: 'Public Sector - Infrastructure', fr: 'Secteur Public - Infrastructure', ar: 'القطاع العام - البنية التحتية' },
  manufacturing: { en: 'Manufacturing', fr: 'Industrie Manufacturière', ar: 'التصنيع' },
  agro_business: { en: 'Agro-Business', fr: 'Agro-Industrie', ar: 'الأعمال الزراعية' },
  real_estate: { en: 'Real Estate Development', fr: 'Promotion Immobilière', ar: 'التطوير العقاري' },
  ...SHOWCASE_SECTOR_LABELS,
};
