// Additional sector "showcase" organizations, seeded on top of the core demo
// data so each of 7 industries has its own organization with 25+ realistic
// NCP sheets (S1-S7 lifecycle) for demos and screenshot capture.
//
// Content is generated from a small set of hand-authored problem archetypes
// per sector, expanded across several site/line/asset locations, so every
// sector ends up with 6 archetypes x 5 locations = 30 distinct sheets.

function expandArchetypes(archetypes, locations) {
  const out = [];
  locations.forEach((loc, li) => {
    archetypes.forEach((a, ai) => {
      const idx = li * archetypes.length + ai;
      const fill = (s) => (s ? s.replace(/\{loc\}/g, loc) : s);
      out.push({
        title: fill(a.title),
        description: fill(a.description),
        department: a.department,
        criticality: a.criticality,
        priority: a.priority,
        frequency: idx % 4 === 0 ? 'recurring' : 'first_time',
        standard: a.standard,
        rootCause: fill(a.rootCause),
        causeCategory: a.causeCategory,
        immediateAction: fill(a.immediateAction),
        correctiveAction: fill(a.correctiveAction),
        lessons: a.lessons,
      });
    });
  });
  return out;
}

const SECTORS = [
  {
    key: 'public_sector',
    orgName: 'National Public Services Agency',
    orgNameFr: 'Agence Nationale des Services Publics',
    sectorType: 'public',
    domain: 'natpubsvc',
    departments: ['Citizen Services', 'Permits & Licensing', 'IT Systems', 'Records Management', 'Procurement'],
    locations: ['Central Service Counter', 'Online Citizen Portal', 'Regional Branch Office', 'Central Archive Center', 'Procurement Unit'],
    archetypes: [
      {
        title: 'Processing delay for citizen permit applications beyond SLA at {loc}',
        description: 'Backlog of permit applications at {loc} exceeded the published 10-business-day service standard, with average processing time reaching 19 days during the review period.',
        department: 'Permits & Licensing', criticality: 'medium', priority: 2,
        standard: 'ISO 9001:2015 Quality Management', causeCategory: 'method',
        rootCause: 'Manual document routing between departments at {loc} created queueing delays with no automated escalation when files stalled.',
        immediateAction: 'Deploy temporary case-review staff to clear the backlog and personally contact affected applicants with revised timelines.',
        correctiveAction: 'Introduce a digital workflow with automated stage-based routing and SLA-breach alerts to supervisors.',
        lessons: 'Manual routing of time-sensitive citizen requests should be replaced by tracked digital workflow the moment volume exceeds a threshold.',
      },
      {
        title: 'Citizen records accessible without role restriction at {loc}',
        description: 'Internal audit at {loc} found that case-worker accounts had read access to citizen records outside their assigned caseload, in breach of the data minimization principle.',
        department: 'IT Systems', criticality: 'high', priority: 1,
        standard: 'ISO/IEC 27001 Information Security Management', causeCategory: 'method',
        rootCause: 'The role-based access control matrix at {loc} was not updated after the last system migration, leaving default broad-access profiles active.',
        immediateAction: 'Restrict access immediately to case-assigned records only and force a password reset for all affected accounts.',
        correctiveAction: 'Rebuild the RBAC matrix against the current organizational chart and add a quarterly access-recertification review.',
        lessons: 'Access control configuration must be explicitly re-validated after every system migration, not assumed to carry over correctly.',
      },
      {
        title: 'Incomplete identity verification during document renewal at {loc}',
        description: 'Post-issuance audit at {loc} found 3 identity document renewals processed without the mandatory biometric cross-check step being completed and logged.',
        department: 'Citizen Services', criticality: 'high', priority: 1,
        standard: 'ISO 9001:2015 Quality Management', causeCategory: 'method',
        rootCause: 'The verification checklist step at {loc} was not enforced as a hard system gate, allowing agents to proceed without completing it under time pressure.',
        immediateAction: 'Suspend the affected documents pending re-verification and notify the security office.',
        correctiveAction: 'Convert the biometric cross-check from a checklist item into a mandatory system gate that blocks issuance until completed.',
        lessons: 'Security-critical verification steps must be enforced by the system itself, not left to procedural discipline alone.',
      },
      {
        title: 'Procurement contract awarded without complete bid documentation at {loc}',
        description: 'Compliance review of a facilities contract issued via {loc} found only two of the required three competitive bids on file, a deviation from public procurement policy.',
        department: 'Procurement', criticality: 'medium', priority: 2,
        standard: 'ISO 37301 Compliance Management Systems', causeCategory: 'method',
        rootCause: 'The procurement officer at {loc} was unaware a policy update had raised the competitive-bid threshold, since policy changes were not systematically pushed to procurement staff.',
        immediateAction: 'Place the contract on hold pending a compliance review and obtain a retroactive bid or re-tender as advised.',
        correctiveAction: 'Implement a mandatory policy-acknowledgment workflow so procurement staff must confirm they have read each policy update before processing new contracts.',
        lessons: 'Policy updates affecting compliance thresholds need active push notification and acknowledgment tracking, not passive publication.',
      },
      {
        title: 'Archive records misfiled leading to lost case file at {loc}',
        description: 'A citizen case file requested from {loc} could not be located after 3 working days; investigation found it had been misfiled under an incorrect case-reference year.',
        department: 'Records Management', criticality: 'medium', priority: 2,
        causeCategory: 'method',
        rootCause: 'The archival indexing process at {loc} relies on manual entry of reference numbers with no barcode/validation check at filing time.',
        immediateAction: 'Initiate a full-shelf search and issue the citizen a formal apology with an interim case update.',
        correctiveAction: 'Introduce barcode scanning at filing time with automated reference-number validation against the case management system.',
        lessons: 'Manual reference-number entry during high-volume filing is inherently error-prone and needs a validation control at the point of filing.',
      },
      {
        title: 'Online service downtime during peak filing period at {loc}',
        description: 'The {loc} experienced 6 hours of unplanned downtime during the tax-filing deadline week, preventing citizens from submitting required declarations on time.',
        department: 'IT Systems', criticality: 'high', priority: 1,
        standard: 'ISO/IEC 27001 Information Security Management', causeCategory: 'machine',
        rootCause: 'Server capacity for {loc} was not scaled ahead of the known seasonal peak, and the monitoring system did not alert operations until the outage had already begun.',
        immediateAction: 'Extend the filing deadline by 5 business days and publish the extension across all citizen channels.',
        correctiveAction: 'Implement auto-scaling infrastructure ahead of known seasonal peaks and add predictive load alerting.',
        lessons: 'Known seasonal demand peaks should trigger pre-emptive capacity planning, not reactive scaling after symptoms appear.',
      },
    ],
  },
  {
    key: 'construction_materials',
    orgName: 'Atlas Construction Materials Manufacturing',
    orgNameFr: 'Atlas Manufacture de Matériaux de Construction',
    sectorType: 'private',
    domain: 'atlascm',
    departments: ['Precast Production', 'Quality Control', 'Batching Plant', 'Curing Yard', 'Logistics & Dispatch'],
    locations: ['Precast Line 1', 'Batching Plant B', 'Rebar Fabrication Shop', 'Curing Yard 2', 'Dispatch Bay 2'],
    archetypes: [
      {
        title: 'Precast concrete panel dimensional tolerance exceeded at {loc}',
        description: 'Random dimensional check of precast wall panels produced at {loc} found 4 panels outside the ±3mm tolerance specified in EN 206, with the deviation concentrated on panel width.',
        department: 'Precast Production', criticality: 'high', priority: 1,
        standard: 'EN 206 Concrete Specification', causeCategory: 'machine',
        rootCause: 'The mold clamping mechanism at {loc} had worn beyond its maintenance limit, allowing slight mold flex during casting.',
        immediateAction: 'Quarantine the non-conforming panels and switch production to a backup mold pending inspection.',
        correctiveAction: 'Replace the worn clamping components and add a mold-wear measurement to the preventive maintenance schedule.',
        lessons: 'Dimensional tolerance issues on precast product often trace back to mold wear; mold condition needs its own maintenance KPI, not just general equipment upkeep.',
      },
      {
        title: 'Aggregate moisture sensor miscalibration at {loc}',
        description: 'Mix design audit at {loc} found the aggregate moisture sensor reading 1.8% lower than actual, causing water dosing to be under-corrected across an estimated 40 m³ of mix.',
        department: 'Batching Plant', criticality: 'high', priority: 1,
        standard: 'ISO 9001:2015 Quality Management', causeCategory: 'measurement',
        rootCause: 'The moisture sensor calibration interval at {loc} was set annually, longer than the manufacturer\'s recommended 6-month cycle for high-throughput plants.',
        immediateAction: 'Recall and re-test the affected mix batches; recalibrate the sensor immediately.',
        correctiveAction: 'Shorten the calibration interval to the manufacturer\'s recommended 6 months and add a daily manual-sample cross-check.',
        lessons: 'Calibration intervals must follow equipment manufacturer guidance for the actual duty cycle, not a generic annual default.',
      },
      {
        title: 'Rebar cage weld spacing non-conforming at {loc}',
        description: 'Inspection at {loc} found tack-weld spacing on 6 fabricated rebar cages exceeding the 300mm maximum specified in the fabrication drawing, reducing cage rigidity during transport.',
        department: 'Precast Production', criticality: 'medium', priority: 2,
        causeCategory: 'method',
        rootCause: 'A new welding operator at {loc} had not yet completed the spacing-specific competency sign-off before being assigned to cage fabrication.',
        immediateAction: 'Rework the affected cages to correct spacing before dispatch.',
        correctiveAction: 'Require documented spacing competency sign-off before any welder is assigned to cage fabrication without supervision.',
        lessons: 'New operators on dimension-critical tasks need a documented competency gate, not on-the-job learning under production pressure.',
      },
      {
        title: 'Curing time shortened due to yard scheduling pressure at {loc}',
        description: 'Production log review at {loc} found several panel batches released from curing 6 hours earlier than the minimum specified curing time to free up yard space for incoming pours.',
        department: 'Curing Yard', criticality: 'high', priority: 1,
        standard: 'EN 206 Concrete Specification', causeCategory: 'method',
        rootCause: 'Yard capacity planning for {loc} did not account for peak production weeks, creating informal pressure to release panels early.',
        immediateAction: 'Hold all early-released panels for additional curing and re-test compressive strength before shipment.',
        correctiveAction: 'Expand yard curing capacity for peak weeks and make minimum curing time a hard release gate in the production system.',
        lessons: 'Curing time is a quality-critical parameter and must be enforced as a system gate, never subject to informal scheduling override.',
      },
      {
        title: 'Cement batch certificate missing on delivery from {loc}',
        description: 'Incoming inspection at {loc} found a cement delivery lacking the mill test certificate required to confirm compliance with the approved cement specification.',
        department: 'Logistics & Dispatch', criticality: 'medium', priority: 2,
        standard: 'ISO 9001:2015 Quality Management', causeCategory: 'method',
        rootCause: 'The supplier\'s certificate transmission to {loc} is manual and was missed during a personnel change at the supplier\'s dispatch office.',
        immediateAction: 'Quarantine the delivery until the certificate is obtained and verified.',
        correctiveAction: 'Add a digital certificate-upload requirement to the supplier portal so goods cannot be marked received without it attached.',
        lessons: 'Paper-based certificate transmission from suppliers is a recurring failure point; require digital, system-enforced attachment at receipt.',
      },
      {
        title: 'Forklift near-miss during panel loading at {loc}',
        description: 'A forklift operator at {loc} narrowly avoided collision with a ground crew member while loading a precast panel onto a delivery trailer, attributed to a blocked sightline.',
        department: 'Logistics & Dispatch', criticality: 'high', priority: 1,
        standard: 'ISO 45001 Occupational Health & Safety', causeCategory: 'environment',
        rootCause: 'Stacked empty pallets at {loc} obstructed the forklift operator\'s sightline to the pedestrian walkway, and no spotter was assigned for the loading operation.',
        immediateAction: 'Clear the obstruction immediately and halt loading operations until a spotter protocol is confirmed in place.',
        correctiveAction: 'Mark a permanent pedestrian exclusion zone during loading and mandate a spotter for all trailer-loading operations.',
        lessons: 'Sightline obstructions around active vehicle movement areas must be actively managed, not left to operator judgment alone.',
      },
    ],
  },
  {
    key: 'healthcare',
    orgName: 'Meridian General Hospital',
    orgNameFr: 'Hôpital Général Meridian',
    sectorType: 'private',
    domain: 'meridianhealth',
    departments: ['Nursing', 'Pharmacy', 'Sterile Processing', 'Laboratory', 'Patient Records'],
    locations: ['Ward 3B', 'Central Pharmacy', 'Sterile Processing Unit', 'Main Laboratory', 'Emergency Department'],
    archetypes: [
      {
        title: 'Medication administered without independent double-check at {loc}',
        description: 'Incident review at {loc} found a high-alert medication administered without the mandatory independent double-check by a second nurse, per policy for insulin and anticoagulants.',
        department: 'Nursing', criticality: 'high', priority: 1,
        standard: 'Joint Commission Patient Safety Standards', causeCategory: 'method',
        rootCause: 'Short-staffing on the shift at {loc} led nursing staff to bypass the double-check step under time pressure, with no system block preventing administration without it.',
        immediateAction: 'Assess the patient immediately for any adverse effect and notify the attending physician; document the incident.',
        correctiveAction: 'Configure the electronic medication administration record to require a second-nurse electronic sign-off before high-alert drugs can be marked administered.',
        lessons: 'High-alert medication safety checks must be enforced by the system, since staffing pressure will otherwise erode manual compliance.',
      },
      {
        title: 'Expired medication found in {loc} dispensing stock',
        description: 'Routine stock audit at {loc} found 14 units of a commonly dispensed medication past their expiry date still present in the active dispensing shelf.',
        department: 'Pharmacy', criticality: 'medium', priority: 2,
        standard: 'ISO 9001:2015 Quality Management', causeCategory: 'method',
        rootCause: 'The manual first-expiry-first-out shelf rotation at {loc} was not consistently performed during high-volume periods.',
        immediateAction: 'Remove and quarantine the expired stock immediately and verify no expired units were dispensed to patients.',
        correctiveAction: 'Implement barcode-based expiry tracking with an automated alert when stock approaches its expiry window.',
        lessons: 'Expiry management on high-turnover stock needs a system-level alert, not reliance on manual shelf checks alone.',
      },
      {
        title: 'Surgical instrument set incomplete after sterilization at {loc}',
        description: 'Pre-operative check at {loc} found a sterilized instrument tray missing 2 of its listed 28 instruments, discovered before the procedure began.',
        department: 'Sterile Processing', criticality: 'high', priority: 1,
        standard: 'ISO 13485 Medical Devices Quality Management', causeCategory: 'method',
        rootCause: 'The instrument count verification after washing at {loc} was performed visually rather than against the tray\'s digital count manifest.',
        immediateAction: 'Substitute a complete backup tray for the procedure and quarantine the incomplete tray for investigation.',
        correctiveAction: 'Require scan-based verification of instrument count against the digital manifest before a tray is released as complete.',
        lessons: 'Manual visual counts on complex instrument trays are error-prone; digital manifest verification closes the gap before it reaches the operating room.',
      },
      {
        title: 'Laboratory sample mislabeling at {loc}',
        description: 'A blood sample processed at {loc} was found to have a label mismatch between the specimen tube and the accompanying request form, caught during the barcode-verification step.',
        department: 'Laboratory', criticality: 'high', priority: 1,
        standard: 'ISO 9001:2015 Quality Management', causeCategory: 'method',
        rootCause: 'Manual label printing at the point of collection in {loc} allowed a mix-up between two patients being drawn in immediate succession.',
        immediateAction: 'Discard the mismatched sample and recollect from the correct patient with a fresh, verified label.',
        correctiveAction: 'Move to bedside barcode label printing at the point of collection so labels are generated only after patient identity is scanned.',
        lessons: 'Label generation must happen at the point of positive patient identification, not be pre-printed in batches.',
      },
      {
        title: 'After-hours patient record access without clinical justification at {loc}',
        description: 'A routine audit of {loc}\'s electronic health record system flagged an account accessing a patient file outside that employee\'s assigned shift and unit, with no documented clinical reason.',
        department: 'Patient Records', criticality: 'high', priority: 1,
        standard: 'ISO/IEC 27001 Information Security Management', causeCategory: 'method',
        rootCause: 'Access logging at {loc} exists but is only reviewed reactively upon complaint, rather than through proactive anomaly detection.',
        immediateAction: 'Suspend the account pending investigation and notify the privacy officer.',
        correctiveAction: 'Implement automated anomaly detection on access logs (off-shift, off-unit access patterns) with a mandatory review workflow.',
        lessons: 'Passive audit-log retention is not sufficient; proactive anomaly alerting is required to catch inappropriate access in a timely way.',
      },
      {
        title: 'Patient fall in {loc} due to incomplete fall-risk reassessment',
        description: 'A patient fall occurred in {loc}; review found the patient\'s fall-risk score had not been reassessed after a medication change known to increase fall risk.',
        department: 'Nursing', criticality: 'high', priority: 1,
        standard: 'Joint Commission Patient Safety Standards', causeCategory: 'method',
        rootCause: 'Fall-risk reassessment in {loc} is currently triggered only by a fixed shift schedule, not by clinically significant events like a new sedative medication order.',
        immediateAction: 'Assess the patient for injury, notify the physician, and complete an immediate fall-risk reassessment.',
        correctiveAction: 'Configure the clinical system to trigger a mandatory fall-risk reassessment automatically whenever a fall-risk-increasing medication is newly ordered.',
        lessons: 'Risk reassessment triggers should be tied to clinically significant events, not only to a fixed time interval.',
      },
    ],
  },
  {
    key: 'dairy',
    orgName: 'Valley Fresh Dairy Products',
    orgNameFr: 'Valley Fresh Produits Laitiers',
    sectorType: 'private',
    domain: 'valleyfresh',
    departments: ['Raw Milk Reception', 'Pasteurization', 'Packaging', 'Cold Chain Logistics', 'Quality Laboratory'],
    locations: ['Reception Bay 1', 'Pasteurizer Line A', 'Packaging Line 3', 'Cold Store 2', 'Distribution Fleet'],
    archetypes: [
      {
        title: 'Raw milk antibiotic residue test positive at {loc}',
        description: 'A raw milk tanker received at {loc} tested positive for antibiotic residue above the regulatory threshold during mandatory pre-acceptance screening.',
        department: 'Raw Milk Reception', criticality: 'high', priority: 1,
        standard: 'HACCP Hazard Analysis Critical Control Points', causeCategory: 'material',
        rootCause: 'The supplying farm\'s post-treatment withdrawal period was not respected before the milk delivered to {loc} was collected, and the collection route had no farm-level pre-screening.',
        immediateAction: 'Reject and quarantine the tanker load and notify the supplying farm and the collection route coordinator.',
        correctiveAction: 'Introduce farm-level rapid antibiotic screening at the collection point before milk is co-mingled into the tanker.',
        lessons: 'Residue screening only at plant reception is too late to isolate a single contaminated farm source; screening must move upstream to point of collection.',
      },
      {
        title: 'Pasteurization temperature deviation at {loc}',
        description: 'Continuous monitoring at {loc} recorded a 2°C temperature drop below the required pasteurization holding temperature for a 4-minute window before the automatic diversion valve activated.',
        department: 'Pasteurization', criticality: 'high', priority: 1,
        standard: 'HACCP Hazard Analysis Critical Control Points', causeCategory: 'machine',
        rootCause: 'A steam pressure fluctuation from the boiler supply to {loc} was not compensated quickly enough by the temperature control loop\'s response time settings.',
        immediateAction: 'Divert and destroy the affected under-pasteurized product batch; verify diversion valve function.',
        correctiveAction: 'Retune the temperature control loop response time and add a boiler steam-pressure stabilization buffer.',
        lessons: 'Critical control point diversion logic must be tested against realistic upstream supply fluctuations, not only steady-state conditions.',
      },
      {
        title: 'Packaging seal integrity failure at {loc}',
        description: 'End-of-line seal integrity testing at {loc} found a 3% reject rate on yogurt cup seals over one production shift, above the 0.5% acceptable threshold.',
        department: 'Packaging', criticality: 'medium', priority: 2,
        standard: 'ISO 9001:2015 Quality Management', causeCategory: 'machine',
        rootCause: 'The heat-sealing bar temperature at {loc} had drifted outside its set-point range due to a worn thermostat, undetected between scheduled calibration checks.',
        immediateAction: 'Stop the line, quarantine affected product, and replace the thermostat before resuming production.',
        correctiveAction: 'Add continuous seal-bar temperature logging with an automated out-of-range alert instead of periodic manual checks.',
        lessons: 'Intermittent drift on sealing equipment is best caught by continuous monitoring, not periodic spot checks alone.',
      },
      {
        title: 'Cold store temperature excursion at {loc}',
        description: 'Data logger review for {loc} showed an unplanned temperature excursion to 8°C for 45 minutes during a refrigeration unit fault, above the 4°C maximum for finished dairy product storage.',
        department: 'Cold Chain Logistics', criticality: 'high', priority: 1,
        standard: 'ISO 22000 Food Safety Management', causeCategory: 'machine',
        rootCause: 'The backup refrigeration unit at {loc} did not engage automatically on primary unit failure due to a misconfigured failover threshold.',
        immediateAction: 'Assess and quarantine affected stock for shelf-life/safety evaluation; repair the refrigeration unit.',
        correctiveAction: 'Reconfigure the automatic failover threshold and add a real-time SMS alert to the cold-chain duty manager on any excursion.',
        lessons: 'Backup equipment failover settings must be tested under realistic fault conditions, not assumed correct after installation.',
      },
      {
        title: 'Distribution vehicle temperature log gap at {loc}',
        description: 'A delivery route audit for {loc} found a 90-minute gap in the refrigerated truck\'s temperature log, coinciding with a driver-reported door-seal issue, with no compensating manual check recorded.',
        department: 'Cold Chain Logistics', criticality: 'medium', priority: 2,
        standard: 'ISO 22000 Food Safety Management', causeCategory: 'machine',
        rootCause: 'The vehicle\'s temperature logger on the {loc} route loses data during a power interruption and has no battery backup, and drivers are not trained to manually log temperature during such gaps.',
        immediateAction: 'Recall affected delivered batches for shelf-life assessment where feasible and brief the driver on manual logging procedure.',
        correctiveAction: 'Retrofit temperature loggers with battery backup across the fleet and add a manual-log fallback procedure to driver training.',
        lessons: 'Cold-chain monitoring equipment needs power-loss resilience; a monitoring gap is functionally the same risk as an actual excursion.',
      },
      {
        title: 'Allergen cross-contact risk on shared line at {loc}',
        description: 'An internal audit at {loc} found the changeover cleaning procedure between an allergen-containing flavored product and a standard product did not include a validated allergen swab test before restart.',
        department: 'Quality Laboratory', criticality: 'high', priority: 1,
        standard: 'ISO 22000 Food Safety Management', causeCategory: 'method',
        rootCause: 'The changeover cleaning SOP for {loc} was written before allergen swab testing was introduced elsewhere in the plant and was never updated to include it.',
        immediateAction: 'Hold the next production run pending a full allergen swab verification of the line.',
        correctiveAction: 'Update the changeover SOP to require a validated allergen swab pass before any shared line restarts after an allergen-containing run.',
        lessons: 'SOPs must be actively reviewed whenever a new control (like allergen swabbing) is introduced elsewhere, not left unsynchronized indefinitely.',
      },
    ],
  },
  {
    key: 'transportation',
    orgName: 'Continental Transport & Logistics',
    orgNameFr: 'Continental Transport et Logistique',
    sectorType: 'private',
    domain: 'contilogistics',
    departments: ['Fleet Maintenance', 'Operations Control', 'Driver Safety', 'Warehouse & Cross-Dock', 'Customer Delivery'],
    locations: ['Depot 4', 'Route 12 Corridor', 'Cross-Dock Hub', 'Maintenance Bay 2', 'Regional Distribution Center'],
    archetypes: [
      {
        title: 'Brake inspection overdue on fleet vehicle at {loc}',
        description: 'Fleet audit at {loc} found a delivery truck operating 12 days past its scheduled brake inspection interval, in breach of the preventive maintenance policy.',
        department: 'Fleet Maintenance', criticality: 'high', priority: 1,
        standard: 'ISO 39001 Road Traffic Safety Management', causeCategory: 'method',
        rootCause: 'The maintenance scheduling system for {loc} does not automatically ground a vehicle when its inspection window lapses; grounding still relies on a dispatcher manually checking status.',
        immediateAction: 'Withdraw the vehicle from service immediately and complete the overdue brake inspection before redeployment.',
        correctiveAction: 'Configure the fleet management system to automatically block dispatch assignment for any vehicle past its inspection due date.',
        lessons: 'Safety-critical maintenance compliance should be enforced by a system block, not left to manual dispatcher verification.',
      },
      {
        title: 'Driver hours-of-service limit exceeded on {loc}',
        description: 'Telematics review of {loc} found a driver logged 1.4 hours beyond the maximum permitted continuous driving time before the mandated rest break.',
        department: 'Driver Safety', criticality: 'high', priority: 1,
        standard: 'ISO 39001 Road Traffic Safety Management', causeCategory: 'method',
        rootCause: 'The route schedule for {loc} did not account for realistic traffic delay margins, creating pressure on the driver to continue driving to meet a delivery window.',
        immediateAction: 'Contact the driver to stop for the mandated rest break immediately and review the delivery commitment with the customer.',
        correctiveAction: 'Rebuild route schedules with realistic traffic buffers and add an in-cab alert that warns the driver and dispatcher as the hours-of-service limit approaches.',
        lessons: 'Schedule design that leaves no margin for normal traffic variability will systematically push drivers toward hours-of-service violations.',
      },
      {
        title: 'Cargo temperature excursion in transit from {loc}',
        description: 'A temperature-sensitive shipment dispatched from {loc} recorded an excursion above the specified range for 35 minutes during a refrigeration unit malfunction en route.',
        department: 'Warehouse & Cross-Dock', criticality: 'high', priority: 1,
        standard: 'ISO 9001:2015 Quality Management', causeCategory: 'machine',
        rootCause: 'The pre-trip refrigeration unit check at {loc} is a visual inspection only and did not detect a compressor fault that only manifested under sustained load.',
        immediateAction: 'Reroute the shipment to the nearest facility for temperature-integrity assessment and notify the customer.',
        correctiveAction: 'Add a functional load-test to the pre-trip refrigeration check rather than a visual inspection alone.',
        lessons: 'Pre-trip equipment checks need to functionally test under load where the failure mode only appears under sustained operation.',
      },
      {
        title: 'Forklift-pedestrian near-miss at {loc}',
        description: 'A near-miss was reported at {loc} when a forklift reversing near the loading dock nearly struck a warehouse associate crossing an unmarked walkway.',
        department: 'Warehouse & Cross-Dock', criticality: 'high', priority: 1,
        standard: 'ISO 45001 Occupational Health & Safety', causeCategory: 'environment',
        rootCause: 'Floor markings delineating pedestrian walkways at {loc} had faded and were not included in the routine facility inspection checklist.',
        immediateAction: 'Cordon off the affected area and reinstate temporary pedestrian markings immediately.',
        correctiveAction: 'Add floor-marking condition to the routine facility inspection checklist with a defined repaint trigger.',
        lessons: 'Passive safety controls like floor markings degrade over time and must be part of a recurring inspection, not a one-time installation.',
      },
      {
        title: 'Proof-of-delivery mismatch on {loc} route',
        description: 'A customer delivery audit for {loc} found 5 shipments marked delivered in the system without a corresponding signed or photographic proof-of-delivery on file.',
        department: 'Customer Delivery', criticality: 'medium', priority: 2,
        standard: 'ISO 9001:2015 Quality Management', causeCategory: 'method',
        rootCause: 'The driver mobile app used on {loc} allows a delivery to be marked complete without mandatorily capturing proof-of-delivery evidence first.',
        immediateAction: 'Contact the affected customers to confirm receipt and manually reconcile the delivery record.',
        correctiveAction: 'Modify the driver mobile app so a delivery cannot be marked complete without a captured signature or photo.',
        lessons: 'Process-critical evidence capture should be a hard system requirement at the point of the transaction, not an optional step.',
      },
      {
        title: 'Hazardous materials placarding incorrect on trailer at {loc}',
        description: 'A pre-departure check at {loc} found a trailer carrying a hazardous materials shipment displaying an outdated placard class that did not match the current manifest.',
        department: 'Operations Control', criticality: 'high', priority: 1,
        standard: 'ISO 45001 Occupational Health & Safety', causeCategory: 'method',
        rootCause: 'Placard selection at {loc} is a manual step performed from memory by dock staff rather than being generated automatically from the shipment manifest.',
        immediateAction: 'Hold the trailer and correct the placarding before departure is authorized.',
        correctiveAction: 'Generate placard requirements automatically from the shipment manifest and require a photo-verification step before dispatch.',
        lessons: 'Regulatory placarding must be system-generated from the authoritative manifest data, not manually selected from memory.',
      },
    ],
  },
  {
    key: 'energy',
    orgName: 'Atlas Energy & Petroleum',
    orgNameFr: 'Atlas Énergie et Pétrole',
    sectorType: 'private',
    domain: 'atlasenergy',
    departments: ['Process Safety', 'Pipeline Operations', 'HSE', 'Storage Operations', 'Control Room'],
    locations: ['Refinery Unit 3', 'Pipeline Segment 14', 'Storage Tank Farm B', 'Wellhead Pad 7', 'Control Room Alpha'],
    archetypes: [
      {
        title: 'Pressure relief valve testing overdue at {loc}',
        description: 'Asset integrity audit at {loc} found a pressure relief valve 45 days past its scheduled test date, a deviation from the process safety management testing interval.',
        department: 'Process Safety', criticality: 'high', priority: 1,
        standard: 'API 570 Piping Inspection Code', causeCategory: 'method',
        rootCause: 'The valve\'s test record at {loc} was not flagged in the maintenance system because it had been replaced under an emergency work order that did not carry over the original test schedule.',
        immediateAction: 'Schedule and complete the overdue test within 24 hours; apply a temporary operating restriction if the test cannot be completed immediately.',
        correctiveAction: 'Add a mandatory schedule-carryover check whenever a safety-critical component is replaced under an emergency work order.',
        lessons: 'Emergency replacement work orders must explicitly re-link to the original maintenance schedule, or safety-critical testing silently falls through the cracks.',
      },
      {
        title: 'Pipeline corrosion monitoring reading anomaly at {loc}',
        description: 'Corrosion monitoring at {loc} recorded a wall-thickness reading below the minimum retirement thickness at one inspection point, triggering an integrity review.',
        department: 'Pipeline Operations', criticality: 'high', priority: 1,
        standard: 'API 570 Piping Inspection Code', causeCategory: 'material',
        rootCause: 'Localized internal corrosion at a low-flow section of {loc} progressed faster than the general corrosion-rate model assumed for the pipeline segment.',
        immediateAction: 'Reduce operating pressure on the affected segment and schedule an emergency inspection.',
        correctiveAction: 'Install a permanent ultrasonic thickness monitoring sensor at the identified low-flow point and revise the segment\'s corrosion-rate model.',
        lessons: 'Uniform corrosion-rate models can miss localized low-flow hotspots; high-risk points need dedicated continuous monitoring, not periodic spot checks alone.',
      },
      {
        title: 'Gas detector calibration lapse in {loc}',
        description: 'A routine calibration audit found a fixed gas detector in {loc} had not been calibrated within its required interval, discovered after a nuisance alarm investigation.',
        department: 'HSE', criticality: 'high', priority: 1,
        standard: 'ISO 45001 Occupational Health & Safety', causeCategory: 'measurement',
        rootCause: 'The calibration due-date tracking for fixed detectors at {loc} was maintained in a separate spreadsheet from the main maintenance system, and the two were not reconciled regularly.',
        immediateAction: 'Calibrate the detector immediately and verify no undetected gas event occurred during the lapse.',
        correctiveAction: 'Migrate fixed-detector calibration tracking fully into the main maintenance system with automated due-date alerts.',
        lessons: 'Safety-critical calibration tracking split across disconnected systems creates a reconciliation gap that can silently expire.',
      },
      {
        title: 'Storage tank overfill alarm test failure at {loc}',
        description: 'Functional testing of the high-level overfill alarm at {loc} found the alarm did not trigger at the specified level during a scheduled proof test.',
        department: 'Storage Operations', criticality: 'high', priority: 1,
        standard: 'ISO 45001 Occupational Health & Safety', causeCategory: 'machine',
        rootCause: 'The level sensor\'s float mechanism at {loc} had accumulated sediment buildup, reducing its sensitivity below the specification threshold.',
        immediateAction: 'Restrict tank fill operations until the alarm is repaired and re-verified, using manual level monitoring as an interim control.',
        correctiveAction: 'Add sediment cleaning to the sensor\'s preventive maintenance schedule and shorten the proof-test interval for tanks in that service.',
        lessons: 'Overfill protection systems in sediment-prone service need maintenance intervals tuned to that specific fouling risk, not a generic schedule.',
      },
      {
        title: 'Well control barrier verification gap at {loc}',
        description: 'A barrier-status audit at {loc} found the secondary well control barrier\'s verification record was 3 weeks overdue, discovered during a routine well integrity review.',
        department: 'Pipeline Operations', criticality: 'high', priority: 1,
        standard: 'ISO 55001 Asset Management', causeCategory: 'method',
        rootCause: 'The well integrity review schedule for {loc} had not accounted for a personnel rotation that left the verification task temporarily unassigned.',
        immediateAction: 'Complete the overdue barrier verification immediately and confirm barrier integrity before continuing operations.',
        correctiveAction: 'Assign well integrity verification tasks to a role rather than a named individual so personnel rotation cannot leave a task unowned.',
        lessons: 'Safety-critical recurring tasks must be owned by a role in the system, not solely by an individual who may rotate off without handover.',
      },
      {
        title: 'Control room alarm flood during process upset at {loc}',
        description: 'An operator log review of a process upset in {loc} found over 200 alarms activated within 10 minutes, exceeding the operator\'s ability to triage effectively per good alarm management practice.',
        department: 'Control Room', criticality: 'medium', priority: 2,
        standard: 'ISO 14001 Environmental Management', causeCategory: 'method',
        rootCause: 'Alarm priority rationalization for {loc} had not been reviewed since the control system was last upgraded, leaving many low-value alarms configured at high priority.',
        immediateAction: 'Manually acknowledge and stabilize the process, then conduct a post-event debrief with the shift team.',
        correctiveAction: 'Perform a full alarm rationalization review for the affected unit against good alarm management practice and re-tier alarm priorities.',
        lessons: 'Alarm system configuration must be periodically re-rationalized as the process and control system evolve, not left static after commissioning.',
      },
    ],
  },
  {
    key: 'construction',
    orgName: 'Skyline Construction Group',
    orgNameFr: 'Skyline Groupe de Construction',
    sectorType: 'private',
    domain: 'skylinecx',
    departments: ['Site Execution', 'Structural Engineering', 'HSE', 'Quality Control', 'Project Management'],
    locations: ['Tower B Site', 'Basement Excavation Zone', 'Crane Zone 2', 'Finishing Floor 14', 'Site Perimeter'],
    archetypes: [
      {
        title: 'Scaffold inspection tag missing at {loc}',
        description: 'A safety walk at {loc} found a fully erected scaffold in active use without a current inspection tag, in breach of the weekly scaffold inspection requirement.',
        department: 'HSE', criticality: 'high', priority: 1,
        standard: 'ISO 45001 Occupational Health & Safety', causeCategory: 'method',
        rootCause: 'The scaffold inspection schedule at {loc} is tracked on a paper tag system with no central register, so a missed inspection is not visible until spotted on-site.',
        immediateAction: 'Stop work on the scaffold, re-inspect it immediately, and tag it before use resumes.',
        correctiveAction: 'Introduce a digital scaffold register with automated inspection due-date alerts visible to the site HSE team.',
        lessons: 'Paper-tag-only inspection systems have no proactive visibility of a missed inspection; a central digital register closes that gap.',
      },
      {
        title: 'Crane lift plan deviation at {loc}',
        description: 'An observed lift at {loc} used a different rigging configuration than specified in the approved lift plan, without a documented re-approval.',
        department: 'Site Execution', criticality: 'high', priority: 1,
        standard: 'ISO 45001 Occupational Health & Safety', causeCategory: 'method',
        rootCause: 'The crane operator and rigging crew at {loc} substituted equipment based on availability without routing the change back through the lift-plan approval process.',
        immediateAction: 'Halt the lift, verify the substituted rigging\'s load rating, and obtain a documented re-approval before continuing.',
        correctiveAction: 'Require any rigging substitution to trigger a mandatory lift-plan re-approval step before the lift can proceed.',
        lessons: 'Equipment substitution under time pressure is a common root cause for lift-plan deviations; the approval gate must be hard-enforced, not discretionary.',
      },
      {
        title: 'Rebar cover thickness below specification at {loc}',
        description: 'A cover-meter survey at {loc} found concrete cover over reinforcement averaging 22mm against a 30mm design minimum on a section of slab formwork.',
        department: 'Structural Engineering', criticality: 'high', priority: 1,
        standard: 'ACI 318 Building Code Requirements for Structural Concrete', causeCategory: 'method',
        rootCause: 'Rebar chairs used at {loc} were an incorrect height for the specified cover, substituted from available stock without a design cross-check.',
        immediateAction: 'Halt the pour, adjust chair height to the correct spec, and verify cover before proceeding.',
        correctiveAction: 'Standardize chair height per drawing on the site material request form so an incorrect substitution cannot be issued.',
        lessons: 'Cover-critical components like rebar chairs need their spec embedded in the material request process itself, not left to site judgment.',
      },
      {
        title: 'Excavation shoring inspection overdue after weather event at {loc}',
        description: 'A daily excavation safety check at {loc} found the trench shoring had not been re-inspected following 36 hours of heavy rainfall, in breach of the post-weather-event inspection rule.',
        department: 'HSE', criticality: 'high', priority: 1,
        standard: 'ISO 45001 Occupational Health & Safety', causeCategory: 'environment',
        rootCause: 'The post-weather-event inspection trigger for {loc} relies on a supervisor remembering to initiate it; no automated rainfall threshold alert exists.',
        immediateAction: 'Exclude personnel from the excavation until a re-inspection confirms shoring integrity.',
        correctiveAction: 'Integrate a rainfall-threshold alert from the site weather station that automatically triggers a mandatory shoring re-inspection task.',
        lessons: 'Weather-triggered safety inspections should be automated from real-time weather data, not dependent on manual recall.',
      },
      {
        title: 'Finishing works material substitution without approval at {loc}',
        description: 'Quality control at {loc} found that a fire-rated door specified for the finishing floor had been substituted with a non-rated equivalent by the finishing subcontractor.',
        department: 'Quality Control', criticality: 'high', priority: 1,
        standard: 'ISO 9001:2015 Quality Management', causeCategory: 'method',
        rootCause: 'The subcontractor\'s procurement team sourced from an alternate supplier during a stock shortage without routing the substitution through the design-approval process.',
        immediateAction: 'Remove and replace the non-conforming doors with the specified fire-rated equivalent before finishing sign-off.',
        correctiveAction: 'Require all material substitutions, including from subcontractors, to be logged and approved through the same design-change workflow as main contractor changes.',
        lessons: 'Substitution control must extend contractually to subcontractor procurement, not only to the main contractor\'s own purchasing.',
      },
      {
        title: 'Site perimeter access control breach at {loc}',
        description: 'A security review at {loc} found the pedestrian gate had been propped open outside authorized hours, allowing unescorted access to an active work zone.',
        department: 'Site Execution', criticality: 'medium', priority: 2,
        standard: 'ISO 45001 Occupational Health & Safety', causeCategory: 'method',
        rootCause: 'The gate\'s self-closing mechanism at {loc} had been temporarily disabled by workers for convenience during a delivery and not re-enabled afterward.',
        immediateAction: 'Re-enable the gate\'s self-closing mechanism immediately and brief the site team on the access-control policy.',
        correctiveAction: 'Fit the gate with an alarm that triggers if it remains open beyond a set time, rather than relying on the self-closer alone.',
        lessons: 'A single point-of-failure safety control like a self-closer needs a secondary alarm layer, since it can be deliberately defeated for convenience.',
      },
    ],
  },
];

export const SHOWCASE_SECTOR_TEMPLATES = {};
for (const s of SECTORS) {
  SHOWCASE_SECTOR_TEMPLATES[s.key] = expandArchetypes(s.archetypes, s.locations);
}

export const SHOWCASE_SECTOR_LABELS = {
  public_sector: { en: 'Public Sector', fr: 'Secteur Public', ar: 'القطاع العام' },
  construction_materials: { en: 'Manufacturing in Construction', fr: 'Industrie des Matériaux de Construction', ar: 'تصنيع مواد البناء' },
  healthcare: { en: 'Healthcare', fr: 'Santé', ar: 'الرعاية الصحية' },
  dairy: { en: 'Agro-Business – Dairy Products', fr: 'Agro-Industrie – Produits Laitiers', ar: 'الأعمال الزراعية - منتجات الألبان' },
  transportation: { en: 'Transportation', fr: 'Transport', ar: 'النقل' },
  energy: { en: 'Oil/Gas/Energy', fr: 'Pétrole/Gaz/Énergie', ar: 'النفط/الغاز/الطاقة' },
  construction: { en: 'Construction', fr: 'Construction', ar: 'البناء' },
};

export const SHOWCASE_ORG_DEFS = SECTORS.map((s) => ({
  name: s.orgName,
  name_fr: s.orgNameFr,
  sector: s.key,
  sectorType: s.sectorType,
  country: 'Morocco',
  planTier: 'assure',
  deploymentModel: 'saas',
  domain: s.domain,
  language: 'en',
  licenseOptions: { supportTier: 'priority', addonCapitalization: true },
}));
