// Clause-level requirement breakdown for each Annex A Standard (standardsLibrary.js).
// Answers "where are all the standard requirements": every Standard seeded into an
// Organization's Knowledge Base gets its own representative list of requirement
// clauses, each illustrated with a simulated non-conformity and the underlying
// problem pattern it typically signals — grounding for both the Standards page's
// requirements drill-down and, longer-term, per-clause RAG retrieval.
// Keyed by the Standard's `code` in ANNEX_A_STANDARDS.
export const STANDARD_REQUIREMENTS = {
  'ISO-9001': [
    { clause: '8.5.1', title: 'Control of production and service provision', text: 'Production and service provision must be carried out under controlled conditions, including documented process parameters and monitoring.', exampleNc: 'Torque values on the final assembly line were not recorded against the documented process parameters for 3 consecutive shifts.', exampleProblem: 'Missing/uncontrolled process parameter monitoring at the point of production.' },
    { clause: '8.7', title: 'Control of nonconforming outputs', text: 'Outputs that do not conform to requirements must be identified, segregated, and controlled to prevent unintended use or delivery.', exampleNc: 'A pallet of rejected units was found co-mingled with conforming stock in the shipping staging area, without a hold tag.', exampleProblem: 'Ineffective physical segregation/tagging of nonconforming material.' },
    { clause: '9.1.2', title: 'Customer satisfaction', text: 'The organization must monitor customer perception of the degree to which requirements have been fulfilled.', exampleNc: 'Three consecutive customer satisfaction surveys were not analyzed or reported to management review.', exampleProblem: 'Customer feedback loop not closed into corrective/preventive action.' },
    { clause: '10.2', title: 'Nonconformity and corrective action', text: 'When a nonconformity occurs, the organization must react, evaluate the need for action to eliminate causes, and review the effectiveness of corrective action taken.', exampleNc: 'A recurring dimensional non-conformity was closed without a documented root cause or effectiveness review.', exampleProblem: 'Corrective action process closed without verifying the root cause was actually eliminated.' },
    { clause: '7.1.5', title: 'Monitoring and measuring resources', text: 'Measuring equipment must be calibrated/verified at specified intervals, and be traceable to measurement standards.', exampleNc: 'A caliper used for final dimensional inspection was found 11 days past its calibration due date.', exampleProblem: 'Calibration schedule not enforced by a systematic reminder/control.' },
  ],
  'ISO-14001': [
    { clause: '6.1.2', title: 'Environmental aspects', text: 'The organization must determine the environmental aspects of its activities and their associated impacts that it can control or influence.', exampleNc: 'A new solvent-based cleaning process was introduced on the line without an updated environmental aspects register entry.', exampleProblem: 'Environmental aspect assessment not triggered by a management-of-change process.' },
    { clause: '8.1', title: 'Operational planning and control', text: 'Operating criteria for processes must be established, implemented, controlled, and maintained.', exampleNc: 'Wastewater pH was found outside the documented operating range for over 2 hours before being noticed.', exampleProblem: 'No real-time monitoring/alarm on a critical operational control parameter.' },
    { clause: '8.2', title: 'Emergency preparedness and response', text: 'The organization must establish, implement, and maintain processes for potential emergency situations.', exampleNc: 'A spill-response drill revealed the site’s secondary containment kit was missing absorbent material.', exampleProblem: 'Emergency response readiness not verified by periodic drills/inspections.' },
    { clause: '9.1.1', title: 'Monitoring, measurement, analysis and evaluation', text: 'The organization must monitor, measure, analyze and evaluate its environmental performance.', exampleNc: 'Monthly emissions monitoring data for one stack was missing for two consecutive reporting periods.', exampleProblem: 'Environmental monitoring schedule not tracked/escalated when missed.' },
    { clause: '10.2', title: 'Nonconformity and corrective action', text: 'The organization must react to nonconformities, take action to control/correct them, and deal with the consequences.', exampleNc: 'An oil leak into a storm drain was contained but the root cause (a worn gasket) was never formally investigated.', exampleProblem: 'Containment closed out without a linked root-cause investigation.' },
  ],
  'ISO-45001': [
    { clause: '8.1.2', title: 'Eliminating hazards and reducing OH&S risks', text: 'The organization must apply the hierarchy of controls to eliminate hazards and reduce OH&S risks.', exampleNc: 'A pinch-point hazard on a conveyor was controlled only by a warning sign, with no physical guard installed.', exampleProblem: 'Hierarchy of controls not applied — administrative control used where an engineering control was feasible.' },
    { clause: '8.2', title: 'Emergency preparedness and response', text: 'Processes must be established to prepare for and respond to potential emergency situations.', exampleNc: 'A site evacuation drill took 14 minutes against an 8-minute target, with 2 muster points unstaffed.', exampleProblem: 'Emergency response plan not tested/updated against actual site conditions.' },
    { clause: '9.1.1', title: 'Monitoring, measurement, analysis and performance evaluation', text: 'The organization must monitor and measure OH&S performance, including proactive and reactive indicators.', exampleNc: 'Near-miss reports dropped 80% quarter-over-quarter with no investigation into under-reporting.', exampleProblem: 'Leading-indicator trend not investigated when it moved sharply.' },
    { clause: '10.2', title: 'Incident, nonconformity and corrective action', text: 'Incidents and nonconformities must be reported, investigated, and corrective actions taken and verified.', exampleNc: 'A forklift near-miss involving a pedestrian was verbally reported but never logged or investigated.', exampleProblem: 'Incident reporting channel bypassed/not enforced at the point of occurrence.' },
    { clause: '6.1.2', title: 'Hazard identification and assessment of risks', text: 'The organization must establish an ongoing, proactive process for hazard identification.', exampleNc: 'A new packaging machine was commissioned without an updated job hazard analysis for the operators.', exampleProblem: 'Hazard identification not integrated into the equipment commissioning process.' },
  ],
  'IATF-16949': [
    { clause: '8.5.1.1', title: 'Control plan', text: 'Control plans must be maintained and used, covering the characteristics from the process flow diagram.', exampleNc: 'A control plan revision following an engineering change was not distributed to the night shift within the required timeframe.', exampleProblem: 'Control plan change-management process not synchronized with shift handover.' },
    { clause: '9.2.2.3', title: 'Manufacturing process audit', text: 'Each manufacturing process must be audited to determine its effectiveness, using a process approach.', exampleNc: 'A scheduled manufacturing process audit was skipped for one work center for two consecutive quarters.', exampleProblem: 'Internal audit schedule adherence not tracked/enforced.' },
    { clause: '10.2.3', title: 'Problem solving', text: 'A formal, disciplined process must be used to resolve nonconformities, including customer complaints.', exampleNc: 'A customer 8D report was closed at step D5 without an approved permanent corrective action.', exampleProblem: 'Structured problem-solving methodology not followed through to completion.' },
    { clause: '10.2.4', title: 'Error-proofing', text: 'Error-proofing methods must be used, with a defined process for challenging/testing error-proofing devices.', exampleNc: 'A poka-yoke sensor on the assembly cell had been bypassed for 6 shifts following a fault, without a deviation record.', exampleProblem: 'Error-proofing device bypass not controlled by a formal deviation/permit process.' },
    { clause: '8.7.1.1', title: 'Customer authorization for concession', text: 'Written or electronic customer authorization must be obtained prior to further processing of nonconforming product.', exampleNc: 'Out-of-spec parts were shipped to the customer under a verbal agreement, with no documented concession on file.', exampleProblem: 'Concession process not enforced before non-conforming shipment.' },
  ],
  'ISO-13485': [
    { clause: '7.5.1', title: 'Control of production and service provision', text: 'Production must be planned, carried out, monitored and controlled to ensure conformity to specifications.', exampleNc: 'A batch record for a sterile device lot was missing the operator’s signature for the sealing step.', exampleProblem: 'Batch record completeness not verified before lot release.' },
    { clause: '8.2.1', title: 'Feedback', text: 'The organization must gather and monitor information relating to whether product requirements have been met, as an input to the quality management system.', exampleNc: 'Post-market complaint trend data was not reviewed against the risk management file for two review cycles.', exampleProblem: 'Post-market feedback loop disconnected from risk management updates.' },
    { clause: '8.3', title: 'Control of nonconforming product', text: 'Nonconforming product must be identified and controlled to prevent unintended use or delivery.', exampleNc: 'A rejected sub-assembly was found in the finished goods staging area without a nonconformance tag.', exampleProblem: 'Nonconforming product identification/segregation not consistently applied.' },
    { clause: '8.5.2', title: 'Corrective action', text: 'Corrective actions must be appropriate to the effects of the nonconformities encountered, with documented investigation of causes.', exampleNc: 'A CAPA for a recurring seal-integrity failure was closed without evidence of effectiveness verification.', exampleProblem: 'CAPA closed before effectiveness of the fix was actually confirmed.' },
    { clause: '7.3.6', title: 'Design and development verification', text: 'Verification must be performed to ensure design outputs meet design input requirements.', exampleNc: 'A design change to a device housing was released to production before verification testing was complete.', exampleProblem: 'Design change released ahead of required verification gate.' },
  ],
  'AS9100': [
    { clause: '8.5.1', title: 'Control of production and service provision', text: 'Production must be carried out under controlled conditions, including special process controls.', exampleNc: 'A special process (heat treatment) log showed a furnace temperature excursion that was not flagged for disposition.', exampleProblem: 'Special process parameter excursion not automatically flagged for review.' },
    { clause: '8.7', title: 'Control of nonconforming outputs', text: 'Nonconforming outputs must be identified and controlled, with disposition authority clearly defined.', exampleNc: 'A nonconforming bracket was reworked by an operator without Material Review Board disposition authority.', exampleProblem: 'Disposition authority for nonconforming product not respected on the shop floor.' },
    { clause: '9.1.3', title: 'Analysis and evaluation', text: 'Data and information from monitoring and measurement must be analyzed to evaluate conformity and process performance.', exampleNc: 'First-pass-yield data for a critical machining cell had been declining for 3 months with no formal analysis triggered.', exampleProblem: 'Trend analysis threshold not defined/triggered for a declining process metric.' },
    { clause: '8.4.2', title: 'Type and extent of control of external provision', text: 'The organization must ensure externally provided processes, products and services do not adversely affect conformity.', exampleNc: 'A sub-tier supplier’s certificate of conformance was accepted without the required first-article inspection report.', exampleProblem: 'Supplier control checklist not fully enforced at receiving inspection.' },
    { clause: '10.2', title: 'Nonconformity and corrective action', text: 'The organization must react to nonconformities and evaluate the need for action to eliminate the causes.', exampleNc: 'A repeat nonconformity on the same part number occurred 4 months after a corrective action was marked closed.', exampleProblem: 'Corrective action did not eliminate the true root cause, allowing recurrence.' },
  ],
  'ISO-22000': [
    { clause: '8.9.2', title: 'Corrective actions', text: 'When critical limits or PRP requirements are not met, the organization must take corrective action.', exampleNc: 'A metal detector rejection at the packing line was manually overridden by an operator without supervisor sign-off.', exampleProblem: 'Critical control point override not gated by a mandatory authorization step.' },
    { clause: '8.5.4', title: 'Hazard control plan', text: 'A hazard control plan must be documented for each identified significant hazard, including critical limits.', exampleNc: 'The hazard control plan for allergen cross-contact had not been updated after a new ingredient was introduced.', exampleProblem: 'Hazard control plan not refreshed after a formulation/ingredient change.' },
    { clause: '8.9.3', title: 'Handling of potentially unsafe products', text: 'Product potentially unsafe must be handled to prevent it entering the food chain until evaluated.', exampleNc: 'A batch flagged for a temperature deviation was released to distribution before food safety evaluation was completed.', exampleProblem: 'Release process not blocked pending food-safety evaluation of a flagged batch.' },
    { clause: '7.5', title: 'Updating information specifying PRPs and hazard control plan', text: 'Documented information must be kept up to date, reflecting the latest process and hazard analysis.', exampleNc: 'A cleaning validation record referenced an SOP version that had been superseded 6 months earlier.', exampleProblem: 'Document control not synchronized with actual operating procedures.' },
  ],
  HACCP: [
    { clause: 'Principle 1', title: 'Conduct a hazard analysis', text: 'Identify biological, chemical, and physical hazards that are reasonably likely to occur.', exampleNc: 'A newly introduced raw material supplier was not included in the hazard analysis review.', exampleProblem: 'Hazard analysis not re-triggered by a supply-chain change.' },
    { clause: 'Principle 2', title: 'Determine critical control points', text: 'Identify points in the process where control can be applied to prevent or eliminate a hazard.', exampleNc: 'A cooking step CCP had no documented rationale linking it back to the hazard analysis.', exampleProblem: 'CCP determination not traceable back to a documented hazard.' },
    { clause: 'Principle 3', title: 'Establish critical limits', text: 'Set the maximum/minimum value to which a physical, biological or chemical hazard must be controlled.', exampleNc: 'The critical limit for chill-storage temperature was set 2°C above the validated safe threshold.', exampleProblem: 'Critical limit not validated against food-safety science before implementation.' },
    { clause: 'Principle 4', title: 'Establish monitoring procedures', text: 'Establish procedures to monitor control of the CCP.', exampleNc: 'Temperature logging at a CCP was done once per shift instead of the documented hourly frequency.', exampleProblem: 'Monitoring frequency not adhered to at the point of execution.' },
    { clause: 'Principle 5', title: 'Establish corrective actions', text: 'Establish corrective actions for when monitoring shows a CCP is not under control.', exampleNc: 'A CCP deviation was recorded but the affected product was not held pending the corrective action outcome.', exampleProblem: 'Product hold not automatically triggered by a recorded CCP deviation.' },
  ],
  'ISO-27001': [
    { clause: 'A.5.7', title: 'Threat intelligence', text: 'Information relating to information security threats must be collected and analyzed.', exampleNc: 'A known CVE affecting a production system was not reviewed against the organization’s asset inventory for 45 days.', exampleProblem: 'Threat intelligence not systematically cross-referenced with the live asset inventory.' },
    { clause: 'A.8.16', title: 'Monitoring activities', text: 'Networks, systems and applications must be monitored for anomalous behavior.', exampleNc: 'An unusual after-hours data export from a database server generated no alert for 3 days.', exampleProblem: 'Monitoring/alerting threshold not tuned to catch the anomalous pattern.' },
    { clause: 'A.5.24', title: 'Information security incident management planning', text: 'The organization must plan and prepare for managing information security incidents.', exampleNc: 'A tabletop incident-response exercise revealed the escalation contact list was 8 months out of date.', exampleProblem: 'Incident response plan not kept current through periodic testing.' },
    { clause: 'A.8.24', title: 'Use of cryptography', text: 'Rules for the effective use of cryptography, including key management, must be defined and implemented.', exampleNc: 'A legacy file transfer process was found using an unencrypted protocol for sensitive data.', exampleProblem: 'Cryptography policy not enforced on a legacy integration.' },
    { clause: '10.1', title: 'Continual improvement / nonconformity and corrective action', text: 'The organization must react to nonconformities and take action to eliminate the causes.', exampleNc: 'A repeat access-control audit finding was logged for the third consecutive quarter without a closed corrective action.', exampleProblem: 'Recurring audit finding not escalated into a durable corrective action.' },
  ],
  'ISO-31000': [
    { clause: '6.4.2', title: 'Risk identification', text: 'The organization must identify risks that might prevent, degrade, delay or enhance the achievement of objectives.', exampleNc: 'A single-source supplier dependency was not captured in the enterprise risk register despite being flagged in a procurement review.', exampleProblem: 'Risk identification not fed by operational/procurement review outputs.' },
    { clause: '6.4.3', title: 'Risk analysis', text: 'The organization must develop an understanding of the nature of risk and its characteristics, including likelihood and consequences.', exampleNc: 'Two risks with materially different consequences were both scored with the same generic “medium” rating.', exampleProblem: 'Risk analysis not applying the organization’s defined likelihood/impact criteria consistently.' },
    { clause: '6.4.4', title: 'Risk evaluation', text: 'The results of risk analysis must be compared against risk criteria to determine where action is required.', exampleNc: 'A risk scored above the acceptance threshold remained untreated for over a year with no documented rationale.', exampleProblem: 'Risk evaluation outcome not linked to a mandatory treatment decision.' },
    { clause: '6.5', title: 'Risk treatment', text: 'The organization must select and implement options for addressing risk.', exampleNc: 'A risk treatment plan was approved but the budget for its mitigation action was never allocated.', exampleProblem: 'Risk treatment plan approved without a resourcing/ownership commitment.' },
    { clause: '6.7', title: 'Monitoring and review', text: 'Both monitoring and review must be planned as part of the risk management process, with clearly defined responsibilities.', exampleNc: 'The risk register had not been reviewed by risk owners in over 9 months.', exampleProblem: 'Periodic risk review cadence not enforced/tracked.' },
  ],
  'ISO-50001': [
    { clause: '6.3', title: 'Energy review', text: 'The organization must develop an energy review, identifying areas of significant energy use.', exampleNc: 'A new compressor installation was not included in the annual energy review’s significant energy use list.', exampleProblem: 'Energy review not refreshed after a capital equipment change.' },
    { clause: '8.1', title: 'Operational planning and control', text: 'Operations and maintenance related to significant energy uses must be planned to ensure they are carried out under specified conditions.', exampleNc: 'A boiler’s preventive maintenance was overdue by 6 weeks past its documented interval.', exampleProblem: 'Maintenance schedule for a significant energy use not enforced.' },
    { clause: '9.1', title: 'Monitoring, measurement, analysis and evaluation of energy performance', text: 'Energy performance indicators must be monitored, measured, analyzed and evaluated at planned intervals.', exampleNc: 'Monthly energy performance indicator reporting was skipped for one facility for two consecutive months.', exampleProblem: 'Energy performance reporting cadence not tracked/escalated when missed.' },
    { clause: '10.2', title: 'Nonconformity and corrective action', text: 'The organization must react to nonconformities related to its energy performance and EnMS.', exampleNc: 'An energy performance deviation identified in an internal audit was not assigned a corrective action owner.', exampleProblem: 'Audit finding not routed into the corrective action process with clear ownership.' },
  ],
  'ISO-20000-1': [
    { clause: '8.2', title: 'Service level management', text: 'Service levels must be agreed, monitored, and reported, with action taken when levels are not met.', exampleNc: 'A P1 incident SLA breach was not reported to the service level review for two consecutive months.', exampleProblem: 'SLA breach reporting not consistently reaching the service review forum.' },
    { clause: '8.6.3', title: 'Incident management', text: 'Incidents must be logged, categorized, prioritized, and resolved within agreed timescales.', exampleNc: 'A major incident was resolved by an engineer’s workaround that was never logged in the incident record.', exampleProblem: 'Incident resolution not fully documented, losing the workaround as reusable knowledge.' },
    { clause: '8.6.4', title: 'Problem management', text: 'Problems must be identified and analyzed to prevent incidents from recurring.', exampleNc: 'Three incidents with the same underlying cause over 60 days did not trigger a formal problem record.', exampleProblem: 'Incident-to-problem escalation threshold not defined/enforced.' },
    { clause: '9.1', title: 'Monitoring, measurement, analysis and evaluation', text: 'The service management system and services must be monitored, measured, analyzed and evaluated.', exampleNc: 'Service availability metrics for a key application were manually compiled and were 2 weeks stale at time of review.', exampleProblem: 'Service monitoring not automated, leading to stale/late performance data.' },
  ],
  'VDA-6.3': [
    { clause: 'P5.1', title: 'Production process — process input', text: 'Process inputs (material, information, resources) must be verified as suitable before production start.', exampleNc: 'A production run was started using a material batch that had not yet received incoming inspection release.', exampleProblem: 'Material release gate not enforced before production start.' },
    { clause: 'P6.3', title: 'Complaint management / customer care', text: 'An effective process must exist for handling customer complaints and feedback.', exampleNc: 'A customer complaint was acknowledged but no 8D or containment action was initiated within the required timeframe.', exampleProblem: 'Complaint intake not linked to a time-bound response process.' },
    { clause: 'P2.1', title: 'Project management', text: 'Project management processes must ensure customer requirements are planned and tracked through APQP-style gates.', exampleNc: 'A design change was implemented in production ahead of the corresponding PPAP re-submission.', exampleProblem: 'Change control not synchronized with customer approval gates.' },
    { clause: 'P7.1', title: 'Customer care, customer satisfaction, service', text: 'Customer satisfaction must be systematically measured and acted upon.', exampleNc: 'A declining customer scorecard rating was not reviewed in the quarterly management meeting for two quarters.', exampleProblem: 'Customer scorecard trend not escalated into management review.' },
  ],
  GMP: [
    { clause: 'Deviation management', title: 'Deviation management', text: 'Deviations from approved procedures must be documented, investigated, and dispositioned before batch release.', exampleNc: 'A minor process deviation was noted verbally by the operator but never entered into the deviation system.', exampleProblem: 'Deviation reporting bypassed at the point of occurrence.' },
    { clause: 'Batch record review', title: 'Batch record review and release', text: 'Batch records must be reviewed and approved by quality before product release.', exampleNc: 'A batch was released with one incomplete signature field on the executed batch record.', exampleProblem: 'Batch record completeness check not enforced prior to release approval.' },
    { clause: 'Change control', title: 'Change control', text: 'Changes to processes, equipment, or materials must be assessed and approved before implementation.', exampleNc: 'A supplier change for a raw material was implemented before the change control assessment was completed.', exampleProblem: 'Change implemented ahead of the required approval gate.' },
    { clause: 'Cleaning validation', title: 'Cleaning validation', text: 'Cleaning procedures for shared equipment must be validated to prevent cross-contamination.', exampleNc: 'A swab test after changeover showed residue above the validated acceptance limit on one occasion.', exampleProblem: 'Cleaning verification result out of validated limits, not caught before next run.' },
    { clause: 'Complaint handling', title: 'Complaint handling', text: 'Product complaints must be recorded, investigated, and evaluated for potential quality impact.', exampleNc: 'A product quality complaint was closed without an assessment of whether other batches were affected.', exampleProblem: 'Complaint investigation scope not extended to related batches.' },
  ],
  'SIX-SIGMA': [
    { clause: 'Define', title: 'Define — project charter and voice of customer', text: 'The problem, goal, scope and customer requirements must be clearly defined before analysis begins.', exampleNc: 'An improvement project was launched without a documented problem statement or baseline metric.', exampleProblem: 'Project chartered without a measurable baseline to judge improvement against.' },
    { clause: 'Measure', title: 'Measure — data collection plan and MSA', text: 'A data collection plan and measurement system analysis must validate that the data used is reliable.', exampleNc: 'A measurement system analysis was skipped, and later the gauge used was found to have unacceptable repeatability.', exampleProblem: 'Measurement system not validated before being used to drive decisions.' },
    { clause: 'Analyze', title: 'Analyze — root cause analysis', text: 'Root causes of variation or defects must be identified and statistically validated where possible.', exampleNc: 'A root cause was accepted based on opinion alone, without supporting process data.', exampleProblem: 'Root cause not statistically or data-validated before action was taken.' },
    { clause: 'Improve', title: 'Improve — solution design and piloting', text: 'Proposed solutions must be piloted and their effect on the problem measured before full rollout.', exampleNc: 'A process change was rolled out to all lines without first piloting it on one line.', exampleProblem: 'Solution rolled out at full scale without a pilot to confirm effectiveness.' },
    { clause: 'Control', title: 'Control — control plan and sustainability', text: 'A control plan must be established to sustain the gains achieved by the improvement.', exampleNc: 'An improved process reverted to the old method within 3 months because no control plan was put in place.', exampleProblem: 'No control plan to sustain the improvement once the project team disengaged.' },
  ],
};
