// Single navigation model (FR-DA-NAV-01, NAV-11). Each item declares its group, route, icon, the view permission
// and the module entitlement it needs — the same codes the server enforces on the matching routes.
export const NAV_GROUPS = ['home', 'portfolio', 'process', 'governance', 'ai', 'reports', 'admin', 'settings'];
const i = (id, group, route, icon, perm, module = null) => ({ id, group, route, icon, perm, module, label: 'nav.' + id });
export const NAV = [
  i('dashboard', 'home', '/', 'LayoutDashboard', 'dashboard.view'),
  i('myTasks', 'home', '/my-tasks', 'ListChecks', 'tasks.execute'),
  i('alerts', 'home', '/alerts', 'Bell', 'alerts.view'),
  i('assistant', 'home', '/assistant', 'MessageSquare', 'assistant.view'),
  i('tenancy', 'portfolio', '/tenancy', 'Network', 'projects.view'),
  i('projects', 'portfolio', '/projects', 'FolderKanban', 'projects.view'),
  i('newProject', 'portfolio', '/projects/new', 'FolderPlus', 'projects.create'),
  i('portfolio', 'portfolio', '/portfolio', 'Grid3x3', 'portfolio.view'),
  i('modules', 'portfolio', '/modules', 'Blocks', 'projects.view'),
  i('records', 'portfolio', '/records', 'Database', 'projects.view'),
  i('macroProcesses', 'process', '/process/mp', 'Layers', 'catalog.view'),
  i('e2eProcesses', 'process', '/process/e2e', 'Workflow', 'catalog.view'),
  i('chain', 'process', '/process/chain', 'GitFork', 'catalog.view'),
  i('coverage', 'process', '/process/coverage', 'CheckCheck', 'catalog.view'),
  i('bpmn', 'process', '/process/bpmn', 'Shapes', 'bpmn.view'),
  i('verticals', 'process', '/process/verticals', 'Factory', 'catalog.view'),
  i('sme', 'process', '/process/sme', 'Gauge', 'catalog.view'),
  i('templates', 'process', '/process/templates', 'LayoutTemplate', 'catalog.view'),
  i('gates', 'process', '/process/gates', 'DoorOpen', 'catalog.view'),
  i('checklists', 'process', '/process/checklists', 'ClipboardCheck', 'catalog.view'),
  i('infoModel', 'process', '/process/model', 'Boxes', 'catalog.view'),
  i('rules', 'governance', '/gov/rules', 'Scale', 'governance.view'),
  i('controls', 'governance', '/gov/controls', 'ShieldCheck', 'governance.view'),
  i('risks', 'governance', '/gov/risks', 'TriangleAlert', 'governance.view'),
  i('kpis', 'governance', '/gov/kpis', 'Target', 'governance.view'),
  i('alertSettings', 'governance', '/gov/alert-settings', 'BellRing', 'governance.view'),
  i('racsi', 'governance', '/gov/racsi', 'Users', 'governance.view'),
  i('rex', 'governance', '/gov/rex', 'Lightbulb', 'governance.view'),
  i('gantt', 'governance', '/gov/gantt', 'ChartGantt', 'projects.view'),
  i('aiUseCases', 'ai', '/ai/use-cases', 'Sparkles', 'ai.view'),
  i('aiUsage', 'ai', '/ai/usage', 'History', 'ai.view'),
  i('kb', 'ai', '/ai/kb', 'BookOpen', 'ai.view'),
  i('aiModel', 'ai', '/ai/model', 'Cpu', 'ai.view'),
  i('reports', 'reports', '/reports', 'FileText', 'reports.view'),
  i('benchmark', 'reports', '/benchmark', 'ChartColumn', 'benchmark.view'),
  i('users', 'admin', '/admin/users', 'UserCog', 'users.manage'),
  i('permissions', 'admin', '/admin/permissions', 'KeyRound', 'permissions.manage'),
  i('configuration', 'admin', '/admin/config', 'SlidersHorizontal', 'config.view'),
  i('pricing', 'admin', '/admin/pricing', 'BadgeDollarSign', 'config.view'),
  i('integrations', 'admin', '/admin/integrations', 'Plug', 'config.view'),
  i('onboarding', 'admin', '/admin/onboarding', 'Rocket', 'config.view'),
  i('audit', 'admin', '/admin/audit', 'ScrollText', 'audit.view'),
  i('backups', 'admin', '/admin/backups', 'DatabaseBackup', 'backup.manage'),
  i('traceability', 'admin', '/admin/traceability', 'ListTree', 'traceability.view'),
  i('settings', 'settings', '/settings', 'Settings', 'profile.edit'),
  i('help', 'settings', '/help', 'LifeBuoy', 'help.view'),
];
