// Requirement traceability: maps each SRS requirement family to the screen and API
// that implement it. Shown on the Traceability screen and in the coverage checklist.
const L = (en, fr, ar) => ({ en, fr, ar });
export const TRACE = {
  'FR-DA-TEN': { screen: 'Organization > Tenancy, OBS', api: '/api/tenancy/*, /api/orgs/:id/obs', module: L('Tenancy and OBS', 'Structure et OBS', 'الهيكل والهيكل التنظيمي') },
  'FR-DA-RBAC': { screen: 'Administration > Users, Permission matrix', api: '/api/orgs/:id/users, /api/admin/permissions', module: L('Users and permissions', 'Utilisateurs et autorisations', 'المستخدمون والصلاحيات') },
  'FR-DA-CFG': { screen: 'Administration > Configuration', api: '/api/admin/orgs/:id/config', module: L('Packs, add-ons, compliance standards', 'Packs, options, normes de conformité', 'الحزم والإضافات ومعايير الامتثال') },
  'FR-DA-AI': { screen: 'Intelligence > AI use cases', api: '/api/orgs/:id/ai/usecases, /api/ai/suggest', module: L('AI use case library', 'Bibliothèque de cas d\'usage IA', 'مكتبة حالات الذكاء الاصطناعي') },
  'FR-DA-KB': { screen: 'Knowledge > Standards, REX', api: '/api/kb, /api/orgs/:id/rex', module: L('Knowledge base', 'Base de connaissances', 'قاعدة المعرفة') },
  'FR-DA-GOV': { screen: 'Governance > Rules, Controls, Risks, RACSI, KPIs', api: '/api/orgs/:id/rules|controls, /api/projects/:id/risks|racsi|kpis', module: L('Governance', 'Gouvernance', 'الحوكمة') },
  'FR-DA-BPMN': { screen: 'Lifecycle > Macro process > Diagram', api: '/api/projects/:id/bpmn/:mp', module: L('BPMN modeling', 'Modélisation BPMN', 'نمذجة BPMN') },
  'FR-DA-REP': { screen: 'Reports', api: '/api/projects/:id/reports/:type?format=pdf|xlsx|docx|csv', module: L('Reports and export', 'Rapports et export', 'التقارير والتصدير') },
  'FR-DA-ALT': { screen: 'Alerts', api: '/api/alerts, /api/alerts/catalog', module: L('Notification center', 'Centre de notifications', 'مركز التنبيهات') },
  'FR-DA-AST': { screen: 'Assistant', api: '/api/assistant/ask', module: L('AI Assistant', 'Assistant IA', 'المساعد الذكي') },
  'FR-DA-AUD': { screen: 'Administration > Audit trail', api: '/api/admin/audit-log', module: L('Audit trail', 'Piste d\'audit', 'سجل التدقيق') },
  'FR-DA-HLP': { screen: 'Help', api: '/api/help', module: L('Help', 'Aide', 'المساعدة') },
  'FR-DA-TPL': { screen: 'Libraries > Templates', api: '/api/libraries/templates', module: L('Template libraries', 'Bibliothèques de modèles', 'مكتبات النماذج') },
  'FR-DA-I18N': { screen: 'Language switcher (EN, FR, AR)', api: '?lang=en|fr|ar', module: L('Localization', 'Localisation', 'التوطين') },
  'FR-DA-WBS': { screen: 'Planning > WBS and Gantt', api: '/api/projects/:id/wbs', module: L('WBS and Gantt', 'OT et Gantt', 'هيكل تجزئة العمل وجانت') },
  'FR-DA-VER': { screen: 'History panel on versioned records', api: '/api/admin/versions/:type/:id', module: L('Version management', 'Gestion des versions', 'إدارة الإصدارات') },
  'FR-DA-COMM': { screen: 'Alerts > Dispatch log', api: '/api/orgs/:id/dispatches', module: L('Multi-channel communication', 'Communication multicanal', 'التواصل متعدد القنوات') },
  'FR-DA-REX': { screen: 'Nonconformity closure, Knowledge > REX', api: '/api/ncs/:id (stage Closed), /api/projects/:id/rex', module: L('Return on experience', 'Retour d\'expérience', 'الدروس المستفادة') },
  'FR-DA-NAV': { screen: 'Application shell', api: '/api/auth/prefs', module: L('Navigation shell', 'Navigation', 'واجهة التنقل') },
  'FR-DA-BMK': { screen: 'Benchmarking', api: '/api/benchmark/*', module: L('Benchmarking', 'Benchmarking', 'المقارنة المرجعية') },
  'FR-DA-OPS': { screen: 'Administration > Operations', api: '/api/admin/backups, /api/health, npm run backup', module: L('Platform operations', 'Exploitation', 'عمليات المنصة') },
  'FR-DA-PFO': { screen: 'Portfolio', api: '/api/portfolio', module: L('Portfolio overview', 'Vue portefeuille', 'نظرة المحفظة') },
  'FR-DA-CHK': { screen: 'Libraries > Checklists, Phase gate panel', api: '/api/libraries/checklists, /api/checklist-items/:id', module: L('Checklist library', 'Bibliothèque de listes de contrôle', 'مكتبة قوائم التحقق') },
  'FR-DA-ATT': { screen: 'Attachments on actions and checklist items', api: '/api/attachments', module: L('Attachments', 'Pièces jointes', 'المرفقات') },
  'FR-DA-VRT': { screen: 'Process design > Verticals', api: '/api/catalog/verticals, /api/admin/orgs/:id/verticals', module: L('Vertical framework', 'Cadre sectoriel', 'إطار القطاعات') },
  'FR-DA-VPR': { screen: 'Process design > Activation matrix', api: '/api/catalog/activation', module: L('Vertical processes', 'Processus sectoriels', 'العمليات القطاعية') },
  'FR-DA-VDT': { screen: 'Process design > Data dictionary', api: '/api/catalog/reference/dataDictionary', module: L('Vertical data', 'Données sectorielles', 'بيانات القطاع') },
  'FR-DA-VCP': { screen: 'Knowledge > Standards, Configuration', api: '/api/catalog/standards', module: L('Vertical compliance', 'Conformité sectorielle', 'الامتثال القطاعي') },
  'FR-DA-VIN': { screen: 'Administration > Integrations', api: '/api/admin/orgs/:id/integrations', module: L('Vertical integrations', 'Intégrations sectorielles', 'التكاملات القطاعية') },
  'FR-DA-VCF': { screen: 'Administration > Verticals', api: '/api/admin/orgs/:id/verticals', module: L('Vertical configuration', 'Configuration sectorielle', 'تهيئة القطاع') },
  'FR-DA-SME': { screen: 'Libraries > SME tracks, New project', api: '/api/libraries/tracks', module: L('SME mode and tracks', 'Mode PME et parcours', 'نمط المؤسسات الصغيرة والمسارات') },
  'FR-DA-SCO': { screen: 'New project > Complexity', api: '/api/orgs/:id/projects/score', module: L('Complexity scoring', 'Score de complexité', 'تقييم التعقيد') },
  'FR-DA-ONB': { screen: 'Organization > Onboarding', api: '/api/orgs/:id (onboarding), /api/admin/orgs/:id/import', module: L('SME onboarding', 'Intégration PME', 'تهيئة المؤسسات الصغيرة') },
  'FR-DA-PKG': { screen: 'Administration > Configuration > Pricing', api: '/api/admin/pricing', module: L('Packaging and pricing', 'Offres et tarifs', 'الحزم والتسعير') },
  'FR-DA-PTC': { screen: 'Libraries > Project templates', api: '/api/libraries/templates', module: L('Project template catalog', 'Catalogue de modèles de projets', 'كتالوج نماذج المشاريع') },
  'FR-DA-PCM': { screen: 'New project (catalog, manual, with AI)', api: '/api/orgs/:id/projects', module: L('Project creation modes', 'Modes de création de projet', 'أنماط إنشاء المشاريع') },
  'FR-DA-GTE': { screen: 'Libraries > Gates, Phase gate panel', api: '/api/libraries/gates, /api/phases/:id/gate', module: L('Gate library', 'Bibliothèque de jalons', 'مكتبة البوابات') },
  'NFR-DA-PERF': { screen: 'All lists (paginated), indexed queries', api: 'SQLite indexes, pagination', module: L('Performance', 'Performance', 'الأداء') },
  'NFR-DA-SEC': { screen: 'Sign-in', api: 'JWT, RBAC, tenant scoping, rate limiting, helmet', module: L('Security', 'Sécurité', 'الأمن') },
  'NFR-DA-REL': { screen: 'Assistant fallback, backups', api: 'Transactions, WAL, backups', module: L('Reliability', 'Fiabilité', 'الموثوقية') },
  'NFR-DA-SCALE': { screen: '—', api: 'Stateless API, separate web tier', module: L('Scalability', 'Évolutivité', 'قابلية التوسع') },
  'NFR-DA-UX': { screen: 'Design tokens, focus states, generated documents', api: '—', module: L('Usability and accessibility', 'Ergonomie et accessibilité', 'سهولة الاستخدام والإتاحة') },
  'NFR-DA-I18N': { screen: 'RTL mirroring in Arabic', api: '—', module: L('Localization', 'Localisation', 'التوطين') },
  'NFR-DA-PORT': { screen: '—', api: 'Node.js only; npm install, npm run seed, npm run dev', module: L('Installability', 'Installabilité', 'قابلية التثبيت') },
  'NFR-DA-MAINT': { screen: '—', api: 'Single modules for packs, alerts, permissions, versions', module: L('Maintainability', 'Maintenabilité', 'قابلية الصيانة') },
  'NFR-DA-COMPAT': { screen: 'Responsive layout, mobile drawer', api: '—', module: L('Compatibility', 'Compatibilité', 'التوافق') },
  'NFR-DA-COMP': { screen: 'AI usage log, audit trail', api: '/api/projects/:id/ai/log', module: L('Auditability', 'Auditabilité', 'قابلية التدقيق') },
  'NFR-DA-DATA': { screen: 'Assistant notice', api: 'No external AI provider is called', module: L('Data retention and privacy', 'Conservation et confidentialité', 'الاحتفاظ بالبيانات والخصوصية') },
};
export function traceOf(reqId) { return TRACE[reqId.replace(/-\d+[a-z]?$/, '')] || null; }
