// Demonstration answers to the IF-PAC forms. Answers are the respondents' own writing, so each organization's
// respondents answer in the organization's working language (en, fr or ar); they are not translated.
const B = {
  learnings: { en: ['Understood the key requirements and the evidence to keep', 'Can apply the method on my own cases', 'Better coordination with the other teams', 'Learned to read the indicators of my area'], fr: ['Compréhension des exigences clés et des preuves à conserver', 'Je sais appliquer la méthode sur mes propres cas', 'Meilleure coordination avec les autres équipes', 'J’ai appris à lire les indicateurs de mon périmètre'], ar: ['فهم المتطلبات الأساسية والأدلة الواجب حفظها', 'أستطيع تطبيق المنهج على حالاتي', 'تنسيق أفضل مع باقي الفرق', 'تعلمت قراءة مؤشرات مجالي'] },
  previous: {
    noticed: { en: ['Trainings were chosen late in the year and with little link to our objectives.', 'Good participation, but little follow-up after the sessions.'], fr: ['Les formations ont été choisies tard dans l’année, avec peu de lien avec nos objectifs.', 'Bonne participation, mais peu de suivi après les sessions.'], ar: ['تم اختيار التكوينات متأخرة في السنة وبصلة ضعيفة بأهدافنا.', 'مشاركة جيدة لكن تتبع ضعيف بعد الدورات.'] },
    strengths: { en: ['Practical trainers who knew our sector.', 'Sessions held on site, close to the teams.'], fr: ['Des formateurs pratiques qui connaissaient notre secteur.', 'Des sessions sur site, proches des équipes.'], ar: ['مكونون عمليون يعرفون قطاعنا.', 'دورات في عين المكان قريبة من الفرق.'] },
    improvements: { en: ['Fewer errors on {standard} records.', 'Supervisors use the new procedures.'], fr: ['Moins d’erreurs sur les enregistrements {standard}.', 'Les encadrants utilisent les nouvelles procédures.'], ar: ['أخطاء أقل في سجلات {standard}.', 'يستعمل المؤطرون المساطر الجديدة.'] },
    challenges: { en: ['Releasing people from the job during peaks.', 'Measuring the effect of the trainings.'], fr: ['Libérer les personnes de leur poste pendant les pics d’activité.', 'Mesurer l’effet des formations.'], ar: ['تحرير الأشخاص من مناصبهم في فترات الذروة.', 'قياس أثر التكوينات.'] },
    liked: { en: ['The workshops on real cases.', 'The exchange between sites.'], fr: ['Les ateliers sur des cas réels.', 'Les échanges entre sites.'], ar: ['الورشات حول حالات حقيقية.', 'التبادل بين المواقع.'] },
    different: { en: ['Shorter half-day formats with a workshop each time.', 'A plan built from the needs of each function.'], fr: ['Des formats courts en demi-journée avec un atelier à chaque fois.', 'Un plan construit à partir des besoins de chaque fonction.'], ar: ['صيغ قصيرة بنصف يوم مع ورشة في كل مرة.', 'مخطط مبني على حاجيات كل وظيفة.'] },
    outcome: { en: ['Teams would apply what they learn the week after.', 'Fewer audit findings.'], fr: ['Les équipes appliqueraient ce qu’elles apprennent dès la semaine suivante.', 'Moins d’écarts en audit.'], ar: ['ستطبق الفرق ما تتعلمه منذ الأسبوع الموالي.', 'ملاحظات أقل في التدقيق.'] },
    suggestions: { en: ['Start with {theme}; add a quiz to check what was learned.', 'Plan the sessions over two years.'], fr: ['Commencer par {theme} ; ajouter un quiz pour vérifier les acquis.', 'Répartir les sessions sur deux ans.'], ar: ['البدء بـ {theme}؛ إضافة اختبار للتحقق من المكتسبات.', 'توزيع الدورات على سنتين.'] },
    company_action: { en: ['Name a sponsor per theme and follow the indicators monthly.'], fr: ['Désigner un sponsor par thème et suivre les indicateurs chaque mois.'], ar: ['تعيين راع لكل موضوع وتتبع المؤشرات شهريا.'] },
  },
  jobs: { en: ['Head of {core}', 'Quality manager', 'Supervisor — {core}', 'Data and AI officer', 'Maintenance manager'], fr: ['Responsable {core}', 'Responsable qualité', 'Encadrant — {core}', 'Chargé données et IA', 'Responsable maintenance'], ar: ['مسؤول {core}', 'مسؤول الجودة', 'مؤطر — {core}', 'مكلف بالبيانات والذكاء الاصطناعي', 'مسؤول الصيانة'] },
  activities: { en: ['Plan and supervise the daily activity; follow the indicators', 'Run audits and corrective actions', 'Coach the team and validate the records', 'Prepare the data and the dashboards'], fr: ['Planifier et superviser l’activité quotidienne ; suivre les indicateurs', 'Conduire les audits et les actions correctives', 'Accompagner l’équipe et valider les enregistrements', 'Préparer les données et les tableaux de bord'], ar: ['تخطيط النشاط اليومي والإشراف عليه؛ تتبع المؤشرات', 'إجراء التدقيقات والإجراءات التصحيحية', 'مواكبة الفريق والمصادقة على السجلات', 'إعداد البيانات ولوحات القيادة'] },
  critical: { en: ['Release decisions', 'Handling of non-conformities', 'Shift hand-over'], fr: ['Décisions de libération', 'Traitement des non-conformités', 'Passation entre équipes'], ar: ['قرارات الإفراج', 'معالجة حالات عدم المطابقة', 'التسليم بين الفرق'] },
  strategy: {
    vision: { en: 'Become the reference of {sector} in the region, with teams trained to the best standards.', fr: 'Devenir la référence du secteur {sector} dans la région, avec des équipes formées aux meilleurs standards.', ar: 'أن نصبح المرجع في قطاع {sector} بالجهة، بفرق مكونة وفق أفضل المعايير.' },
    mission: { en: 'Deliver safe, compliant service through skilled people and controlled processes.', fr: 'Offrir un service sûr et conforme grâce à des équipes compétentes et des processus maîtrisés.', ar: 'تقديم خدمة آمنة ومطابقة بفضل فرق كفؤة ومسارات متحكم فيها.' },
    values: { en: 'Commitment · Excellence · Sharing', fr: 'Engagement · Excellence · Partage', ar: 'الالتزام · التميز · التقاسم' },
    context: { en: 'Strong competition, stricter {standard} audits and the arrival of {theme}.', fr: 'Concurrence forte, audits {standard} plus stricts et arrivée de {theme}.', ar: 'منافسة قوية وتدقيقات {standard} أكثر صرامة ووصول {theme}.' },
    products_existing: { en: 'Core services of {core}', fr: 'Services de base de {core}', ar: 'الخدمات الأساسية لـ {core}' },
    products_new: { en: 'Digital services supported by {theme}', fr: 'Services numériques appuyés sur {theme}', ar: 'خدمات رقمية مدعومة بـ {theme}' },
    segments: { en: 'Large accounts · Public sector · Individual customers', fr: 'Grands comptes · Secteur public · Particuliers', ar: 'الحسابات الكبرى · القطاع العام · الأفراد' },
    strategies: { en: 'Operational excellence and controlled digital transformation.', fr: 'Excellence opérationnelle et transformation numérique maîtrisée.', ar: 'التميز التشغيلي والتحول الرقمي المتحكم فيه.' },
    priority_axes: { en: 'Leadership and performance · {theme} · {standard} compliance · Dashboards', fr: 'Leadership et performance · {theme} · Conformité {standard} · Tableaux de bord', ar: 'القيادة والأداء · {theme} · المطابقة لـ {standard} · لوحات القيادة' },
    actions: { en: 'Training engineering under way; quality system review; digital roadmap.', fr: 'Ingénierie de formation en cours ; revue du système qualité ; feuille de route numérique.', ar: 'هندسة التكوين جارية؛ مراجعة نظام الجودة؛ خارطة طريق رقمية.' },
  },
  dates: { en: [['2008', 'Company founded'], ['2014', 'Second site opened'], ['2019', '{standard} certification'], ['2025', 'Digital transformation program launched']], fr: [['2008', 'Création de l’entreprise'], ['2014', 'Ouverture du deuxième site'], ['2019', 'Certification {standard}'], ['2025', 'Lancement du programme de transformation numérique']], ar: [['2008', 'تأسيس المؤسسة'], ['2014', 'افتتاح الموقع الثاني'], ['2019', 'الحصول على شهادة {standard}'], ['2025', 'إطلاق برنامج التحول الرقمي']] },
  objectives: { en: [['Improve customer satisfaction', 'Satisfaction score ≥ 85% by end of year'], ['Reduce non-quality costs', '-20% rework in 12 months'], ['Develop human capital', '80% of critical roles certified']], fr: [['Améliorer la satisfaction des clients', 'Score de satisfaction ≥ 85 % d’ici la fin de l’année'], ['Réduire les coûts de non-qualité', '-20 % de reprises en 12 mois'], ['Développer le capital humain', '80 % des rôles critiques certifiés']], ar: [['تحسين رضا الزبناء', 'نسبة رضا ≥ 85٪ في نهاية السنة'], ['خفض تكاليف اللاجودة', 'خفض إعادة العمل بـ 20٪ خلال 12 شهرا'], ['تطوير الرأسمال البشري', 'اعتماد 80٪ من الأدوار الحرجة']] },
  grades: { en: ['Technicians, operators', 'Team leads', 'Supervisors', 'Managers', 'Directors'], fr: ['Techniciens, opérateurs', 'Chefs d’équipe', 'Superviseurs', 'Responsables', 'Directeurs'], ar: ['تقنيون، عمال', 'رؤساء فرق', 'مشرفون', 'مسؤولون', 'مديرون'] },
  swot: {
    strengths: { en: ['Experienced, committed team', 'Good knowledge of the market', 'Stable processes'], fr: ['Équipe expérimentée et engagée', 'Bonne connaissance du marché', 'Processus stables'], ar: ['فريق ذو خبرة وملتزم', 'معرفة جيدة بالسوق', 'مسارات مستقرة'] },
    weaknesses: { en: ['Low use of {theme}', 'Reporting kept in spreadsheets', 'Little versatility between roles'], fr: ['Faible usage de {theme}', 'Reporting tenu sur des tableurs', 'Peu de polyvalence entre les postes'], ar: ['ضعف استعمال {theme}', 'تقارير على جداول البيانات', 'تعدد مهام ضعيف بين المناصب'] },
    opportunities: { en: ['Demand for digital services', 'Training contracts refunded by OFPPT'], fr: ['Demande de services numériques', 'Contrats de formation remboursés par l’OFPPT'], ar: ['الطلب على الخدمات الرقمية', 'عقود تكوين يسترجعها مكتب التكوين المهني'] },
    threats: { en: ['Stricter {standard} audits', 'Departure of key experts'], fr: ['Audits {standard} plus stricts', 'Départ d’experts clés'], ar: ['تدقيقات {standard} أكثر صرامة', 'مغادرة خبراء محوريين'] },
  },
  tasks: { en: ['Record the daily activity in the system', 'Check the quality of the output', 'Report incidents and deviations', 'Use {theme} tools in my work', 'Train new colleagues'], fr: ['Enregistrer l’activité quotidienne dans le système', 'Contrôler la qualité de la production', 'Signaler les incidents et écarts', 'Utiliser les outils de {theme} dans mon travail', 'Former les nouveaux collègues'], ar: ['تسجيل النشاط اليومي في النظام', 'مراقبة جودة الإنتاج', 'التبليغ عن الحوادث والانحرافات', 'استعمال أدوات {theme} في عملي', 'تكوين الزملاء الجدد'] },
  projects: { en: [['{theme} pilot', 'Pilot on one site before roll-out', 'In progress'], ['{standard} recertification', 'Audit preparation and evidence', 'Planned']], fr: [['Pilote {theme}', 'Pilote sur un site avant généralisation', 'En cours'], ['Recertification {standard}', 'Préparation de l’audit et des preuves', 'Planifié']], ar: [['مشروع نموذجي {theme}', 'تجربة في موقع قبل التعميم', 'جار'], ['تجديد شهادة {standard}', 'إعداد التدقيق والأدلة', 'مبرمج']] },
  ambitions: {
    ambitions: { en: ['Make my team autonomous on {theme} within a year.', 'Reach zero major finding at the next audit.'], fr: ['Rendre mon équipe autonome sur {theme} d’ici un an.', 'Atteindre zéro écart majeur au prochain audit.'], ar: ['جعل فريقي مستقلا في {theme} خلال سنة.', 'الوصول إلى صفر ملاحظة كبرى في التدقيق المقبل.'] },
    feelings: { en: ['Proud and more confident.', 'Relieved and motivated.'], fr: ['Fier et plus confiant.', 'Soulagé et motivé.'], ar: ['فخور وأكثر ثقة.', 'مرتاح ومتحفز.'] },
    evidence: { en: ['The indicators of my area improve for three months.', 'The audit report confirms it.'], fr: ['Les indicateurs de mon périmètre progressent pendant trois mois.', 'Le rapport d’audit le confirme.'], ar: ['تتحسن مؤشرات مجالي لمدة ثلاثة أشهر.', 'يؤكد ذلك تقرير التدقيق.'] },
    can_do: { en: ['Share good practices in weekly meetings.'], fr: ['Partager les bonnes pratiques en réunion hebdomadaire.'], ar: ['تقاسم الممارسات الجيدة في الاجتماعات الأسبوعية.'] },
    will_do: { en: ['Follow the training and coach two colleagues.'], fr: ['Suivre la formation et accompagner deux collègues.'], ar: ['متابعة التكوين ومواكبة زميلين.'] },
    needs: { en: ['{theme}; Time management and priorities', 'Communication with the team; Problem solving', '{standard} requirements; Dashboards'], fr: ['{theme} ; Gestion du temps et priorités', 'Communication avec l’équipe ; Résolution de problèmes', 'Exigences {standard} ; Tableaux de bord'], ar: ['{theme}؛ تدبير الوقت والأولويات', 'التواصل مع الفريق؛ حل المشكلات', 'متطلبات {standard}؛ لوحات القيادة'] },
    impact: { en: ['Fewer errors and faster service.', 'Better audit results and staff retention.', 'Teams able to use {theme} safely.'], fr: ['Moins d’erreurs et un service plus rapide.', 'De meilleurs résultats d’audit et une meilleure fidélisation du personnel.', 'Des équipes capables d’utiliser {theme} en sécurité.'], ar: ['أخطاء أقل وخدمة أسرع.', 'نتائج تدقيق أفضل والحفاظ على الموارد البشرية.', 'فرق قادرة على استعمال {theme} بأمان.'] },
    recommendations: { en: ['Keep sessions short and practical.', 'Involve the managers in the follow-up.'], fr: ['Garder des sessions courtes et pratiques.', 'Impliquer les managers dans le suivi.'], ar: ['الإبقاء على دورات قصيرة وعملية.', 'إشراك المسؤولين في التتبع.'] },
  },
  ai: { en: ['Daily, for triage and reports.', 'Lack of training and unclear rules.', 'Data protection and validation of results.', '{theme}; data quality', 'Short workshops on the job, then coaching.'], fr: ['Chaque jour, pour le tri et les rapports.', 'Manque de formation et règles peu claires.', 'Protection des données et validation des résultats.', '{theme} ; qualité des données', 'Des ateliers courts sur le poste, puis du coaching.'], ar: ['يوميا، للفرز والتقارير.', 'نقص في التكوين وقواعد غير واضحة.', 'حماية البيانات والمصادقة على النتائج.', '{theme}؛ جودة البيانات', 'ورشات قصيرة في العمل ثم مواكبة.'] },
  orientations: { en: 'Update job descriptions, individual objectives and the yearly assessment; build career paths.', fr: 'Mettre à jour les fiches de poste, les objectifs individuels et l’évaluation annuelle ; construire les chemins de carrière.', ar: 'تحيين بطاقات المناصب والأهداف الفردية والتقييم السنوي؛ بناء المسارات المهنية.' },
};
const fill = (s, v) => String(s).replace(/\{(\w+)\}/g, (m, k) => v[k] ?? m);

/** Answers to a form for one respondent. `r` is the seeded random generator; `skip` the share of sections left empty. */
export function answersFor(form, ctx, r, { skip = 0.08 } = {}) {
  const l = ctx.lang; const v = { theme: ctx.theme[l] || ctx.theme.en, core: ctx.core[l] || ctx.core.en, standard: ctx.standard, sector: ctx.sector[l] || ctx.sector.en, org: ctx.org[l] || ctx.org.en };
  const pickArr = a => a[Math.floor(r() * a.length)];
  const bank = (b, i = null) => fill(Array.isArray(b[l] || b.en) ? (i == null ? pickArr(b[l] || b.en) : (b[l] || b.en)[i % (b[l] || b.en).length]) : (b[l] || b.en), v);
  const int = (a, b) => a + Math.floor(r() * (b - a + 1));
  const A = {}; const flags = { previous_plan: r() > 0.15, hr_function: /human|ressources|بشرية/i.test(ctx.functionName || '') };
  for (const s of form.sections) {
    if (s.type === 'note' || (!['identity', 'strategy'].includes(s.id) && r() < skip)) continue;
    switch (s.id) {
      case 'identity': A[s.id] = { full_name: ctx.name, position: ctx.position, reports_to: ctx.reportsTo, experience_years: int(4, 26), years_in_position: int(1, 9), age: int(26, 58) }; break;
      case 'training_history': A[s.id] = Array.from({ length: int(1, 3) }, (_, i) => ({ title: i ? `${v.standard} — ${l === 'fr' ? 'sensibilisation' : l === 'ar' ? 'توعية' : 'awareness'}` : v.theme, month_year: `${String(int(1, 12)).padStart(2, '0')}/2025`, days: int(1, 3), learnings: bank(B.learnings) })); break;
      case 'previous_plan': A[s.id] = Object.fromEntries(s.items.map(it => [it.key, B.previous[it.key] ? bank(B.previous[it.key]) : ''])); break;
      case 'org_chart': A[s.id] = { confirmed: { value: 'Yes' } }; break;
      case 'jobs': A[s.id] = Array.from({ length: 3 }, (_, i) => ({ job_title: bank(B.jobs, i + int(0, 2)), existing: i === 2 ? 'Future' : 'Existing', key_activities: bank(B.activities, i), competences: i === 2 ? v.theme : bank(B.ambitions.needs, i), critical: bank(B.critical, i) })); break;
      case 'strategy': A[s.id] = Object.fromEntries(s.rows.map(rw => [rw.key, { details: bank(B.strategy[rw.key] || { en: '' }) }])); break;
      case 'key_dates': A[s.id] = (B.dates[l] || B.dates.en).map(([d, e]) => ({ date: d, event: fill(e, v) })); break;
      case 'objectives': A[s.id] = (B.objectives[l] || B.objectives.en).slice(0, int(2, 3)).map(([o, sm], i) => ({ objective: o, smart: sm, link_customer: i === 0, link_financial: i === 1, link_operational: i !== 2, link_hr: i === 2, link_innovation: r() > 0.6, competences: i === 0 ? v.theme : bank(B.ambitions.needs, i) })); break;
      case 'performance': A[s.id] = ctx.functions.map(f => ({ function: f, ms: int(2, 5), mo: int(2, 5), op: int(1, 5), competences: r() > 0.5 ? v.theme : bank(B.ambitions.needs) })); break;
      case 'leadership':
        A[s.id] = s.columns.some(c => c.key === 'pct') ? Object.fromEntries(s.rows.map((rw, i) => [rw.key, { pct: [42, 28, 18, 8, 4][i] + int(-3, 3), grade: (B.grades[l] || B.grades.en)[i], details: '' }])) : Object.fromEntries(s.rows.map((rw, i) => [rw.key, { self: Math.max(1, int(2, 5) - i), details: '' }])); break;
      case 'transverse': A[s.id] = Object.fromEntries(s.rows.map(rw => [rw.key, { documented: r() > 0.45 ? 'Yes' : 'No', owner: r() > 0.6 ? 'Yes' : 'No', score: int(1, 4) }])); break;
      case 'swot': case 'swot_ot': A[s.id] = Object.fromEntries(s.boxes.map(b => [b.key, (B.swot[b.key][l] || B.swot[b.key].en).map(x => fill(x, v)).slice(0, int(2, 3)).join('; ')])); break;
      case 'swot_function': A[s.id] = [{ scope: ctx.functionName || v.core, strengths: bank(B.swot.strengths), weaknesses: bank(B.swot.weaknesses), competences: v.theme }, { scope: v.core, strengths: bank(B.swot.strengths), weaknesses: bank(B.swot.weaknesses), competences: bank(B.ambitions.needs) }]; break;
      case 'swot_light': A[s.id] = [{ strengths: bank(B.swot.strengths), weaknesses: bank(B.swot.weaknesses), competences: v.theme }, { strengths: bank(B.swot.strengths), weaknesses: bank(B.swot.weaknesses), competences: bank(B.ambitions.needs) }]; break;
      case 'strategic_planning': A[s.id] = Object.fromEntries(s.items.map((it, i) => [it.key, { value: i < 2 || r() > 0.5 ? 'Yes' : 'No', comment: '' }])); break;
      case 'soft_skills': A[s.id] = Object.fromEntries(s.items.map(it => [it.key, s.scale?.allowNew && r() < 0.05 ? 'Nv' : String(int(2, 5))])); break;
      case 'hr_orientations': if (flags.hr_function) A[s.id] = { orientations: bank(B.orientations) }; break;
      case 'job_sheet': A[s.id] = Array.from({ length: 4 }, (_, i) => ({ task: bank(B.tasks, i), status: i === 3 ? 'New' : 'Existing', critical: int(2, 5), performance: int(2, 5), competences: i === 3 ? v.theme : bank(B.ambitions.needs, i) })); break;
      case 'projects': A[s.id] = (B.projects[l] || B.projects.en).map(([pj, d, st]) => ({ project: fill(pj, v), details: fill(d, v), start: '2026-02-01', end: '2026-12-15', state: st, remarks: '', competences: v.theme })); break;
      case 'ambitions': A[s.id] = Object.fromEntries(s.items.map(it => [it.key, bank(B.ambitions[it.key] || { en: '' })])); break;
      case 'ai_sector': A[s.id] = Object.fromEntries(s.items.map((it, i) => [it.key, bank(B.ai, i)])); break;
      default: break;
    }
  }
  return { answers: A, flags };
}
