// In-app Help articles (one per module, identical set in every language) and the
// FAQ corpus used by the AI Assistant's application-help mode (FR-DA-HLP-01..03, FR-DA-AST-04).
const S = (en, fr, ar) => ({ en, fr, ar });

export const HELP = [
  { id: 'H01', module: 'home', title: S('Home and my tasks', 'Accueil et mes tâches', 'الرئيسية ومهامي'), body: S(
    'The Home screen shows your open steps, overdue items and unread alerts for the selected project. Choose the organization and project in the header switcher. Each tile opens the matching list.',
    'L\'accueil affiche vos étapes ouvertes, les éléments en retard et les alertes non lues du projet sélectionné. Choisissez l\'organisation et le projet dans le sélecteur de l\'en-tête. Chaque tuile ouvre la liste correspondante.',
    'تعرض الشاشة الرئيسية خطواتك المفتوحة والبنود المتأخرة والتنبيهات غير المقروءة للمشروع المختار. اختر المؤسسة والمشروع من محدد الترويسة. تفتح كل بطاقة القائمة المقابلة.') },
  { id: 'H02', module: 'tenancy', title: S('Groups, organizations and projects', 'Groupes, organisations et projets', 'المجموعات والمؤسسات والمشاريع'), body: S(
    'An organization may belong to a group (Yes/No) or be independent. Each organization is a separate tenant: its data is never visible to another tenant. Projects are the management-system runs (QMS or QHSE) of an organization. Open Tenancy to see the tree and the table.',
    'Une organisation peut appartenir à un groupe (Oui/Non) ou être indépendante. Chaque organisation est un locataire distinct : ses données ne sont jamais visibles par un autre locataire. Les projets sont les déploiements du système de management (SMQ ou QHSE) d\'une organisation. Ouvrez Structure pour voir l\'arbre et le tableau.',
    'قد تنتمي المؤسسة إلى مجموعة (نعم/لا) أو تكون مستقلة. كل مؤسسة مستأجر منفصل: لا تظهر بياناتها لأي مستأجر آخر. المشاريع هي تشغيلات نظام الإدارة (الجودة أو الجودة والصحة والسلامة والبيئة) للمؤسسة. افتح «الهيكل» لرؤية الشجرة والجدول.') },
  { id: 'H03', module: 'projects', title: S('Creating a project', 'Créer un projet', 'إنشاء مشروع'), body: S(
    'Use New project. Three tabs are available: From the catalog (pick a published template), Manual (enter fields, choose vertical, mode and track) and With AI (describe the project; the assistant drafts it and you accept, edit or reject each item). The complexity score recommends the mode and the SME track.',
    'Utilisez Nouveau projet. Trois onglets sont disponibles : Depuis le catalogue (choisir un modèle publié), Manuel (saisir les champs, choisir le secteur, le mode et le parcours) et Avec l\'IA (décrire le projet ; l\'assistant le rédige et vous acceptez, modifiez ou rejetez chaque élément). Le score de complexité recommande le mode et le parcours PME.',
    'استخدم «مشروع جديد». تتوفر ثلاث تبويبات: من الكتالوج (اختيار نموذج منشور)، ويدويًا (إدخال الحقول واختيار القطاع والنمط والمسار)، وبالذكاء الاصطناعي (صف المشروع فيصوغه المساعد وتقبل كل بند أو تعدله أو ترفضه). توصي درجة التعقيد بالنمط ومسار المؤسسات الصغيرة.') },
  { id: 'H04', module: 'lifecycle', title: S('Running the lifecycle (E2E processes)', 'Dérouler le cycle de vie (processus E2E)', 'تشغيل دورة الحياة (العمليات الشاملة)'), body: S(
    'The Lifecycle screen shows the 12 end-to-end processes as phases. Open a phase to see its macro processes, then open a macro process to execute its tasks and steps. Each step has a form; fill the required fields and select Complete. Steps follow their order: a step opens when the previous one is done.',
    'L\'écran Cycle de vie présente les 12 processus de bout en bout sous forme de phases. Ouvrez une phase pour voir ses macro-processus, puis un macro-processus pour exécuter ses tâches et étapes. Chaque étape comporte un formulaire ; renseignez les champs obligatoires puis choisissez Terminer. Les étapes suivent leur ordre : une étape s\'ouvre lorsque la précédente est terminée.',
    'تعرض شاشة دورة الحياة العمليات الشاملة الاثنتي عشرة كمراحل. افتح مرحلة لرؤية عملياتها الكلية، ثم افتح عملية كلية لتنفيذ مهامها وخطواتها. لكل خطوة نموذج؛ املأ الحقول الإلزامية ثم اختر «إنهاء». تتبع الخطوات ترتيبها: تُفتح الخطوة عند اكتمال السابقة.') },
  { id: 'H05', module: 'lifecycle', title: S('Gates and checklists', 'Jalons et listes de contrôle', 'البوابات وقوائم التحقق'), body: S(
    'Each phase ends with a gate from the Gate Library. The gate brings its checklists. A mandatory item that is not done blocks the Go decision unless a waiver with justification is approved. Decisions are Go, No-Go, Hold or Recycle and are kept in the audit trail.',
    'Chaque phase se termine par un jalon de la bibliothèque des jalons. Le jalon apporte ses listes de contrôle. Un élément obligatoire non réalisé bloque la décision Go, sauf dérogation justifiée et approuvée. Les décisions sont Go, No-Go, En attente ou Recyclage et sont conservées dans la piste d\'audit.',
    'تنتهي كل مرحلة ببوابة من مكتبة البوابات، وتجلب البوابة قوائم تحققها. يمنع البند الإلزامي غير المنجز قرار المضي ما لم يُعتمد استثناء مبرر. القرارات هي: المضي، عدم المضي، التعليق، إعادة التدوير، وتُحفظ في سجل التدقيق.') },
  { id: 'H06', module: 'catalog', title: S('Process design catalog', 'Référentiel de conception des processus', 'كتالوج تصميم العمليات'), body: S(
    'The catalog holds the 12 end-to-end processes, 162 macro processes with their SIPOC, tasks and steps, the 30 segments, the activation matrix and the standards mapping. Filter by tier, function or E2E process. The BPMN view renders each flow as a BPMN 2.0 diagram.',
    'Le référentiel contient les 12 processus de bout en bout, les 162 macro-processus avec leur SIPOC, tâches et étapes, les 30 segments, la matrice d\'activation et la correspondance des normes. Filtrez par niveau, fonction ou processus E2E. La vue BPMN restitue chaque flux sous forme de diagramme BPMN 2.0.',
    'يضم الكتالوج العمليات الشاملة الاثنتي عشرة و162 عملية كلية مع SIPOC ومهامها وخطواتها، والقطاعات الثلاثين، ومصفوفة التفعيل، ومطابقة المعايير. صفِّ حسب المستوى أو الوظيفة أو العملية الشاملة. يعرض عرض BPMN كل تدفق كمخطط BPMN 2.0.') },
  { id: 'H07', module: 'governance', title: S('Governance: rules, controls, risks, KPIs, RACSI', 'Gouvernance : règles, contrôles, risques, KPI, RACSI', 'الحوكمة: القواعد والضوابط والمخاطر والمؤشرات وRACSI'), body: S(
    'Business rules link a condition to an action. Controls are classified by COSO component. Risks and opportunities use a 5 × 5 likelihood × impact heat map. KPIs have a formula, a target and a frequency. RACSI activities accept exactly one Accountable.',
    'Les règles métier relient une condition à une action. Les contrôles sont classés par composante COSO. Les risques et opportunités utilisent une carte de chaleur 5 × 5 probabilité × impact. Les KPI ont une formule, une cible et une fréquence. Les activités RACSI acceptent exactement une Autorité.',
    'تربط قواعد الأعمال شرطًا بإجراء. تُصنَّف الضوابط حسب مكونات COSO. تستخدم المخاطر والفرص خريطة حرارية 5 × 5 للاحتمالية × الأثر. لكل مؤشر أداء صيغة ومستهدف وتكرار. تقبل أنشطة RACSI مساءَلًا واحدًا فقط.') },
  { id: 'H08', module: 'records', title: S('Nonconformities and corrective actions', 'Non-conformités et actions correctives', 'حالات عدم المطابقة والإجراءات التصحيحية'), body: S(
    'Report a problem to open a nonconformity. It moves through capture, containment, root cause, corrective action, effectiveness check and capitalization. The owner and the evaluator of an action must be different people; the platform refuses the same person in both roles.',
    'Signalez un problème pour ouvrir une non-conformité. Elle passe par la saisie, le confinement, la cause racine, l\'action corrective, la vérification de l\'efficacité et la capitalisation. Le propriétaire et l\'évaluateur d\'une action doivent être des personnes différentes ; la plateforme refuse la même personne dans les deux rôles.',
    'أبلغ عن مشكلة لفتح حالة عدم مطابقة. تمر الحالة بالرصد والاحتواء والسبب الجذري والإجراء التصحيحي والتحقق من الفعالية والاستفادة. يجب أن يختلف مالك الإجراء عن مقيّمه؛ وترفض المنصة إسناد الدورين للشخص نفسه.') },
  { id: 'H09', module: 'records', title: S('Audits and findings', 'Audits et constats', 'التدقيقات والملاحظات'), body: S(
    'Plan internal and certification audits, record findings by clause and link each finding to an action. The audit report can be exported to PDF, Excel or Word.',
    'Planifiez les audits internes et de certification, enregistrez les constats par article et reliez chaque constat à une action. Le rapport d\'audit peut être exporté en PDF, Excel ou Word.',
    'خطط للتدقيقات الداخلية وتدقيقات الاعتماد، وسجّل الملاحظات حسب البند واربط كل ملاحظة بإجراء. يمكن تصدير تقرير التدقيق إلى PDF أو Excel أو Word.') },
  { id: 'H10', module: 'records', title: S('Documents and policies', 'Documents et politiques', 'الوثائق والسياسات'), body: S(
    'Documents follow Draft, In Review, Approved, Published, Superseded and Archived. A QMS project carries a single-standard policy; a QHSE project carries an integrated policy. Every edit creates a new version; history is never deleted and can be compared or reverted.',
    'Les documents suivent les statuts Brouillon, En revue, Approuvé, Publié, Remplacé et Archivé. Un projet SMQ porte une politique mono-norme ; un projet QHSE porte une politique intégrée. Chaque modification crée une nouvelle version ; l\'historique n\'est jamais supprimé et peut être comparé ou restauré.',
    'تمر الوثائق بالحالات: مسودة، قيد المراجعة، معتمد، منشور، مستبدل، مؤرشف. يحمل مشروع نظام إدارة الجودة سياسة أحادية المعيار، ويحمل مشروع الجودة والصحة والسلامة والبيئة سياسة متكاملة. ينشئ كل تعديل إصدارًا جديدًا؛ ولا يُحذف السجل أبدًا ويمكن مقارنته أو الرجوع إليه.') },
  { id: 'H11', module: 'records', title: S('Return on experience (REX)', 'Retour d\'expérience (REX)', 'الدروس المستفادة'), body: S(
    'When you close a nonconformity, an action or a project, the platform proposes a REX entry: what went well, what did not, root cause, recommendation, category and rating. You can skip it and add it later from the REX register. REX entries feed the knowledge base search.',
    'Lorsque vous clôturez une non-conformité, une action ou un projet, la plateforme propose une fiche REX : ce qui a bien fonctionné, ce qui n\'a pas fonctionné, cause racine, recommandation, catégorie et note. Vous pouvez l\'ignorer et l\'ajouter plus tard depuis le registre REX. Les REX alimentent la recherche de la base de connaissances.',
    'عند إغلاق حالة عدم مطابقة أو إجراء أو مشروع، تقترح المنصة إدخال درس مستفاد: ما نجح، وما لم ينجح، والسبب الجذري، والتوصية، والفئة، والتقييم. يمكنك تخطيه وإضافته لاحقًا من سجل الدروس. تغذي الدروس المستفادة البحث في قاعدة المعرفة.') },
  { id: 'H12', module: 'kpi', title: S('KPIs and dashboards', 'KPI et tableaux de bord', 'المؤشرات ولوحات المعلومات'), body: S(
    'The KPI screen lists each indicator with its latest value, target and status colour. Colours follow one scale from red (worst) to dark green (best). Open a KPI to see its 12-month trend and to record a new measurement.',
    'L\'écran KPI liste chaque indicateur avec sa dernière valeur, sa cible et sa couleur de statut. Les couleurs suivent une échelle unique du rouge (moins bon) au vert foncé (meilleur). Ouvrez un KPI pour voir sa tendance sur 12 mois et saisir une nouvelle mesure.',
    'تعرض شاشة المؤشرات كل مؤشر بآخر قيمة ومستهدفه ولون حالته. تتبع الألوان مقياسًا واحدًا من الأحمر (الأسوأ) إلى الأخضر الداكن (الأفضل). افتح مؤشرًا لرؤية اتجاهه على 12 شهرًا وتسجيل قياس جديد.') },
  { id: 'H13', module: 'alerts', title: S('Alerts and notifications', 'Alertes et notifications', 'التنبيهات والإشعارات'), body: S(
    'Alerts are raised by business rules and thresholds (for example a KPI outside tolerance or a critical nonconformity). The bell in the header shows unread alerts. Mark an alert as read or dismiss it. Choose your channels (in-app, e-mail, webhook) per category in Settings.',
    'Les alertes sont levées par les règles métier et les seuils (par exemple un KPI hors tolérance ou une non-conformité critique). La cloche de l\'en-tête indique les alertes non lues. Marquez une alerte comme lue ou masquez-la. Choisissez vos canaux (application, e-mail, webhook) par catégorie dans Paramètres.',
    'تُطلق التنبيهات بواسطة قواعد الأعمال والعتبات (مثل مؤشر خارج التفاوت أو حالة عدم مطابقة حرجة). يعرض الجرس في الترويسة التنبيهات غير المقروءة. ضع علامة مقروء على التنبيه أو أخفه. اختر قنواتك (داخل التطبيق، البريد، webhook) لكل فئة من الإعدادات.') },
  { id: 'H14', module: 'ai', title: S('AI use cases and the AI Assistant', 'Cas d\'usage de l\'IA et assistant IA', 'حالات استخدام الذكاء الاصطناعي والمساعد الذكي'), body: S(
    'AI features are Assistive or Augmented, never autonomous. Every suggestion is labelled as AI-generated and needs your decision: accept, edit or reject. Suggestions are grounded in your own records and the knowledge base, and the references are shown. The AI Assistant answers data questions within your permissions and "How do I…?" questions.',
    'Les fonctions d\'IA sont d\'assistance ou augmentées, jamais autonomes. Chaque suggestion est étiquetée comme générée par l\'IA et requiert votre décision : accepter, modifier ou rejeter. Les suggestions s\'appuient sur vos enregistrements et la base de connaissances, et les références sont affichées. L\'assistant IA répond aux questions sur les données dans la limite de vos autorisations et aux questions « Comment faire… ? ».',
    'ميزات الذكاء الاصطناعي مساعدة أو معززة ولا تكون مستقلة أبدًا. يُوسم كل اقتراح بأنه مولّد بالذكاء الاصطناعي ويتطلب قرارك: قبول أو تعديل أو رفض. تستند الاقتراحات إلى سجلاتك وقاعدة المعرفة مع عرض المراجع. يجيب المساعد الذكي عن أسئلة البيانات ضمن صلاحياتك وعن أسئلة «كيف أفعل…؟».') },
  { id: 'H15', module: 'reports', title: S('Reports and exports', 'Rapports et exports', 'التقارير والتصدير'), body: S(
    'Each standard report can be downloaded as PDF, Excel or Word. File names contain the report key and the date. Tables with an export button download a CSV of exactly the rows and columns on screen.',
    'Chaque rapport standard peut être téléchargé en PDF, Excel ou Word. Les noms de fichiers contiennent la clé du rapport et la date. Les tableaux dotés d\'un bouton d\'export téléchargent un CSV contenant exactement les lignes et colonnes affichées.',
    'يمكن تنزيل كل تقرير قياسي بصيغة PDF أو Excel أو Word. تتضمن أسماء الملفات مفتاح التقرير والتاريخ. تنزّل الجداول المزودة بزر تصدير ملف CSV يطابق الصفوف والأعمدة المعروضة.') },
  { id: 'H16', module: 'benchmark', title: S('Internal benchmarking', 'Benchmarking interne', 'المقارنة المرجعية الداخلية'), body: S(
    'Compare metrics across your projects, or across the organizations of your group using aggregates only. Segments with fewer than 3 records are marked not comparable. An administrator can withdraw the organization from group sharing. No comparison is made with organizations outside the group.',
    'Comparez les indicateurs entre vos projets, ou entre les organisations de votre groupe à partir d\'agrégats uniquement. Les segments de moins de 3 enregistrements sont marqués non comparables. Un administrateur peut retirer l\'organisation du partage de groupe. Aucune comparaison n\'est faite avec des organisations extérieures au groupe.',
    'قارن المقاييس بين مشاريعك أو بين مؤسسات مجموعتك باستخدام المجاميع فقط. تُعلَّم الفئات التي تقل سجلاتها عن 3 بأنها غير قابلة للمقارنة. يمكن للمسؤول سحب المؤسسة من المشاركة مع المجموعة. لا تتم أي مقارنة مع مؤسسات خارج المجموعة.') },
  { id: 'H17', module: 'admin', title: S('Users, roles and the permission matrix', 'Utilisateurs, rôles et matrice des autorisations', 'المستخدمون والأدوار ومصفوفة الصلاحيات'), body: S(
    'Administrators create users and assign one or more roles. The permission matrix shows every permission against every role; changes apply immediately. Screens you cannot open show an access notice that names the missing permission.',
    'Les administrateurs créent les utilisateurs et attribuent un ou plusieurs rôles. La matrice des autorisations affiche chaque autorisation pour chaque rôle ; les modifications s\'appliquent immédiatement. Les écrans inaccessibles affichent un avis d\'accès indiquant l\'autorisation manquante.',
    'ينشئ المسؤولون المستخدمين ويسندون إليهم دورًا أو أكثر. تعرض مصفوفة الصلاحيات كل صلاحية مقابل كل دور؛ وتُطبق التغييرات فورًا. تعرض الشاشات التي لا يمكنك فتحها إشعار وصول يذكر الصلاحية الناقصة.') },
  { id: 'H18', module: 'admin', title: S('Packs, add-ons and compliance standards', 'Packs, options et normes de conformité', 'الحزم والإضافات ومعايير الامتثال'), body: S(
    'An organization has one base pack (SME Essentials, Professional or Enterprise), optional industry and capability packs, add-ons and compliance standards. Features and quotas are checked by the server. Activating a compliance standard seeds starting controls; it is not a certification, an external audit or a legal attestation.',
    'Une organisation dispose d\'un pack de base (Essentiels PME, Professionnel ou Entreprise), de packs sectoriels et de capacité facultatifs, d\'options et de normes de conformité. Les fonctions et quotas sont vérifiés par le serveur. L\'activation d\'une norme de conformité crée des contrôles de départ ; ce n\'est ni une certification, ni un audit externe, ni une attestation juridique.',
    'لدى المؤسسة حزمة أساسية واحدة (أساسيات المؤسسات الصغيرة أو المهنية أو المؤسسية)، وحزم قطاعية وقدرات اختيارية، وإضافات ومعايير امتثال. يتحقق الخادم من الميزات والحصص. يُنشئ تفعيل معيار الامتثال ضوابط ابتدائية؛ وليس شهادة اعتماد ولا تدقيقًا خارجيًا ولا إقرارًا قانونيًا.') },
  { id: 'H19', module: 'admin', title: S('Verticals, SME tracks and complexity scoring', 'Secteurs, parcours PME et score de complexité', 'القطاعات ومسارات المؤسسات الصغيرة ودرجة التعقيد'), body: S(
    'A vertical activates its macro processes and E2E processes by configuration. SME mode offers Light, Standard and Advanced tracks. The complexity score uses weighted criteria that must total 100%; overriding the recommended track needs a written justification.',
    'Un secteur active ses macro-processus et processus E2E par configuration. Le mode PME propose les parcours Léger, Standard et Avancé. Le score de complexité utilise des critères pondérés dont le total doit être de 100 % ; déroger au parcours recommandé exige une justification écrite.',
    'يفعّل القطاع عملياته الكلية والشاملة عبر الإعدادات. يوفر نمط المؤسسات الصغيرة المسارات الخفيف والقياسي والمتقدم. تستخدم درجة التعقيد معايير مرجحة يجب أن يبلغ مجموعها 100%؛ ويتطلب تجاوز المسار الموصى به مبررًا مكتوبًا.') },
  { id: 'H20', module: 'settings', title: S('Language, menu and personal settings', 'Langue, menu et paramètres personnels', 'اللغة والقائمة والإعدادات الشخصية'), body: S(
    'Switch between English, French and Arabic at any time from the header; Arabic mirrors the whole layout. In Settings you can pin the menu or let it slide away, dock it left, right, top or bottom, and mark favourites. These choices follow you on every device.',
    'Passez de l\'anglais au français ou à l\'arabe à tout moment depuis l\'en-tête ; l\'arabe inverse toute la mise en page. Dans Paramètres, vous pouvez épingler le menu ou le laisser se replier, l\'ancrer à gauche, à droite, en haut ou en bas et marquer des favoris. Ces choix vous suivent sur tous vos appareils.',
    'بدّل بين الإنجليزية والفرنسية والعربية في أي وقت من الترويسة؛ وتعكس العربية التخطيط بالكامل. من الإعدادات يمكنك تثبيت القائمة أو جعلها منزلقة، وتثبيتها يسارًا أو يمينًا أو أعلى أو أسفل، وتحديد المفضلة. تتبعك هذه الاختيارات على كل أجهزتك.') },
  { id: 'H21', module: 'admin', title: S('Backups and platform operations', 'Sauvegardes et exploitation', 'النسخ الاحتياطي وعمليات المنصة'), body: S(
    'The server takes a backup every day and keeps it for 14 days. The platform administrator can start a backup on demand and see the list. To restore, stop the server, copy the backup file over data/dynamicms.db and start again; migrations run automatically.',
    'Le serveur effectue une sauvegarde chaque jour et la conserve 14 jours. L\'administrateur de la plateforme peut lancer une sauvegarde à la demande et consulter la liste. Pour restaurer, arrêtez le serveur, copiez le fichier de sauvegarde sur data/dynamicms.db puis redémarrez ; les migrations s\'exécutent automatiquement.',
    'يأخذ الخادم نسخة احتياطية يوميًا ويحتفظ بها 14 يومًا. يمكن لمسؤول المنصة بدء نسخة احتياطية عند الطلب ورؤية القائمة. للاستعادة، أوقف الخادم وانسخ ملف النسخة فوق data/dynamicms.db ثم أعد التشغيل؛ تُنفذ الترحيلات تلقائيًا.') },
  { id: 'H22', module: 'planning', title: S('WBS and Gantt planning', 'OT et planning Gantt', 'هيكل تجزئة العمل ومخطط جانت'), body: S(
    'Group any actions into a work breakdown structure and view it as a Gantt chart. Summary bars recompute from their children. Planned, in-progress, completed and overdue items use distinct styles.',
    'Regroupez des actions dans une organisation du travail (OT) et affichez-la en diagramme de Gantt. Les barres de synthèse se recalculent à partir de leurs enfants. Les éléments planifiés, en cours, terminés et en retard ont des styles distincts.',
    'اجمع أي إجراءات في هيكل تجزئة عمل واعرضه كمخطط جانت. تُعاد حسابات الأشرطة الإجمالية من عناصرها الفرعية. للبنود المخططة وقيد التنفيذ والمكتملة والمتأخرة أنماط مميزة.') },
];

export const FAQ = [
  { q: S('How do I complete a step?', 'Comment terminer une étape ?', 'كيف أُنهي خطوة؟'), a: S('Open Lifecycle, choose the phase and the macro process, open the step, fill the required fields and select Complete step.', 'Ouvrez Cycle de vie, choisissez la phase et le macro-processus, ouvrez l\'étape, renseignez les champs obligatoires puis choisissez Terminer l\'étape.', 'افتح دورة الحياة، واختر المرحلة والعملية الكلية، وافتح الخطوة، واملأ الحقول الإلزامية ثم اختر «إنهاء الخطوة».'), module: 'lifecycle' },
  { q: S('How do I reopen a completed step?', 'Comment rouvrir une étape terminée ?', 'كيف أعيد فتح خطوة مكتملة؟'), a: S('Open the step and select Reopen. Enter a justification; the change is written to the audit trail. Reopening is refused once the phase gate is decided.', 'Ouvrez l\'étape et choisissez Rouvrir. Saisissez une justification ; la modification est inscrite dans la piste d\'audit. La réouverture est refusée une fois le jalon de la phase décidé.', 'افتح الخطوة واختر «إعادة فتح». أدخل مبررًا؛ ويُسجَّل التغيير في سجل التدقيق. تُرفض إعادة الفتح بعد البت في بوابة المرحلة.'), module: 'lifecycle' },
  { q: S('How do I report a problem?', 'Comment signaler un problème ?', 'كيف أبلغ عن مشكلة؟'), a: S('Open Nonconformities and select Report a problem. Enter the title, description, source and criticality. A critical problem raises an alert to the Quality Manager.', 'Ouvrez Non-conformités et choisissez Signaler un problème. Saisissez le titre, la description, la source et la criticité. Un problème critique lève une alerte au responsable qualité.', 'افتح «حالات عدم المطابقة» واختر «الإبلاغ عن مشكلة». أدخل العنوان والوصف والمصدر ودرجة الخطورة. تطلق المشكلة الحرجة تنبيهًا إلى مدير الجودة.'), module: 'records' },
  { q: S('Can the same person own and evaluate an action?', 'La même personne peut-elle porter et évaluer une action ?', 'هل يمكن لشخص واحد أن يملك إجراءً ويقيّمه؟'), a: S('No. The owner and the evaluator must be different users. The server rejects the request otherwise.', 'Non. Le propriétaire et l\'évaluateur doivent être des utilisateurs différents. Sinon le serveur rejette la demande.', 'لا. يجب أن يكون المالك والمقيّم مستخدمَين مختلفين، وإلا يرفض الخادم الطلب.'), module: 'records' },
  { q: S('How do I export a report to Word or PDF?', 'Comment exporter un rapport en Word ou PDF ?', 'كيف أصدّر تقريرًا إلى Word أو PDF؟'), a: S('Open Reports, choose the report and select PDF, Excel or Word. The file downloads with the report key and date in its name.', 'Ouvrez Rapports, choisissez le rapport puis PDF, Excel ou Word. Le fichier est téléchargé avec la clé du rapport et la date dans son nom.', 'افتح «التقارير»، واختر التقرير ثم PDF أو Excel أو Word. يُنزَّل الملف ويتضمن اسمه مفتاح التقرير والتاريخ.'), module: 'reports' },
  { q: S('How do I change the language?', 'Comment changer de langue ?', 'كيف أغيّر اللغة؟'), a: S('Use the language switcher in the header (EN, FR, AR). Your choice is saved for your next sign-in.', 'Utilisez le sélecteur de langue de l\'en-tête (EN, FR, AR). Votre choix est enregistré pour votre prochaine connexion.', 'استخدم محدد اللغة في الترويسة (EN، FR، AR). يُحفظ اختيارك لتسجيل الدخول التالي.'), module: 'settings' },
  { q: S('How do I move the menu to the right or the top?', 'Comment déplacer le menu à droite ou en haut ?', 'كيف أنقل القائمة إلى اليمين أو الأعلى؟'), a: S('Open Settings, then Menu, and choose the dock position. You can also pin or unpin the menu there.', 'Ouvrez Paramètres, puis Menu, et choisissez la position d\'ancrage. Vous pouvez aussi y épingler ou désépingler le menu.', 'افتح «الإعدادات» ثم «القائمة» واختر موضع التثبيت. يمكنك أيضًا تثبيت القائمة أو إلغاء تثبيتها من هناك.'), module: 'settings' },
  { q: S('Does activating ISO 27001 certify my organization?', 'L\'activation d\'ISO 27001 certifie-t-elle mon organisation ?', 'هل يؤدي تفعيل ISO 27001 إلى اعتماد مؤسستي؟'), a: S('No. Activating a compliance standard seeds starting controls. It is not a certification, an external audit or a legal attestation of compliance.', 'Non. L\'activation d\'une norme de conformité crée des contrôles de départ. Ce n\'est ni une certification, ni un audit externe, ni une attestation juridique de conformité.', 'لا. يُنشئ تفعيل معيار الامتثال ضوابط ابتدائية، وليس شهادة اعتماد ولا تدقيقًا خارجيًا ولا إقرارًا قانونيًا بالامتثال.'), module: 'admin' },
  { q: S('How do I create a project with AI?', 'Comment créer un projet avec l\'IA ?', 'كيف أنشئ مشروعًا بالذكاء الاصطناعي؟'), a: S('Open Projects, select New project, then the With AI tab. Describe the project in one or two sentences, review each proposed item and accept or reject it before saving.', 'Ouvrez Projets, choisissez Nouveau projet, puis l\'onglet Avec l\'IA. Décrivez le projet en une ou deux phrases, examinez chaque élément proposé et acceptez-le ou rejetez-le avant d\'enregistrer.', 'افتح «المشاريع» واختر «مشروع جديد» ثم تبويب «بالذكاء الاصطناعي». صف المشروع في جملة أو جملتين، وراجع كل بند مقترح واقبله أو ارفضه قبل الحفظ.'), module: 'projects' },
  { q: S('How do I compare my organization with the group?', 'Comment comparer mon organisation au groupe ?', 'كيف أقارن مؤسستي بالمجموعة؟'), a: S('Open Benchmarking and choose Across the group. Only aggregates are shown; organizations with fewer than 3 projects are not ranked.', 'Ouvrez Benchmarking et choisissez Dans le groupe. Seuls des agrégats sont affichés ; les organisations de moins de 3 projets ne sont pas classées.', 'افتح «المقارنة المرجعية» واختر «عبر المجموعة». تُعرض المجاميع فقط؛ ولا تُرتَّب المؤسسات التي لديها أقل من 3 مشاريع.'), module: 'benchmark' },
  { q: S('Where do I see who changed a record?', 'Où voir qui a modifié un enregistrement ?', 'أين أرى من عدّل سجلًا؟'), a: S('Open Administration, then Audit trail. Each entry shows the user, time, record and the values before and after, with the justification.', 'Ouvrez Administration, puis Piste d\'audit. Chaque entrée indique l\'utilisateur, l\'heure, l\'enregistrement et les valeurs avant et après, avec la justification.', 'افتح «الإدارة» ثم «سجل التدقيق». يعرض كل إدخال المستخدم والوقت والسجل والقيم قبل التغيير وبعده مع المبرر.'), module: 'admin' },
  { q: S('How do I take a backup?', 'Comment faire une sauvegarde ?', 'كيف أنشئ نسخة احتياطية؟'), a: S('As platform administrator, open Administration, then Operations, and select Back up now. From the command line run: npm run backup.', 'En tant qu\'administrateur de la plateforme, ouvrez Administration, puis Exploitation, et choisissez Sauvegarder maintenant. En ligne de commande : npm run backup.', 'بصفتك مسؤول المنصة، افتح «الإدارة» ثم «العمليات» واختر «نسخ احتياطي الآن». ومن سطر الأوامر: npm run backup.'), module: 'admin' },
];
