// Standards Knowledge Base: short, plain-language summaries of the standards most
// used by the seeded runs, with their key clauses. Used by the Knowledge Base screen
// and by the AI Assistant's retrieval (FR-DA-KB-01, FR-DA-AST-02). Summaries are
// written for orientation; they do not reproduce the standards' text.
const S = (en, fr, ar) => ({ en, fr, ar });
const C = (id, en, fr, ar) => ({ id, title: S(en, fr, ar) });

export const KB = [
  { id: 'KB-9001', standard: 'ISO 9001:2015', family: 'QMS', title: S('ISO 9001 — Quality management systems', 'ISO 9001 — Systèmes de management de la qualité', 'ISO 9001 — أنظمة إدارة الجودة'),
    summary: S('Sets requirements for a quality management system that consistently delivers conforming products and services and improves customer satisfaction. Built on the process approach, risk-based thinking and the Plan-Do-Check-Act cycle.',
      'Définit les exigences d\'un système de management de la qualité qui fournit de façon constante des produits et services conformes et améliore la satisfaction des clients. Repose sur l\'approche processus, l\'approche par les risques et le cycle PDCA.',
      'يحدد متطلبات نظام إدارة جودة يقدّم باستمرار منتجات وخدمات مطابقة ويحسّن رضا العملاء، ويقوم على نهج العمليات والتفكير القائم على المخاطر ودورة التخطيط والتنفيذ والتحقق والتصرف.'),
    clauses: [C('4', 'Context of the organization', 'Contexte de l\'organisme', 'سياق المؤسسة'), C('5', 'Leadership', 'Leadership', 'القيادة'), C('6', 'Planning', 'Planification', 'التخطيط'), C('7', 'Support', 'Support', 'الدعم'), C('8', 'Operation', 'Réalisation des activités opérationnelles', 'التشغيل'), C('9', 'Performance evaluation', 'Évaluation des performances', 'تقييم الأداء'), C('10', 'Improvement', 'Amélioration', 'التحسين')],
    e2e: ['E2E-01', 'E2E-02', 'E2E-04', 'E2E-05', 'E2E-08', 'E2E-09', 'E2E-10'] },
  { id: 'KB-14001', standard: 'ISO 14001:2015', family: 'EMS', title: S('ISO 14001 — Environmental management systems', 'ISO 14001 — Systèmes de management environnemental', 'ISO 14001 — أنظمة الإدارة البيئية'),
    summary: S('Helps an organization manage its environmental aspects, fulfil compliance obligations and address risks and opportunities, with a life-cycle perspective and a commitment to prevent pollution.',
      'Aide l\'organisme à maîtriser ses aspects environnementaux, à respecter ses obligations de conformité et à traiter risques et opportunités, dans une perspective de cycle de vie et avec un engagement de prévention de la pollution.',
      'يساعد المؤسسة على إدارة جوانبها البيئية والوفاء بالتزامات الامتثال ومعالجة المخاطر والفرص، من منظور دورة الحياة مع الالتزام بمنع التلوث.'),
    clauses: [C('6.1.2', 'Environmental aspects', 'Aspects environnementaux', 'الجوانب البيئية'), C('6.1.3', 'Compliance obligations', 'Obligations de conformité', 'التزامات الامتثال'), C('8.1', 'Operational planning and control', 'Planification et maîtrise opérationnelles', 'التخطيط والضبط التشغيلي'), C('8.2', 'Emergency preparedness and response', 'Préparation et réponse aux situations d\'urgence', 'التأهب والاستجابة للطوارئ'), C('9.1.2', 'Evaluation of compliance', 'Évaluation de la conformité', 'تقييم الامتثال')],
    e2e: ['E2E-01', 'E2E-03', 'E2E-08', 'E2E-11'] },
  { id: 'KB-45001', standard: 'ISO 45001:2018', family: 'OHSMS', title: S('ISO 45001 — Occupational health and safety', 'ISO 45001 — Santé et sécurité au travail', 'ISO 45001 — الصحة والسلامة المهنية'),
    summary: S('Provides a framework to prevent work-related injury and ill health and to provide safe and healthy workplaces, with worker consultation and participation at its core.',
      'Fournit un cadre pour prévenir les traumatismes et pathologies liés au travail et offrir des lieux de travail sûrs et sains, avec la consultation et la participation des travailleurs au cœur du système.',
      'يوفر إطارًا لمنع الإصابات والأمراض المرتبطة بالعمل وتوفير أماكن عمل آمنة وصحية، مع جعل استشارة العاملين ومشاركتهم في صميم النظام.'),
    clauses: [C('5.4', 'Consultation and participation of workers', 'Consultation et participation des travailleurs', 'استشارة العاملين ومشاركتهم'), C('6.1.2', 'Hazard identification and assessment of risks', 'Identification des dangers et évaluation des risques', 'تحديد المخاطر وتقييمها'), C('8.1.2', 'Eliminating hazards and reducing OH&S risks', 'Élimination des dangers et réduction des risques', 'إزالة المخاطر وتقليلها'), C('8.2', 'Emergency preparedness and response', 'Préparation et réponse aux situations d\'urgence', 'التأهب والاستجابة للطوارئ'), C('10.2', 'Incident, nonconformity and corrective action', 'Événements indésirables, non-conformités et actions correctives', 'الحوادث وعدم المطابقة والإجراءات التصحيحية')],
    e2e: ['E2E-01', 'E2E-03', 'E2E-09'] },
  { id: 'KB-19011', standard: 'ISO 19011:2018', family: 'Audit', title: S('ISO 19011 — Guidelines for auditing management systems', 'ISO 19011 — Lignes directrices pour l\'audit des systèmes de management', 'ISO 19011 — إرشادات تدقيق أنظمة الإدارة'),
    summary: S('Guides the management of an audit programme, the conduct of audits and the competence of auditors. Used to qualify internal auditors and plan the internal audit cycle.',
      'Guide la gestion d\'un programme d\'audit, la réalisation des audits et la compétence des auditeurs. Sert à qualifier les auditeurs internes et à planifier le cycle d\'audit interne.',
      'يرشد إدارة برنامج التدقيق وإجراء التدقيقات وكفاءة المدققين، ويُستخدم لتأهيل المدققين الداخليين وتخطيط دورة التدقيق الداخلي.'),
    clauses: [C('5', 'Managing an audit programme', 'Management d\'un programme d\'audit', 'إدارة برنامج التدقيق'), C('6', 'Conducting an audit', 'Réalisation d\'un audit', 'إجراء التدقيق'), C('7', 'Competence of auditors', 'Compétence des auditeurs', 'كفاءة المدققين')],
    e2e: ['E2E-02', 'E2E-04', 'E2E-10'] },
  { id: 'KB-31000', standard: 'ISO 31000:2018', family: 'Risk', title: S('ISO 31000 — Risk management guidelines', 'ISO 31000 — Management du risque', 'ISO 31000 — إرشادات إدارة المخاطر'),
    summary: S('Describes principles, a framework and a process to identify, analyse, evaluate and treat risks, and to monitor and communicate about them.',
      'Décrit des principes, un cadre et un processus pour identifier, analyser, évaluer et traiter les risques, puis les surveiller et en communiquer.',
      'يصف المبادئ والإطار والعملية لتحديد المخاطر وتحليلها وتقييمها ومعالجتها ثم مراقبتها والتواصل بشأنها.'),
    clauses: [C('6.4', 'Risk assessment', 'Appréciation du risque', 'تقييم المخاطر'), C('6.5', 'Risk treatment', 'Traitement du risque', 'معالجة المخاطر'), C('6.6', 'Monitoring and review', 'Suivi et revue', 'المراقبة والمراجعة')],
    e2e: ['E2E-01', 'E2E-03'] },
  { id: 'KB-IATF', standard: 'IATF 16949:2016', family: 'Sector', title: S('IATF 16949 — Automotive quality', 'IATF 16949 — Qualité automobile', 'IATF 16949 — جودة قطاع السيارات'),
    summary: S('Adds automotive requirements to ISO 9001: product safety, PPAP, control plans, layered process audits, supplier development and customer-specific requirements.',
      'Ajoute les exigences automobiles à l\'ISO 9001 : sécurité produit, PPAP, plans de surveillance, audits LPA, développement des fournisseurs et exigences spécifiques clients.',
      'يضيف متطلبات قطاع السيارات إلى ISO 9001: سلامة المنتج وPPAP وخطط الضبط والتدقيقات متعددة المستويات وتطوير الموردين ومتطلبات العملاء الخاصة.'),
    clauses: [C('8.3.4.4', 'Product approval process (PPAP)', 'Processus d\'homologation produit (PPAP)', 'عملية اعتماد المنتج (PPAP)'), C('8.5.1.1', 'Control plan', 'Plan de surveillance', 'خطة الضبط'), C('9.2.2.3', 'Manufacturing process audit', 'Audit du processus de fabrication', 'تدقيق عملية التصنيع')], e2e: ['E2E-08'] },
  { id: 'KB-AS9100', standard: 'AS9100D', family: 'Sector', title: S('AS9100D — Aviation, space and defence quality', 'AS9100D — Qualité aéronautique, spatiale et défense', 'AS9100D — جودة الطيران والفضاء والدفاع'),
    summary: S('Extends ISO 9001 with configuration management, first article inspection, counterfeit part prevention, FOD prevention and special process control.',
      'Étend l\'ISO 9001 avec la gestion de configuration, l\'inspection premier article, la prévention des pièces contrefaites, la prévention des corps étrangers et la maîtrise des procédés spéciaux.',
      'يوسّع ISO 9001 بإدارة التهيئة وفحص القطعة الأولى ومنع القطع المقلدة ومنع الأجسام الغريبة وضبط العمليات الخاصة.'),
    clauses: [C('8.1.2', 'Configuration management', 'Gestion de configuration', 'إدارة التهيئة'), C('8.1.4', 'Prevention of counterfeit parts', 'Prévention des pièces contrefaites', 'منع القطع المقلدة'), C('8.5.1.3', 'Production process verification (FAI)', 'Vérification du processus de production (FAI)', 'التحقق من عملية الإنتاج (FAI)')], e2e: ['E2E-08'] },
  { id: 'KB-13485', standard: 'ISO 13485:2016', family: 'Sector', title: S('ISO 13485 — Medical devices quality', 'ISO 13485 — Qualité des dispositifs médicaux', 'ISO 13485 — جودة الأجهزة الطبية'),
    summary: S('Quality management requirements for medical devices across design, production, sterilization, traceability and post-market surveillance, with risk management per ISO 14971.',
      'Exigences qualité pour les dispositifs médicaux : conception, production, stérilisation, traçabilité et surveillance après commercialisation, avec gestion des risques selon l\'ISO 14971.',
      'متطلبات إدارة الجودة للأجهزة الطبية عبر التصميم والإنتاج والتعقيم والتتبع والمراقبة بعد التسويق، مع إدارة المخاطر وفق ISO 14971.'),
    clauses: [C('7.3', 'Design and development', 'Conception et développement', 'التصميم والتطوير'), C('7.5.8', 'Identification and traceability', 'Identification et traçabilité', 'التعريف والتتبع'), C('8.2.1', 'Feedback and post-market surveillance', 'Retour d\'information et surveillance après commercialisation', 'التغذية الراجعة والمراقبة بعد التسويق')], e2e: ['E2E-08', 'E2E-09'] },
  { id: 'KB-22000', standard: 'ISO 22000 / FSSC 22000', family: 'Sector', title: S('ISO 22000 — Food safety management', 'ISO 22000 — Management de la sécurité des denrées alimentaires', 'ISO 22000 — إدارة سلامة الأغذية'),
    summary: S('Combines HACCP principles, prerequisite programmes and interactive communication along the food chain to control food safety hazards.',
      'Associe les principes HACCP, les programmes prérequis et la communication interactive le long de la chaîne alimentaire pour maîtriser les dangers.',
      'يجمع مبادئ HACCP والبرامج الأساسية والتواصل التفاعلي على طول السلسلة الغذائية لضبط مخاطر سلامة الأغذية.'),
    clauses: [C('8.2', 'Prerequisite programmes', 'Programmes prérequis', 'البرامج الأساسية'), C('8.5', 'Hazard control (HACCP plan)', 'Maîtrise des dangers (plan HACCP)', 'ضبط المخاطر (خطة HACCP)'), C('8.9', 'Control of nonconformities', 'Maîtrise des non-conformités', 'ضبط حالات عدم المطابقة')], e2e: ['E2E-08'] },
  { id: 'KB-27001', standard: 'ISO/IEC 27001:2022', family: 'ISMS', title: S('ISO/IEC 27001 — Information security', 'ISO/IEC 27001 — Sécurité de l\'information', 'ISO/IEC 27001 — أمن المعلومات'),
    summary: S('Requirements for an information security management system: risk assessment, statement of applicability and Annex A controls for organizational, people, physical and technological security.',
      'Exigences d\'un système de management de la sécurité de l\'information : appréciation des risques, déclaration d\'applicabilité et mesures de l\'annexe A.',
      'متطلبات نظام إدارة أمن المعلومات: تقييم المخاطر وبيان قابلية التطبيق وضوابط الملحق (أ).'),
    clauses: [C('6.1.2', 'Information security risk assessment', 'Appréciation des risques de sécurité', 'تقييم مخاطر أمن المعلومات'), C('6.1.3', 'Statement of applicability', 'Déclaration d\'applicabilité', 'بيان قابلية التطبيق'), C('A.5.15', 'Access control', 'Contrôle d\'accès', 'ضبط الوصول')], e2e: ['E2E-06'] },
  { id: 'KB-19650', standard: 'ISO 19650', family: 'Sector', title: S('ISO 19650 — Information management using BIM', 'ISO 19650 — Gestion de l\'information par le BIM', 'ISO 19650 — إدارة المعلومات باستخدام BIM'),
    summary: S('Defines how information is managed over the life of built assets with BIM: information requirements, BIM execution plan, common data environment and delivery milestones.',
      'Définit la gestion de l\'information sur le cycle de vie des ouvrages avec le BIM : exigences d\'information, plan d\'exécution BIM, environnement commun de données et jalons de livraison.',
      'يحدد كيفية إدارة المعلومات طوال عمر الأصول المبنية باستخدام BIM: متطلبات المعلومات وخطة تنفيذ BIM وبيئة البيانات المشتركة ومراحل التسليم.'),
    clauses: [C('5.3', 'Exchange information requirements', 'Exigences d\'échange d\'information', 'متطلبات تبادل المعلومات'), C('5.4', 'BIM execution plan', 'Plan d\'exécution BIM', 'خطة تنفيذ BIM'), C('5.6', 'Collaborative production of information', 'Production collaborative de l\'information', 'الإنتاج التعاوني للمعلومات')], e2e: ['E2E-05', 'E2E-08'] },
  { id: 'KB-1090', standard: 'EN 1090', family: 'Sector', title: S('EN 1090 — Execution of steel and aluminium structures', 'EN 1090 — Exécution des structures en acier et aluminium', 'EN 1090 — تنفيذ الهياكل الفولاذية والألمنيوم'),
    summary: S('Requires factory production control, welding coordination and execution classes (EXC1–EXC4) for CE marking of structural components.',
      'Exige un contrôle de la production en usine, une coordination en soudage et des classes d\'exécution (EXC1–EXC4) pour le marquage CE des composants structuraux.',
      'يتطلب ضبط الإنتاج في المصنع وتنسيق اللحام وفئات التنفيذ (EXC1–EXC4) لوضع علامة CE على المكونات الإنشائية.'),
    clauses: [C('FPC', 'Factory production control', 'Contrôle de la production en usine', 'ضبط الإنتاج في المصنع'), C('EXC', 'Execution classes', 'Classes d\'exécution', 'فئات التنفيذ'), C('WPQR', 'Welding procedure qualification', 'Qualification des modes opératoires de soudage', 'تأهيل إجراءات اللحام')], e2e: ['E2E-08'] },
  { id: 'KB-GMP', standard: 'EU GMP / ICH Q10', family: 'Sector', title: S('GMP and ICH Q10 — Pharmaceutical quality system', 'BPF et ICH Q10 — Système qualité pharmaceutique', 'ممارسات التصنيع الجيدة وICH Q10 — نظام الجودة الدوائي'),
    summary: S('Good manufacturing practice with a pharmaceutical quality system covering change control, CAPA, deviation management, data integrity (ALCOA+) and management review.',
      'Bonnes pratiques de fabrication avec un système qualité pharmaceutique couvrant la maîtrise des changements, les CAPA, les déviations, l\'intégrité des données (ALCOA+) et la revue de direction.',
      'ممارسات التصنيع الجيدة مع نظام جودة دوائي يشمل ضبط التغيير والإجراءات التصحيحية والوقائية وإدارة الانحرافات وسلامة البيانات (ALCOA+) ومراجعة الإدارة.'),
    clauses: [C('3.2.2', 'CAPA system', 'Système CAPA', 'نظام الإجراءات التصحيحية والوقائية'), C('3.2.3', 'Change management', 'Maîtrise des changements', 'إدارة التغيير'), C('Annex 1', 'Sterile manufacturing and cleanrooms', 'Fabrication stérile et salles propres', 'التصنيع المعقم والغرف النظيفة')], e2e: ['E2E-08', 'E2E-09'] },
  { id: 'KB-21001', standard: 'ISO 21001:2018', family: 'Sector', title: S('ISO 21001 — Educational organizations', 'ISO 21001 — Organismes d\'éducation', 'ISO 21001 — المؤسسات التعليمية'),
    summary: S('Management system for educational organizations focused on learner and beneficiary satisfaction, accessible learning and equitable assessment.',
      'Système de management des organismes d\'éducation centré sur la satisfaction des apprenants et bénéficiaires, l\'accessibilité et l\'équité de l\'évaluation.',
      'نظام إدارة للمؤسسات التعليمية يركز على رضا المتعلمين والمستفيدين وإتاحة التعلم وعدالة التقييم.'),
    clauses: [C('8.3', 'Design and development of educational products', 'Conception des produits éducatifs', 'تصميم المنتجات التعليمية'), C('8.5.1', 'Delivery of educational services', 'Prestation des services éducatifs', 'تقديم الخدمات التعليمية')], e2e: ['E2E-08'] },
  { id: 'KB-SA8000', standard: 'SA8000 / ISO 26000', family: 'Social', title: S('SA8000 and ISO 26000 — Social responsibility', 'SA8000 et ISO 26000 — Responsabilité sociétale', 'SA8000 وISO 26000 — المسؤولية الاجتماعية'),
    summary: S('SA8000 sets auditable requirements on child labour, forced labour, health and safety, working hours and wages; ISO 26000 gives guidance on social responsibility themes.',
      'SA8000 fixe des exigences auditables sur le travail des enfants, le travail forcé, la santé-sécurité, la durée du travail et les salaires ; l\'ISO 26000 donne des lignes directrices sur la responsabilité sociétale.',
      'يضع SA8000 متطلبات قابلة للتدقيق بشأن عمل الأطفال والعمل القسري والصحة والسلامة وساعات العمل والأجور، ويقدم ISO 26000 إرشادات حول المسؤولية الاجتماعية.'),
    clauses: [C('1', 'Child labour', 'Travail des enfants', 'عمل الأطفال'), C('3', 'Health and safety', 'Santé et sécurité', 'الصحة والسلامة'), C('8', 'Remuneration', 'Rémunération', 'الأجور')], e2e: ['E2E-04'] },
  { id: 'KB-PDCA', standard: 'PDCA / HLS', family: 'Method', title: S('Harmonized structure and the PDCA cycle', 'Structure harmonisée et cycle PDCA', 'الهيكل الموحد ودورة PDCA'),
    summary: S('ISO management system standards share one harmonized structure (clauses 4 to 10). An integrated QHSE system runs one context analysis, one policy, one risk register, one audit programme and one management review for all standards in scope.',
      'Les normes de systèmes de management ISO partagent une structure harmonisée (chapitres 4 à 10). Un système QHSE intégré conduit une seule analyse du contexte, une politique, un registre des risques, un programme d\'audit et une revue de direction pour toutes les normes du périmètre.',
      'تشترك معايير أنظمة الإدارة من ISO في هيكل موحد (البنود 4 إلى 10). ويُجري النظام المتكامل للجودة والصحة والسلامة والبيئة تحليل سياق واحدًا وسياسة واحدة وسجل مخاطر واحدًا وبرنامج تدقيق واحدًا ومراجعة إدارة واحدة لجميع المعايير ضمن النطاق.'),
    clauses: [C('Plan', 'Clauses 4–7', 'Chapitres 4–7', 'البنود 4–7'), C('Do', 'Clause 8', 'Chapitre 8', 'البند 8'), C('Check', 'Clause 9', 'Chapitre 9', 'البند 9'), C('Act', 'Clause 10', 'Chapitre 10', 'البند 10')], e2e: ['E2E-01', 'E2E-10', 'E2E-12'] },
];
