// Localized labels for status and code values stored as stable English codes.
const L = (en, fr, ar) => ({ en, fr, ar });
export const LABELS = {
  // step / process / phase statuses
  Done: L('Done', 'Terminée', 'منجزة'), InProgress: L('In progress', 'En cours', 'قيد التنفيذ'), Todo: L('To do', 'À faire', 'للتنفيذ'),
  Completed: L('Completed', 'Terminé', 'مكتمل'), NotStarted: L('Not started', 'Non démarré', 'لم يبدأ'),
  Closed: L('Closed', 'Clôturé', 'مغلق'), Active: L('Active', 'Actif', 'نشط'), Planned: L('Planned', 'Planifié', 'مخطط'), AtGate: L('At gate', 'Au jalon', 'عند البوابة'), OnHold: L('On hold', 'En attente', 'معلّق'),
  'In progress': L('In progress', 'En cours', 'قيد التنفيذ'), 'At gate': L('At gate', 'Au jalon', 'عند البوابة'), 'On hold': L('On hold', 'En attente', 'معلّق'), 'Not started': L('Not started', 'Non démarré', 'لم يبدأ'), 'Not applicable': L('Not applicable', 'Sans objet', 'غير منطبق'), Stopped: L('Stopped', 'Arrêté', 'متوقف'),
  Go: L('Go', 'Go', 'المضي'), 'No-Go': L('No-Go', 'No-Go', 'عدم المضي'), Hold: L('Hold', 'En attente', 'تعليق'),
  // records
  Open: L('Open', 'Ouverte', 'مفتوح'), Analysis: L('Analysis', 'Analyse', 'التحليل'), Action: L('Action', 'Action', 'الإجراء'), Verification: L('Verification', 'Vérification', 'التحقق'),
  Minor: L('Minor', 'Mineure', 'ثانوية'), Major: L('Major', 'Majeure', 'رئيسية'), Critical: L('Critical', 'Critique', 'حرجة'),
  High: L('High', 'Élevée', 'مرتفعة'), Medium: L('Medium', 'Moyenne', 'متوسطة'), Low: L('Low', 'Faible', 'منخفضة'),
  Customer: L('Customer', 'Client', 'العميل'), Audit: L('Audit', 'Audit', 'التدقيق'), Process: L('Process', 'Processus', 'العملية'), Supplier: L('Supplier', 'Fournisseur', 'المورد'), Incident: L('Incident', 'Incident', 'حادث'),
  Product: L('Product', 'Produit', 'المنتج'), Metrology: L('Metrology', 'Métrologie', 'القياس'), Documentation: L('Documentation', 'Documentation', 'التوثيق'), Competence: L('Competence', 'Compétence', 'الكفاءة'), 'OH&S': L('OH&S', 'SST', 'الصحة والسلامة المهنية'), Environment: L('Environment', 'Environnement', 'البيئة'),
  Containment: L('Containment', 'Confinement', 'احتواء'), Corrective: L('Corrective', 'Corrective', 'تصحيحي'), Preventive: L('Preventive', 'Préventive', 'وقائي'), Treatment: L('Treatment', 'Traitement', 'معالجة'), Improvement: L('Improvement', 'Amélioration', 'تحسين'),
  Effective: L('Effective', 'Efficace', 'فعّال'), 'Partially effective': L('Partially effective', 'Partiellement efficace', 'فعّال جزئيًا'), 'Not effective': L('Not effective', 'Inefficace', 'غير فعّال'),
  Internal: L('Internal', 'Interne', 'داخلي'), Mock: L('Mock', 'À blanc', 'تجريبي'), Certification: L('Certification', 'Certification', 'الاعتماد'), Surveillance: L('Surveillance', 'Surveillance', 'المتابعة'),
  Observation: L('Observation', 'Observation', 'ملاحظة'), OFI: L('Opportunity for improvement', 'Piste d\'amélioration', 'فرصة للتحسين'), Noted: L('Noted', 'Pris en compte', 'مسجلة'),
  Published: L('Published', 'Publié', 'منشور'), Draft: L('Draft', 'Brouillon', 'مسودة'), 'In review': L('In review', 'En revue', 'قيد المراجعة'), Superseded: L('Superseded', 'Remplacé', 'مستبدل'), Retired: L('Retired', 'Retiré', 'متقاعد'),
  Policy: L('Policy', 'Politique', 'سياسة'), Manual: L('Manual', 'Manuel', 'دليل'), Procedure: L('Procedure', 'Procédure', 'إجراء'), Sheet: L('Process sheet', 'Fiche processus', 'بطاقة عملية'), Map: L('Process map', 'Cartographie', 'خريطة'), Plan: L('Plan', 'Plan', 'خطة'), Register: L('Register', 'Registre', 'سجل'),
  Risk: L('Risk', 'Risque', 'مخاطرة'), Opportunity: L('Opportunity', 'Opportunité', 'فرصة'), Hazard: L('Hazard', 'Danger', 'خطر'), Aspect: L('Aspect', 'Aspect', 'جانب بيئي'),
  Treated: L('Treated', 'Traité', 'معالج'), Monitoring: L('Monitoring', 'Sous surveillance', 'تحت المراقبة'),
  'On track': L('On track', 'Dans les temps', 'في المسار'), 'At risk': L('At risk', 'À risque', 'معرّض للخطر'),
  Valid: L('Valid', 'Valide', 'ساري'), Overdue: L('Overdue', 'Échu', 'متأخر'), Approved: L('Approved', 'Approuvé', 'معتمد'), Conditional: L('Conditional', 'Sous condition', 'مشروط'), 'Under review': L('Under review', 'En évaluation', 'قيد التقييم'),
  Implemented: L('Implemented', 'Mise en œuvre', 'منفّذة'), Proposed: L('Proposed', 'Proposée', 'مقترحة'), Held: L('Held', 'Tenue', 'منعقدة'),
  Accepted: L('Accepted', 'Acceptée', 'مقبول'), Edited: L('Edited', 'Modifiée', 'معدَّل'), Rejected: L('Rejected', 'Rejetée', 'مرفوض'), Pending: L('Pending', 'En attente', 'معلّق'),
  Assistive: L('Assistive', 'Assistance', 'مساعد'), Augmented: L('Augmented', 'Augmentée', 'معزز'),
  QMS: L('QMS', 'SMQ', 'نظام إدارة الجودة'), QHSE: L('QHSE', 'QHSE', 'الجودة والصحة والسلامة والبيئة'), FULL: L('Full lifecycle', 'Cycle complet', 'دورة كاملة'), SME: L('SME', 'PME', 'مؤسسة صغيرة ومتوسطة'),
  'TRK-LIGHT': L('Light track', 'Parcours léger', 'المسار الخفيف'), 'TRK-STANDARD': L('Standard track', 'Parcours standard', 'المسار القياسي'), 'TRK-ADVANCED': L('Advanced track', 'Parcours avancé', 'المسار المتقدم'),
  Inherit: L('Inherit', 'Hériter', 'وراثة'), Inactive: L('Inactive', 'Inactif', 'غير نشط'),
  Large: L('Large', 'Grande entreprise', 'مؤسسة كبيرة'),
  Annual: L('Annual', 'Annuel', 'سنوي'), 'Semi-annual': L('Semi-annual', 'Semestriel', 'نصف سنوي'), Quarterly: L('Quarterly', 'Trimestriel', 'ربع سنوي'), Monthly: L('Monthly', 'Mensuel', 'شهري'), Weekly: L('Weekly', 'Hebdomadaire', 'أسبوعي'), Daily: L('Daily', 'Quotidien', 'يومي'), 'Per event': L('Per event', 'À chaque événement', 'عند كل حدث'), 'Every 2 years': L('Every 2 years', 'Tous les 2 ans', 'كل سنتين'), 'Every 3 years': L('Every 3 years', 'Tous les 3 ans', 'كل 3 سنوات'), Custom: L('Custom', 'Personnalisée', 'مخصص'),
  Intranet: L('Intranet', 'Intranet', 'الشبكة الداخلية'), 'E-mail': L('E-mail', 'E-mail', 'البريد الإلكتروني'), Meeting: L('Meeting', 'Réunion', 'اجتماع'), 'Notice board': L('Notice board', 'Panneau d\'affichage', 'لوحة الإعلانات'), Portal: L('Portal', 'Portail', 'البوابة'),
  Validation: L('Validation', 'Validation', 'التحقق'), Notification: L('Notification', 'Notification', 'إشعار'), Escalation: L('Escalation', 'Escalade', 'تصعيد'), Calculation: L('Calculation', 'Calcul', 'حساب'),
  Detective: L('Detective', 'Détective', 'كشفي'), Manual: L('Manual', 'Manuel', 'يدوي'), Automated: L('Automated', 'Automatisé', 'آلي'),
  'Control Activities': L('Control activities', 'Activités de contrôle', 'أنشطة الرقابة'), 'Control Environment': L('Control environment', 'Environnement de contrôle', 'بيئة الرقابة'), 'Risk Assessment': L('Risk assessment', 'Évaluation des risques', 'تقييم المخاطر'), 'Information & Communication': L('Information and communication', 'Information et communication', 'المعلومات والتواصل'), 'Monitoring Activities': L('Monitoring activities', 'Activités de pilotage', 'أنشطة المتابعة'),
  'Not tested': L('Not tested', 'Non testé', 'لم يُختبر'), 'Needs improvement': L('Needs improvement', 'À améliorer', 'يحتاج إلى تحسين'),
  Disabled: L('Disabled', 'Désactivé', 'معطّل'), Failed: L('Failed', 'Échec', 'فشل'), OK: L('OK', 'OK', 'سليم'), Delivered: L('Delivered', 'Délivré', 'تم التسليم'), Queued: L('Queued', 'En file', 'في الانتظار'),
  Organization: L('Organization', 'Organisation', 'مؤسسة'), Site: L('Site', 'Site', 'موقع'), Department: L('Department', 'Service', 'قسم'), Project: L('Project', 'Projet', 'مشروع'),
  catalog: L('From the catalog', 'Depuis le catalogue', 'من الكتالوج'), manual: L('Manual', 'Manuelle', 'يدوي'), ai: L('With AI', 'Avec l\'IA', 'بالذكاء الاصطناعي'),
  universal: L('Universal', 'Universel', 'عام'), vertical: L('Vertical', 'Sectoriel', 'قطاعي'), Small: L('Small', 'Petite', 'صغيرة'), Medium: L('Medium', 'Moyenne', 'متوسطة'), Micro: L('Micro', 'Micro', 'صغرى'),
  // step form options and document types added with the structured forms
  Yes: L('Yes', 'Oui', 'نعم'), No: L('No', 'Non', 'لا'), Partly: L('Partly', 'Partiellement', 'جزئيًا'),
  'Single-standard': L('Single standard', 'Norme unique', 'معيار واحد'), Integrated: L('Integrated', 'Intégré', 'متكامل'),
  Quiz: L('Quiz', 'Quiz', 'اختبار قصير'), 'On-the-job observation': L('On-the-job observation', 'Observation au poste', 'الملاحظة في موقع العمل'), 'Supervisor assessment': L('Supervisor assessment', 'Évaluation par le responsable', 'تقييم المشرف'), 'Practical test': L('Practical test', 'Test pratique', 'اختبار عملي'),
  'Review decision': L('Review decision', 'Décision de revue', 'قرار مراجعة'), 'Per event': L('Per event', 'Par événement', 'عند كل حدث'),
  Scope: L('Scope', 'Périmètre', 'النطاق'), Instruction: L('Work instruction', 'Instruction de travail', 'تعليمات العمل'), Report: L('Report', 'Rapport', 'تقرير'), Matrix: L('Matrix', 'Matrice', 'مصفوفة'),
  Site: L('Site', 'Site', 'الموقع'), Department: L('Department', 'Service', 'القسم'), Organization: L('Organization', 'Organisation', 'المؤسسة'), Project: L('Project', 'Projet', 'المشروع'),
  Weekly: L('Weekly', 'Hebdomadaire', 'أسبوعي'),
};
export const label = (code, lang) => (LABELS[code] ? LABELS[code][lang] ?? LABELS[code].en : code);
