// Registers kept per project, with the label of each field (trilingual). The first fields
// listed are the columns of the register table; the others show in the entry details.
const L = (en, fr, ar) => ({ en, fr, ar });
const f = (key, en, fr, ar, type) => ({ key, label: L(en, fr, ar), ...(type ? { type } : {}) });
const owner = f('owner', 'Owner', 'Responsable', 'المسؤول', 'role');
const date = f('date', 'Date', 'Date', 'التاريخ', 'date');

export const REGISTER_DEFS = [
  { key: 'context', name: L('Context issues', 'Enjeux du contexte', 'قضايا السياق'), fields: [f('type', 'Type', 'Type', 'النوع'), f('category', 'Category', 'Catégorie', 'الفئة'), f('impact', 'Impact (1–5)', 'Impact (1–5)', 'الأثر (1–5)')] },
  { key: 'parties', name: L('Interested parties', 'Parties intéressées', 'الأطراف المعنية'), fields: [f('needs', 'Needs and expectations', 'Besoins et attentes', 'الاحتياجات والتوقعات'), f('influence', 'Influence', 'Influence', 'النفوذ'), f('interest', 'Interest', 'Intérêt', 'الاهتمام')] },
  { key: 'objectives', name: L('Objectives', 'Objectifs', 'الأهداف'), fields: [f('kpi', 'KPI', 'KPI', 'المؤشر'), f('baseline', 'Baseline', 'Référence', 'خط الأساس'), f('target', 'Target', 'Cible', 'المستهدف'), f('current', 'Current value', 'Valeur actuelle', 'القيمة الحالية'), f('deadline', 'Deadline', 'Échéance', 'الموعد النهائي', 'date'), f('relevance', 'Policy axis', 'Axe de la politique', 'محور السياسة'), f('resources', 'Resources', 'Ressources', 'الموارد')] },
  { key: 'obligations', name: L('Compliance obligations', 'Obligations de conformité', 'التزامات الامتثال'), fields: [f('type', 'Type', 'Type', 'النوع'), f('reference', 'Reference', 'Référence', 'المرجع'), f('evaluation', 'Evaluation', 'Évaluation', 'التقييم'), f('lastEvaluated', 'Last evaluated', 'Dernière évaluation', 'آخر تقييم', 'date'), f('nextEvaluation', 'Next evaluation', 'Prochaine évaluation', 'التقييم التالي', 'date'), owner, f('authority', 'Source / authority', 'Source / autorité', 'المصدر / الجهة'), f('applicability', 'Applies to', 'S\'applique à', 'ينطبق على'), f('requirement', 'Requirement', 'Exigence', 'المتطلب'), f('compliance', 'How complied', 'Mode de conformité', 'طريقة الامتثال'), f('frequencyMonths', 'Evaluation interval (months)', 'Périodicité d\'évaluation (mois)', 'فترة التقييم (أشهر)'), f('evidence', 'Evidence', 'Preuve', 'الدليل'), f('action', 'Action', 'Action', 'الإجراء')] },
  { key: 'certificates', name: L('Certificates', 'Certificats', 'الشهادات'), fields: [f('body', 'Certification body', 'Organisme de certification', 'هيئة الاعتماد'), f('number', 'Number', 'Numéro', 'الرقم'), f('issued', 'Issued', 'Délivré', 'تاريخ الإصدار', 'date'), f('expiry', 'Expiry', 'Expiration', 'تاريخ الانتهاء', 'date')] },
  { key: 'suppliers', name: L('Suppliers', 'Fournisseurs', 'الموردون'), fields: [f('category', 'Category', 'Catégorie', 'الفئة'), f('score', 'Score (%)', 'Note (%)', 'الدرجة (%)'), f('class', 'Class', 'Classe', 'الفئة'), f('lastEvaluation', 'Last evaluation', 'Dernière évaluation', 'آخر تقييم', 'date'), f('nextEvaluation', 'Next evaluation', 'Prochaine évaluation', 'التقييم التالي', 'date'), f('critical', 'Critical', 'Critique', 'حرج'), f('certification', 'Certification', 'Certification', 'الاعتماد'), f('quality', 'Quality (1–5)', 'Qualité (1–5)', 'الجودة (1–5)'), f('delivery', 'Delivery (1–5)', 'Livraison (1–5)', 'التسليم (1–5)'), f('price', 'Price (1–5)', 'Prix (1–5)', 'السعر (1–5)'), f('service', 'Service (1–5)', 'Service (1–5)', 'الخدمة (1–5)'), f('hse', 'HSE (1–5)', 'HSE (1–5)', 'السلامة (1–5)'), f('otd', 'On-time delivery', 'Livraison à l\'heure', 'التسليم في الموعد'), f('ppm', 'PPM', 'PPM', 'PPM'), f('complaints', 'Complaints', 'Réclamations', 'الشكاوى'), f('action', 'Action', 'Action', 'الإجراء')] },
  { key: 'ideas', name: L('Improvement ideas', 'Idées d\'amélioration', 'أفكار التحسين'), fields: [f('roi', 'ROI (%)', 'ROI (%)', 'العائد (%)'), f('effort', 'Effort', 'Effort', 'الجهد'), f('submittedBy', 'Submitted by', 'Proposée par', 'اقترحها')] },
  { key: 'competence', name: L('Competence', 'Compétences', 'الكفاءات'), fields: [f('role', 'Role', 'Rôle', 'الدور', 'role'), f('holder', 'Holder', 'Titulaire', 'الحائز'), f('required', 'Required level', 'Niveau requis', 'المستوى المطلوب'), f('level', 'Level', 'Niveau', 'المستوى'), f('gap', 'Gap', 'Écart', 'الفجوة'), f('criticality', 'Criticality', 'Criticité', 'الأهمية'), f('acquiredBy', 'How acquired', 'Mode d\'acquisition', 'طريقة الاكتساب'), f('evidence', 'Evidence', 'Preuve', 'الدليل'), f('trainedOn', 'Trained on', 'Formé le', 'تاريخ التدريب', 'date'), f('action', 'Action', 'Action', 'الإجراء')] },
  { key: 'training', name: L('Training records', 'Enregistrements de formation', 'سجلات التدريب'), fields: [f('type', 'Type', 'Type', 'النوع'), date, f('durationH', 'Hours', 'Heures', 'الساعات'), f('trainer', 'Trainer', 'Formateur', 'المدرب'), f('effectiveness', 'Effectiveness (%)', 'Efficacité (%)', 'الفعالية (%)'), f('provider', 'Provider', 'Prestataire', 'الجهة'), f('participants', 'Participants', 'Participants', 'المشاركون'), f('competence', 'Competence', 'Compétence', 'الكفاءة'), f('evaluation', 'Evaluation', 'Évaluation', 'التقييم'), f('result', 'Result', 'Résultat', 'النتيجة'), f('effectivenessMethod', 'Effectiveness method', 'Méthode d\'efficacité', 'طريقة الفعالية'), f('certificate', 'Certificate', 'Certificat', 'الشهادة')] },
  { key: 'calibration', name: L('Measuring equipment', 'Équipements de mesure', 'معدات القياس'), fields: [f('category', 'Category', 'Catégorie', 'الفئة'), f('serial', 'Serial number', 'Numéro de série', 'الرقم التسلسلي'), f('tolerance', 'Required accuracy', 'Exactitude requise', 'الدقة المطلوبة'), f('lastCalibration', 'Last calibration', 'Dernier étalonnage', 'آخر معايرة', 'date'), f('nextCalibration', 'Next calibration', 'Prochain étalonnage', 'المعايرة التالية', 'date'), f('manufacturer', 'Manufacturer', 'Fabricant', 'الصانع'), f('model', 'Model', 'Modèle', 'الطراز'), f('location', 'Location', 'Emplacement', 'الموقع'), f('user', 'User', 'Utilisateur', 'المستخدم'), f('range', 'Range', 'Étendue', 'النطاق'), f('resolution', 'Resolution', 'Résolution', 'الدقة'), f('method', 'Method', 'Méthode', 'الطريقة'), f('provider', 'Provider', 'Prestataire', 'الجهة'), f('certificate', 'Certificate', 'Certificat', 'الشهادة'), f('frequencyMonths', 'Interval (months)', 'Périodicité (mois)', 'الفترة (أشهر)'), f('result', 'Last result', 'Dernier résultat', 'آخر نتيجة'), f('error', 'Error found', 'Écart constaté', 'الخطأ المرصود'), f('traceability', 'Traceability', 'Raccordement', 'التتبع'), f('outOfTolerance', 'Out-of-tolerance assessment', 'Évaluation du hors-tolérance', 'تقييم الخروج عن التفاوت')] },
  { key: 'commplan', name: L('Communication plan', 'Plan de communication', 'خطة التواصل'), fields: [f('audience', 'With whom', 'Avec qui', 'مع من'), f('sender', 'Who', 'Qui', 'من', 'role'), f('channel', 'How', 'Comment', 'كيف'), f('frequency', 'When', 'Quand', 'متى'), f('purpose', 'Why', 'Pourquoi', 'لماذا'), f('direction', 'Internal / external', 'Interne / externe', 'داخلي / خارجي'), f('language', 'Language', 'Langue', 'اللغة'), f('record', 'Record', 'Enregistrement', 'السجل'), f('feedback', 'Feedback', 'Retour', 'الملاحظات')] },
  { key: 'commlog', name: L('Communication records', 'Enregistrements de communication', 'سجلات التواصل'), fields: [date, f('audience', 'Audience', 'Destinataires', 'الجمهور'), f('channel', 'Channel', 'Canal', 'القناة'), f('by', 'By', 'Par', 'بواسطة'), f('reach', 'Reach', 'Portée', 'العدد'), f('evidence', 'Evidence', 'Preuve', 'الدليل'), f('feedback', 'Feedback', 'Retour', 'الملاحظات')] },
  { key: 'changes', name: L('Changes', 'Modifications', 'التغييرات'), fields: [f('type', 'Type', 'Type', 'النوع'), date, f('requester', 'Requested by', 'Demandée par', 'طلبه'), f('riskLevel', 'Risk level', 'Niveau de risque', 'مستوى الخطر'), f('plannedDate', 'Planned', 'Prévue', 'المخطط', 'date'), f('reason', 'Reason', 'Motif', 'السبب'), f('impacted', 'Impacted', 'Impacts', 'المتأثر'), f('likelihood', 'Likelihood', 'Probabilité', 'الاحتمالية'), f('impact', 'Impact', 'Impact', 'الأثر'), f('resources', 'Resources', 'Ressources', 'الموارد'), f('approvedBy', 'Approved by', 'Approuvée par', 'اعتمده'), f('approvalDate', 'Approval date', 'Date d\'approbation', 'تاريخ الاعتماد', 'date'), f('implementation', 'Implementation', 'Mise en œuvre', 'التنفيذ'), f('verification', 'Verification', 'Vérification', 'التحقق'), f('reviewDate', 'Post-change review', 'Revue après changement', 'المراجعة بعد التغيير', 'date'), f('integrity', 'Integrity of the system', 'Intégrité du système', 'سلامة النظام')] },
  { key: 'controlplan', name: L('Control plan', 'Plan de surveillance', 'خطة الضبط'), fields: [f('characteristic', 'Characteristic', 'Caractéristique', 'الخاصية'), f('classification', 'Class', 'Classe', 'الفئة'), f('specification', 'Specification', 'Spécification', 'المواصفة'), f('frequency', 'Frequency', 'Fréquence', 'التكرار'), f('responsible', 'Responsible', 'Responsable', 'المسؤول', 'role'), f('charType', 'Product / process', 'Produit / procédé', 'منتج / عملية'), f('method', 'Measurement technique', 'Technique de mesure', 'تقنية القياس'), f('sample', 'Sample', 'Échantillon', 'العينة'), f('control', 'Control method', 'Méthode de maîtrise', 'طريقة الضبط'), f('record', 'Record', 'Enregistrement', 'السجل'), f('reaction', 'Reaction plan', 'Plan de réaction', 'خطة الاستجابة')] },
  { key: 'reqreview', name: L('Requirements reviews', 'Revues des exigences', 'مراجعات المتطلبات'), fields: [f('customer', 'Customer', 'Client', 'العميل'), f('type', 'Type', 'Type', 'النوع'), date, f('decision', 'Decision', 'Décision', 'القرار'), f('reviewedBy', 'Reviewed by', 'Revue par', 'راجعه'), f('requirements', 'Requirements reviewed', 'Exigences revues', 'المتطلبات المراجعة'), f('capability', 'Capability', 'Aptitude', 'القدرة'), f('leadTime', 'Lead time', 'Délai', 'المدة'), f('legal', 'Legal', 'Légal', 'قانوني'), f('conditions', 'Conditions', 'Conditions', 'الشروط'), f('confirmed', 'Confirmed to customer', 'Confirmée au client', 'التأكيد للعميل', 'date')] },
  { key: 'releases', name: L('Releases', 'Libérations', 'الإفراج'), fields: [date, f('result', 'Result', 'Résultat', 'النتيجة'), f('releasedBy', 'Released by', 'Libéré par', 'أفرج عنه'), f('evidence', 'Evidence', 'Preuve', 'الدليل'), f('criteria', 'Criteria', 'Critères', 'المعايير'), f('conform', 'Conforming', 'Conforme', 'مطابق')] },
  { key: 'nco', name: L('Nonconforming outputs', 'Éléments non conformes', 'المخرجات غير المطابقة'), fields: [f('ncCode', 'NC ref.', 'Réf. NC', 'مرجع عدم المطابقة'), date, f('disposition', 'Disposition', 'Traitement', 'المعالجة'), f('authority', 'Decided by', 'Décidé par', 'قرره'), f('cost', 'Cost', 'Coût', 'التكلفة'), f('product', 'Product', 'Produit', 'المنتج'), f('quantity', 'Quantity', 'Quantité', 'الكمية'), f('detectedAt', 'Detected at', 'Détecté à', 'مكان الاكتشاف'), f('customerInformed', 'Customer informed', 'Client informé', 'إعلام العميل'), f('concession', 'Concession', 'Dérogation', 'التنازل')] },
  { key: 'capa', name: L('8D reports', 'Rapports 8D', 'تقارير 8D'), fields: [f('ncCode', 'NC ref.', 'Réf. NC', 'مرجع عدم المطابقة'), f('opened', 'Opened', 'Ouvert le', 'تاريخ الفتح', 'date'), f('champion', 'Champion', 'Pilote', 'المسؤول'), f('priority', 'Priority', 'Priorité', 'الأولوية'), f('closed', 'Closed', 'Clôturé le', 'تاريخ الإغلاق', 'date'), f('rootCause', 'Root cause', 'Cause racine', 'السبب الجذري'), f('validation', 'Validation', 'Validation', 'التحقق'), f('lessons', 'Lessons learned', 'Enseignements', 'الدروس المستفادة')] },
  { key: 'reviews', name: L('Management reviews', 'Revues de direction', 'مراجعات الإدارة'), fields: [date, f('attendees', 'Attendees', 'Participants', 'الحضور'), f('outputs', 'Outputs', 'Éléments de sortie', 'المخرجات')] },
  { key: 'incidents', name: L('Incidents', 'Incidents', 'الحوادث'), fields: [f('type', 'Type', 'Type', 'النوع'), date, f('lostDays', 'Lost days', 'Jours perdus', 'الأيام الضائعة'), f('investigated', 'Investigated', 'Enquêté', 'تم التحقيق')] },
];
export const REGISTERS = REGISTER_DEFS.map(r => r.key);
