"""Builds "DynamicMS — Response to the feedback on User Guide 2 (SME QMS, Scenario 1)": every
note of the reviewed guide, what changed in the application and where to see it, plus the
IMS document templates delivered and seeded."""
import json
import os
from brand import (new_document, cover, toc, para, bullets, numbered, table, callout)

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BUILD = os.path.join(ROOT, 'deliverables', 'build')
OUT = os.path.join(ROOT, 'deliverables')

GENERAL = [
    ('Where to create a new group?', 'Administration › Groups and organizations (platform administrator): New group, edit, delete an empty group. Organization › Tenancy points to it.', 'Administration › Groups and organizations'),
    ('Where to create a new organization? (group: yes, no)', 'New organization asks "Part of a group?" — No: independent organization; Yes: choose the group. The organization is created with its administrator and a default structure (head office and departments) so the forms can pick units and people at once.', 'Administration › Groups and organizations › New organization'),
    ('For each step, a brief and a detailed description (expand, collapse).', 'Every step has a brief description and a detailed one: purpose, how to fill the form, inputs to use, expected result, performer and ISO clause, in English, French and Arabic. Show / Hide the detailed description on the step.', 'Any step › What to record'),
    ('"Workshop records and Internal issues" appears in many places.', 'Removed. Items are now records with their own source per row: named records, studies, registers, interviews or dates (for example "Quotation register: 9 corrections in Q3 2025").', 'Steps with record tables; User Guide 2'),
    ('For each macro process, an optional checklist of what is required before starting.', '"Before you start (optional checklist)" on the macro process page: inputs available, previous macro processes of the phase completed, owner and RACSI, document templates, KPIs, people informed. System-checked items tick themselves; the others are ticked by the user (who and when are kept). Not blocking.', 'Macro process › Tasks and steps'),
    ('All the information generated by the steps should be available to put in documents.', 'Documents are generated from the project data: step values (issues, parties, scope, commitments, reviews, communications, changes), registers, RACSI, KPIs, risks, audits, nonconformities and actions. 57 data sources are available to the templates.', 'Records › Documents; IMS Document Templates'),
    ('Suggest the documents mandatory for the selected standards, with CRUD/RBAC.', 'Tab "Required by the standards": documented information required by ISO 9001, ISO 14001 and ISO 45001 for the project standards, maintain (document) or retain (record), clause, and the document answering it; Create for a missing one. Rights: records.view to read, records.manage to create and change.', 'Records › Documents › Required by the standards'),
    ('Possibility to create new documents.', 'New document: from a template filled with the project data, or blank.', 'Records › Documents › New document'),
    ('Word / PDF with a table of contents (except the policy); Excel with a cover page.', 'Every generated Word and PDF file has a cover page and a table of contents, except the policies (one page, no table of contents). Excel workbooks have a cover sheet then one sheet per table.', 'Downloads of any document'),
    ('Document templates, with the possibility to create new ones.', '37 IMS templates in a library (policies, scope, manual, context analysis, registers, procedures, plans, reports); Copy to edit, New template, Retire. Section editor: title, type (free text, project data, approval block), data source, text with placeholders, order.', 'Records › Documents › Templates'),
    ('Customizable layout (logo, graphic chart…) like in Word.', 'Layout tab: logo image or logo text, table header color, accent color, title color, header text and footer text, with a preview; applied to DOCX, PDF and XLSX.', 'Records › Documents › Layout'),
    ('For any document, see its structure and content, with CRUD/RBAC.', 'The document page shows every section with its data (Structure and content). On a draft, Edit the structure adds, renames, reorders or deletes sections and edits free text.', 'Records › Documents › a document'),
    ('Documents: CRUD/RBAC.', 'Create, read, edit (title, review frequency), new version (regenerated or copied), delete a never-published document, retire a published one with a justification. The author cannot approve their own version. All changes go to the audit trail.', 'Records › Documents'),
    ('In any step, a "Generate document" button.', 'Card "Documents of this step" with Generate document: the templates of the macro process are suggested first; the draft is linked to the step and downloadable from it.', 'Any step'),
    ('Documents with version management.', 'Draft 0.x → In review → Published; the previous version becomes Superseded; each version can be downloaded; minor (x.y+1) or major (x+1.0) change.', 'Records › Documents › a document › Versions'),
    ('BPMN diagram: Expand should use the whole screen, with a way back.', 'Full screen button: the diagram takes the whole screen; Exit full screen or Escape returns to the page. The former expand icon was "fit to screen" and is now labelled so.', 'Macro process › BPMN diagram'),
    ('Naming: function and macro process names start with a noun; task and step names start with a verb and are explicit.', '1,451 step names and all generic task names were rewritten in the three languages with the object of the macro process ("Fix quality policy review periodicity", "Update the quality policy document"). Steps whose source name started with a noun now start with a verb. Saving a BPMN diagram warns about task names that do not follow the rule.', 'All lifecycle screens; User Guides'),
    ('Where to configure the LLM for AI use cases: standard LLMs with their models, custom LLM.', 'Administration › AI models: Anthropic (Claude Opus 5.5, Sonnet 5.5, Fable 5.1, Haiku 4.5), OpenAI, Azure OpenAI, Google Gemini, Mistral, or a custom model with an OpenAI-compatible endpoint; API key stored encrypted; test the connection; a model per use case. Without a provider, the built-in engine answers.', 'Administration › AI models'),
    ('"Items identified": separate records/cells with CRUD, not one cell.', 'Register items are a table: one row per item with Item, Category, Description and impact, Relevance, Source / evidence; Add a row, edit a cell, delete a row.', 'Steps of form "Register items"'),
    ('"Source / evidence": separate records/cells with CRUD, not one cell.', 'Source / evidence is a column: each item has its own source.', 'Same'),
    ('Any AI use case mapped to the right step, with a prompt about that step.', 'A step shows only the AI use case linked to it (not all the use cases of the macro process). The 23 AI-assisted steps that had none now have one (41 in total). Each use case has a prompt written from its step; at run time it adds the organization, standards, values already typed and results of the previous steps. View prompt shows it.', 'Any AI-assisted step; Intelligence › AI use cases'),
    ('Difference between "Rédiger la politique" and "Rédiger la politique à partir d\'un modèle"?', 'They were two sources of the process design (a manual draft and the template/AI draft). They are now distinct and in order: step 4 "Generate the quality policy draft from the template" (AI-assisted), then step 5 "Adapt the quality policy commitments to the organization".', 'UMS022 (MP-002)'),
    ('UMS022: one place to select the standard(s) before any policy elaboration.', 'Step 1 of UMS022 is now "Select the standards and scope type of the quality policy" (form Standards and scope). Its value becomes the standards of the project, used by every document and by the list of required documents. A QMS project keeps quality standards only (Atlas: ISO 9001).', 'UMS022 step 1'),
    ('For any step, attach documents with history.', 'Attachments on every step (and document, nonconformity, audit, action) with versions: New version on a file keeps the previous ones (version, author, date, note).', 'Any step › Attachments'),
    ('Indicators: explain why; select KPIs from a list, with custom to create a new one.', 'Measurement form: one row per KPI chosen from the project list (KPIs of the macro process first), a mandatory "Why this KPI for this step", the value and the target; New KPI creates a KPI from the step. Values are recorded in the KPI history and raise an alert when off target.', 'Steps of form "Measurement"'),
    ('"What to type" is too generic; details that produce the desired outputs are needed.', 'Step-specific content was written for the E2E-01 core macro processes (UMS016 context, UMS022 policy, UMS031 objectives, UMS002 process architecture) and the generic content now names the macro process outputs, dated records and people. The user guides print the record tables in full.', 'User Guide 2, Scenario 1'),
    ('"For QMS steps, you can also consider the attached document."', 'No other document was attached to the request (only the reviewed User Guide 2). Please send it: its content will be added to the step content of the QMS scenarios.', '—'),
]

INLINE = [
    ('UMS016 step 1 — Scope / notes: dropdown from the OBS and its functions, with custom.', 'Organization units in scope: picker of the OBS units (sites, departments) with an "Other (type)" value; chaired by (role) added.'),
    ('UMS016 steps 2–4 — Items and Source / evidence as separate records.', 'Record tables with one row per issue or party and its own source.'),
    ('UMS016 step 5 — Score (1–5): explain the score and add a decision matrix.', 'Assessment form = decision matrix: criteria, weights, score 1–5 per criterion with the facts, scoring scale, weighted score computed (3.5 = Defined) and conclusion.'),
    ('UMS016 — "Competence gap closure rate: why this at this stage?"', 'The periodic review of the context is now a Review form. Measurement steps only propose the KPIs of their macro process, with the reason.'),
    ('UMS016 — "Here it is a review: why not frequency and other information?"', 'Review form: frequency, review date, next review, chair, participants, inputs reviewed (table), decisions and actions (table; each decision becomes an action).'),
    ('UMS022 — Communication audience in one cell.', 'Communication records: one row per audience with channel, date, key message and who communicates (ISO 9001 §7.4).'),
    ('UMS022 — Planned activities "should create actions managed by the Action plan module".', 'Plan form rows (activity, owner, start, due, deliverable) become actions of the Action plan when the step is completed; the step links them.'),
    ('UMS022 — "Procedures with BPMN and exception flow: relationship with the step?"', 'The step is now "Check the quality policy draft against ISO 9001 §5.2", an assessment with the §5.2 criteria; no unrelated indicator.'),
    ('UMS022 — "Policy document generated automatically: where is the document?"', 'The service step links the generated policy (AT-UNI-QMS-POL-Q), downloadable in PDF and Word from the step and from Documents.'),
    ('UMS031 — "Multiple records/cells with SMART, not one cell."', 'SMART objectives form: specific objective, KPI, baseline, target, relevance, owner, deadline, resources; each row becomes an entry of the objectives register.'),
    ('UMS031 — "Records filed in DynamicMS: where are the records?" (three times)', 'Execution, service and change steps list the records they produced (documents, register entries, actions) as links.'),
    ('UMS002 — "These details are not useful."', 'Process architecture content: scope and levels, management/core/support processes with owners, BPMN flows with gateways, validation criteria and the §4.4.1 decision matrix.'),
    ('UMS002 — "Person / team should come from the OBS; RACSI table in five columns for macro processes by default, and tasks/steps if needed."', 'Assignment form: person picked from the OBS, organization units, RACSI in five columns (one A). Macro process › RACSI tab edits the macro process RACSI and, when needed, a step-level RACSI.'),
    ('UMS002 — "Put the decision matrix."', 'Verify alignment is an assessment against ISO 9001 §4.4.1 a–f with weights, scores and facts.'),
]

NAMES = [
    ('MP-002', 'Fix review periodicity', 'Fix quality policy review periodicity'),
    ('MP-002', 'Draft policy', 'Adapt the quality policy commitments to the organization'),
    ('MP-002', 'Draft policy from template', 'Generate the quality policy draft from the template'),
    ('MP-002', 'Update', 'Update the quality policy document'),
    ('MP-002', 'Select policy standards and scope type', 'Select the standards and scope type of the quality policy (now step 1)'),
    ('MP-003', 'Cascade', 'Cascade the quality policy into quality objectives'),
    ('MP-004', 'Define scope', 'Define the process architecture scope'),
    ('MP-004', 'Map in BPMN', 'Map each process in BPMN'),
    ('MP-004', 'Flag lowest-level elements as tasks', 'Flag lowest-level process elements as executable tasks'),
    ('All', 'Plan & Prepare / Execute / Verify, Record & Close', 'Plan and prepare {object} / Execute {object} activities / Verify, record and close {object}'),
]

MP002 = [
    ('1', '10', 'Select the standards and scope type of the quality policy', 'Standards and scope'),
    ('2', '1', 'Fix quality policy review periodicity', 'Periodicity'),
    ('3', '3', 'Consult top management on the quality policy', 'Register items'),
    ('4', '11', 'Generate the quality policy draft from the template', 'AI-assisted draft'),
    ('5', '2', 'Adapt the quality policy commitments to the organization', 'Document'),
    ('6', '4', 'Integrate mandatory commitments into the quality policy', 'Register items (§5.2.1 a–d)'),
    ('7', '5', 'Align the quality policy with ISO requirements and strategy', 'Execution'),
    ('8', '12', 'Check the quality policy draft against ISO 9001 §5.2', 'Assessment (decision matrix)'),
    ('9', '6', 'Obtain top management approval of the quality policy', 'Decision'),
    ('10', '13', 'Publish the quality policy and generate its files', 'Automated service task'),
    ('11', '7', 'Communicate the quality policy', 'Communication'),
    ('12', '8', 'Plan the quality policy review', 'Review'),
    ('13', '9', 'Update the quality policy document', 'Change'),
]


def build():
    tpl = json.load(open(os.path.join(BUILD, 'templates.json'), encoding='utf8'))
    doc = new_document('Response to the feedback on User Guide 2', 'DynamicMS — Feedback response')
    cover(doc, 'Feedback response', 'Response to the Feedback on User Guide 2', 'SME QMS — Scenario 1 (Atlas Universal SME) · changes in the application, the guides and the documents', 'POWERACT Consulting · DynamicMS 1.0 · September 2026')
    toc(doc)
    doc.add_heading('Summary', level=1)
    para(doc, 'The feedback on User Guide 2 (SME QMS, Scenario 1) listed general gaps of the application and comments on the steps of UMS016, UMS022, UMS031 and UMS002. POWERACT Consulting updated DynamicMS, its demonstration data and its documents accordingly, and added a library of IMS document templates, seeded and ready to download.')
    bullets(doc, [
        ('Forms. ', 'Lists became record tables with one row per item and its own source; assessments became decision matrices; reviews, SMART objectives, plans (actions), communications and KPIs (with the reason for the KPI) have their own forms; people and units come from the OBS; RACSI in five columns.'),
        ('Names and descriptions. ', '1,451 step names and the generic task names made explicit; every step has a brief and a detailed description.'),
        ('Documents. ', f"{len(tpl['templates'])} IMS templates; documents generated from the project data with cover, table of contents (except policies), versions, structure editing, layout and downloads in Word, PDF and Excel; {tpl['totals']['documents']:,} documents seeded across {tpl['totals']['projects']} projects."),
        ('Administration. ', 'Groups and organizations (member of a group or independent); AI models (standard providers and models, or custom).'),
        ('Deliverables. ', 'User Guide 2 and User Guide 1 regenerated; IMS Document Templates (new); this response; installation guide, coverage checklist and presentations updated.'),
    ])
    doc.add_heading('General notes', level=1)
    table(doc, ['#', 'Feedback', 'What changed', 'Where'], [[str(i + 1), a, b, c] for i, (a, b, c) in enumerate(GENERAL)], [0.8, 5.0, 8.4, 3.8], size=9)
    doc.add_heading('Comments on the steps of Scenario 1', level=1)
    table(doc, ['#', 'Comment', 'What changed'], [[str(i + 1), a, b] for i, (a, b) in enumerate(INLINE)], [0.8, 6.6, 10.6], size=9)
    doc.add_heading('Explicit names (highlighted in the guide)', level=1)
    table(doc, ['Macro process', 'Before', 'Now'], [list(x) for x in NAMES], [2.6, 6.2, 9.2], size=9.5)
    doc.add_heading('New sequence of UMS022 — Quality policy', level=2)
    para(doc, 'The standards are selected once, first; the template draft comes before the manual adaptation; the ISO 9001 §5.2 check precedes the approval; the published policy is linked to the step.')
    table(doc, ['New #', 'Former #', 'Step', 'Form'], [list(x) for x in MP002], [1.6, 1.8, 10.2, 4.4], size=9.5)
    doc.add_heading('IMS document templates delivered and seeded', level=1)
    para(doc, f"Request 2 (suggest templates for the IMS documents) and request 3 (seed the application with them, populated and ready to download) are answered by the template library of DynamicMS and the document DynamicMS_IMS_Document_Templates (catalogue, required documented information per standard, sections and data sources). The table lists the templates.")
    table(doc, ['Code', 'Template', 'Formats', 'Required by'], [[t['code'], t['name'], ', '.join(t['formats']), '; '.join(f"{s} §{t['clauses'].get(s, '')} ({k})" for s, k in t['mandatory'].items()) or 'Recommended'] for t in tpl['templates']], [2.6, 7.0, 2.6, 5.8], size=8.5)
    at = next(p for p in tpl['projects'] if p['code'] == 'AT-UNI-QMS')
    para(doc, f"In Scenario 1 (AT-UNI-QMS), {len(at['documents'])} documents are generated from these templates; they are listed in User Guide 2 and in the template catalogue, and a sample set (Word, PDF, Excel) is delivered in DynamicMS_Sample_IMS_Documents.zip.")
    doc.add_heading('How to check the changes', level=1)
    numbered(doc, [
        'Install and seed the application (Installation Guide), then sign in as ims@atlas-sme.example (password Demo@2026) and select project AT-UNI-QMS.',
        'Open Lifecycle › E2E-01 › UMS016, then step 2 "Identify external issues": the issues are rows, each with its source.',
        'Open UMS022: step 1 selects the standards; step 8 shows the §5.2 decision matrix; step 10 links the published policy; step 12 is a review with its decisions turned into actions.',
        'Open UMS031 step 2: SMART objectives linked to the objectives register. Open UMS002 › RACSI: the five-column RACSI with a step-level line.',
        'Open Records › Documents: the four tabs (Documents, Required by the standards, Templates, Layout); download the quality policy (no table of contents) and the context analysis (with table of contents).',
        'Sign in as admin@dynamicms.example (Admin@2026): Administration › Groups and organizations; as admin@atlas-sme.example: Administration › AI models.',
    ])
    callout(doc, 'The message mentioned a document to consider for the QMS steps, but no such file was attached. Please send it to include its content in the next update.', 'Pending.')
    path = os.path.join(OUT, 'DynamicMS_Feedback_Response_User_Guide_2.docx')
    doc.save(path)
    print('saved', path)


if __name__ == '__main__':
    build()
