"""French text of the IMS Document Templates catalog (build_templates_doc.py)."""

SOURCES_FR = {
    'policy_statement': "Texte de politique validé à l'étape MP-002.11 (brouillon assisté par IA, puis modifié), ou politique publiée.",
    'policy_statement_env': "Engagements environnementaux construits à partir du profil de l'organisme.",
    'policy_statement_ohs': "Engagements SST construits à partir du profil de l'organisme.",
    'policy_commitments': "Engagements recueillis lors de la consultation de la direction (étape MP-002.3).",
    'scope': "Énoncé du périmètre, sites, exigences non applicables et processus externalisés (étape MP-001.8).",
    'obs_units': "Sites et départements de la structure de l'organisation (OBS) avec leurs membres.",
    'standards': "Normes choisies une seule fois pour le projet (étape MP-002.10).",
    'processes': "Macro-processus du projet avec phase, pilote et statut.",
    'racsi': "RACSI de chaque macro-processus (cinq colonnes, un seul Approbateur).",
    'mp_racsi': "RACSI du macro-processus du document.",
    'documents': "Liste maîtresse des documents du projet : version, statut, propriétaire, prochaine revue.",
    'mandatory_matrix': "Informations documentées exigées par les normes du projet et leur existence.",
    'context_issues': "Registre du contexte (enjeux externes et internes).",
    'context_external': "Enjeux externes saisis à l'étape MP-001.2, une ligne par enjeu avec sa source.",
    'context_internal': "Enjeux internes saisis à l'étape MP-001.3, une ligne par enjeu avec sa source.",
    'parties': "Parties intéressées et leurs besoins et attentes (étape MP-001.4 ou registre des parties).",
    'objectives': "Registre des objectifs rempli par l'étape des objectifs SMART (MP-003.2) : KPI, cible, responsable, échéance.",
    'obligations': "Registre des obligations de conformité avec l'évaluation de la conformité.",
    'competence': "Registre des compétences : titulaire, niveau atteint, niveau requis, date de formation.",
    'training': "Sessions de formation réalisées dans les étapes de formation, avec leur efficacité.",
    'calibration': "Registre des équipements de surveillance et de mesure avec dates d'étalonnage.",
    'suppliers': "Registre des fournisseurs avec note, dernière évaluation et statut.",
    'reviews': "Revues de direction tenues, avec participants et éléments de sortie.",
    'incidents': "Registre des incidents (presque-accidents, premiers soins, incidents environnementaux).",
    'ideas': "Idées d'amélioration avec ROI, effort et statut.",
    'risks': "Registre des risques avec probabilité, impact, score, risque résiduel, traitement et propriétaire.",
    'risks_top': "Risques de score 12 et plus.",
    'opportunities': "Opportunités du registre des risques.",
    'aspects': "Aspects environnementaux du registre des risques.",
    'hazards': "Dangers du registre des risques.",
    'risk_scale': "Échelle de probabilité et d'impact (1 à 5) et classes de score.",
    'kpis': "KPI avec cible, dernière valeur et statut (atteint ou non).",
    'mp_kpis': "KPI du macro-processus du document.",
    'kpi_values': "Valeurs mensuelles des KPI sur les six derniers mois.",
    'actions_objectives': "Actions prévues pour atteindre les objectifs.",
    'actions_corrective': "Actions curatives, correctives et préventives.",
    'actions_improvement': "Actions d'amélioration.",
    'actions_review': "Actions décidées en revue.",
    'ncs': "Non-conformités avec source, criticité, cause racine et étape.",
    'ncs_major': "Non-conformités majeures et critiques.",
    'audits': "Programme d'audit : type, critères, date, auditeur responsable, statut.",
    'audits_done': "Audits réalisés.",
    'findings': "Constats d'audit avec article, type et statut.",
    'rex': "Retours d'expérience (ce qui a fonctionné, ce qui n'a pas fonctionné, recommandation).",
    'controls': "Contrôles avec type, fréquence, propriétaire et efficacité.",
    'rules': "Règles de gestion des macro-processus du projet.",
    'communications': "Enregistrements de communication saisis dans les étapes de communication (quoi, avec qui, comment, quand, qui).",
    'changes': "Modifications saisies dans les étapes de changement : ce qui change, pourquoi et qui l'a autorisé.",
    'revisions': "Historique des révisions du document lui-même.",
    'mp_goal': "Finalité, déclencheur et événement de fin du macro-processus.",
    'mp_sipoc': "SIPOC du macro-processus.",
    'mp_steps': "Tâches et étapes du macro-processus avec rôle et statut.",
    'phase_racsi': "RACSI des macro-processus de la phase.",
    'phase_steps': "Étapes de la phase avec rôle et statut.",
    'phase_outputs': "Sorties (enregistrements) des macro-processus de la phase.",
    'phase_kpis': "KPI des macro-processus de la phase.",
    'step_rows:MP-001.7': "Interactions entre processus saisies à l'étape MP-001.7.",
    'step_matrix:MP-001.5': "Matrice de décision de l'évaluation des besoins et attentes (étape MP-001.5).",
    'step_review:MP-001.10': "Revue périodique du contexte (étape MP-001.10) : fréquence, dates, décisions.",
    'doc_identity': "Identification du document : référence, version, propriétaire, organisme, normes, fréquence de revue et prochaine revue.",
    'references': "Normes et documents associés (manuel, cartographie des processus, liste maîtresse).",
    'definitions': "Termes utilisés dans les procédures : SIPOC, RACSI, BPMN, jalon et Go / No-Go, information documentée.",
    'policy_vision:Q': "Vision et ambition de l'organisme, enjeux de contexte et normes sur lesquelles repose le système.",
    'policy_vision:IMS': "Vision et ambition (qualité, santé, sécurité et environnement).", 'policy_vision:E': "Vision et ambition (environnement).", 'policy_vision:OHS': "Vision et ambition (santé et sécurité au travail).",
    'policy_axes:Q': "Axes stratégiques (clients, excellence opérationnelle, amélioration, personnel, conformité, partenaires, outils), chacun avec ses engagements et les objectifs mesurables du registre des objectifs qui lui sont liés.",
    'policy_axes:IMS': "Axes stratégiques incluant santé-sécurité et environnement, chacun avec des objectifs mesurables.", 'policy_axes:E': "Axes stratégiques environnementaux avec objectifs.", 'policy_axes:OHS': "Axes stratégiques SST avec objectifs.",
    'policy_commitments:Q': "Engagements du dirigeant (« En tant que dirigeant, je m'engage à… »), y compris la délégation au responsable du système de management.",
    'policy_commitments:IMS': "Engagements du dirigeant pour la qualité, la SST (prévention, consultation) et l'environnement (prévention de la pollution, obligations de conformité).", 'policy_commitments:E': "Engagements environnementaux du dirigeant.", 'policy_commitments:OHS': "Engagements SST du dirigeant.",
    'policy_roles:Q': "Rôle des managers et de chaque collaborateur ; message de clôture du dirigeant.", 'policy_roles:IMS': "Rôle des managers et des collaborateurs.", 'policy_roles:E': "Rôle des managers et des collaborateurs.", 'policy_roles:OHS': "Rôle des managers et des collaborateurs.",
    'policy_review': "Communication, mise à disposition et revue de la politique (date de la dernière revue de direction).",
    'policy_signature': "Nom, fonction, lieu, date et signature du dirigeant.",
    'org_profile': "Profil de l'organisme : activité, site, effectif, clients, système de management, certificats, responsable du système.",
    'scope_statement': "Énoncé du périmètre construit à partir du profil et du périmètre saisi à l'étape MP-001.8.",
    'scope_summary': "Énoncé du périmètre et exigences non applicables.",
    'products_services': "Produits et services du périmètre avec leurs clients et principales exigences.",
    'outsourced': "Processus externalisés et interfaces, avec leur mode de maîtrise.",
    'exclusions': "Exigences non applicables et leur justification.",
    'process_list': "Processus avec type (management, réalisation, support), pilote, finalité et indicateurs.",
    'pmap_diagram': "Cartographie des processus : processus de management, de réalisation et support entre exigences et satisfaction des clients.",
    'context_summary': "Principaux enjeux et parties intéressées.", 'leadership_summary': "Leadership et engagement, avec les axes stratégiques de la politique.",
    'planning_summary': "Méthode des risques, risques majeurs et objectifs.", 'support_summary': "Ressources, équipements de mesure, compétences, communication et informations documentées.",
    'operation_summary': "Planification et maîtrise opérationnelles, avec le plan de surveillance.", 'performance_summary': "Indicateurs atteints, audits et revues de direction.",
    'improvement_summary': "Non-conformités, clôtures et idées d'amélioration.", 'clause_matrix': "Matrice de correspondance : article, exigence, processus et document.",
    'context_method': "Méthode PESTEL, SWOT et parties intéressées, et fréquence de revue.",
    'pestle': "Enjeux externes par facteur PESTEL : risque ou opportunité, impact, tendance, plus les enjeux saisis à l'étape MP-001.2.",
    'swot': "Forces, faiblesses, opportunités et menaces construites à partir du registre du contexte et des idées d'amélioration.",
    'parties_full': "Parties intéressées : interne ou externe, besoins et attentes, obligation de conformité, influence, intérêt, priorité et surveillance.",
    'power_grid': "Grille influence / intérêt : gérer de près, satisfaire, informer, surveiller.",
    'context_conclusions': "Risques et opportunités résultant de l'analyse.",
    'risk_summary': "Nombre de risques par niveau et d'opportunités.",
    'risks_full': "Risques avec cause, conséquence, moyens de maîtrise existants, probabilité, impact, score, traitement, risque résiduel, propriétaire et statut.",
    'opportunities_full': "Opportunités avec bénéfice, faisabilité et action pour les saisir.", 'heatmap': "Carte de chaleur : nombre de risques par probabilité et impact.",
    'objectives_summary': "Objectifs en bonne voie et à risque.",
    'objectives_full': "Objectifs SMART : axe de la politique, KPI, référence, cible, valeur actuelle, échéance, responsable, ressources et statut.",
    'obligations_full': "Obligations : type, autorité, référence, applicabilité, exigence, mode de conformité, responsable, périodicité, dernière et prochaine évaluation.",
    'obligations_summary': "Évaluation de la conformité : conforme, partiellement conforme, non conforme.", 'obligations_actions': "Actions en cas de conformité partielle ou de non-conformité.",
    'mp_header': "Identité du processus : type, pilote, finalité, déclencheur, fin, normes et phase.",
    'mp_bpmn': "Diagramme BPMN du macro-processus : un couloir par rôle, ses étapes, la passerelle Go / No-Go et l'événement de fin.",
    'mp_steps_sipoc': "Étapes du macro-processus, chacune avec son SIPOC (fournisseurs, entrées, sorties, clients) et son rôle responsable.",
    'mp_gonogo': "Critères Go pour clôturer le processus, traitement du No-Go, décideur et statut actuel.",
    'mp_risks': "Risques et contrôles du macro-processus.", 'mp_docs': "Documents et enregistrements du macro-processus.",
    'phase_bpmn': "Vue BPMN de la phase : macro-processus en sous-processus et jalon de la phase.",
    'phase_activities': "Pour chaque macro-processus de la phase : finalité, déclencheur, pilote, diagramme BPMN, SIPOC de chaque étape et critères Go / No-Go.",
    'phase_gate': "Jalon de la phase : critères d'entrée et de sortie, liste de contrôle avec preuves, règles de décision (Go, No-Go, Attente, Reprise) et décision enregistrée.",
    'phase_records': "Enregistrements produits dans la phase : propriétaire, stockage et conservation.", 'phase_risks': "Risques et règles de gestion de la phase.",
    'wi_safety': "Règles de sécurité et EPI.", 'wi_tools': "Outils et équipements avec la validité de leur étalonnage.", 'wi_steps': "Instructions avec points clés et raisons.", 'wi_checks': "Contrôles qualité avec critères d'acceptation et réaction.",
    'racsi_rules': "Règles d'utilisation de la matrice RACSI.",
    'competence_req': "Compétences requises par rôle avec niveau, criticité et mode d'acquisition.",
    'competence_matrix': "Matrice personnes × compétences avec niveaux réels / requis (couleur : atteint, écart de 1, écart de 2 ou plus).",
    'competence_gaps': "Écarts de compétence et leurs actions.", 'training_plan': "Plan de formation : formation, type, organisme, date, heures, statut.",
    'training_full': "Enregistrements de formation : date, formateur, participants, évaluation, résultat et efficacité avec sa méthode.", 'competence_scale': "Niveaux de compétence 1 à 4.",
    'cal_summary': "État de l'étalonnage : valide, bientôt échu, échu, hors tolérance.",
    'calibration_full': "Registre des équipements : identifiant, catégorie, marque et modèle, numéro de série, emplacement et utilisateur, étendue, exactitude requise, méthode, périodicité, prochaine échéance, statut.",
    'cal_records': "Enregistrements d'étalonnage : date, prestataire, certificat, erreur constatée, résultat et traçabilité.",
    'cal_oot': "Analyse d'impact des équipements trouvés hors tolérance (ISO 9001 §7.1.5.2).", 'cal_legend': "Signification des statuts d'étalonnage.",
    'commplan': "Plan de communication : quoi, pourquoi, avec qui, interne ou externe, qui, comment, quand et enregistrement.",
    'commlog': "Journal de communication : date, sujet, public, canal, émetteur, portée, preuve et retour.",
    'doc_hierarchy': "Quatre niveaux de documentation et leur approbateur.",
    'documents_full': "Documents : type, niveau, article, version, statut, propriétaire, approbateur, date d'application, revue, prochaine revue et diffusion.",
    'records_retention': "Enregistrements à conserver : propriétaire, stockage, protection, durée de conservation et élimination.", 'external_docs': "Documents d'origine externe et leur mise à jour.",
    'supplier_criteria': "Critères d'évaluation et pondérations ; classes A, B et C.",
    'suppliers_full': "Évaluations des fournisseurs : catégorie, certification, criticité, notes par critère, note globale, classe, statut, dernière et prochaine évaluation.",
    'supplier_perf': "Performance des fournisseurs : livraison à l'heure, PPM, réclamations et action.",
    'ctrl_header': "Identification du plan de surveillance : produits, opérations, stade, contact clé et équipe.",
    'controlplan': "Plan de surveillance : opération, caractéristique, produit ou processus, classe (critique, majeure, mineure), spécification, technique de mesure, échantillon, fréquence, méthode de contrôle, responsable, enregistrement et plan de réaction.",
    'ctrl_reaction': "Règles du plan de réaction.", 'nco_summary': "Nombre, éléments ouverts, dérogations et coût des éléments de sortie non conformes.",
    'nco_full': "Éléments de sortie non conformes : référence NC, date, description, quantité, lieu de détection, traitement, autorité, client informé, dérogation et coût.",
    'reqreview': "Revues des exigences client : demande, client, type, exigences revues, capacité, délai, décision, revue par et confirmation.",
    'changes_customer': "Modifications de produits, services ou processus qui affectent les exigences.", 'release_criteria': "Critères d'acceptation pour la libération issus du plan de surveillance.",
    'releases': "Enregistrements de libération : travail ou lot, date, critères, résultat, libéré par et preuve.",
    'change_process': "Demande, évaluation, approbation, mise en œuvre et vérification des modifications.",
    'changes_full': "Demandes de modification : type, date, demandeur, motif, processus et documents impactés, ressources, approbation et date prévue.",
    'change_risk': "Évaluation de l'impact et des risques de chaque modification et intégrité du système.", 'change_verification': "Mise en œuvre, vérification de l'efficacité et revue après modification.",
    'aspects_full': "Aspects : activité, impact, condition, fréquence, gravité, significativité, lien réglementaire, maîtrise et propriétaire.", 'aspects_method': "Critères de significativité.",
    'hazards_full': "Dangers : activité, dommage possible, personnes exposées, probabilité, gravité, risque, mesures existantes et complémentaires, risque résiduel et propriétaire.", 'hierarchy_controls': "Hiérarchie des mesures de maîtrise.",
    'epr_scenarios': "Scénarios d'urgence avec la réponse immédiate, le responsable et les moyens.", 'epr_roles': "Organisation et rôles en situation d'urgence.", 'epr_contacts': "Contacts d'urgence.",
    'incidents_full': "Incidents avec type, date, jours perdus, enquête et enseignements.",
    'kpi_summary': "Indicateurs atteints, non atteints et en progrès.", 'kpi_results': "Résultats de six périodes avec tendance et statut.", 'kpi_results_short': "Résultats des trois dernières périodes.",
    'kpi_analysis': "Analyse et action pour chaque indicateur non atteint.", 'kpi_definitions': "Définitions des indicateurs : formule, unité, cible, sens, fréquence de mesure et d'analyse, source, responsable.",
    'audprg_intro': "Objectifs du programme, étendue, règle de fréquence, méthodes, ressources et risques.",
    'audit_universe': "Fréquence d'audit par processus selon son importance et son risque, avec les derniers et prochains audits.",
    'audits_full': "Audits planifiés : type, périmètre et processus, critères, fréquence (option de liste ou personnalisée), date, durée, équipe et statut.",
    'auditors': "Auditeurs, qualification et indépendance.", 'freq_legend': "Options de fréquence d'audit et leur usage type.",
    'audit_header': "Identification de l'audit : référence, type, date, durée, objectifs, périmètre, critères, auditeur responsable, équipe, audités, méthode et fréquence.",
    'audit_summary': "Nombre de constats par classement et conclusion sur la conformité et l'efficacité.", 'audit_strengths': "Points forts observés.",
    'audit_findings': "Constats avec classement, article, domaine, description, date de réponse attendue et statut.",
    'audit_nc_detail': "Rapport détaillé de chaque non-conformité : classement, exigence, énoncé, preuve objective, processus, audité, correction, cause racine, action corrective, réponse attendue, vérification et statut.",
    'audit_ofi': "Observations et pistes de progrès avec preuves.", 'finding_grading': "Définitions des non-conformités majeures et mineures, des observations et des pistes de progrès, et de la réponse attendue.",
    'audit_conclusion': "Conclusion, suivi, diffusion et limites.",
    'mr_header': "Identification de la réunion : date, lieu, président, participants, secrétaire et revue précédente.", 'mr_agenda': "Ordre du jour de la revue.",
    'mr_inputs': "Chaque élément d'entrée de l'ISO 9001 §9.3.2 (a à f) avec son statut, sa tendance et son évaluation.", 'mr_outputs': "Décisions et actions par catégorie du §9.3.3 avec responsable et échéance.",
    'mr_conclusion': "Conclusions sur la pertinence, l'adéquation et l'efficacité ; prochaine revue.", 'ncs_short': "Non-conformités de la période.",
    'nc_summary': "Nombre, critiques ou majeures, ouvertes et coût des non-conformités.",
    'ncs_full': "Non-conformités : source, criticité, détection, propriétaire, correction, cause racine, action corrective, échéance, efficacité et statut.",
    'capa_d0': "D0 : référence 8D, non-conformité, source, criticité, dates, pilote, priorité.", 'capa_d1': "D1 : membres de l'équipe et leur rôle.",
    'capa_d2': "D2 : description du problème (quoi, où, quand, qui, combien, comment détecté, pourquoi c'est un problème).", 'capa_d3': "D3 : actions de confinement avec responsable, date et résultat.",
    'capa_d4': "D4 : Ishikawa (6M), 5 Pourquoi et causes racines vérifiées (apparition et non-détection).", 'capa_d5': "D5–D6 : actions correctives permanentes, responsables, échéances, vérification et validation de l'efficacité.",
    'capa_d7': "D7 : prévention de la récurrence (déploiement horizontal, registre des risques, base de connaissances).", 'capa_d8': "D8 : enseignements, clôture et reconnaissance de l'équipe.",
    'needs_parties': "Besoins et attentes saisis dans le registre des besoins : parties intéressées concernées, type, obligation de conformité et réponse de l'organisme à chacun.",
    'ideas_full': "Opportunités d'amélioration avec source, auteur, ROI, effort, priorité et statut.",
}

REVIEW_FR = {'Per event': 'À chaque événement', 'Annual': 'Annuelle', 'Monthly': 'Mensuelle', 'Semi-annual': 'Semestrielle', 'Quarterly': 'Trimestrielle'}
STATUS_FR = {'Draft': 'Brouillon', 'In review': 'En revue', 'Published': 'Publié', 'Superseded': 'Remplacé'}
OWNER_FR = {
    'transformation_manager': 'Responsable de la transformation', 'hr_manager': 'Responsable RH', 'ims_manager': 'Responsable SMI',
    'operations_manager': 'Responsable des opérations', 'quality_manager': 'Responsable qualité', 'process_excellence_manager': "Responsable de l'excellence des processus",
    'risk_manager': 'Responsable des risques', 'document_controller': 'Gestionnaire documentaire', 'performance_manager': 'Responsable de la performance',
    'audit_manager': "Responsable d'audit", 'compliance_officer': 'Responsable conformité', 'hse_manager': 'Responsable HSE', 'top_management': 'Direction',
}
