// src/lib/faq.js
// Static application-help corpus (Standard SRS FR-DA-HLP-01/03, FR-DA-AST-04): one entry
// per module, ranked by simple keyword overlap in AIAssistantWidget.jsx and listed
// searchably on the Help page.
export const FAQ_CORPUS = [
  { topic: 'Clients & Projects', q: 'How do I start a new engagement?', a: 'Go to Clients, create or select a client, then go to Projects and click "+ New Project". Select the project in the top bar, then open Project Workspace.' },
  { topic: 'Clients & Projects', q: 'What is the difference between a Client and a Project?', a: 'A Client is the end customer your consulting firm serves (it can have many engagements over time). A Project is one specific scope-to-specs engagement for that client, driven through the 4-step wizard.' },
  { topic: 'Step 1', q: 'How do I upload a SOW?', a: 'Open a Project, go to Step 1: Upload SOW, and fill in the objectives, scope, deliverables, timeline, constraints and stakeholder fields. DynamicBA runs a pre-flight quality check and will generate clarifying questions if the SOW looks incomplete.' },
  { topic: 'Step 1', q: 'What happens if my SOW is vague?', a: 'If the completeness score is below 70, business rule BR-02 fires and DynamicBA generates a list of clarifying questions (one per under-specified section) for you to send to the client sponsor before continuing.' },
  { topic: 'Step 2', q: 'How does AI Generates Spec Package work?', a: 'Step 2 walks you section by section through Context Enrichment, Current-State Analysis, Opportunity Assessment, To-Be Design and Specs Generation. You enter real data (stakeholders, pain points, candidates, etc.) and DynamicBA computes scores and governance artifacts deterministically — every output is explainable, not a black box.' },
  { topic: 'Step 2', q: 'How is the feasibility score calculated?', a: 'Feasibility = 30% technical feasibility + 25% data quality + 20% process stability + 25% strategic fit, each scored 0-100. A candidate at or above 80 is automatically promoted to the prioritization matrix (rule BR-07).' },
  { topic: 'Step 2', q: 'How is ROI payback calculated?', a: 'Payback (months) = one-time cost / annual benefit x 12. A candidate with payback over 18 months is automatically deprioritized to the strategic backlog (rule BR-08).' },
  { topic: 'Step 3', q: 'How do I get client sign-off?', a: 'In Step 3: Review & Validate, compile the package, generate the executive summary, then use "Capture Sign-Off" to record the client sponsor\'s typed signature and timestamp. If sign-off is not captured within 5 business days of delivery, an SLA alert (rule BR-13) is raised.' },
  { topic: 'Step 4', q: 'How do I export the handoff package?', a: 'In Step 4: Export & Handoff, choose Word, Excel, or JSON. Visio, Jira, and Azure DevOps exports are represented as a Development Backlog Item list you can import manually, per rule BR-14 (unsupported formats route to the manual export fallback).' },
  { topic: 'Governance', q: 'What are Business Rules, Controls, Risks, KPIs and Alerts?', a: 'These are DynamicBA\'s own governance layer (D03-D07): Business Rules define condition/action logic; Controls are preventive/detective safeguards; Risks are tracked with inherent/residual scores; KPIs measure the pipeline; Alerts notify the right role when a rule fires. See the Governance page for the full reference catalogue plus every instance raised on your projects.' },
  { topic: 'AI Use Cases', q: 'Is DynamicBA\'s AI autonomous?', a: 'No. Every AI Use Case is tiered Assistive or Augmented, never Autonomous, and every output is explainable and requires a named human checkpoint before it takes effect (see the AI Use Cases page).' },
  { topic: 'Licensing', q: 'What is included in my plan?', a: 'Starter includes SOW Ingestion only. Professional adds Context Enrichment, Process Discovery and Opportunity Assessment. Enterprise adds To-Be Design, Specs Generation and Validation & Handoff (the full pipeline). Pay-Per-Project buys the full pipeline for a single engagement. See Admin > Licensing.' },
  { topic: 'Licensing', q: 'What happens if I reach my user limit?', a: 'Once your Organization\'s member count reaches your plan\'s maxUsers, new sign-ups to join your Organization are rejected (enforced both in the app and by Firestore Security Rules). An admin can upgrade the plan from Admin > Licensing.' },
  { topic: 'Admin', q: 'How do I change a user\'s role?', a: 'Go to Admin > Users & Roles (org_admin only) and edit their assigned role(s). Changes take effect immediately for that user\'s next action.' },
  { topic: 'Recycle Bin', q: 'How do I recover a deleted project?', a: 'Go to Recycle Bin, find the project, and click Restore. Restoring a project keeps all of its artifacts and alert history intact.' },
]
