// src/lib/schema.js
// D09 Information Class Model (32 object classes) + D10 Data Dictionary (83 attributes),
// merged into one schema registry keyed by Object_Class_ID. This drives the generic,
// schema-driven Project Artifact Explorer (src/components/ArtifactExplorer.jsx) so every
// one of the 32 classes gets real CRUD without 32 bespoke page components.

export const OBJECT_CLASSES = [
  { id: 'OC-01', name: 'SOW', label: 'Statement of Work', desc: 'Signed Statement of Work document defining project scope, deliverables, and constraints.', mp: ['MP-01'] },
  { id: 'OC-02', name: 'Proposal', label: 'Proposal', desc: 'Commercial sales proposal preceding the signed SOW.', mp: ['MP-01'] },
  { id: 'OC-03', name: 'CRM_Record', label: 'CRM Record', desc: 'Client record and interaction history imported from the connected CRM system.', mp: ['MP-01'] },
  { id: 'OC-04', name: 'Client', label: 'Client', desc: 'The client organization engaging DynamicBA for a scope-to-specs project.', mp: ['MP-01', 'MP-02'] },
  { id: 'OC-05', name: 'Stakeholder', label: 'Stakeholder', desc: 'An individual with interest in, or influence over, the project (sponsor, SME, process owner).', mp: ['MP-01', 'MP-02'] },
  { id: 'OC-06', name: 'Client_Sponsor', label: 'Client Sponsor', desc: 'The client-side executive accountable for approving deliverables.', parent: 'Stakeholder', mp: ['MP-02', 'MP-07'] },
  { id: 'OC-07', name: 'SME_Interview', label: 'SME Interview', desc: 'A recorded or transcribed subject-matter-expert interview.', mp: ['MP-02', 'MP-03'] },
  { id: 'OC-08', name: 'Context_Model', label: 'Context Model', desc: "The structured knowledge model of the client's processes, systems, roles, and data.", mp: ['MP-02'] },
  { id: 'OC-09', name: 'System_Landscape', label: 'System Landscape', desc: "Diagram and inventory of the client's relevant IT systems.", mp: ['MP-02'] },
  { id: 'OC-10', name: 'Process_Inventory', label: 'Process Inventory', desc: 'Prioritized catalogue of client business processes in scope.', mp: ['MP-02', 'MP-03'] },
  { id: 'OC-11', name: 'As_Is_Process_Map', label: 'As-Is Process Map', desc: 'High-level process map (HLPM-AsIs) representing the current-state process.', mp: ['MP-03'] },
  { id: 'OC-12', name: 'Task_Repository_AsIs', label: 'Task Repository (As-Is)', desc: 'Task repository (TR-AsIs) detailing current-state tasks and steps.', mp: ['MP-03'] },
  { id: 'OC-13', name: 'Pain_Point', label: 'Pain Point', desc: 'A documented inefficiency, bottleneck, or issue observed in the current-state process.', mp: ['MP-03'] },
  { id: 'OC-14', name: 'Baseline_Metric', label: 'Baseline Metric', desc: 'A quantified current-state performance measure used to benchmark improvement.', mp: ['MP-03', 'MP-04'] },
  { id: 'OC-15', name: 'Automation_Candidate', label: 'Automation Candidate', desc: 'A process, task, or step identified as a candidate for automation.', mp: ['MP-04'] },
  { id: 'OC-16', name: 'Feasibility_Assessment', label: 'Feasibility Assessment', desc: 'Technical and data feasibility evaluation for an automation candidate.', mp: ['MP-04'] },
  { id: 'OC-17', name: 'ROI_Model', label: 'ROI Model', desc: 'Return-on-investment calculation for an automation candidate.', mp: ['MP-04'] },
  { id: 'OC-18', name: 'To_Be_Process_Map', label: 'To-Be Process Map', desc: 'Future-state process map (HLPM-ToBe) designed for a prioritized candidate.', mp: ['MP-05'] },
  { id: 'OC-19', name: 'Use_Case', label: 'Use Case', desc: 'A procedure describing a user or system interaction within the future-state process.', mp: ['MP-05', 'MP-06'] },
  { id: 'OC-20', name: 'Exception_Flow', label: 'Exception Flow', desc: 'A defined handling path for a process exception in the future-state design.', mp: ['MP-05'] },
  { id: 'OC-21', name: 'Integration_Point', label: 'Integration Point', desc: 'A system integration touchpoint required by the future-state process.', mp: ['MP-05', 'MP-06'] },
  { id: 'OC-22', name: 'Business_Rule_Spec', label: 'Business Rule Spec', desc: 'Formal specification of a business rule governing the future-state process.', mp: ['MP-05', 'MP-06'] },
  { id: 'OC-23', name: 'Control_Spec', label: 'Control Spec', desc: 'Formal specification of a governance control protecting the future-state process.', mp: ['MP-05', 'MP-06'] },
  { id: 'OC-24', name: 'Alert_Spec', label: 'Alert Spec', desc: 'Formal specification of an alert raised by the future-state process.', mp: ['MP-05', 'MP-06'] },
  { id: 'OC-25', name: 'KPI_Spec', label: 'KPI Spec', desc: 'Formal specification of a KPI measuring the future-state process.', mp: ['MP-04', 'MP-05', 'MP-06'] },
  { id: 'OC-26', name: 'Report_Spec', label: 'Report Spec', desc: 'Formal specification of a report or cockpit consuming process data.', mp: ['MP-05', 'MP-06'] },
  { id: 'OC-27', name: 'Risk_Opportunity', label: 'Risk / Opportunity', desc: 'A risk or opportunity register entry associated with the process.', mp: ['MP-03', 'MP-04', 'MP-05'] },
  { id: 'OC-28', name: 'Traceability_Link', label: 'Traceability Link', desc: 'An evidence link connecting a specified requirement to its source SOW or interview paragraph.', mp: ['MP-06'] },
  { id: 'OC-29', name: 'Spec_Package', label: 'Spec Package', desc: 'The consolidated Automation Spec Package deliverable assembled across all sections.', mp: ['MP-06', 'MP-07'] },
  { id: 'OC-30', name: 'Handoff_Package', label: 'Handoff Package', desc: 'The technical bundle handed off to the development team at project close.', parent: 'Spec_Package', mp: ['MP-07'] },
  { id: 'OC-31', name: 'Development_Backlog_Item', label: 'Development Backlog Item', desc: 'A backlog item derived from the spec package for the implementation team.', mp: ['MP-07'] },
  { id: 'OC-32', name: 'Client_SignOff', label: 'Client Sign-Off', desc: 'The e-signature record capturing client acceptance of the spec package.', mp: ['MP-07'] },
]

// Attribute types: string | integer | decimal | boolean | date | enum(...)
export const ATTRIBUTES = [
  { id: 'ATTR-0001', oc: 'OC-01', name: 'SOW_ID', type: 'string', required: true, rule: 'Must be unique; format SOW-YYYYMM-NNN' },
  { id: 'ATTR-0002', oc: 'OC-01', name: 'Status', type: 'enum', options: ['Draft', 'Ingested', 'Quality-Checked', 'Approved'], required: true, rule: 'Must be one of the defined enum values' },
  { id: 'ATTR-0003', oc: 'OC-01', name: 'Completeness_Score', type: 'integer', required: true, rule: 'Range 0-100' },
  { id: 'ATTR-0004', oc: 'OC-01', name: 'Signed_Date', type: 'date', required: true, rule: 'Must not be a future date' },
  { id: 'ATTR-0005', oc: 'OC-02', name: 'Proposal_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0006', oc: 'OC-02', name: 'Value_Amount', type: 'decimal', required: false, rule: 'Must be >= 0 when present' },
  { id: 'ATTR-0007', oc: 'OC-03', name: 'CRM_Record_ID', type: 'string', required: true, rule: 'Must match the source CRM record identifier format' },
  { id: 'ATTR-0008', oc: 'OC-03', name: 'Source_System', type: 'enum', options: ['Salesforce', 'HubSpot', 'Pipedrive'], required: true, rule: 'Must be one of the three supported CRM systems' },
  { id: 'ATTR-0009', oc: 'OC-04', name: 'Client_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0010', oc: 'OC-04', name: 'Client_Name', type: 'string', required: true, rule: 'Non-empty' },
  { id: 'ATTR-0011', oc: 'OC-04', name: 'Industry', type: 'string', required: false, rule: 'Free text; align to a recognized industry taxonomy where possible' },
  { id: 'ATTR-0012', oc: 'OC-05', name: 'Stakeholder_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0013', oc: 'OC-05', name: 'Name', type: 'string', required: true, rule: 'Non-empty' },
  { id: 'ATTR-0014', oc: 'OC-05', name: 'Role', type: 'string', required: true, rule: 'Non-empty; e.g. Process Owner, SME, IT Lead' },
  { id: 'ATTR-0015', oc: 'OC-05', name: 'Influence_Level', type: 'enum', options: ['Low', 'Medium', 'High'], required: false, rule: 'Must be one of the defined enum values when present' },
  { id: 'ATTR-0016', oc: 'OC-06', name: 'Client_Sponsor_ID', type: 'string', required: true, rule: 'Must be unique; shares the Stakeholder_ID namespace' },
  { id: 'ATTR-0017', oc: 'OC-06', name: 'Signing_Authority', type: 'boolean', required: true, rule: 'True/False' },
  { id: 'ATTR-0018', oc: 'OC-07', name: 'SME_Interview_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0019', oc: 'OC-07', name: 'Interview_Date', type: 'date', required: true, rule: 'Must not be a future date' },
  { id: 'ATTR-0020', oc: 'OC-07', name: 'Transcript_Status', type: 'enum', options: ['Pending', 'Transcribed', 'Validated'], required: true, rule: 'Must be one of the defined enum values' },
  { id: 'ATTR-0021', oc: 'OC-08', name: 'Context_Model_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0022', oc: 'OC-08', name: 'Completeness_Score', type: 'integer', required: true, rule: 'Range 0-100' },
  { id: 'ATTR-0023', oc: 'OC-08', name: 'Approved_Date', type: 'date', required: false, rule: "Must not precede the Context Model's creation date" },
  { id: 'ATTR-0024', oc: 'OC-09', name: 'System_Landscape_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0025', oc: 'OC-09', name: 'System_Count', type: 'integer', required: true, rule: 'Must be >= 0' },
  { id: 'ATTR-0026', oc: 'OC-10', name: 'Process_Inventory_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0027', oc: 'OC-10', name: 'Priority_Score', type: 'integer', required: false, rule: 'Range 0-100 when present' },
  { id: 'ATTR-0028', oc: 'OC-11', name: 'As_Is_Process_Map_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0029', oc: 'OC-11', name: 'Version', type: 'string', required: true, rule: 'Semantic version format, e.g. 1.0' },
  { id: 'ATTR-0030', oc: 'OC-11', name: 'Validated', type: 'boolean', required: true, rule: 'True/False' },
  { id: 'ATTR-0031', oc: 'OC-12', name: 'Task_Repository_AsIs_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0032', oc: 'OC-12', name: 'Task_Count', type: 'integer', required: true, rule: 'Must be >= 1' },
  { id: 'ATTR-0033', oc: 'OC-13', name: 'Pain_Point_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0034', oc: 'OC-13', name: 'Description', type: 'string', required: true, rule: 'Non-empty' },
  { id: 'ATTR-0035', oc: 'OC-13', name: 'Severity', type: 'enum', options: ['Low', 'Medium', 'High', 'Critical'], required: true, rule: 'Must be one of the defined enum values' },
  { id: 'ATTR-0036', oc: 'OC-14', name: 'Baseline_Metric_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0037', oc: 'OC-14', name: 'Metric_Name', type: 'string', required: true, rule: 'Non-empty' },
  { id: 'ATTR-0038', oc: 'OC-14', name: 'Value', type: 'decimal', required: true, rule: 'Must be >= 0' },
  { id: 'ATTR-0039', oc: 'OC-14', name: 'Unit', type: 'string', required: true, rule: 'Non-empty; e.g. hours, %, count' },
  { id: 'ATTR-0040', oc: 'OC-15', name: 'Automation_Candidate_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0041', oc: 'OC-15', name: 'Name', type: 'string', required: true, rule: 'Non-empty' },
  { id: 'ATTR-0042', oc: 'OC-15', name: 'Feasibility_Score', type: 'integer', required: true, rule: 'Range 0-100' },
  { id: 'ATTR-0043', oc: 'OC-16', name: 'Feasibility_Assessment_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0044', oc: 'OC-16', name: 'Data_Availability_Rating', type: 'enum', options: ['Low', 'Medium', 'High'], required: true, rule: 'Must be one of the defined enum values' },
  { id: 'ATTR-0045', oc: 'OC-17', name: 'ROI_Model_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0046', oc: 'OC-17', name: 'Payback_Months', type: 'decimal', required: true, rule: 'Must be >= 0' },
  { id: 'ATTR-0047', oc: 'OC-17', name: 'NPV', type: 'decimal', required: false, rule: 'May be negative' },
  { id: 'ATTR-0048', oc: 'OC-18', name: 'To_Be_Process_Map_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0049', oc: 'OC-18', name: 'Version', type: 'string', required: true, rule: 'Semantic version format, e.g. 1.0' },
  { id: 'ATTR-0050', oc: 'OC-18', name: 'Status', type: 'enum', options: ['Draft', 'Under Review', 'Approved'], required: true, rule: 'Must be one of the defined enum values' },
  { id: 'ATTR-0051', oc: 'OC-19', name: 'Use_Case_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0052', oc: 'OC-19', name: 'Name', type: 'string', required: true, rule: 'Non-empty' },
  { id: 'ATTR-0053', oc: 'OC-19', name: 'Status', type: 'enum', options: ['Draft', 'Detailed', 'Approved'], required: true, rule: 'Must be one of the defined enum values' },
  { id: 'ATTR-0054', oc: 'OC-20', name: 'Exception_Flow_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0055', oc: 'OC-20', name: 'Human_Checkpoint_Required', type: 'boolean', required: true, rule: 'True/False' },
  { id: 'ATTR-0056', oc: 'OC-21', name: 'Integration_Point_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0057', oc: 'OC-21', name: 'Target_System', type: 'string', required: true, rule: 'Non-empty' },
  { id: 'ATTR-0058', oc: 'OC-22', name: 'Business_Rule_Spec_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0059', oc: 'OC-22', name: 'Status', type: 'enum', options: ['Draft', 'Specified', 'Approved'], required: true, rule: 'Must be one of the defined enum values' },
  { id: 'ATTR-0060', oc: 'OC-22', name: 'Formula_Reference', type: 'string', required: false, rule: 'Must resolve to a Document 2 Formula_ID when present' },
  { id: 'ATTR-0061', oc: 'OC-23', name: 'Control_Spec_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0062', oc: 'OC-23', name: 'Type', type: 'enum', options: ['Preventive', 'Detective'], required: true, rule: 'Must be one of exactly two values' },
  { id: 'ATTR-0063', oc: 'OC-24', name: 'Alert_Spec_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0064', oc: 'OC-24', name: 'Severity', type: 'enum', options: ['Low', 'Medium', 'High', 'Critical'], required: true, rule: 'Must be one of the defined enum values' },
  { id: 'ATTR-0065', oc: 'OC-25', name: 'KPI_Spec_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0066', oc: 'OC-25', name: 'Target_Value', type: 'string', required: true, rule: 'Non-empty' },
  { id: 'ATTR-0067', oc: 'OC-26', name: 'Report_Spec_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0068', oc: 'OC-26', name: 'Refresh_Cadence', type: 'enum', options: ['Real-time', 'Daily', 'Weekly', 'Monthly', 'On Completion'], required: true, rule: 'Must be one of the defined enum values' },
  { id: 'ATTR-0069', oc: 'OC-27', name: 'Risk_Opportunity_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0070', oc: 'OC-27', name: 'Category', type: 'string', required: true, rule: 'Non-empty' },
  { id: 'ATTR-0071', oc: 'OC-28', name: 'Traceability_Link_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0072', oc: 'OC-28', name: 'Coverage_Percent', type: 'integer', required: true, rule: 'Range 0-100' },
  { id: 'ATTR-0073', oc: 'OC-28', name: 'Source_Paragraph_Ref', type: 'string', required: true, rule: 'Non-empty; cites the source document paragraph' },
  { id: 'ATTR-0074', oc: 'OC-29', name: 'Spec_Package_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0075', oc: 'OC-29', name: 'Section_Count', type: 'integer', required: true, rule: 'Must equal 6 at completion' },
  { id: 'ATTR-0076', oc: 'OC-30', name: 'Handoff_Package_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0077', oc: 'OC-30', name: 'Delivered_Date', type: 'date', required: false, rule: 'Must not be a future date when present' },
  { id: 'ATTR-0078', oc: 'OC-30', name: 'Format', type: 'enum', options: ['Word', 'Excel', 'Visio', 'Jira', 'Azure DevOps'], required: true, rule: 'Must be one of the defined enum values' },
  { id: 'ATTR-0079', oc: 'OC-31', name: 'Development_Backlog_Item_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0080', oc: 'OC-31', name: 'Priority', type: 'enum', options: ['Low', 'Medium', 'High'], required: true, rule: 'Must be one of the defined enum values' },
  { id: 'ATTR-0081', oc: 'OC-32', name: 'Client_SignOff_ID', type: 'string', required: true, rule: 'Must be unique' },
  { id: 'ATTR-0082', oc: 'OC-32', name: 'Status', type: 'enum', options: ['Pending', 'Signed', 'Declined'], required: true, rule: 'Must be one of the defined enum values' },
  { id: 'ATTR-0083', oc: 'OC-32', name: 'Signed_Date', type: 'date', required: false, rule: 'Required when Status = Signed' },
]

export function attributesFor(objectClassId) {
  return ATTRIBUTES.filter((a) => a.oc === objectClassId)
}

export function objectClassByName(name) {
  return OBJECT_CLASSES.find((c) => c.name === name)
}

// Every extra descriptive field every record also carries, regardless of class,
// so the generic Artifact Explorer always has something human-readable to show/search.
export const COMMON_FIELDS = ['title', 'notes']
