// src/lib/catalogue.js
// DynamicBA's own platform-defined reference catalogue — transcribed verbatim from the
// Core Business-Architecture Deliverables Workbook (D01-D10, D15, D26). This is global,
// read-only, non-tenant-scoped reference data: the same for every Organization, exactly
// like MASTER_PROCESSES in the sibling mySCM app.

// ---------------------------------------------------------------------------
// D01 — Macro Processes (7)
// ---------------------------------------------------------------------------
export const MACRO_PROCESSES = [
  { id: 'MP-01', name: 'SOW Ingestion & Understanding', objective: 'Accurately capture and interpret the signed SOW, extract key requirements, and identify gaps or ambiguities without manual setup or configuration.', trigger: 'Signed SOW and sales handoff package received from the account manager.', terminalState: 'Structured SOW Summary approved and project workspace created.', ownerRole: 'Lead Business Analyst', module: 'SOW Ingestion Module', moduleId: 'MOD-01' },
  { id: 'MP-02', name: 'Context Enrichment', objective: "Build a comprehensive understanding of the client's environment - processes, systems, roles, and data - without templates or configuration.", trigger: 'Approved SOW Summary from MP-01.', terminalState: 'Context Model, Stakeholder Map, and SME interview packs approved.', ownerRole: 'Business Analyst', module: 'Context Enrichment Module', moduleId: 'MOD-02' },
  { id: 'MP-03', name: 'Current-State Process Analysis', objective: 'Document the as-is state, identify pain points, and capture baseline metrics without manual transcription or mapping.', trigger: 'Approved Context Model and scheduled SME interview sessions.', terminalState: 'Current-State Report validated, with baselined process maps and metrics.', ownerRole: 'Senior Business Analyst', module: 'Process Discovery Module', moduleId: 'MOD-03' },
  { id: 'MP-04', name: 'Automation Opportunity Assessment', objective: 'Identify, evaluate, and prioritize automation candidates based on feasibility, ROI, and strategic alignment, with confidence scoring and consultant calibration.', trigger: 'Validated Current-State Report.', terminalState: 'Prioritized automation opportunity report approved by the steering committee.', ownerRole: 'Automation Consultant', module: 'Opportunity Assessment Module', moduleId: 'MOD-04' },
  { id: 'MP-05', name: 'To-Be Process Design', objective: 'Design the future-state process - maps, use cases, controls, alerts, rules, KPIs, and reporting - without heavy BPMN tooling.', trigger: 'Approved automation business case.', terminalState: 'Validated to-be design package covering all governance artifacts.', ownerRole: 'Solution Architect', module: 'To-Be Design Module', moduleId: 'MOD-05' },
  { id: 'MP-06', name: 'Automation Specs Generation', objective: 'Produce a complete, traceable, validated specification package that development teams can implement without ambiguity.', trigger: 'Validated to-be design package.', terminalState: 'Full specification package generated with an end-to-end traceability matrix.', ownerRole: 'Solution Architect', module: 'Specs Generation Module', moduleId: 'MOD-06' },
  { id: 'MP-07', name: 'Validation & Handoff', objective: 'Obtain client sign-off, baseline the specifications, and hand off a complete package to the development team with full traceability.', trigger: 'Complete specification package generated by MP-06.', terminalState: 'Client sign-off obtained and technical handoff package delivered.', ownerRole: 'Delivery Lead', module: 'Validation & Handoff Module', moduleId: 'MOD-07' },
]

export const RASCI_BY_MACRO_PROCESS = {
  'MP-01': { responsible: 'AI Engine (Consultant-Reviewed)', accountable: 'Lead Business Analyst', support: 'Platform Integration Engine', consulted: 'Sales Team / Account Manager', informed: 'Client Sponsor' },
  'MP-02': { responsible: 'AI Engine (Consultant-Reviewed)', accountable: 'Business Analyst', support: 'Platform Integration Engine', consulted: 'Client SMEs / IT Team', informed: 'Client Sponsor' },
  'MP-03': { responsible: 'AI Engine (Consultant-Reviewed)', accountable: 'Senior Business Analyst', support: 'Platform Transcription Engine', consulted: 'SME Interviewees / Process Owners', informed: 'Project Sponsor' },
  'MP-04': { responsible: 'AI Engine (Consultant-Reviewed)', accountable: 'Automation Consultant', support: 'N/A', consulted: 'IT Architects / Finance', informed: 'Steering Committee' },
  'MP-05': { responsible: 'AI Engine (Consultant-Reviewed)', accountable: 'Solution Architect', support: 'N/A', consulted: 'Automation Engineers / Compliance', informed: 'Process Owners' },
  'MP-06': { responsible: 'AI Engine (Consultant-Reviewed)', accountable: 'Solution Architect', support: 'N/A', consulted: 'Development Team / QA', informed: 'Client Sponsor' },
  'MP-07': { responsible: 'Client Portal Engine / Platform Export Engine', accountable: 'Delivery Lead', support: 'N/A', consulted: 'Development Team', informed: 'Project Sponsor' },
}

// User-facing 4-step wizard <-> internal macro process mapping
export const USER_FACING_STEPS = [
  { key: 'upload_sow', label: 'Upload SOW', macroProcesses: ['MP-01'] },
  { key: 'generate_spec', label: 'AI Generates Spec Package', macroProcesses: ['MP-02', 'MP-03', 'MP-04', 'MP-05', 'MP-06'] },
  { key: 'review_validate', label: 'Review & Validate', macroProcesses: ['MP-07'], stepRange: [1, 6] },
  { key: 'export_handoff', label: 'Export & Handoff', macroProcesses: ['MP-07'], stepRange: [7, 9] },
]

// ---------------------------------------------------------------------------
// D02 — Tasks & Steps (63)
// ---------------------------------------------------------------------------
const T = 'AI-Assisted Task', U = 'User Task', S = 'Service Task'
export const STEPS = [
  { id: 'MP-01.1', mp: 'MP-01', task: 'SOW Intake & Import', name: 'Upload SOW and Handoff Package', type: U, desc: 'Consultant uploads the signed SOW and sales handoff package into the workspace.', role: 'Lead Business Analyst' },
  { id: 'MP-01.2', mp: 'MP-01', task: 'SOW Intake & Import', name: 'Import Existing SOWs, Specs & Templates', type: S, desc: "The platform imports the client's or firm's existing SOWs, specs, and templates so DynamicBA learns the house style.", role: 'Platform Integration Engine' },
  { id: 'MP-01.3', mp: 'MP-01', task: 'SOW Intake & Import', name: 'Auto-Import CRM SOW Summary & Client Background', type: S, desc: 'The platform pulls client context, prior interactions, and background notes from the connected CRM system.', role: 'Platform Integration Engine' },
  { id: 'MP-01.4', mp: 'MP-01', task: 'SOW Parsing & Quality Check', name: 'Parse SOW Structure', type: T, desc: 'AI parses the SOW into its constituent sections (scope, deliverables, timeline, constraints).', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-01.5', mp: 'MP-01', task: 'SOW Parsing & Quality Check', name: 'Run Pre-Flight SOW Quality Check', type: T, desc: "AI assesses the SOW's clarity, completeness, and specificity and produces a completeness score.", role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-01.6', mp: 'MP-01', task: 'SOW Parsing & Quality Check', name: 'Generate Vague SOW Clarifying Questions', type: T, desc: 'AI drafts clarifying questions and flags assumptions for any SOW sections found to be vague or ambiguous.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-01.7', mp: 'MP-01', task: 'Requirement Extraction & Summary', name: 'Extract Objectives, Scope, Deliverables, Timeline & Constraints', type: T, desc: "AI extracts the SOW's core requirement elements into structured fields.", role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-01.8', mp: 'MP-01', task: 'Requirement Extraction & Summary', name: 'Identify Stakeholders, Systems & Processes', type: T, desc: 'AI identifies named stakeholders, systems, and processes referenced in the SOW and cross-references them against the proposal.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-01.9', mp: 'MP-01', task: 'Requirement Extraction & Summary', name: 'Produce Structured SOW Summary & Create Project Workspace', type: T, desc: 'AI produces the final structured SOW Summary and provisions a pre-populated project workspace for MP-02.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-02.1', mp: 'MP-02', task: 'Client Environment Data Collection', name: 'Ingest Client Responses & Additional Documents', type: S, desc: 'The platform ingests client responses to clarifying questions plus SOPs, org charts, and system diagrams.', role: 'Platform Integration Engine' },
  { id: 'MP-02.2', mp: 'MP-02', task: 'Client Environment Data Collection', name: 'Extract Process Names, Roles & System References', type: T, desc: "AI extracts named processes, roles, and system references from the ingested documents, in the client's working language.", role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-02.3', mp: 'MP-02', task: 'Client Environment Data Collection', name: 'Apply Industry Accelerator Patterns', type: T, desc: 'AI applies relevant patterns from the finance, healthcare, manufacturing, retail, or telecom accelerator packs.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-02.4', mp: 'MP-02', task: 'Context Modeling', name: 'Handle Missing-Stakeholder Edge Case', type: T, desc: 'AI flags process areas with no identified owner or sponsor and suggests targeted elicitation questions.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-02.5', mp: 'MP-02', task: 'Context Modeling', name: 'Handle Undocumented-Process Edge Case', type: T, desc: 'AI infers undocumented process detail from adjacent evidence and marks the resulting confidence level.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-02.6', mp: 'MP-02', task: 'Context Modeling', name: 'Build Context Knowledge Model', type: T, desc: 'AI assembles the extracted entities into a structured context knowledge model with a completeness score.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-02.7', mp: 'MP-02', task: 'Stakeholder & Interview Preparation', name: 'Generate Stakeholder Map', type: T, desc: 'AI generates a stakeholder map showing influence and interest for each identified stakeholder.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-02.8', mp: 'MP-02', task: 'Stakeholder & Interview Preparation', name: 'Generate System Landscape Diagram', type: T, desc: "AI generates a system landscape diagram of the client's relevant applications and integrations.", role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-02.9', mp: 'MP-02', task: 'Stakeholder & Interview Preparation', name: 'Prepare SME Interview Packs & Schedule Sessions', type: U, desc: 'Consultant reviews AI-prepared SME interview packs, approves them, and schedules the interview sessions.', role: 'Business Analyst' },
  { id: 'MP-03.1', mp: 'MP-03', task: 'Interview Capture & Synthesis', name: 'Transcribe SME Interviews', type: S, desc: 'The platform transcribes recorded SME interviews across supported languages.', role: 'Platform Transcription Engine' },
  { id: 'MP-03.2', mp: 'MP-03', task: 'Interview Capture & Synthesis', name: 'Summarize Interview Findings', type: T, desc: 'AI summarizes the key findings from each transcribed interview.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-03.3', mp: 'MP-03', task: 'Interview Capture & Synthesis', name: 'Extract Process Steps, Decisions & Exceptions', type: T, desc: 'AI extracts discrete process steps, decision points, and exceptions from the interview transcripts.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-03.4', mp: 'MP-03', task: 'As-Is Process Mapping', name: 'Draft As-Is Process Maps', type: T, desc: 'AI drafts as-is process maps from the extracted steps, decisions, and exceptions.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-03.5', mp: 'MP-03', task: 'As-Is Process Mapping', name: 'Validate Maps Against Transcripts', type: T, desc: 'AI validates the drafted maps against the source transcripts and flags inconsistencies.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-03.6', mp: 'MP-03', task: 'As-Is Process Mapping', name: 'Design HLPM-AsIs & TR-AsIs', type: T, desc: 'AI designs the High-Level Process Map and Task Repository for the current state.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-03.7', mp: 'MP-03', task: 'Baseline & Pain Point Analysis', name: 'Identify & Classify Pain Points', type: T, desc: 'AI identifies and classifies process pain points by severity and root cause.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-03.8', mp: 'MP-03', task: 'Baseline & Pain Point Analysis', name: 'Capture Baseline Metrics & Perform Waste Analysis', type: T, desc: 'AI captures baseline performance metrics and performs a waste analysis of the current-state process.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-03.9', mp: 'MP-03', task: 'Baseline & Pain Point Analysis', name: 'Produce Current-State Report', type: T, desc: 'AI produces the consolidated current-state report for consultant review.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-04.1', mp: 'MP-04', task: 'Candidate Identification & Scoring', name: 'Identify Automation Candidates', type: T, desc: 'AI identifies candidate processes, tasks, and steps for automation from the current-state report.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-04.2', mp: 'MP-04', task: 'Candidate Identification & Scoring', name: 'Define Feasibility Criteria', type: T, desc: 'AI proposes technical and data feasibility criteria for candidate scoring, subject to consultant sign-off.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-04.3', mp: 'MP-04', task: 'Candidate Identification & Scoring', name: 'Score Candidates Against Criteria', type: T, desc: 'AI scores each candidate against the agreed feasibility criteria.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-04.4', mp: 'MP-04', task: 'Feasibility & ROI Analysis', name: 'Assess Technical Feasibility & Data Quality', type: T, desc: 'AI assesses technical feasibility and underlying data availability and quality for each candidate.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-04.5', mp: 'MP-04', task: 'Feasibility & ROI Analysis', name: 'Estimate ROI per Candidate', type: T, desc: 'AI estimates the return on investment for each automation candidate.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-04.6', mp: 'MP-04', task: 'Feasibility & ROI Analysis', name: 'Build Prioritization Matrix', type: T, desc: 'AI builds a prioritization matrix combining feasibility, ROI, and strategic alignment.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-04.7', mp: 'MP-04', task: 'Risk, KPI & Business Case Definition', name: 'Assess & Prioritize Risks and Opportunities', type: T, desc: 'AI assesses and prioritizes the risks and opportunities associated with the shortlisted candidates.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-04.8', mp: 'MP-04', task: 'Risk, KPI & Business Case Definition', name: 'Define Target KPIs & Reporting Needs', type: T, desc: 'AI defines target KPIs and reporting needs for the prioritized candidates.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-04.9', mp: 'MP-04', task: 'Risk, KPI & Business Case Definition', name: 'Generate Automation Business Case with Confidence Calibration', type: T, desc: 'AI generates the automation business case; the consultant calibrates confidence scores and the model learns from the adjustment.', role: 'Automation Consultant' },
  { id: 'MP-05.1', mp: 'MP-05', task: 'Future-State Process Mapping', name: 'Select Candidates for Detailed Design', type: T, desc: 'AI shortlists prioritized candidates for detailed future-state design, subject to consultant confirmation.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-05.2', mp: 'MP-05', task: 'Future-State Process Mapping', name: 'Design HLPM-ToBe & HLF-ToBe', type: T, desc: 'AI designs the future-state High-Level Process Map and High-Level Flow.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-05.3', mp: 'MP-05', task: 'Future-State Process Mapping', name: 'Design TR-ToBe & LLF-ToBe', type: T, desc: 'AI designs the future-state Task Repository and Low-Level Flow.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-05.4', mp: 'MP-05', task: 'Control & Exception Design', name: 'Design Human-in-the-Loop Touchpoints & Exception Flows', type: T, desc: 'AI designs human-in-the-loop checkpoints and exception-handling flows for the future-state process.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-05.5', mp: 'MP-05', task: 'Control & Exception Design', name: 'Identify Integration Points & Data Inputs/Outputs', type: T, desc: 'AI identifies system integration points and defines data inputs and outputs for each future-state step.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-05.6', mp: 'MP-05', task: 'Control & Exception Design', name: 'Elaborate Use Cases (Procedures)', type: T, desc: "AI elaborates detailed use cases (procedures) describing each future-state interaction, in the client's working language.", role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-05.7', mp: 'MP-05', task: 'Governance Artifact Design', name: 'Design Alerts & Controls', type: T, desc: 'AI designs the alerts and governance controls that protect the future-state process.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-05.8', mp: 'MP-05', task: 'Governance Artifact Design', name: 'Refine Business Rules, Risks/Opportunities & KPIs', type: T, desc: 'AI refines the business rules, risk/opportunity entries, and KPIs first identified during current-state analysis.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-05.9', mp: 'MP-05', task: 'Governance Artifact Design', name: 'Design Reporting, RACI & Decision Log', type: T, desc: 'AI designs the reporting layer, drafts a RACI matrix, and generates a design-decision log.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-06.1', mp: 'MP-06', task: 'Functional & Data Specification', name: 'Generate Functional Requirements', type: T, desc: "AI generates functional requirements from the validated to-be design, in the client's working language.", role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-06.2', mp: 'MP-06', task: 'Functional & Data Specification', name: 'Specify Business Rules with Decision Tables', type: T, desc: 'AI specifies each business rule as a formal decision table.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-06.3', mp: 'MP-06', task: 'Functional & Data Specification', name: 'Generate Data Specifications', type: T, desc: 'AI generates data specifications aligned to the Information Class Model.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-06.4', mp: 'MP-06', task: 'Integration & Governance Specification', name: 'Generate Integration Specifications & NFRs', type: T, desc: 'AI generates integration specifications and non-functional requirements for the future-state process.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-06.5', mp: 'MP-06', task: 'Integration & Governance Specification', name: 'Specify Alerts with Triggers, Thresholds & Recipients', type: T, desc: "AI specifies each alert's trigger condition, threshold, and recipient list.", role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-06.6', mp: 'MP-06', task: 'Integration & Governance Specification', name: 'Specify Controls with Validation Rules & Audit Trails', type: T, desc: "AI specifies each control's validation rules and required audit trail.", role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-06.7', mp: 'MP-06', task: 'KPI, UAT & Traceability', name: 'Specify KPIs with Data Sources & Calculation Logic', type: T, desc: "AI specifies each KPI's data source and calculation logic.", role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-06.8', mp: 'MP-06', task: 'KPI, UAT & Traceability', name: 'Generate User Stories, Acceptance Criteria & UAT Scenarios', type: T, desc: 'AI generates user stories, acceptance criteria, and UAT scenarios for the development backlog.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-06.9', mp: 'MP-06', task: 'KPI, UAT & Traceability', name: 'Build Traceability Matrix with Paragraph-Level Evidence Links', type: T, desc: 'AI builds the traceability matrix, linking every requirement to its source SOW or interview paragraph.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-07.1', mp: 'MP-07', task: 'Internal Review & Packaging', name: 'Compile Full Spec Package for Review', type: U, desc: 'Consultant compiles the complete specification package (Sections 1-6) for internal quality review.', role: 'Delivery Lead' },
  { id: 'MP-07.2', mp: 'MP-07', task: 'Internal Review & Packaging', name: 'Generate Executive Summary for Sponsor', type: T, desc: 'AI generates an executive summary of the specification package for the client sponsor.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-07.3', mp: 'MP-07', task: 'Internal Review & Packaging', name: 'Generate Technical Handoff Package', type: T, desc: 'AI generates the technical handoff package for the development team.', role: 'AI Engine (Consultant-Reviewed)' },
  { id: 'MP-07.4', mp: 'MP-07', task: 'Client Sign-Off', name: 'Present Spec Package to Client Sponsor', type: U, desc: 'Delivery Lead presents the specification package and executive summary to the client sponsor.', role: 'Delivery Lead' },
  { id: 'MP-07.5', mp: 'MP-07', task: 'Client Sign-Off', name: 'Obtain Client Sign-Off via E-Signature', type: S, desc: 'The platform routes the package for client e-signature and captures the sign-off record.', role: 'Client Portal Engine' },
  { id: 'MP-07.6', mp: 'MP-07', task: 'Client Sign-Off', name: 'Log Acceptance & Money-Back Guarantee Status', type: S, desc: 'The platform logs client acceptance and closes out the money-back guarantee window.', role: 'Platform Integration Engine' },
  { id: 'MP-07.7', mp: 'MP-07', task: 'Handoff & Closeout', name: 'Export Package to Word, Excel, Visio, Jira & Azure DevOps', type: S, desc: "The platform exports the signed-off package to the client's or firm's chosen target formats and systems.", role: 'Platform Export Engine' },
  { id: 'MP-07.8', mp: 'MP-07', task: 'Handoff & Closeout', name: 'Publish Development Backlog', type: S, desc: 'The platform publishes the generated development backlog to the target project-tracking system.', role: 'Platform Integration Engine' },
  { id: 'MP-07.9', mp: 'MP-07', task: 'Handoff & Closeout', name: 'Produce Handoff Readiness Report & Time Savings Report', type: T, desc: 'AI produces the handoff readiness report and the engagement time-savings report.', role: 'AI Engine (Consultant-Reviewed)' },
]

// ---------------------------------------------------------------------------
// D03 — Business Rules (14) & D03a — Actions Registry (14)
// ---------------------------------------------------------------------------
export const ACTIONS = [
  { id: 'ACT-01', name: 'Flag SOW for Manual Structuring Review', type: 'Notification', target: 'SOW', desc: 'Marks the ingested SOW record for manual structuring review by a business analyst when automated parsing cannot resolve its section structure.' },
  { id: 'ACT-02', name: 'Generate Vague SOW Clarifying Question Set', type: 'Document Generation', target: 'SOW', desc: 'Creates a structured list of clarifying questions addressed to the client sponsor when SOW completeness falls below the configured threshold.' },
  { id: 'ACT-03', name: 'Flag Missing Stakeholder for Elicitation', type: 'Notification', target: 'Stakeholder', desc: 'Creates a placeholder stakeholder record and notifies the business analyst that a client sponsor or process owner must be identified.' },
  { id: 'ACT-04', name: 'Log Context Gap', type: 'Data Write', target: 'Context_Model', desc: 'Appends a context-gap entry to the Context Model record identifying the missing information element.' },
  { id: 'ACT-05', name: 'Flag Map Inconsistency for Consultant Review', type: 'Notification', target: 'As_Is_Process_Map', desc: 'Marks the affected as-is process map section for consultant validation when transcript and map step counts diverge by more than the configured tolerance.' },
  { id: 'ACT-06', name: 'Escalate High-Waste Process to Opportunity Backlog', type: 'Routing', target: 'Pain_Point', desc: 'Adds the associated pain point to the automation-opportunity backlog for prioritized assessment in MP-04.' },
  { id: 'ACT-07', name: 'Promote Candidate to Prioritization Matrix', type: 'Routing', target: 'Automation_Candidate', desc: 'Moves the automation candidate into the active prioritization matrix for ROI and strategic scoring.' },
  { id: 'ACT-08', name: 'Deprioritize Candidate to Strategic Backlog', type: 'Routing', target: 'Automation_Candidate', desc: 'Moves the automation candidate out of the near-term roadmap into the strategic (long-horizon) backlog.' },
  { id: 'ACT-09', name: 'Insert Mandatory Human Review Checkpoint', type: 'Data Write', target: 'Exception_Flow', desc: 'Inserts a mandatory human-in-the-loop checkpoint into the exception flow governing the affected step.' },
  { id: 'ACT-10', name: 'Attach Segregation-of-Duties Check', type: 'Data Write', target: 'Control_Spec', desc: 'Attaches a segregation-of-duties validation to a preventive control linked to a financial action.' },
  { id: 'ACT-11', name: 'Flag Formula as Pending Document 2 Registration', type: 'Notification', target: 'Business_Rule_Spec', desc: "Marks a rule's referenced formula as pending registration in Document 2's Formula Registry rather than fabricating a Formula_ID." },
  { id: 'ACT-12', name: 'Reject KPI Specification for Rework', type: 'Routing', target: 'KPI_Spec', desc: 'Returns the KPI specification to the authoring consultant when its data source cannot be resolved to the Information Class Model.' },
  { id: 'ACT-13', name: 'Trigger Delivery Lead Escalation', type: 'Notification', target: 'Client_SignOff', desc: 'Notifies the delivery lead when client sign-off is overdue against the five-business-day SLA.' },
  { id: 'ACT-14', name: 'Route Package to Manual Export Fallback', type: 'Routing', target: 'Handoff_Package', desc: 'Routes the export request to the manual export fallback process when the automated export engine does not support the requested target format.' },
]

export const BUSINESS_RULES = [
  { id: 'BR-01', step: 'MP-01.4', condition: 'Parsed SOW section count falls below the minimum structural threshold defined for the domain.', action: 'ACT-01', type: 'Validation' },
  { id: 'BR-02', step: 'MP-01.5', condition: 'Pre-flight SOW completeness score is below 70.', action: 'ACT-02', type: 'Escalation' },
  { id: 'BR-03', step: 'MP-02.4', condition: 'No client sponsor or process owner has been identified from the SOW or CRM data.', action: 'ACT-03', type: 'Escalation' },
  { id: 'BR-04', step: 'MP-02.6', condition: 'Context Model completeness score is below the configured minimum threshold.', action: 'ACT-04', type: 'Validation' },
  { id: 'BR-05', step: 'MP-03.5', condition: 'As-is process map step count deviates from the transcript step count by more than 10%.', action: 'ACT-05', type: 'Validation' },
  { id: 'BR-06', step: 'MP-03.8', condition: 'Baseline cycle time exceeds the applicable industry benchmark by more than 25%.', action: 'ACT-06', type: 'Escalation' },
  { id: 'BR-07', step: 'MP-04.3', condition: 'Composite feasibility score is at or above 80.', action: 'ACT-07', type: 'Routing' },
  { id: 'BR-08', step: 'MP-04.5', condition: 'Projected payback period exceeds 18 months.', action: 'ACT-08', type: 'Routing' },
  { id: 'BR-09', step: 'MP-05.4', condition: 'Step is classified as an AI-Assisted Task and processes client financial or personal data.', action: 'ACT-09', type: 'Routing' },
  { id: 'BR-10', step: 'MP-05.7', condition: 'Control type is Preventive and the control is linked to a financial action.', action: 'ACT-10', type: 'Validation' },
  { id: 'BR-11', step: 'MP-06.2', condition: "A business rule's KRI/KPI formula cites a Formula_ID not yet present in Document 2's Formula Registry.", action: 'ACT-11', type: 'Validation' },
  { id: 'BR-12', step: 'MP-06.7', condition: "A KPI's calculation logic cites a data source outside the approved Information Class Model.", action: 'ACT-12', type: 'Validation' },
  { id: 'BR-13', step: 'MP-07.5', condition: 'Client sign-off is not received within 5 business days of package delivery.', action: 'ACT-13', type: 'Escalation' },
  { id: 'BR-14', step: 'MP-07.7', condition: 'The requested export target format is unsupported by the current export engine.', action: 'ACT-14', type: 'Routing' },
]

// ---------------------------------------------------------------------------
// D04 — Controls (10)
// ---------------------------------------------------------------------------
export const CONTROLS = [
  { id: 'CTRL-01', name: 'SOW Completeness Gate', type: 'Preventive', steps: ['MP-01.5'], desc: 'Prevents progression to context enrichment until the pre-flight SOW quality check completeness score meets the minimum threshold.' },
  { id: 'CTRL-02', name: 'Vague SOW Human Review', type: 'Detective', steps: ['MP-01.6'], desc: 'Detects and surfaces vague or ambiguous SOW content for consultant clarification before requirement extraction proceeds.' },
  { id: 'CTRL-03', name: 'Stakeholder Completeness Check', type: 'Preventive', steps: ['MP-02.4'], desc: 'Prevents context modeling from completing until at least one client sponsor and one process owner are identified.' },
  { id: 'CTRL-04', name: 'Interview Transcript Accuracy Review', type: 'Detective', steps: ['MP-03.1'], desc: 'Detects transcription errors by sampling AI-generated transcripts against source recordings.' },
  { id: 'CTRL-05', name: 'As-Is Map Validation Gate', type: 'Preventive', steps: ['MP-03.5'], desc: 'Prevents an as-is process map from being finalized until it is validated against the underlying interview transcripts.' },
  { id: 'CTRL-06', name: 'ROI Estimate Sign-Off', type: 'Detective', steps: ['MP-04.5'], desc: 'Requires consultant sign-off on every AI-generated ROI estimate before it informs prioritization.' },
  { id: 'CTRL-07', name: 'Human-in-the-Loop Enforcement', type: 'Preventive', steps: ['MP-05.4'], desc: 'Prevents any AI-Assisted Task touching client financial or personal data from executing without a defined human checkpoint.' },
  { id: 'CTRL-08', name: 'Business Rule Formula Integrity Check', type: 'Detective', steps: ['MP-06.2'], desc: "Detects business rules whose free-text KRI/KPI formula does not match the expression registered under their Formula_ID." },
  { id: 'CTRL-09', name: 'Pre-Export Traceability Completeness Check', type: 'Preventive', steps: ['MP-06.9'], desc: 'Prevents package export until every requirement in the traceability matrix carries a paragraph-level evidence link.' },
  { id: 'CTRL-10', name: 'Client Sign-Off SLA Monitor', type: 'Detective', steps: ['MP-07.5'], desc: 'Detects sign-off requests that exceed the five-business-day SLA and triggers delivery-lead escalation.' },
]

// ---------------------------------------------------------------------------
// D05 — Risks (10)
// ---------------------------------------------------------------------------
export const RISKS = [
  { id: 'RISK-01', name: 'SOW Misinterpretation Risk', category: 'Delivery Quality', inherent: 4, residual: 2, controls: ['CTRL-01', 'CTRL-02'], kriFormula: 'Count of client-reported SOW misinterpretations / Total SOWs processed in period' },
  { id: 'RISK-02', name: 'Missing Stakeholder Blind Spot', category: 'Delivery Quality', inherent: 3, residual: 1, controls: ['CTRL-03'], kriFormula: 'Count of projects with a missing sponsor or process owner at kickoff / Total projects' },
  { id: 'RISK-03', name: 'Transcription Inaccuracy', category: 'Data Quality', inherent: 3, residual: 2, controls: ['CTRL-04'], kriFormula: 'Sample transcript word error rate (%)' },
  { id: 'RISK-04', name: 'As-Is Map Fidelity Risk', category: 'Data Quality', inherent: 4, residual: 2, controls: ['CTRL-05'], kriFormula: 'Percentage of as-is maps requiring consultant correction after validation' },
  { id: 'RISK-05', name: 'Overstated ROI Risk', category: 'Financial', inherent: 4, residual: 2, controls: ['CTRL-06'], kriFormula: 'Variance between AI-estimated and consultant-validated ROI (%)' },
  { id: 'RISK-06', name: 'Unsupervised AI Action on Sensitive Data', category: 'Compliance', inherent: 5, residual: 2, controls: ['CTRL-07'], kriFormula: 'Count of AI-Assisted steps executed on sensitive data without a human checkpoint' },
  { id: 'RISK-07', name: 'Business Rule / Formula Drift', category: 'Data Quality', inherent: 3, residual: 1, controls: ['CTRL-08'], kriFormula: 'Count of business rules with mismatched free-text and registered formulas' },
  { id: 'RISK-08', name: 'Incomplete Traceability at Export', category: 'Delivery Quality', inherent: 4, residual: 1, controls: ['CTRL-09'], kriFormula: 'Percentage of requirements missing a paragraph-level evidence link at export time' },
  { id: 'RISK-09', name: 'Client Sign-Off Delay Risk', category: 'Operational', inherent: 2, residual: 1, controls: ['CTRL-10'], kriFormula: 'Average days from package delivery to client sign-off' },
  { id: 'RISK-10', name: 'Hallucinated Requirement Risk', category: 'Data Quality', inherent: 5, residual: 2, controls: ['CTRL-02', 'CTRL-09'], kriFormula: 'Hallucination rate (%) - proportion of AI-asserted facts not traceable to a source paragraph' },
]

// ---------------------------------------------------------------------------
// D06 — KPIs (10)
// ---------------------------------------------------------------------------
export const KPIS = [
  { id: 'KPI-01', name: 'SOW-to-Summary Cycle Time', type: 'Operational', formula: 'Average hours from SOW upload to approved SOW Summary', target: '< 4 hours', mp: 'MP-01' },
  { id: 'KPI-02', name: 'SOW Completeness Score', type: 'Operational', formula: 'Weighted average of pre-flight quality dimensions (0-100)', target: '>= 85', mp: 'MP-01' },
  { id: 'KPI-03', name: 'Context Model Completeness Rate', type: 'Operational', formula: 'Percentage of required context fields populated at Context Model approval', target: '>= 95%', mp: 'MP-02' },
  { id: 'KPI-04', name: 'Current-State Report Cycle Time', type: 'Operational', formula: 'Average hours from first SME interview to approved Current-State Report', target: '< 24 hours', mp: 'MP-03' },
  { id: 'KPI-05', name: 'Automation Candidate Yield', type: 'Strategic', formula: 'Number of candidates scoring >= 80 feasibility / Total candidates identified', target: '>= 30%', mp: 'MP-04' },
  { id: 'KPI-06', name: 'Average Candidate ROI Payback', type: 'Strategic', formula: 'Average projected payback period (months) across prioritized candidates', target: '<= 12 months', mp: 'MP-04' },
  { id: 'KPI-07', name: 'To-Be Design Benchmark Quality', type: 'Strategic', formula: 'Consultant-rated quality score of AI-generated to-be design (%) vs. senior-consultant baseline', target: '>= 90%', mp: 'MP-05' },
  { id: 'KPI-08', name: 'Spec Package Traceability Coverage', type: 'Operational', formula: 'Percentage of specification requirements with a paragraph-level evidence link', target: '100%', mp: 'MP-06' },
  { id: 'KPI-09', name: 'Client Sign-Off Rate on First Submission', type: 'Strategic', formula: 'Percentage of spec packages accepted by the client without a rework cycle', target: '>= 80%', mp: 'MP-07' },
  { id: 'KPI-10', name: 'Total Consultant Hours Saved', type: 'Strategic', formula: 'Sum of (manual baseline hours - actual hours logged) across all macro processes per project', target: '>= 58 hours / project', mp: 'MP-07' },
]

// ---------------------------------------------------------------------------
// D07 — Alerts (8)
// ---------------------------------------------------------------------------
export const ALERTS_CATALOGUE = [
  { id: 'ALRT-01', rule: 'BR-02', severity: 'High', escalation: 'Business Analyst -> Delivery Lead', step: 'MP-01.5' },
  { id: 'ALRT-02', rule: 'BR-03', severity: 'Critical', escalation: 'Business Analyst -> Client Sponsor', step: 'MP-02.4' },
  { id: 'ALRT-03', rule: 'BR-06', severity: 'Medium', escalation: 'Business Analyst -> Automation Consultant', step: 'MP-03.8' },
  { id: 'ALRT-04', rule: 'BR-08', severity: 'Low', escalation: 'Automation Consultant -> Steering Committee', step: 'MP-04.5' },
  { id: 'ALRT-05', rule: 'BR-09', severity: 'Critical', escalation: 'Solution Architect -> Compliance Team', step: 'MP-05.4' },
  { id: 'ALRT-06', rule: 'BR-11', severity: 'Medium', escalation: 'Solution Architect -> Document 2 Registry Owner', step: 'MP-06.2' },
  { id: 'ALRT-07', rule: 'BR-13', severity: 'High', escalation: 'Delivery Lead -> Project Sponsor', step: 'MP-07.5' },
  { id: 'ALRT-08', rule: 'BR-14', severity: 'Medium', escalation: 'Delivery Lead -> Platform Operations', step: 'MP-07.7' },
]

// ---------------------------------------------------------------------------
// D08 — Reports / Cockpits (8)
// ---------------------------------------------------------------------------
export const REPORTS_CATALOGUE = [
  { id: 'RPT-01', name: 'SOW Intake Cockpit', audience: 'Business Analyst', cadence: 'Real-time', fields: ['SOW.Status', 'SOW.Completeness_Score', 'KPI-01', 'KPI-02'] },
  { id: 'RPT-02', name: 'Context & Stakeholder Dashboard', audience: 'Business Analyst', cadence: 'Daily', fields: ['Context_Model.Completeness_Score', 'Stakeholder.Role', 'KPI-03'] },
  { id: 'RPT-03', name: 'Current-State Analysis Report', audience: 'Process Owner', cadence: 'On Completion', fields: ['Baseline_Metric.Value', 'Pain_Point.Severity', 'KPI-04'] },
  { id: 'RPT-04', name: 'Opportunity Prioritization Cockpit', audience: 'Steering Committee', cadence: 'Weekly', fields: ['Automation_Candidate.Feasibility_Score', 'ROI_Model.Payback_Months', 'KPI-05', 'KPI-06'] },
  { id: 'RPT-05', name: 'To-Be Design Review Report', audience: 'Solution Architect', cadence: 'On Completion', fields: ['To_Be_Process_Map.Version', 'Use_Case.Status', 'KPI-07'] },
  { id: 'RPT-06', name: 'Spec Package Quality Cockpit', audience: 'Delivery Lead', cadence: 'Real-time', fields: ['Traceability_Link.Coverage_Percent', 'Business_Rule_Spec.Status', 'KPI-08'] },
  { id: 'RPT-07', name: 'Client Acceptance Dashboard', audience: 'Delivery Lead', cadence: 'Weekly', fields: ['Client_SignOff.Status', 'Client_SignOff.Signed_Date', 'KPI-09'] },
  { id: 'RPT-08', name: 'Engagement Time Savings Report', audience: 'Project Sponsor', cadence: 'Monthly', fields: ['KPI-10', 'Handoff_Package.Delivered_Date'] },
]

// ---------------------------------------------------------------------------
// D15 — AI Use Cases (16)
// ---------------------------------------------------------------------------
export const AI_USE_CASES = [
  { id: 'AIUC-01', name: 'SOW Structure Parsing', step: 'MP-01.4', taskType: 'Extraction', risk: 'Medium', checkpoint: 'Consultant reviews the parsed structure before extraction proceeds.', scope: 'Global', custom: false },
  { id: 'AIUC-02', name: 'Vague SOW Clarifying Question Generation', step: 'MP-01.6', taskType: 'Generation', risk: 'Medium', checkpoint: 'Consultant edits or approves generated questions before they are sent to the client.', scope: 'Global', custom: false },
  { id: 'AIUC-03', name: 'Requirement & Constraint Extraction', step: 'MP-01.7', taskType: 'Extraction', risk: 'Medium', checkpoint: 'Consultant validates extracted objectives, scope, and constraints.', scope: 'Global', custom: false },
  { id: 'AIUC-04', name: 'Industry Accelerator Pattern Matching', step: 'MP-02.3', taskType: 'Classification', risk: 'Low', checkpoint: "Consultant confirms the applied accelerator pack is relevant to the client's industry.", scope: 'Group', custom: false },
  { id: 'AIUC-05', name: 'Context Knowledge Model Construction', step: 'MP-02.6', taskType: 'Synthesis', risk: 'Medium', checkpoint: 'Consultant reviews the context model before stakeholder mapping proceeds.', scope: 'Global', custom: false },
  { id: 'AIUC-06', name: 'Stakeholder Map Generation', step: 'MP-02.7', taskType: 'Generation', risk: 'Low', checkpoint: 'Consultant adds any missing stakeholders before interview packs are issued.', scope: 'Global', custom: false },
  { id: 'AIUC-07', name: 'As-Is Process Map Drafting', step: 'MP-03.4', taskType: 'Generation', risk: 'Medium', checkpoint: 'Consultant validates maps against transcripts before baselining.', scope: 'Global', custom: false },
  { id: 'AIUC-08', name: 'Pain Point Identification & Classification', step: 'MP-03.7', taskType: 'Classification', risk: 'Low', checkpoint: 'Consultant confirms the severity classification assigned to each pain point.', scope: 'Global', custom: false },
  { id: 'AIUC-09', name: 'Automation Candidate Scoring', step: 'MP-04.3', taskType: 'Scoring', risk: 'Medium', checkpoint: 'Consultant reviews and calibrates confidence scores before candidates are prioritized.', scope: 'Global', custom: false },
  { id: 'AIUC-10', name: 'ROI Estimation', step: 'MP-04.5', taskType: 'Calculation', risk: 'High', checkpoint: 'Consultant validates the ROI estimate before it informs the automation business case.', scope: 'Global', custom: false },
  { id: 'AIUC-11', name: 'To-Be Process Map Design', step: 'MP-05.2', taskType: 'Generation', risk: 'Medium', checkpoint: 'Consultant validates to-be design decisions before governance artifacts are drafted.', scope: 'Global', custom: false },
  { id: 'AIUC-12', name: 'Use Case Elaboration', step: 'MP-05.6', taskType: 'Generation', risk: 'Low', checkpoint: 'Consultant reviews elaborated use cases before controls are attached.', scope: 'Global', custom: false },
  { id: 'AIUC-13', name: 'Business Rule Specification with Decision Tables', step: 'MP-06.2', taskType: 'Generation', risk: 'Medium', checkpoint: 'Consultant confirms rule logic and formula references before specification is finalized.', scope: 'Global', custom: false },
  { id: 'AIUC-14', name: 'KPI Specification', step: 'MP-06.7', taskType: 'Generation', risk: 'Medium', checkpoint: "Consultant confirms each KPI's data source and target before specification is finalized.", scope: 'Global', custom: false },
  { id: 'AIUC-15', name: 'Traceability Matrix Construction', step: 'MP-06.9', taskType: 'Synthesis', risk: 'High', checkpoint: 'Consultant spot-checks paragraph-level evidence links before export.', scope: 'Global', custom: false },
  { id: 'AIUC-16', name: 'Client-Specific Retail Accelerator (Custom)', step: 'MP-02.3', taskType: 'Classification', risk: 'Low', checkpoint: 'Consultant approves the custom accelerator pack before it is applied to a live project.', scope: 'Project', custom: true, basedOn: 'AIUC-04', approvalStatus: 'Pending Approval' },
]

// ---------------------------------------------------------------------------
// D26 — Modules & Tiers (8 modules / 4 tiers)
// ---------------------------------------------------------------------------
export const MODULES = [
  { id: 'MOD-01', name: 'SOW Ingestion Module', tier: 'starter', model: 'Subscription', macroProcesses: ['MP-01'], rateLimit: '20 SOWs / month' },
  { id: 'MOD-02', name: 'Context Enrichment Module', tier: 'professional', model: 'Subscription', macroProcesses: ['MP-02'], rateLimit: '15 context models / month' },
  { id: 'MOD-03', name: 'Process Discovery Module', tier: 'professional', model: 'Subscription', macroProcesses: ['MP-03'], rateLimit: '15 current-state analyses / month' },
  { id: 'MOD-04', name: 'Opportunity Assessment Module', tier: 'professional', model: 'Subscription', macroProcesses: ['MP-04'], rateLimit: '15 opportunity assessments / month' },
  { id: 'MOD-05', name: 'To-Be Design Module', tier: 'enterprise', model: 'Subscription', macroProcesses: ['MP-05'], rateLimit: 'Unlimited within contracted project cap' },
  { id: 'MOD-06', name: 'Specs Generation Module', tier: 'enterprise', model: 'Subscription', macroProcesses: ['MP-06'], rateLimit: 'Unlimited within contracted project cap' },
  { id: 'MOD-07', name: 'Validation & Handoff Module', tier: 'enterprise', model: 'Subscription', macroProcesses: ['MP-07'], rateLimit: 'Unlimited within contracted project cap' },
  { id: 'MOD-08', name: 'Full Scope-to-Specs Pay-Per-Project Bundle', tier: 'pay_per_project', model: 'Per-Project', macroProcesses: ['MP-01', 'MP-02', 'MP-03', 'MP-04', 'MP-05', 'MP-06', 'MP-07'], rateLimit: '1 project per purchase' },
]

// Cumulative plan -> module entitlement (Starter modules included in Professional, etc.)
// Decision recorded for Open Question #11 (D26 vs D30 reconciliation): each subscription
// tier is treated as cumulative/inclusive of the tiers below it, so a customer only ever
// holds one active plan and always has a usable, end-to-end pipeline once on Enterprise.
export const PLAN_MODULES = {
  starter: ['MOD-01'],
  professional: ['MOD-01', 'MOD-02', 'MOD-03', 'MOD-04'],
  enterprise: ['MOD-01', 'MOD-02', 'MOD-03', 'MOD-04', 'MOD-05', 'MOD-06', 'MOD-07'],
  pay_per_project: ['MOD-08'],
}

export const PLAN_LABELS = {
  starter: 'Starter',
  professional: 'Professional',
  enterprise: 'Enterprise',
  pay_per_project: 'Pay-Per-Project',
}

export function alertForRule(ruleId) {
  return ALERTS_CATALOGUE.find((a) => a.rule === ruleId)
}

export function macroProcessAllowedByPlan(plan, macroProcessId) {
  const modIds = PLAN_MODULES[plan] || []
  if (plan === 'pay_per_project') return true // MOD-08 covers MP-01..MP-07 for the purchased project
  return MODULES.some((m) => modIds.includes(m.id) && m.macroProcesses.includes(macroProcessId))
}
