// src/lib/reportContent.js
// Builds the DynamicBA Automation Specification Package as a neutral list of content
// "blocks" consumed by both the Word and PDF renderers (src/lib/reportRenderers.js), so
// the two formats are always structurally identical, per D10's own OC-29 Spec_Package
// definition (ATTR-0075: Section_Count must equal 6 at completion). Sections 1-6 below
// are that canonical structure; Section 7 (Validation & Handoff) and the appendices are
// the wrapper material a real handoff package ships alongside it.
//
// The appendices reproduce DynamicBA's own platform reference catalogue (process model,
// governance catalogue, AI use case library, canonical data dictionary, licensing model)
// in full — this is real, non-fabricated system documentation, not padding: a
// specification package is expected to carry the standards it was built against.
import {
  MACRO_PROCESSES, STEPS, RASCI_BY_MACRO_PROCESS, BUSINESS_RULES, ACTIONS, CONTROLS,
  RISKS, KPIS, ALERTS_CATALOGUE, REPORTS_CATALOGUE, AI_USE_CASES, MODULES, PLAN_LABELS,
} from './catalogue'
import { OBJECT_CLASSES, ATTRIBUTES } from './schema'

function fmtMoney(n) { return n || n === 0 ? `$${Number(n).toLocaleString()}` : '—' }
function fmtList(arr, fn) { return (arr || []).map(fn) }
function y(text) { return { type: 'h1', text } }
function y2(text) { return { type: 'h2', text } }
function y3(text) { return { type: 'h3', text } }
function p(text) { return { type: 'p', text } }
function bullets(items) { return { type: 'bullets', items } }
function table(headers, rows, widths) { return { type: 'table', headers, rows, widths } }
function pagebreak() { return { type: 'pagebreak' } }
function caption(text) { return { type: 'caption', text } }

export function buildReportBlocks(project, b) {
  const B = []
  const add = (...items) => B.push(...items)
  const candidates = b.candidates || []
  const stakeholders = b.stakeholders || []
  const sponsor = stakeholders.find((s) => /sponsor/i.test(s.Role || '')) || stakeholders[0]

  // =========================================================================
  add(y('Executive Summary'))
  add(p(`This Automation Specification Package documents the "${project.name}" engagement end to end: the signed Statement of Work, the client context and current-state analysis behind it, the automation opportunities assessed and prioritized, the future-state design and governance model produced for the accepted opportunities, the resulting automation specifications, and the traceability linking every specified requirement back to its source. It was produced by DynamicBA's scope-to-specs pipeline under a human-in-the-loop review model: every score, classification, and generated artifact in this package was computed by a deterministic, explainable rule engine and reviewed by the consulting team named on the cover page before being included here — nothing in this document was generated by an unreviewable model.`))
  add(p(`Engagement status at the time this package was generated: ${project.status === 'completed' ? 'Complete — client sign-off obtained and the technical handoff package delivered to the development team.' : project.status === 'in_progress' ? 'In progress — the engagement is still moving through the four-step pipeline.' : 'Not yet started beyond SOW intake.'} ${candidates.length} automation candidate(s) were assessed, of which ${candidates.filter((c) => c.Feasibility_Score >= 80).length} scored at or above the 80-point feasibility threshold DynamicBA uses to promote a candidate into the active prioritization matrix (rule BR-07).`))
  add(table(
    ['Metric', 'Value'],
    [
      ['Client Sponsor', sponsor?.Name || '—'],
      ['SOW Completeness Score', b.sow ? `${b.sow.Completeness_Score}/100` : '—'],
      ['Automation Candidates Assessed', String(candidates.length)],
      ['Use Cases Elaborated', String((b.useCases || []).length)],
      ['Business Rule Specifications', String((b.ruleSpecs || []).length)],
      ['KPI Specifications', String((b.kpiSpecs || []).length)],
      ['Traceability Links Recorded', String((b.traceabilityLinks || []).length)],
      ['Client Sign-Off Status', b.signOff?.Status || 'Pending'],
      ['Consultant Hours Saved (KPI-10)', project.hoursSaved != null ? String(project.hoursSaved) : '—'],
    ],
    [4500, 5040],
  ))
  add(pagebreak())

  // =========================================================================
  add(y('Section 1 of 6 — Statement of Work'))
  add(p('This section reproduces the Statement of Work as ingested and quality-checked in MP-01 (SOW Ingestion & Understanding), together with the stakeholder register DynamicBA validated against it (control CTRL-03, Stakeholder Completeness Check).'))
  add(y2('1.1 Engagement Objectives, Scope & Deliverables'))
  add(p(`Objectives: ${b.sow?.objectives || 'Not yet recorded.'}`))
  add(p(`Scope: ${b.sow?.scope || 'Not yet recorded.'}`))
  add(p(`Deliverables: ${b.sow?.deliverables || 'Not yet recorded.'}`))
  add(p(`Timeline: ${b.sow?.timeline || 'Not yet recorded.'}`))
  add(p(`Constraints: ${b.sow?.constraints || 'Not yet recorded.'}`))
  add(y2('1.2 SOW Quality Assessment'))
  add(p(`DynamicBA's pre-flight quality check (rule BR-02, control CTRL-01) scored this SOW at ${b.sow?.Completeness_Score ?? '—'} out of 100. ${b.sow?.Completeness_Score >= 70 ? 'This meets the minimum threshold of 70 required to proceed to context enrichment without a clarification cycle.' : 'This fell below the minimum threshold of 70, and a clarifying-question cycle with the client sponsor was required before the engagement proceeded (rule BR-02, action ACT-02).'} SOW status is currently recorded as "${b.sow?.Status || 'Draft'}".`))
  add(y2('1.3 Stakeholder Register'))
  add(table(['Name', 'Role', 'Influence'], stakeholders.length ? stakeholders.map((s) => [s.Name, s.Role, s.Influence_Level || '—']) : [['—', '—', '—']], [3200, 3200, 3140]))
  add(pagebreak())

  // =========================================================================
  add(y('Section 2 of 6 — Context & Stakeholder Landscape'))
  add(p('This section documents MP-02 (Context Enrichment): the client’s systems, processes, and organizational context DynamicBA assembled into a structured Context Knowledge Model, validated against control CTRL-03 (at least one client sponsor and one process owner identified).'))
  add(y2('2.1 Context Model'))
  add(p(`Context Model completeness score: ${b.contextModel?.Completeness_Score ?? '—'}/100. ${b.contextModel?.Completeness_Score >= 70 ? 'This clears the minimum threshold for context enrichment to be considered complete.' : 'This has not yet cleared the minimum completeness threshold of 70 (rule BR-04); further systems, processes, or stakeholders should be captured.'}`))
  add(y2('2.2 System Landscape'))
  add((b.systemLandscape || []).length ? table(['System'], b.systemLandscape.map((s) => [s.System_Landscape_ID]), [9540]) : p('No system landscape entries recorded yet.'))
  add(pagebreak())

  // =========================================================================
  add(y('Section 3 of 6 — Current-State Analysis'))
  add(p('This section documents MP-03 (Current-State Process Analysis): the as-is process map validated against source interview transcripts (control CTRL-05), the pain points identified and severity-classified, and the baseline performance metrics used to benchmark improvement.'))
  add(y2('3.1 As-Is Process Map'))
  add(p(`As-is process map version ${b.asIsMap?.Version || '1.0'} is recorded as ${b.asIsMap?.Validated ? 'validated against the underlying interview transcripts.' : 'not yet validated against the underlying interview transcripts (control CTRL-05).'}`))
  add(y2('3.2 Pain Points'))
  add((b.painPoints || []).length ? table(['Description', 'Severity'], b.painPoints.map((pp) => [pp.Description, pp.Severity]), [7040, 2500]) : p('No pain points recorded yet.'))
  add(y2('3.3 Baseline Metrics'))
  add((b.baselineMetrics || []).length ? table(['Metric', 'Value', 'Unit'], b.baselineMetrics.map((m) => [m.Metric_Name, String(m.Value), m.Unit]), [4500, 2500, 2540]) : p('No baseline metrics recorded yet.'))
  add(pagebreak())

  // =========================================================================
  add(y('Section 4 of 6 — Automation Opportunity Assessment & Business Case'))
  add(p('This section documents MP-04 (Automation Opportunity Assessment): every candidate scored against DynamicBA’s composite feasibility formula (30% technical feasibility, 25% data quality, 20% process stability, 25% strategic fit) and its return-on-investment model, with the prioritization decision each candidate received under rules BR-07 (promote at feasibility ≥ 80) and BR-08 (deprioritize at payback > 18 months).'))
  if (!candidates.length) {
    add(p('No automation candidates have been scored on this engagement yet.'))
  } else {
    candidates.forEach((c, i) => {
      const roi = (b.roiModels || [])[i] || {}
      const fa = (b.feasibilityAssessments || [])[i] || {}
      const decision = c.Feasibility_Score >= 80 ? 'Promoted to the active prioritization matrix (rule BR-07: feasibility ≥ 80).' : roi.Payback_Months > 18 ? 'Deprioritized to the strategic backlog (rule BR-08: payback exceeds 18 months).' : 'Retained for further evaluation — neither auto-promoted nor deprioritized under the current thresholds.'
      add(y3(`4.${i + 1} Candidate: ${c.Name}`))
      add(p(`Composite Feasibility Score: ${c.Feasibility_Score}/100. Data Availability Rating: ${fa.Data_Availability_Rating || '—'}. Projected ROI Payback: ${roi.Payback_Months ?? '—'} months. Three-year Net Present Value (undiscounted, per the interim formula pending Document 2’s Formula Registry): ${fmtMoney(roi.NPV)}.`))
      add(p(`Prioritization decision: ${decision}`))
    })
  }
  add(pagebreak())

  // =========================================================================
  add(y('Section 5 of 6 — To-Be Design & Governance'))
  add(p('This section documents MP-05 (To-Be Process Design): the future-state process map, its elaborated use cases and integration points, the human-in-the-loop exception handling designed for AI-assisted steps touching sensitive data (control CTRL-07, rule BR-09), the preventive/detective controls protecting the future-state process (rule BR-10 for controls linked to a financial action), and the risk/opportunity register.'))
  add(y2('5.1 Future-State Process Map'))
  add(p(`Future-state process map version ${b.toBeMap?.Version || '1.0'}, status: ${b.toBeMap?.Status || 'Draft'}.`))
  add(y2('5.2 Use Cases'))
  add((b.useCases || []).length ? table(['Use Case', 'Status'], b.useCases.map((u) => [u.Name, u.Status]), [7040, 2500]) : p('No use cases elaborated yet.'))
  add(y2('5.3 Integration Points'))
  add((b.integrationPoints || []).length ? table(['Target System'], b.integrationPoints.map((i) => [i.Target_System]), [9540]) : p('No integration points recorded yet.'))
  add(y2('5.4 Exception Flows & Human-in-the-Loop Checkpoints'))
  add((b.exceptionFlows || []).length ? table(['AI-Assisted', 'Handles Sensitive Data', 'Human Checkpoint Required'], b.exceptionFlows.map((e) => [e.isAiAssisted || e.Human_Checkpoint_Required !== undefined ? String(!!e.isAiAssisted) : '—', String(!!e.handlesSensitiveData), String(!!e.Human_Checkpoint_Required)]), [3180, 3180, 3180]) : p('No exception flows recorded yet.'))
  add(y2('5.5 Control Specifications'))
  add((b.controlSpecs || []).length ? table(['Type', 'Linked to Financial Action'], b.controlSpecs.map((c) => [c.Type, String(!!c.linkedToFinancialAction)]), [4770, 4770]) : p('No control specifications recorded yet.'))
  add(y2('5.6 Risk / Opportunity Register'))
  add((b.risks || []).length ? table(['Category'], b.risks.map((r) => [r.Category]), [9540]) : p('No risks or opportunities recorded yet.'))
  add(pagebreak())

  // =========================================================================
  add(y('Section 6 of 6 — Automation Specifications & Traceability'))
  add(p('This section documents MP-06 (Automation Specs Generation): the formal business rule and KPI specifications, alert and report specifications, and the paragraph-level traceability matrix linking every specified requirement back to its source SOW or interview paragraph (control CTRL-09: export is gated on 100% traceability coverage).'))
  add(y2('6.1 Business Rule Specifications'))
  add((b.ruleSpecs || []).length ? table(['Rule Spec', 'Status'], b.ruleSpecs.map((r) => [r.Business_Rule_Spec_ID, r.Status]), [7040, 2500]) : p('No business rule specifications recorded yet.'))
  add(y2('6.2 KPI Specifications'))
  add((b.kpiSpecs || []).length ? table(['KPI Spec', 'Target Value', 'Data Source'], b.kpiSpecs.map((k) => [k.KPI_Spec_ID, k.Target_Value, k.dataSource || '—']), [3180, 3180, 3180]) : p('No KPI specifications recorded yet.'))
  add(y2('6.3 Alert Specifications'))
  add((b.alertSpecs || []).length ? table(['Severity'], b.alertSpecs.map((a) => [a.Severity]), [9540]) : p('No alert specifications recorded yet.'))
  add(y2('6.4 Report Specifications'))
  add((b.reportSpecs || []).length ? table(['Refresh Cadence'], b.reportSpecs.map((r) => [r.Refresh_Cadence]), [9540]) : p('No report specifications recorded yet.'))
  add(y2('6.5 Traceability Matrix'))
  const coverage = (b.traceabilityLinks || []).length ? Math.round(b.traceabilityLinks.reduce((s, t) => s + (t.Coverage_Percent || 0), 0) / b.traceabilityLinks.length) : 0
  add(p(`Aggregate traceability coverage across ${(b.traceabilityLinks || []).length} recorded link(s): ${coverage}%. ${coverage >= 100 ? 'This satisfies control CTRL-09’s pre-export completeness gate.' : 'This has not yet reached the 100% coverage control CTRL-09 requires before export.'}`))
  add((b.traceabilityLinks || []).length ? table(['Coverage %', 'Source Paragraph Reference'], b.traceabilityLinks.map((t) => [String(t.Coverage_Percent), t.Source_Paragraph_Ref]), [3180, 6360]) : p('No traceability links recorded yet.'))
  add(pagebreak())

  // =========================================================================
  add(y('Section 7 — Validation, Sign-Off & Handoff Record'))
  add(p('This section documents MP-07 (Validation & Handoff): compilation of the full package for internal review, presentation to the client sponsor, e-signature capture, the five-business-day sign-off SLA (control CTRL-10), and the technical handoff to the development team.'))
  add(y2('7.1 Client Sign-Off'))
  add(p(`Sign-off status: ${b.signOff?.Status || 'Pending'}.${b.signOff?.Signed_Date ? ` Signed on ${b.signOff.Signed_Date} by ${project.signOffSponsor || sponsor?.Name || 'the client sponsor'}.` : ''}`))
  add(y2('7.2 Handoff Package'))
  add(p(`Handoff package ${b.handoffPackage ? `delivered on ${b.handoffPackage.Delivered_Date} in ${b.handoffPackage.Format} format.` : 'has not yet been generated.'}`))
  add(y2('7.3 Development Backlog'))
  add((b.backlogItems || []).length ? table(['Backlog Item', 'Priority'], b.backlogItems.map((i) => [i.Development_Backlog_Item_ID, i.Priority]), [7040, 2500]) : p('No backlog items published yet.'))
  add(y2('7.4 Governance Alerts Raised on This Engagement'))
  add((b.projectAlerts || []).length
    ? table(['Alert', 'Rule', 'Severity', 'Detail'], b.projectAlerts.map((a) => [a.alertId, a.ruleId, a.severity, a.detail]), [1200, 1200, 1200, 5940])
    : p('No governance alerts have been raised on this engagement.'))
  add(pagebreak())

  // =========================================================================================
  // APPENDICES — full platform reference documentation, included with every handoff package.
  // =========================================================================================
  add(y('Appendix A — DynamicBA Process Catalogue Reference (D01/D02)'))
  add(p('DynamicBA runs every engagement through the same 7 internal macro processes, decomposed into 63 executable steps. This appendix reproduces that full reference catalogue, including the RASCI accountability assigned to each macro process, so the handoff package is self-contained and traceable to the platform’s own process model.'))
  MACRO_PROCESSES.forEach((mp, idx) => {
    const rasci = RASCI_BY_MACRO_PROCESS[mp.id]
    add(y2(`${mp.id} — ${mp.name}`))
    add(p(`Objective: ${mp.objective}`))
    add(p(`Trigger: ${mp.trigger} Terminal State: ${mp.terminalState} Owner Role: ${mp.ownerRole}.`))
    add(table(['Responsible', 'Accountable', 'Support', 'Consulted', 'Informed'], [[rasci.responsible, rasci.accountable, rasci.support, rasci.consulted, rasci.informed]], [1908, 1908, 1908, 1908, 1908]))
    const steps = STEPS.filter((s) => s.mp === mp.id)
    add(table(['Step', 'Name', 'Type', 'Role'], steps.map((s) => [s.id, s.name, s.type, s.role]), [1200, 4340, 1800, 2200]))
    if (idx < MACRO_PROCESSES.length - 1) add(pagebreak())
  })
  add(pagebreak())

  add(y('Appendix B — Governance Catalogue Reference (D03–D08)'))
  add(p('DynamicBA’s governance layer — the business rules, controls, risks, KPIs, alerts, and reports that ran throughout this engagement — is reproduced here in full so any governance alert cited in Section 7.4 can be traced back to its defining rule, action, and control.'))
  add(y2('B.1 Business Rules (D03)'))
  add(table(['Rule', 'Triggering Step', 'Condition', 'Type'], BUSINESS_RULES.map((r) => [r.id, r.step, r.condition, r.type]), [900, 1400, 5940, 1300]))
  add(pagebreak())
  add(y2('B.2 Actions Registry (D03a)'))
  add(table(['Action', 'Name', 'Type', 'Description'], ACTIONS.map((a) => [a.id, a.name, a.type, a.desc]), [900, 2300, 1500, 4840]))
  add(pagebreak())
  add(y2('B.3 Controls (D04)'))
  add(table(['Control', 'Name', 'Type', 'Description'], CONTROLS.map((c) => [c.id, c.name, c.type, c.desc]), [900, 2200, 1300, 5140]))
  add(pagebreak())
  add(y2('B.4 Risk Register (D05)'))
  add(table(['Risk', 'Name', 'Category', 'Inherent', 'Residual'], RISKS.map((r) => [r.id, r.name, r.category, String(r.inherent), String(r.residual)]), [900, 2840, 2000, 1900, 1900]))
  add(pagebreak())
  add(y2('B.5 KPIs (D06)'))
  add(table(['KPI', 'Name', 'Type', 'Target'], KPIS.map((k) => [k.id, k.name, k.type, k.target]), [900, 3340, 1500, 3800]))
  add(pagebreak())
  add(y2('B.6 Alerts (D07)'))
  add(table(['Alert', 'Rule', 'Severity', 'Escalation Path'], ALERTS_CATALOGUE.map((a) => [a.id, a.rule, a.severity, a.escalation]), [900, 900, 1400, 6340]))
  add(pagebreak())
  add(y2('B.7 Reports / Cockpits (D08)'))
  add(table(['Report', 'Name', 'Audience', 'Cadence'], REPORTS_CATALOGUE.map((r) => [r.id, r.name, r.audience, r.cadence]), [900, 3840, 2400, 2400]))
  add(pagebreak())

  add(y('Appendix C — AI Use Case Governance Library (D15)'))
  add(p('Every AI-assisted step in this engagement ran under one of the 16 governed AI Use Cases below. Each is tiered Assistive or Augmented — never Autonomous — and carries a named human checkpoint, per DynamicBA’s AI governance architecture.'))
  add(table(['Use Case', 'Name', 'Step', 'Risk', 'Human Checkpoint'], AI_USE_CASES.map((u) => [u.id, u.name, u.step, u.risk, u.checkpoint]), [900, 2340, 1200, 900, 4200]))
  add(pagebreak())

  add(y('Appendix D — Canonical Data Dictionary (D09/D10)'))
  add(p('Every artifact in this package is an instance of one of DynamicBA’s 32 canonical object classes. This appendix reproduces the full Information Class Model and attribute-level data dictionary, so any field cited above can be checked against its authoritative definition and validation rule.'))
  OBJECT_CLASSES.forEach((oc, idx) => {
    const attrs = ATTRIBUTES.filter((a) => a.oc === oc.id)
    add(y3(`${oc.id} — ${oc.label}`))
    add(p(oc.desc))
    add(table(['Attribute', 'Type', 'Required', 'Validation Rule'], attrs.map((a) => [a.name, a.type, a.required ? 'Yes' : 'No', a.rule]), [2200, 1300, 1000, 5040]))
    if (idx < OBJECT_CLASSES.length - 1) add(pagebreak())
  })
  add(pagebreak())

  add(y('Appendix E — Licensing & Module Entitlement (D26)'))
  add(p(`This engagement was delivered under the Organization’s active plan. The table below shows DynamicBA’s full commercial module and tier model for reference.`))
  add(table(['Module', 'Name', 'Tier', 'Licensing Model', 'Rate Limit'], MODULES.map((m) => [m.id, m.name, PLAN_LABELS[m.tier] || m.tier, m.model, m.rateLimit]), [900, 2800, 1600, 1640, 2600]))
  add(pagebreak())

  add(y('Appendix F — Platform Governance & Security Statement'))
  add(p('DynamicBA is built on the DynamicMS Suite’s common platform architecture. The statements below summarize the governance and security posture every engagement on the platform runs under, for inclusion in client-facing due-diligence review.'))
  add(bullets([
    'Explainable AI only: every AI capability is tiered Assistive or Augmented; an Autonomous tier — an AI taking an irreversible action with no human decision in the loop — is out of scope for the platform.',
    'Tenant isolation by construction: every data-bearing record is scoped to an Organization; no query, export, or AI retrieval may return another tenant’s data.',
    'Commercial gating as a second, independent axis: Solution Pack/module entitlement gates feature access alongside, never instead of, role-based access control.',
    'Governance is structured, not narrative: business rules, controls, risks, and accountability are captured as typed, queryable records tagged back to a process or step, not left in prose documents.',
    'Every AI-generated output is labeled as such, wherever shown, alongside its tier and a named human checkpoint requiring review before it takes effect.',
    'An append-only audit log records every governed change (actor, timestamp, entity, before/after value), viewable read-only by an authorized auditor role.',
    'By default, and whenever no external AI provider connection is configured, tenant data is never transmitted to a third party — every AI capability in this build runs entirely on a deterministic, explainable rule engine.',
  ]))
  add(pagebreak())

  add(y('Glossary'))
  add(table(['Term', 'Meaning'], [
    ['MP-01 – MP-07', 'DynamicBA’s 7 internal macro processes, SOW Ingestion through Validation & Handoff.'],
    ['D01 – D10', 'The Core Business-Architecture Deliverables Workbook tabs defining the process backbone, governance layer, and canonical data model.'],
    ['D15', 'The governed AI Use Case Library.'],
    ['D26', 'The Modules & Tiers licensing and packaging model.'],
    ['RASCI', 'Responsible, Accountable, Support, Consulted, Informed — the macro-process-level accountability model.'],
    ['SOW', 'Statement of Work — the signed engagement scope document.'],
    ['KRI / KPI', 'Key Risk Indicator / Key Performance Indicator — every formula in this package is the interim, documented expression pending Document 2’s Formula Registry.'],
  ], [2400, 7140]))
  add(caption(`Generated by DynamicBA on ${new Date().toISOString().slice(0, 10)}. This document is AI-assisted and consultant-reviewed per DynamicBA’s human-in-the-loop governance model.`))

  return B
}
