// Where each SRS requirement group is implemented: the screen a user opens and the server module that enforces it.
export const TRACE = {
  'FR-DA-TEN': { screens: [['/admin/organizations', 'Organizations']], server: 'routes/admin.js (groups, organizations, OBS), db.js org_id scoping', verify: 'Create a group, an organization and an OBS node; switch organization as platform admin.' },
  'FR-DA-RBAC': { screens: [['/admin/users', 'Users'], ['/admin/permissions', 'Permissions'], ['/role-menus', 'Role menus']], server: 'lib/perms.js, lib/security.js requirePerm', verify: 'Open the permission matrix; sign in as a supplier and confirm hidden menus.' },
  'FR-DA-CFG': { screens: [['/admin/configuration', 'Configuration'], ['/admin/catalog', 'Catalog'], ['/admin/integrations', 'Integrations']], server: 'lib/entitlements.js, routes/admin.js (config, integrations)', verify: 'Change the subscription; register a connector and test it.' },
  'FR-DA-AI': { screens: [['/ai', 'AI use cases']], server: 'lib/ai.js, routes/intelligence.js (use cases, generate, usage log)', verify: 'Generate a suggestion on a task and accept it; read the usage log.' },
  'FR-DA-KB': { screens: [['/knowledge', 'Knowledge base']], server: 'lib/rag.js (TF-IDF retrieval), routes/intelligence.js', verify: 'Search the knowledge base; add an organization document.' },
  'FR-DA-GOV': { screens: [['/business-rules', 'Business rules'], ['/controls', 'Controls'], ['/risks', 'Risks'], ['/kpis', 'KPIs'], ['/racsi', 'RACSI']], server: 'routes/governance.js', verify: 'Edit a control with a justification and restore an earlier version.' },
  'FR-DA-BPMN': { screens: [['/bpmn', 'BPMN models']], server: 'routes/governance.js (bpmn), seed/bpmn.js', verify: 'Open an E2E model, edit and save it.' },
  'FR-DA-REP': { screens: [['/reports', 'Reports']], server: 'reports/index.js, reports/export.js (PDF, XLSX, DOCX)', verify: 'Open a report and export it in each format.' },
  'FR-DA-ALT': { screens: [['/alerts', 'Alerts']], server: 'lib/alerts.js (catalog, background evaluation)', verify: 'Open Alerts; acknowledge an overdue-task alert.' },
  'FR-DA-AST': { screens: [['/assistant', 'Assistant']], server: 'lib/ai.js assistant intents with permission checks', verify: 'Ask "How many active projects?" and "Open my tasks".' },
  'FR-DA-AUD': { screens: [['/admin/audit', 'Audit trail']], server: 'lib/audit.js, entity_versions', verify: 'Search the audit trail for a justification.' },
  'FR-DA-HLP': { screens: [['/help', 'Help']], server: 'lib/help.js (EN, FR, AR articles)', verify: 'Search Help in each language.' },
  'FR-DA-TPL': { screens: [['/templates', 'Templates']], server: 'routes/intelligence.js (templates, versioned)', verify: 'Create a template and restore a previous version.' },
  'FR-DA-I18N': { screens: [['/settings', 'Settings']], server: 'lib/i18n.js, i18n/*.json dictionaries, RTL layout', verify: 'Switch to Arabic; the layout mirrors right-to-left.' },
  'FR-DA-WBS': { screens: [['/wbs', 'WBS & Gantt']], server: 'routes/intelligence.js (wbs), reports Gantt export', verify: 'Add a WBS item with a predecessor; export the Gantt.' },
  'FR-DA-VER': { screens: [['/templates', 'Templates'], ['/controls', 'Controls'], ['/tracks', 'Tracks']], server: 'routes/util.js crud versions + revert', verify: 'Open Version history on a record and restore a version.' },
  'FR-DA-COMM': { screens: [['/notifications', 'Notifications']], server: 'lib/dispatch.js (in-app, e-mail, webhook, SMS, push, retries)', verify: 'Turn on e-mail for gate events; read the delivery log.' },
  'FR-DA-REX': { screens: [['/rex', 'Lessons learned']], server: 'routes/intelligence.js (rex, register)', verify: 'Record a lesson after a Kill decision.' },
  'NFR-DA-PERF': { screens: [['/', 'Dashboard']], server: 'SQLite WAL, indexes, paged tables', verify: 'Dashboard and lists load within a second on the seeded data.' },
  'NFR-DA-SEC': { screens: [['/admin/audit', 'Audit trail'], ['/admin/licensing', 'Licensing']], server: 'helmet, rate limit, bcrypt, JWT, AES-GCM credential encryption, HMAC inbound, tenant isolation tests', verify: 'Run npm test in the server folder (tenant isolation).' },
  'NFR-DA-REL': { screens: [['/notifications', 'Notifications']], server: 'delivery queue with retries, background tick', verify: 'Retry failed deliveries from Notifications.' },
  'NFR-DA-SCALE': { screens: [['/admin/organizations', 'Organizations']], server: 'multi-tenant org_id model, quotas by tier', verify: 'Six organizations run side by side in the seed.' },
  'NFR-DA-UX': { screens: [['/', 'Dashboard']], server: 'web design tokens, one status scale, keyboard focus states', verify: 'Navigate with the keyboard; pin and move the navigation bar.' },
  'NFR-DA-I18N': { screens: [['/settings', 'Settings']], server: 'i18n dictionaries added by configuration', verify: 'Add a language file to server/src/i18n.' },
  'NFR-DA-PORT': { screens: [['/admin/licensing', 'Licensing']], server: 'SaaS and OnPrem licence providers, Node only runtime', verify: 'Set DEPLOYMENT_MODE=onprem and install a .lic file.' },
  'NFR-DA-MAINT': { screens: [['/admin/traceability', 'Traceability']], server: 'modular routes and libraries, reference data as JSON', verify: 'Reference data lives in server/src/data.' },
  'NFR-DA-COMPAT': { screens: [['/reports', 'Reports']], server: 'standard exports (PDF, XLSX, DOCX, CSV), REST JSON API', verify: 'Export any table to CSV.' },
  'NFR-DA-COMP': { screens: [['/admin/configuration', 'Configuration']], server: 'compliance standards activation with non-certification disclosure', verify: 'Activate a standard; its controls are tagged.' },
  'NFR-DA-DATA': { screens: [['/data-model', 'Data model']], server: 'D09/D10 classes and data dictionary', verify: 'Open the data model.' },
};
export const groupOf = (id) => id.split('-').slice(0, 3).join('-');
